import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-09-03";

export const companies20260903Daily: Company[] = [
  {
    slug: "jamf",
    name: "Jamf",
    category: "Apple端末管理・セキュリティ",
    broadCategory: "セキュリティ・IT運用",
    hq: "ミネアポリス（米国）",
    japanPresence: "Jamf Japan合同会社・東京。gBizINFOの事業所被保険者数57人",
    hiringStatus: "積極採用",
    salesRoles: 3,
    description: "Mac、iPhone、iPadの配布・設定からID、アプリ、脅威対策までを一体で管理。東京で営業、営業技術、内勤営業を公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.jamf.com/about/careers/jobs/",
    tags: ["Anchor", "Apple", "Endpoint Management", "Identity", "Security", "Tokyo"],
  },
  {
    slug: "matterport",
    name: "Matterport",
    category: "建物3Dデジタルツイン・空間データ",
    broadCategory: "コマース・業界特化",
    hq: "サニーベール（米国）",
    japanPresence: "マーターポート株式会社・東京。gBizINFOの事業所被保険者数6人",
    hiringStatus: "積極採用",
    salesRoles: 3,
    description: "建物を撮影し、寸法・共有・外部連携を備えた3Dデジタルツインへ変換。日本で直販、販売パートナー、顧客技術支援を公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.costargroup.com/careers",
    tags: ["Digital Twin", "Spatial Data", "PropTech", "Enterprise", "Tokyo", "Hybrid"],
  },
  {
    slug: "gamma",
    name: "Gamma",
    category: "AI資料・文書・Webページ作成",
    broadCategory: "業務自動化・コラボレーション",
    hq: "サンフランシスコ（米国）",
    japanPresence: "日本法人・国内拠点・日本向け公式求人は未確認。日本語を含む60超の言語で作成可能",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "文章やメモからプレゼンテーション、文書、Webページ、SNS投稿を生成し、共同編集・公開・分析までを一つにまとめるAI作成基盤。",
    lastChecked: checkedAt,
    careersUrl: "https://careers.gamma.app/",
    entryStatus: "not-entered",
    tags: ["AI", "Presentation", "Document", "Website", "Collaboration", "Pre-entry"],
  },
];

type JobDraft = Pick<Job, "id" | "companySlug" | "title" | "segment" | "location" | "workStyle" | "language" | "source" | "descriptionSummary" | "genbaTake" | "desiredProfile">;

function makeJob(draft: JobDraft): Job {
  return {
    ...draft,
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    compensationReality: "日本の給与、変動報酬、株式、担当範囲、評価指標は公式求人で確認できない。提示条件と評価方法を面接で確認したい。",
    careerInsights: {
      fit: `${draft.segment}で、顧客課題の確認から複数部門を動かす実行まで担いたい人に向く。`,
      thingsToKnow: "担当範囲、評価指標、支援体制、給与・賞与・株式、日本組織の人数は十分に公開されていない。面接で確認したい。",
      marketValue: `${draft.segment}の成果を商談、導入、利用、顧客KPIで定量化できれば、隣接する企業向けソフトウェアの同職種・上位職へ再現性を説明しやすい。`,
      tenureAndPromotion: `【Genba仮説】${draft.segment}では在籍年数より、担当範囲の成果と再利用できる実行の型が次の職位を左右する。支持材料: 公式求人は顧客成果と部門横断の実行を求める。求人数の多さだけで昇進機会が多いとは断定しない。反証・留保: 日本の昇進率・離職率・職位別基準は未公開。面接で確認: 直近24カ月の昇進・異動・退職と次の職位に必要な定量成果は。`,
      priorCompanies: `【Genba仮説】${draft.segment}に近い顧客課題、複数の意思決定者、目標責任を持った人材が隣接する。支持材料: 公式求人は社名より顧客の意思決定を前へ進めた経験を重視する。特定企業からの採用傾向や優遇は確認できず、経験の構造だけを見ている。反証・留保: 日本の採用者を同じ条件で十分に集計できない。面接で確認: 直近採用者の前職領域、共通スキル、立ち上がり期間は。`,
      nextCompanies: `【Genba仮説】${draft.segment}の成果を数字で残せれば、同領域の専門職、より大きな顧客層、Lead・管理職へ広げやすい。支持材料: 公式求人が成果責任と部門横断の実行を置く。特定の転職先や昇格を保証せず、成果の再現性を説明できることが前提。反証・留保: 公開された転職先分布ではなく職務構造からの仮説。面接で確認: 退職者の次職種と社内で担当範囲を広げた実例は。`,
    },
  };
}

export const jobs20260903Daily: Job[] = [
  makeJob({
    id: "jamf-account-executive-japan-r41",
    companySlug: "jamf",
    title: "Account Executive - Japan",
    segment: "Enterprise Sales / Apple Management & Security",
    location: "東京都",
    workStyle: "東京オフィス勤務。出社頻度は公式求人で確認できず",
    language: "日本語ネイティブ、英語での業務遂行",
    source: { label: "Jamf Careers (Workday)", url: "https://jamfsoftware.wd1.myworkdayjobs.com/en-US/Jamf/job/Tokyo-Office/Account-Executive---Japan_R41" },
    descriptionSummary: "日本の新規・既存顧客へApple端末の導入・拡大計画を確認し、営業技術、販売パートナー、Appleと連携して提案、予測、受注を担う。",
    genbaTake: "端末管理の機能比較に閉じず、配布、更新、ID、セキュリティ、利用者体験を一つの運用計画へまとめ、専用投資の事業価値を証明する営業。",
    desiredProfile: "公式求人は企業向け技術営業、担当市場の計画・予測、複数の意思決定者と販売パートナーを動かす力、日本語・英語を重視する。",
  }),
  makeJob({
    id: "jamf-systems-engineer-japan-r58-1",
    companySlug: "jamf",
    title: "Systems Engineer | Japan",
    segment: "Sales Engineering / Apple Management & Security",
    location: "東京都",
    workStyle: "東京オフィス勤務。顧客先・イベント対応、出張最大30%",
    language: "日本語ネイティブ、英語での業務遂行",
    source: { label: "Jamf Careers (Workday)", url: "https://jamfsoftware.wd1.myworkdayjobs.com/en-US/Jamf/job/Tokyo-Office/Systems-Engineer--102JPN182-_R58-1" },
    descriptionSummary: "営業と連携し、顧客・販売パートナーの技術要件を整理して、デモ、技術評価、概念実証、試験導入を成功まで支援する。",
    genbaTake: "製品説明だけでなく、既存の端末・ID・セキュリティ環境との共存を設計し、評価期間内に運用負荷と安全性の改善を証明する技術営業。",
    desiredProfile: "公式求人はApple技術、企業向け端末管理・セキュリティ、顧客向けデモと技術評価、日本語・英語での意思疎通を重視する。",
  }),
  makeJob({
    id: "jamf-inside-sales-representative-japan-korea-r40",
    companySlug: "jamf",
    title: "Inside Sales Representative - Japan & Korea",
    segment: "Inside Sales / New, Existing & Partner",
    location: "東京都",
    workStyle: "東京オフィス勤務。出張10%（米国研修を含む）",
    language: "日本語ネイティブ、英語での業務遂行。韓国語は歓迎",
    source: { label: "Jamf Careers (Workday)", url: "https://jamfsoftware.wd1.myworkdayjobs.com/en-US/Jamf/job/Tokyo-Office/Inside-Sales-Representative---Japan---Korea_R40" },
    descriptionSummary: "日本・韓国の新規・既存顧客と販売会社へ接点を作り、課題確認、技術デモの設定、中小規模商談の受注、見積・発注処理を担う。",
    genbaTake: "商談件数だけを作るのではなく、既存顧客の端末拡大とID・セキュリティ需要を見つけ、販売パートナー経由も含めて受注まで進める役割。",
    desiredProfile: "公式求人は内勤営業または顧客対応、見込み案件の評価、見積・予測、複数部門との連携、日本語・英語を重視する。",
  }),
  makeJob({
    id: "matterport-senior-account-executive-tokyo-r38612",
    companySlug: "matterport",
    title: "Senior Account Executive, Matterport - Tokyo",
    segment: "Enterprise Sales / Spatial Data",
    location: "東京都",
    workStyle: "東京勤務。出社頻度は公式求人で確認できず",
    language: "日本語・英語での業務遂行",
    source: { label: "CoStar Group Careers (Workday)", url: "https://costar.wd1.myworkdayjobs.com/en-US/CoStarCareers/job/Tokyo-JP---Matterport/Senior-Account-Executive--Matterport---Tokyo_R38612" },
    descriptionSummary: "日本の不動産、建設、施設運用等の顧客へ新規開拓から提案、評価、交渉、受注、既存拡大までを担う。",
    genbaTake: "3D画像を売るのではなく、現地訪問、手戻り、販売、施工、施設管理の業務を共通の空間記録へ変え、削減効果を示す営業。",
    desiredProfile: "公式求人は企業向けSaaS営業、複雑商談、新規開拓、経営層との関係構築、日本語・英語での業務遂行を重視する。",
  }),
  makeJob({
    id: "matterport-channel-account-manager-tokyo-r39474-1",
    companySlug: "matterport",
    title: "Channel Account Manager, Matterport - Tokyo",
    segment: "Channel Sales / Spatial Data",
    location: "日本",
    workStyle: "Home-based - Japan。東京・虎ノ門へ通勤可能で、顧客・販売パートナー訪問あり",
    language: "日本語・英語での業務遂行",
    source: { label: "CoStar Group Careers (Workday)", url: "https://costar.wd1.myworkdayjobs.com/en-US/CoStarCareers/job/Home-based---Japan-JP/Channel-Account-Manager--Matterport---Tokyo_R39474-1" },
    descriptionSummary: "日本の販売パートナーを開拓・育成し、共同計画、案件創出、教育、予測、受注を通じてMatterportの販売網を広げる。",
    genbaTake: "契約社数ではなく、撮影機器、ソフトウェア、導入支援を組み合わせ、販売会社が自律して案件を作り顧客成果まで運べる型を作る役割。",
    desiredProfile: "公式求人は販売網の開拓・成長、共同営業、予測と目標管理、複数部門の連携、日本語・英語を重視する。",
  }),
  makeJob({
    id: "matterport-customer-support-engineer-tokyo-r38416",
    companySlug: "matterport",
    title: "Customer Support Engineer, Matterport - Tokyo",
    segment: "Customer Support Engineering / Spatial Data",
    location: "東京都",
    workStyle: "東京・虎ノ門へ通勤可能であること。出社頻度は公式求人で確認できず",
    language: "日本語ネイティブ級、英語での文書・会話・プレゼンテーション",
    source: { label: "CoStar Group Careers Europe (Workday)", url: "https://costar.wd1.myworkdayjobs.com/en-US/CoStarCareersEurope/job/Tokyo-JP---STR/Customer-Support-Engineer--Matterport---Tokyo_R38416" },
    descriptionSummary: "日本の顧客・販売パートナーに対し、撮影機器、アプリ、クラウド処理、アカウント、外部連携の技術課題を切り分けて解決する。",
    genbaTake: "問い合わせ処理に閉じず、現場の撮影から3D処理・共有までの停止要因を特定し、再発防止と製品改善へつなぐ顧客技術支援。",
    desiredProfile: "公式求人は顧客向け技術支援7年以上、重要案件のエスカレーション、QA・製品・開発との連携、日本語・英語での問題解決を重視する。",
  }),
];
