import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-13";

export const companies20260813: Company[] = [
  { slug: "sysdig", name: "Sysdig", category: "Cloud Native Security / CNAPP", broadCategory: "セキュリティ・IT運用", hq: "San Francisco, US", japanPresence: "日本語公式サイト / Tokyo Japan GTM", hiringStatus: "積極採用", salesRoles: 1, description: "runtime insightを核にcloud・container securityを統合。NTTドコモ等の国内事例を持ち、Country Manager Japanを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/sysdig?department=Sales", tags: ["CNAPP", "Cloud Security", "Kubernetes", "Country Manager", "Enterprise"] },
  { slug: "saviynt", name: "Saviynt", category: "Identity Security / IGA", broadCategory: "セキュリティ・IT運用", hq: "Los Angeles, US", japanPresence: "日本語公式サイト / Japan sales team", hiringStatus: "積極採用", salesRoles: 1, description: "人・workload・AI agentのidentity governanceを統合。JapanのStrategic Account ExecutiveとSolution Engineerを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/saviynt?department=Sales", tags: ["Identity Security", "IGA", "Zero Trust", "Strategic", "Enterprise"] },
  { slug: "walkme", name: "WalkMe", category: "Digital Adoption / Software Intelligence", broadCategory: "業務自動化・コラボレーション", hq: "Tel Aviv, Israel", japanPresence: "WalkMe株式会社 / Tokyo", hiringStatus: "積極採用", salesRoles: 3, description: "software導入後の利用定着と業務遂行を画面上で支援。JapanでAlliance、Partner Sales、Solution Advisorを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/walkme?location=Tokyo", tags: ["Digital Adoption", "Change Management", "SAP", "Partner", "Enterprise"] },
  { slug: "sonar", name: "Sonar", category: "Code Quality / Application Security", broadCategory: "セキュリティ・IT運用", hq: "Geneva / Austin", japanPresence: "日本語公式サイト / Tokyo On-site GTM", hiringStatus: "積極採用", salesRoles: 2, description: "developer workflow内でcode qualityとsecurityを継続管理。JapanでEnterprise Territory ManagerとPartner Business Managerを募集。", lastChecked: "2026-08-17", careersUrl: "https://jobs.lever.co/sonarsource", tags: ["Developer Tools", "AppSec", "Code Quality", "Enterprise", "Partner"] },
  { slug: "asana", name: "Asana", category: "Work Management / AI Collaboration", broadCategory: "業務自動化・コラボレーション", hq: "San Francisco, US", japanPresence: "Asana Japan / Tokyo office", hiringStatus: "採用中", salesRoles: 1, description: "人とAI agentの仕事・目標・workflowをWork Graphで接続。TokyoでCorporate Account Executiveを募集。", lastChecked: checkedAt, careersUrl: "https://asana.com/jobs/tokyo", tags: ["Work Management", "AI Collaboration", "Corporate", "Enterprise", "PLG"] },
  { slug: "channel-talk", name: "Channel Talk", category: "AI顧客対応・CRM基盤", broadCategory: "CRM・顧客体験", hq: "ソウル（韓国）", japanPresence: "株式会社Channel Corporation・東京", hiringStatus: "積極採用", salesRoles: 11, description: "公式ATSの日本求人20件から、SMB、Enterprise、Partner、Field Sales、Sales Engineer、Forward Deployed Engineerなど営業・GTM関連11職種を掲載。勤務形態は職種別に異なる。", lastChecked: "2026-08-17", careersUrl: "https://jobs.lever.co/zoyi?department=Japan", tags: ["Customer Service", "CRM", "AI Agent", "SMB", "Enterprise", "Japan Growth"] },
  { slug: "extreme-networks", name: "Extreme Networks", category: "Cloud Networking / Network Fabric", broadCategory: "セキュリティ・IT運用", hq: "Morrisville, US", japanPresence: "Extreme Networks Japan / Tokyo", hiringStatus: "採用中", salesRoles: 1, description: "campus・branch・data center networkをcloud管理とautomationで統合。TokyoでServices Sales Account Executiveを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/extremenetworks?location=Tokyo%2C+Japan", tags: ["Networking", "Cloud Management", "Services Sales", "Enterprise", "Channel"] },
  { slug: "zadara", name: "Zadara", category: "Sovereign Edge Cloud / Storage", broadCategory: "AI・データ基盤", hq: "Irvine, US", japanPresence: "日本語公式サイト / Japan customers / Tokyo sales coverage", hiringStatus: "採用中", salesRoles: 1, description: "service providerとenterprise向けにsovereign edge cloud、compute、storageを提供。TokyoでSenior Account Executiveを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/Zadara?location=Tokyo", tags: ["Cloud", "Storage", "Sovereign AI", "Edge", "Service Provider"] },
  { slug: "sixsense", name: "6sense", category: "Revenue AI / Account Intelligence", broadCategory: "CRM・顧客体験", hq: "San Francisco, US", japanPresence: "日本法人・国内拠点を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "buyer signalとAIでaccount prioritizationを行うRevenue AI platform。APAC展開からJapan進出条件を継続観測。", lastChecked: checkedAt, careersUrl: "https://6sense.com/careers/", tags: ["日本未進出", "Revenue AI", "ABM", "Sales Intelligence", "APAC"], entryStatus: "not-entered" },
  { slug: "abnormal-ai", name: "Abnormal AI", category: "AI-Native Email Security", broadCategory: "セキュリティ・IT運用", hq: "San Francisco, US", japanPresence: "日本法人・国内拠点を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "behavioral AIでemail・human-layer attackを検知。APJ投資とenterprise tractionからJapan進出条件を継続観測。", lastChecked: checkedAt, careersUrl: "https://careers.abnormal.ai/", tags: ["日本未進出", "Email Security", "AI Security", "Enterprise", "APJ"], entryStatus: "not-entered" },
  { slug: "apollo-io", name: "Apollo.io", category: "Sales Intelligence / Engagement", broadCategory: "CRM・顧客体験", hq: "San Francisco, US", japanPresence: "日本法人・国内拠点を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "B2B data、prospecting、engagementを一体化するGTM platform。global利用とAPAC需要からJapan進出条件を継続観測。", lastChecked: checkedAt, careersUrl: "https://www.apollo.io/careers", tags: ["日本未進出", "Sales Intelligence", "GTM", "PLG", "APAC"], entryStatus: "not-entered" },
];

type JobSeed = {
  slug: string; title: string; segment: string; location: string; workStyle: string; language: string; url: string;
  summary: string; take: string; profile: string; fit: string; marketValue: string;
};

const seeds: JobSeed[] = [
  { slug: "sysdig", title: "Country Manager, Japan", segment: "Japan Leadership / Enterprise", location: "Tokyo", workStyle: "hybrid", language: "日本語 / 英語", url: "https://jobs.lever.co/sysdig?department=Sales", summary: "日本のsales strategy、pipeline、partner、team、forecastを持ち、cloud-native security事業を拡大するcountry leadership role。", take: "runtime securityの技術差だけでなく、CISO、platform engineering、DevSecOpsの優先順位を一つのrisk reductionへ束ねる。", profile: "公式求人はJapan marketでのenterprise security sales leadership、team building、partner、forecast、executive relationshipを重視。", fit: "日本市場のGTMと組織を自ら作るsecurity leaderに向く。", marketValue: "CNAPP、Kubernetes、CISO sales、country managementを横断する経験。" },
  { slug: "saviynt", title: "Strategic Account Executive, Japan", segment: "Strategic / Identity Security", location: "Japan", workStyle: "hybrid", language: "日本語 / 英語", url: "https://jobs.lever.co/saviynt/e309fb59-65aa-486d-ada7-6f06fc3c0c58", summary: "large enterpriseへidentity governance、privileged access、application accessを提案し、new logo、partner、renewal、expansionを動かす。", take: "license管理ではなく、誰・workload・AI agentが何へaccessできるかをrisk、audit、productivityの経営課題へ変える。", profile: "公式求人はenterprise software sales、complex cycle、C-level、partner、pipeline creationの実績を求める。", fit: "securityとbusiness processを横断するstrategic sellerに向く。", marketValue: "IGA、Zero Trust、AI identity、regulated enterprise salesの専門性。" },
  { slug: "walkme", title: "Partner Sales Manager", segment: "Partner / Digital Adoption", location: "東京", workStyle: "ハイブリッド（出社日数は明記なし）", language: "日本語（流暢またはネイティブ）／英語（ビジネス）", url: "https://www.walkme.com/jobs/partner-sales-manager/", summary: "日本のSAP partnerを含むSI・consulting・technology ecosystemを初期から構築し、enablement、source/influence opportunity、subscription target、deal executionを通じてnet-new revenueを作る。", take: "tool導入ではなく、SAP等のtransformation投資が現場で使われ成果になるまでをpartnerと売る。", profile: "公式求人はpartner ecosystemを初期から構築したsales実績、Salesforce・SuccessFactors・Ariba・Concur・ServiceNow知識、日本語とbusiness Englishを重視。", fit: "partner ecosystemでlarge transformationを動かしたい人に向く。", marketValue: "Digital Adoption、change management、SI co-sellの複合経験。" },
  { slug: "sonar", title: "Enterprise Territory Manager - Japan", segment: "Enterprise / Developer Security", location: "Tokyo", workStyle: "on-site（週3日office可否を応募時確認）", language: "英語（professional）／日本語要件は明記なし", url: "https://jobs.lever.co/sonarsource/4a5dfed7-c01a-44e9-af6a-5917cf056a88", summary: "new logo、territory、channel、outbound、buying process、license sizing、forecastを担う。", take: "scanner機能ではなく、developer velocityを落とさずnew codeのquality・security debtを減らすoperating modelを売る。", profile: "公式求人はB2B sales 7年以上、technical buyer、large enterprise、professional Englishを重視。", fit: "technical buyerとeconomic buyerをつなげるenterprise hunterに向く。", marketValue: "DevTools、AppSec、product-led enterprise salesの専門性。" },
  { slug: "asana", title: "Corporate Account Executive", segment: "Corporate / Work Management", location: "東京", workStyle: "office-centric hybrid（火・木＋追加1日office）", language: "日本語（fluent）／英語要件は明記なし", url: "https://asana.com/jobs/apply/7628932", summary: "small〜large企業のnew logoとstrategic upsellをprospect、qualify、closeまでfull-cycleで担当し、SE・Marketing・CSと連携する。", take: "task toolではなく、strategyとexecution、人とAI agentの仕事を同じWork Graphへ載せるchange sale。", profile: "公式求人はB2B sales 4年以上、新規corporate account、full-cycle、pipeline、fluent Japaneseを求める。英語要件は明記しない。", fit: "PLG usageをenterprise standardへ変えるsellerに向く。", marketValue: "Work Management、AI adoption、land-and-expandの経験。" },
  { slug: "channel-talk", title: "Enterprise Sales", segment: "Enterprise / AI CX", location: "Tokyo, Hanzomon", workStyle: "hybrid", language: "日本語 / 英語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "大手企業へchat、CRM、voice、AI agentを組み合わせ、customer communicationと売上・support operationを変える。", take: "chat導入ではなく、問い合わせ、電話、marketing、顧客dataを一つにしてAI resolutionとrevenueを同時に設計する。", profile: "公式求人群はnew business、field sales、partner、enterprise BDR等を横断し、日本のGTM拡大を示す。", fit: "成長組織でproductとsales playbookを一緒に作りたい人に向く。", marketValue: "AI CX、CRM、Korea-Japan scale-up、multi-segment salesの経験。" },
  { slug: "extreme-networks", title: "Sr. Services Sales Account Executive", segment: "Enterprise / Services", location: "Tokyo, Japan", workStyle: "hybrid", language: "日本語 / 英語", url: "https://jobs.lever.co/extremenetworks?location=Tokyo%2C+Japan", summary: "network transformationに必要なprofessional services、support、adoptionをhardware・software案件へ組み込む。", take: "box売りではなく、design、migration、operation、supportまで含めてnetwork投資のriskとtime-to-valueを売る。", profile: "公式求人はservices sales、networking、complex account、partner、cross-functional executionを重視。", fit: "network技術とcommercial serviceを束ねるaccount sellerに向く。", marketValue: "Cloud Networking、services attach、channel salesの専門性。" },
  { slug: "zadara", title: "Senior Account Executive", segment: "Enterprise / Service Provider", location: "Tokyo", workStyle: "remote", language: "日本語 / 英語", url: "https://jobs.lever.co/Zadara?location=Tokyo", summary: "enterpriseとservice providerへmanaged cloud、storage、compute、sovereign edgeをfull-cycleで提案。", take: "容量単価ではなく、data location、control、運用、consumption economicsをcloud alternativeとして設計する。", profile: "公式求人はenterprise infrastructure sales、new logo、partner、forecast、executive relationshipを重視。", fit: "cloud・storageのarchitectureをbusiness caseへ変えたいhunterに向く。", marketValue: "Sovereign cloud、edge、storage-as-a-service、partner GTMの経験。" },
];

const additionalSeeds: JobSeed[] = [
  { slug: "walkme", title: "Director, Alliances and Channels", segment: "Japan Leadership / Alliances", location: "東京", workStyle: "ハイブリッド（週3日出社）", language: "日本語（流暢）／英語（ビジネス）", url: "https://www.walkme.com/jobs/director-alliances-and-channels/", summary: "Japanのglobal SI・consulting・advisory partner戦略、共同pipeline、enablement、sales generationを統括。", take: "partner紹介件数ではなく、transformation案件へDigital Adoptionを標準で組み込むecosystemを作る。", profile: "公式求人はAccenture・PwC・Deloitte・IBM・EY等とのjoint GTM、partner ecosystem構築、日本語とbusiness Englishを重視。", fit: "Japan partner ecosystemを経営レベルで作りたいleaderに向く。", marketValue: "Alliance leadership、change transformation、Japan GTMの経験。" },
  { slug: "walkme", title: "Solution Advisor", segment: "Pre-sales / Value Engineering", location: "東京", workStyle: "ハイブリッド（週3日出社）", language: "日本語（流暢）／英語（ビジネス）", url: "https://www.walkme.com/jobs/solution-advisor/", summary: "顧客workflowを分析し、technical PoC、demo、solution design、value hypothesisでDigital Adoptionの技術・業務適合を作る。", take: "機能demoではなく、利用者行動とsoftware ROIをつなぐ業務設計が核。", profile: "公式求人はenterprise SaaS technical presales・SE・consulting 5年以上、日本語とbusiness Englishを重視。", fit: "技術とchange managementを両方扱うsolution sellerに向く。", marketValue: "Digital Adoption、Value Engineering、enterprise pre-salesの経験。" },
  { slug: "sonar", title: "Partner Business Manager - Japan", segment: "Partner / Developer Security", location: "Tokyo", workStyle: "on-site（日数非公開）", language: "公式求人で明記なし", url: "https://jobs.lever.co/sonarsource/ca83677b-0f8b-4aba-8907-3549327fe0d1", summary: "JapanのSI・reseller・distributor・hyperscalerを開拓し、enablement、QBR、new bookings、renewalを担う。", take: "developer toolの紹介販売ではなく、software quality・AppSecをdelivery標準へ組み込むpartner motion。", profile: "公式求人はtechnology software channel 7年以上、partner plan、pipeline、conflict managementを重視。", fit: "developer ecosystemをpartnerでscaleしたい人に向く。", marketValue: "DevTools、AppSec、channel developmentの経験。" },
  { slug: "channel-talk", title: "SMB Sales", segment: "SMB / Full-cycle", location: "Tokyo, Hanzomon", workStyle: "hybrid", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "SMB顧客へcustomer support、CRM、AI agentを提案し、discoveryから契約まで担当。", take: "chatの便利さではなく、少人数teamのresponse、conversion、repeat purchaseを短いcycleで成果化する。", profile: "公式求人は顧客理解、new business、fast execution、team collaborationを重視。", fit: "成長marketで高回転のfull-cycle salesを磨きたい人に向く。", marketValue: "SMB SaaS、AI CX、high-velocity salesの経験。" },
  { slug: "channel-talk", title: "Inside Sales", segment: "Inside Sales / Pipeline", location: "Tokyo, Hanzomon", workStyle: "on-site", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "inbound・outboundから課題を発見し、qualified meetingとpipelineを作る。", take: "件数だけでなく、顧客communicationの現状を診断してAEへ文脈を渡すcategory education。", profile: "公式求人は顧客志向、行動量、learning、data-driven improvementを重視。", fit: "AI CX領域でprospectingの型を作りたい人に向く。", marketValue: "SDR/BDR、CRM、AI customer serviceの基礎。" },
  { slug: "channel-talk", title: "Inside Sales Leader", segment: "Inside Sales / Leadership", location: "Tokyo, Hanzomon", workStyle: "on-site", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "inside sales teamのtarget、process、coaching、conversionを設計し、再現性あるpipeline engineを作る。", take: "個人meeting数ではなく、segment別message、handoff、conversion、rampをmanagement systemにする。", profile: "公式求人はinside sales成果、team leadership、process design、coachingを重視。", fit: "scale-upのpipeline組織をゼロから整えたいleaderに向く。", marketValue: "Revenue Development leadership、AI CX category creationの経験。" },
  { slug: "channel-talk", title: "Partner Sales", segment: "Partner / Japan", location: "Tokyo, Hanzomon", workStyle: "hybrid", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "agency・SI・technology partnerを開拓し、joint solution、enablement、referral・co-sell pipelineを作る。", take: "紹介制度ではなく、EC・customer service変革をpartnerのservice offeringへ埋め込む。", profile: "公式求人はpartner development、relationship、joint planning、sales executionを重視。", fit: "Japan ecosystemでproduct adoptionをscaleしたい人に向く。", marketValue: "Partner sales、CX consulting、ecosystem GTMの経験。" },
  { slug: "channel-talk", title: "Field Sales", segment: "Mid-market / Field", location: "Tokyo, Hanzomon", workStyle: "on-site", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "成長企業のsupport・marketing・sales stakeholderへ入り、AI CX platformをfull-cycleで提案。", take: "single department toolではなく、会話dataとAIを複数teamのcustomer lifecycleへ広げる。", profile: "公式求人はB2B sales、discovery、proposal、negotiation、顧客成果へのownershipを重視。", fit: "product feedbackを近距離でGTMへ反映したいfield sellerに向く。", marketValue: "Mid-market SaaS、multi-product CX salesの経験。" },
  { slug: "channel-talk", title: "Field Sales Leader", segment: "Field Sales / Leadership", location: "Tokyo, Hanzomon", workStyle: "on-site", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "field sales teamのpipeline、forecast、coaching、sales processを設計し、Japan growthを率いる。", take: "個人のhero saleではなく、segment別ICP・message・stage・win/lossを再現可能なplaybookにする。", profile: "公式求人はsales leadership、quota achievement、coaching、forecast、cross-functional executionを重視。", fit: "急成長SaaSの営業組織をbuildしたいleaderに向く。", marketValue: "Japan scale-up、sales management、AI CXの経験。" },
  { slug: "channel-talk", title: "Enterprise BDR", segment: "Enterprise / Business Development", location: "Tokyo, Hanzomon", workStyle: "hybrid", language: "日本語", url: "https://jobs.lever.co/zoyi?department=Japan", summary: "large accountのCX・digital・EC・support leaderをresearchし、strategic meetingとnew pipelineを作る。", take: "大量送信ではなく、企業のcustomer communication構造を仮説化してexecutive discussionを作る。", profile: "公式求人はenterprise prospecting、account research、executive communication、persistenceを重視。", fit: "大手向けの仮説型outboundを磨きたい人に向く。", marketValue: "Enterprise BDR、account-based selling、AI CXの経験。" },
];

export const jobs20260813: Job[] = [...seeds, ...additionalSeeds].map((seed) => ({
  id: `${seed.slug}-${seed.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
  companySlug: seed.slug, title: seed.title, segment: seed.segment, location: seed.location, workStyle: seed.workStyle, language: seed.language,
  firstSeen: checkedAt, lastChecked: checkedAt, source: { label: `${seed.slug} official careers`, url: seed.url }, descriptionSummary: seed.summary, genbaTake: seed.take,
  compensationReality: "日本のbase、OTE、equity、quota、acceleratorは公開求人で確認できない。選考でramp、credit rule、達成率まで確認したい。",
  desiredProfile: seed.profile,
  careerInsights: { fit: seed.fit, thingsToKnow: "日本ARR、顧客数、ramped seller達成率、平均ACV、sales cycleは非公開。", marketValue: seed.marketValue, tenureAndPromotion: "日本teamの平均在籍年数、離職率、昇進実績は公開情報で確認できない。", priorCompanies: "公開profileの十分な母数は未確認。求人要件に近いenterprise software、security、cloud、SaaS経験者が候補になる。", nextCompanies: "公開集計は未確認。担当categoryでの成果は隣接するenterprise softwareのAE、partner、sales leadershipへつながり得る（仮説）。" },
}));
