import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-09-19";

export const companies20260919Daily: Company[] = [
  {
    slug: "edb",
    name: "EDB",
    category: "Postgres・データ主権・AI基盤",
    broadCategory: "AI・データ基盤",
    hq: "ベッドフォード（米国）",
    japanPresence: "EDB Japan・東京。日本語公式サイトと東京勤務の現行求人3件を公式確認",
    hiringStatus: "積極採用",
    salesRoles: 3,
    description: "企業向けPostgresとデータ・AI基盤を提供する。東京で営業責任者、アカウントエグゼクティブ、営業開発を公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.enterprisedb.com/jp/careers",
    tags: ["Postgres", "Data Sovereignty", "Database Modernization", "AI", "Enterprise Sales", "Tokyo"],
  },
  {
    slug: "3e",
    name: "3E",
    category: "製品規制・化学物質・サプライチェーン情報",
    broadCategory: "セキュリティ・IT運用",
    hq: "カールスバッド（米国）",
    japanPresence: "東京オフィス（丸の内）。会社公式の拠点一覧と東京勤務の現行求人を確認",
    hiringStatus: "採用中",
    salesRoles: 2,
    description: "化学物質、製品安全、規制、供給網の情報を専門家監修のデータとAIで提供する。東京で新規営業と顧客担当を公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/3E",
    tags: ["Regulatory Intelligence", "Product Compliance", "Chemical Safety", "Supply Chain", "Enterprise Sales", "Tokyo"],
  },
  {
    slug: "mixpanel",
    name: "Mixpanel",
    category: "製品行動分析・実験・セッション解析",
    broadCategory: "CRM・顧客体験",
    hq: "サンフランシスコ（米国）",
    japanPresence: "日本法人・国内拠点は未確認。Singaporeを拠点に日本市場を担当する営業求人を公式確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "利用者の行動をイベント単位で分析し、製品改善と定着を支援する。Singaporeから日本市場を開拓する上級営業を公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://job-boards.greenhouse.io/mixpanel",
    entryStatus: "pre-entry-signal",
    tags: ["日本進出の兆しあり", "Product Analytics", "Experimentation", "Session Replay", "Enterprise Sales", "Singapore"],
  },
];

type JobDraft = Pick<Job, "id" | "companySlug" | "title" | "segment" | "location" | "workStyle" | "language" | "source" | "descriptionSummary" | "genbaTake" | "desiredProfile">;

function makeJob(draft: JobDraft): Job {
  return {
    ...draft,
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    compensationReality: "公式求人に日本向けの給与、変動給、株式、目標、達成率の十分な記載はない。面接で確認したい。",
    careerInsights: {
      fit: `${draft.segment}で、顧客課題を事業成果へ変え、複数の関係者を動かしたい人に向く。`,
      thingsToKnow: "目標、担当範囲、達成率、支援体制、報酬構成は十分に公開されていない。",
      marketValue: `${draft.segment}の成果を案件創出、受注、導入、利用、顧客KPIで定量化できれば、隣接する企業向け技術企業の同職種へ再現性を説明しやすい。`,
      tenureAndPromotion: "年数だけでなく、担当拡張、顧客成果、再利用できる実行の型が次の役割の土台になる。",
      priorCompanies: "同領域の顧客課題、複数の意思決定者、成果責任を持った経験が隣接する。",
      nextCompanies: "担当規模と成果を数字で残せれば、同領域の専門職や市場責任者へ広げやすい。",
    },
  };
}

export const jobs20260919Daily: Job[] = [
  makeJob({
    id: "edb-director-sales-japan-7812564003",
    companySlug: "edb",
    title: "Director Sales",
    segment: "Japan Sales Leadership / Data Platform",
    location: "東京・日本",
    workStyle: "東京勤務。Hybridまたは日本国内Remoteを検討すると公式求人に記載",
    language: "日本語は流暢、英語は業務水準を求める",
    source: { label: "EDB Careers (Greenhouse)", url: "https://www.enterprisedb.com/careers/job-openings?gh_jid=7812564003" },
    descriptionSummary: "日本の売上、案件創出、予測、営業組織、販売パートナーを持ち、大手企業と公共分野のデータベース刷新・AI基盤案件を主導する。",
    genbaTake: "既存データベースの置換営業だけでなく、データ主権、運用費、AI活用を経営課題へ結び、日本の直販とパートナー経路を同時に作る責任者。",
    desiredProfile: "公式求人は企業向け技術営業15年以上、営業管理3〜5年以上、日本の大手企業・公共分野、SI・クラウドの関係網、データ基盤、日本語と英語を重視する。",
  }),
  makeJob({
    id: "edb-senior-account-executive-japan-7586615003",
    companySlug: "edb",
    title: "Senior Account Executive",
    segment: "Enterprise Sales / Postgres",
    location: "東京・日本",
    workStyle: "東京勤務。公式求人に出社頻度の明記なし",
    language: "日本語・英語の詳細水準は公式求人で確認",
    source: { label: "EDB Careers (Greenhouse)", url: "https://www.enterprisedb.com/careers/job-openings?gh_jid=7586615003" },
    descriptionSummary: "大手企業の新規開拓と既存拡大を持ち、データベース刷新、可用性、運用費、AI活用の事業価値を関係者へ提案する。",
    genbaTake: "Postgresの技術説明ではなく、既存資産を止めずに移行する条件、主権、費用、運用リスクを整理し、長い企業購買を前へ進める役割。",
    desiredProfile: "公式求人は企業向けソフトウェア営業、複雑な案件、新規開拓、経営層への価値提案、予測と交渉、データベースまたはデータ管理経験を重視する。",
  }),
  makeJob({
    id: "edb-sales-development-rep-japan-7864825003",
    companySlug: "edb",
    title: "Sales Development Rep",
    segment: "Sales Development / Data Platform",
    location: "東京・日本",
    workStyle: "東京勤務。公式求人に出社頻度の明記なし",
    language: "日本市場の顧客対応。日本語・英語の詳細水準は公式求人で確認",
    source: { label: "EDB Careers (Greenhouse)", url: "https://www.enterprisedb.com/careers/job-openings?gh_jid=7864825003" },
    descriptionSummary: "日本の対象企業を調査し、データベース刷新、データ主権、AI基盤の課題から商談を作り、営業・技術担当へつなぐ。",
    genbaTake: "件数中心の接触ではなく、既存データベースの費用・人材・規制・AI準備度を仮説化し、技術部門と経営層が対話できる入口を作る役割。",
    desiredProfile: "公式求人の現行掲載を確認。担当件数、活動目標、昇格条件、利用する情報源、英語利用頻度は選考で確認したい。",
  }),
  makeJob({
    id: "3e-business-development-executive-japan-a46635ae",
    companySlug: "3e",
    title: "Business Development Executive",
    segment: "New Business / Regulatory Intelligence",
    location: "東京",
    workStyle: "Hybrid。東京オフィス勤務。担当は日本とその他のアジア太平洋地域",
    language: "日本市場を担当。日本語・英語の詳細水準は公式求人で確認",
    source: { label: "3E Careers (Ashby)", url: "https://jobs.ashbyhq.com/3E/a46635ae-4f6f-4a17-a13c-6e9f038ece17" },
    descriptionSummary: "化学・職場安全、製品安全・スチュワードシップ、供給網・持続可能性の3製品群で新規案件を作り、契約までを持つ。",
    genbaTake: "規制情報の購読販売ではなく、製品を市場へ出せない、回収や事故が起きる、供給網を説明できないリスクを投資判断へ変える新規営業。",
    desiredProfile: "公式求人は自ら案件を作る姿勢、市場分析、個別の接触設計、複雑な企業営業、規制・安全・供給網の課題理解を重視する。",
  }),
  makeJob({
    id: "3e-account-manager-japan-574f4328",
    companySlug: "3e",
    title: "Account Manager",
    segment: "Account Management / Product Compliance",
    location: "東京",
    workStyle: "Hybrid。東京オフィスへ週3日出社、月5日まで主に国内出張の可能性あり",
    language: "日本語は母語水準、英語は流暢さを求める",
    source: { label: "3E Careers (Ashby)", url: "https://jobs.ashbyhq.com/3E/574f4328-edbf-4953-80ee-68b174e12b58" },
    descriptionSummary: "日本を中心とする顧客群の更新、利用、拡大を持ち、規制・製品安全の課題から追加製品の機会を見つける。",
    genbaTake: "更新管理だけでなく、顧客の製品群、対象国、規制変更を読み、利用定着と追加投資を同じ顧客成果へ結ぶ役割。",
    desiredProfile: "公式求人はB2B営業・顧客成功・顧客管理1〜3年、日本語母語水準、英語流暢、顧客維持、更新、追加提案、Salesforce活用を求める。",
  }),
  makeJob({
    id: "mixpanel-senior-enterprise-account-executive-japan-8080832",
    companySlug: "mixpanel",
    title: "Senior Enterprise Account Executive, Japan",
    segment: "Enterprise Sales / Product Analytics",
    location: "Singapore（日本市場担当）",
    workStyle: "SingaporeのHybrid勤務。日本国内勤務、日本法人、国内拠点の記載はない",
    language: "英語は業務水準。日本市場での新規開拓経験を求めるが、日本語水準の明記はない",
    source: { label: "Mixpanel Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/mixpanel/jobs/8080832" },
    descriptionSummary: "日本の大手デジタル企業へ製品行動分析を提案し、6〜18か月の購買、正式提案、調達、情報安全審査を契約まで進める。",
    genbaTake: "画面分析のデモではなく、製品開発、成長、データ、経営の複数責任者に、何を作るべきかを早く判断する価値を共通の事業指標で示す役割。",
    desiredProfile: "公式求人は企業向けSaaSの一貫した営業7年以上、日本での新規開拓、経営層との交渉、6〜18か月の複雑な案件、業務英語を重視する。",
  }),
];
