import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内外の専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchTwentyTwo: Job[] = [
  job({
    id: "replit-growth-lead-japan-current", companySlug: "replit", title: "Growth Lead, Japan", segment: "Business Development / Japan Market", location: "東京・日本", workStyle: "Remote - Japan（東京based）", language: "日本語（native・business）／英語（bonus）",
    source: { label: "Replit Careers (Ashby)", url: "https://jobs.ashbyhq.com/replit/999e1432-3edd-453b-b598-ab4b26e1bc5c" },
    descriptionSummary: "日本のenterprise・government partnership、channel・reseller activation、education、PLG・community、market representationとpipelineを担うGrowth Lead。",
    genbaTake: "単一のsales territoryより、direct・channel・education・communityを同時に立ち上げ、product-led usageをenterprise pipelineへ変えるmarket-building role。",
    compensationReality: "日本の給与、bonus、equity、quota、pipeline target、partner creditは公式求人で確認できない。",
    desiredProfile: "公式求人は日本語native・business、Japan marketのGTM・partnership、enterprise・government、channel activation、cross-functional executionを重視。英語はbonus。", domain: "AI Software Creation・Japan Growth",
  }),
  job({
    id: "uipath-commercial-sales-account-executive-japan-current", companySlug: "uipath", title: "Commercial Sales - Account Executive", segment: "Commercial Sales / Agentic Automation", location: "東京・日本", workStyle: "On-site", language: "英語に抵抗がない方／日本語要件は明記なし",
    source: { label: "UiPath Careers (Ashby)", url: "https://jobs.ashbyhq.com/uipath/aa157f58-44d8-4532-9114-4932e8b97c1d" }, descriptionSummary: "commercial customerのnew business・expansionを担い、AI agent、robot、人を編成するautomation platformを提案するAccount Executive。", genbaTake: "RPA seatでなく、agent・robot・humanを跨ぐworkflowのcycle time、error、cost、controlを売る。", compensationReality: "日本のbase、OTE、pay mix、equity、quota、attainmentは非公開。", desiredProfile: "公式求人のsales責任とEnglishへの抵抗がないことを基準にし、日本語要件を推測しない。", domain: "Agentic Automation・Commercial Sales",
  }),
  job({
    id: "uipath-senior-business-development-representative-japan-current", companySlug: "uipath", title: "Senior Business Development Representative - Japan", segment: "Business Development / Agentic Automation", location: "東京・日本", workStyle: "On-site", language: "公式求人で人間言語の明記なし",
    source: { label: "UiPath Careers (Ashby)", url: "https://jobs.ashbyhq.com/uipath/4fc38eed-040e-441b-b24a-0a9611ce7ef9" }, descriptionSummary: "Japanのtarget accountを調査し、outbound、qualification、AE・Marketing連携でpipelineを作るSenior BDR。", genbaTake: "automation一般論でなく、業界・process別の経営課題とagentic automationの初期use caseを接続する。", compensationReality: "日本のbase、variable、OTE、quota、attainmentは非公開。", desiredProfile: "公式求人はpipeline creation、account research、outbound、AE・Marketing連携、enterprise softwareへの関心を重視。", domain: "Agentic Automation・Business Development",
  }),
  job({
    id: "uipath-enterprise-sales-associate-financial-services-japan-current", companySlug: "uipath", title: "エンタープライズ セールス アソシエイト – 金融業界担当", segment: "Enterprise Sales / Financial Services", location: "東京・日本", workStyle: "On-site", language: "英語文章に抵抗がなく、英語communicationを得意または上達したい方",
    source: { label: "UiPath Careers (Ashby)", url: "https://jobs.ashbyhq.com/uipath/5ef37d24-1557-4d47-a44a-b503c52805a7" }, descriptionSummary: "金融業界のenterprise accountでaccount planning、pipeline、商談推進を支援し、AEと連携するSales Associate。", genbaTake: "regulated workflowで効率化だけでなく、audit、human oversight、resilience、change managementを提案条件にする。", compensationReality: "日本の給与、bonus、OTE、quota、attainmentは非公開。", desiredProfile: "公式求人は金融業界、enterprise account、営業process、部門横断の実行と英語文章への抵抗がないことを重視。", domain: "Financial Services・Enterprise Automation Sales",
  }),
  job({
    id: "uipath-sales-engineer-specialist-team-japan-current", companySlug: "uipath", title: "Sales Engineer - Specialist Team", segment: "Specialist Pre-sales / Agentic Automation", location: "東京・日本", workStyle: "On-site", language: "日本語（business）／英語（business、TOEIC 800+相当）",
    source: { label: "UiPath Careers (Ashby)", url: "https://jobs.ashbyhq.com/uipath/eefc4fcf-5686-4dd2-a584-8a2848d63f5b" }, descriptionSummary: "specialist領域のdiscovery、architecture、demo・PoC、technical validationを担い、Salesとcloseを支援するSales Engineer。", genbaTake: "demo成功で終わらず、actual workflowでagent・robot・human orchestrationの精度、control、運用を実証する。", compensationReality: "日本の給与、bonus、OTE、pay mix、quotaは非公開。", desiredProfile: "公式求人はtechnical pre-sales、automation・AI、architecture、PoC、business Japaneseとbusiness Englishを重視。", domain: "Agentic Automation・Solutions Engineering",
  }),
  job({ id: "wiz-growth-account-executive-japan-smb-current", companySlug: "wiz", title: "Growth Account Executive, Japan (SMB)", segment: "SMB / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4654701006/growth-account-executive-japan-smb?gh_jid=4654701006" }, descriptionSummary: "Japan SMBのnew business、pipeline、full-cycle saleを担うGrowth AE。", genbaTake: "cloud inventoryからrisk prioritization、remediation、multi-product adoptionへ広げる。", compensationReality: "日本のbase、OTE、equity、quota、attainmentは非公開。", desiredProfile: "公式求人のcloud security・SaaS sales、pipeline、executive sellingを基準にし、言語を補完しない。", domain: "Cloud Security・SMB Sales" }),
  job({ id: "wiz-mid-enterprise-account-executive-japan-current", companySlug: "wiz", title: "Mid-Enterprise Account Executive", segment: "Mid Enterprise / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4665115006/mid-enterprise-account-executive?gh_jid=4665115006" }, descriptionSummary: "Japan mid-enterpriseのnew logo・expansion、pipeline、executive relationを担うAE。", genbaTake: "CISO・cloud・engineeringの共通risk modelを作り、Wiz Code・Cloud・Defendへexpandする。", compensationReality: "日本のbase、OTE、equity、quota、attainmentは非公開。", desiredProfile: "公式求人のenterprise SaaS・security sales、pipeline ownership、complex stakeholderを基準にする。", domain: "Cloud Security・Enterprise Sales" }),
  job({ id: "wiz-regional-partner-manager-japan-current", companySlug: "wiz", title: "Regional Partner Manager", segment: "Channel / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4685263006/regional-partner-manager?gh_jid=4685263006" }, descriptionSummary: "Japanのregional partner strategy、enablement、pipeline、co-sellを担うPartner Manager。", genbaTake: "partner数でなくsourced・influenced pipeline、technical readiness、delivery qualityを運用する。", compensationReality: "日本のbase、variable、OTE、partner targetは非公開。", desiredProfile: "公式求人のcloud・security channel、partner business plan、pipeline、cross-functional executionを重視。", domain: "Cloud Security・Channel Sales" }),
  job({ id: "wiz-senior-strategic-partner-manager-global-si-japan-current", companySlug: "wiz", title: "Senior Strategic Partner Manager - Global SI, Japan", segment: "Global SI / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "日本語・英語（fluent written・verbal）", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4685261006/senior-strategic-partner-manager-global-si-japan?gh_jid=4685261006" }, descriptionSummary: "JapanのGlobal SI alliance、joint GTM、pipeline、executive relationを担うSenior Partner Manager。global travelあり。", genbaTake: "GSIのadvisory・migration・managed serviceへWizを組み込み、repeatable offerを作る。", compensationReality: "日本のbase、variable、OTE、partner quotaは非公開。", desiredProfile: "公式求人はGSI alliance、joint GTM、executive stakeholder、日英fluent、global travelを重視。", domain: "Cloud Security・Global SI Alliances" }),
  job({ id: "wiz-senior-technical-account-manager-japan-current", companySlug: "wiz", title: "Senior Technical Account Manager", segment: "Post-sales / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4665474006/senior-technical-account-manager?gh_jid=4665474006" }, descriptionSummary: "strategic customerのtechnical adoption、risk reduction、success plan、renewal・expansionを支援するSenior TAM。", genbaTake: "alert消化でなく、coverage、critical risk、remediation SLA、adoptionをexecutive valueへ変える。", compensationReality: "日本の給与、bonus、growth target、担当社数は非公開。", desiredProfile: "公式求人のcloud security、technical account management、executive communication、customer outcomeを重視。", domain: "Cloud Security・Technical Account Management" }),
  job({ id: "wiz-solutions-engineer-japan-current", companySlug: "wiz", title: "Solutions Engineer", segment: "Pre-sales / Cloud Security", location: "Greater Tokyo・日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4665302006/solutions-engineer?gh_jid=4665302006" }, descriptionSummary: "Greater Tokyoのtechnical discovery、demo、evaluation、architecture、close支援を担うSE。出張最大50%。", genbaTake: "顧客cloudでcoverage、risk prioritization、remediation workflow、deployment effortを実測する。", compensationReality: "日本の給与、OTE、pay mix、quotaは非公開。", desiredProfile: "公式求人はcloud security、technical pre-sales、demo・evaluation、architecture、最大50% travelを重視。", domain: "Cloud Security・Solutions Engineering" }),
  job({ id: "wiz-senior-advanced-delivery-architect-japan-current", companySlug: "wiz", title: "Sr. Advanced Delivery Architect – Advanced Services, Japan", segment: "Advanced Services / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4645539006/sr-advanced-delivery-architect-advanced-services-japan?gh_jid=4645539006" }, descriptionSummary: "complex customerのarchitecture、implementation、governance、advanced services deliveryを担う。", genbaTake: "購入後のconfigurationをcloud operating model、policy、remediation、integrationへ定着させる。", compensationReality: "日本の給与、bonus、utilization target、担当project数は非公開。", desiredProfile: "公式求人のcloud security architecture、enterprise delivery、customer advisory、cross-functional executionを重視。", domain: "Cloud Security・Advanced Services" }),
  job({ id: "wiz-technical-account-manager-japan-current", companySlug: "wiz", title: "Technical Account Manager", segment: "Post-sales / Cloud Security", location: "日本", workStyle: "Remote - Japan", language: "公式求人で人間言語の明記なし", source: { label: "Wiz Careers", url: "https://www.wiz.io/careers/job/4682671006/technical-account-manager?gh_jid=4682671006" }, descriptionSummary: "customer adoption、technical success、risk reduction、renewal・expansionを担うTAM。", genbaTake: "usageだけでなくcritical risk closure、coverage、policy、stakeholder adoptionをsuccess planへ置く。", compensationReality: "日本の給与、bonus、growth target、担当社数は非公開。", desiredProfile: "公式求人のcloud・security、technical customer management、adoption、executive communicationを重視。", domain: "Cloud Security・Technical Account Management" }),
];
