import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-10-05";

export const companies20261005Daily: Company[] = [
  {
    slug: "legora",
    name: "Legora",
    category: "法務AI・リサーチ・文書業務基盤",
    broadCategory: "AI・データ基盤",
    hq: "ストックホルム（スウェーデン）",
    japanPresence: "東京のGo To Market・Legal Engineer・Engagement Manager求人を公式確認。日本法人名、オフィス所在地、国内在籍人数は未確認",
    hiringStatus: "積極採用",
    salesRoles: 4,
    description: "弁護士の調査、大量文書レビュー、起案、共同作業をAIで支援。東京で営業、導入、法務業務設計の4職種を募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/legora",
    tags: ["Legal AI", "Enterprise", "Legal Operations", "Customer Delivery", "Tokyo"],
  },
  {
    slug: "rescale",
    name: "Rescale",
    category: "クラウドHPC・デジタルエンジニアリング",
    broadCategory: "AI・データ基盤",
    hq: "サンフランシスコ（米国）",
    japanPresence: "Rescale Japan株式会社・東京。2016年に日本法人を設立し、国内顧客事例と東京のSolutions Architect求人を確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "研究開発のシミュレーション、HPC計算、データとAIを複数クラウド上で統制。日本顧客の技術評価と導入を担うSolutions Architectを募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/rescale",
    tags: ["HPC", "Digital Engineering", "Cloud", "Manufacturing", "Japan"],
  },
  {
    slug: "drata",
    name: "Drata",
    category: "セキュリティ・コンプライアンス自動化",
    broadCategory: "セキュリティ・IT運用",
    hq: "San Francisco, US",
    japanPresence: "日本法人・国内拠点・Japan専任求人は未確認。Remote APACの顧客導入求人は確認したが、日本からの応募可否は未確認",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "監査証跡の収集、統制の継続監視、顧客への信頼証明、第三者・AIリスク管理を支援。APAC導入体制の拡張を日本進出の手前の信号として観測。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/drata",
    tags: ["日本未進出", "GRC", "Compliance", "Trust", "APAC"],
    entryStatus: "not-entered",
  },
];

type JobDraft = Pick<Job, "id" | "companySlug" | "title" | "segment" | "location" | "workStyle" | "language" | "source" | "descriptionSummary" | "genbaTake" | "desiredProfile" | "compensationReality">;

function makeJob(draft: JobDraft): Job {
  return {
    ...draft,
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    careerInsights: {
      fit: `${draft.segment}で、顧客の業務・技術・組織を一つの成果責任へつなげたい人に向く。`,
      thingsToKnow: "目標、達成率、担当範囲、既存案件、国内支援体制、評価・昇進、報酬構成は公開情報だけでは十分に分からない。",
      marketValue: `${draft.segment}の成果を商談、導入、利用、更新、顧客KPIで定量化できれば、隣接する海外テクノロジー企業へ再現性を説明しやすい。`,
      tenureAndPromotion: "在籍年数だけでなく、担当拡張、顧客成果、再利用できる市場開拓・導入支援の型が次の役割の土台になる。",
      priorCompanies: "企業向け営業、コンサルティング、技術導入、複数の意思決定者を動かす顧客支援の経験が隣接する。",
      nextCompanies: "担当市場と成果を数字で残せれば、企業営業、地域リード、顧客成功、ソリューション技術、導入責任者へ広げやすい。",
    },
  };
}

export const jobs20261005Daily: Job[] = [
  makeJob({
    id: "legora-enterprise-account-executive-japan-42f62bc1",
    companySlug: "legora",
    title: "Enterprise Account Executive - Japan",
    segment: "Japan Enterprise Legal AI Sales",
    location: "Tokyo",
    workStyle: "On-site。公式求人でリモート日数の記載なし",
    language: "日本語・英語の具体的な必須水準は公式求人で要確認",
    source: { label: "Legora Careers (Ashby)", url: "https://jobs.ashbyhq.com/legora/42f62bc1-edef-4406-ab82-2dc8a09de327" },
    descriptionSummary: "日本の法律事務所・企業法務に対し、市場戦略、新規開拓、パイプライン、商談、収益まで一貫して持つ。",
    genbaTake: "AI機能の説明だけでなく、法務の調査・レビュー・起案をどう作り変えるかを経営・パートナー層と設計する市場開拓営業。",
    compensationReality: "日本の給与、変動給、目標、株式、雇用主体は公開求人で確認できない。",
    desiredProfile: "複雑な企業向け新規開拓、経営層商談、日本市場の構築を自律的に進める力が重要。",
  }),
  makeJob({
    id: "legora-engagement-manager-japan-a5cefa32",
    companySlug: "legora",
    title: "Engagement Manager - Japan",
    segment: "Japan Legal AI Adoption / Customer Transformation",
    location: "Tokyo",
    workStyle: "On-site。公式求人でリモート日数の記載なし",
    language: "日本語・英語の詳細要件は公式求人で要確認",
    source: { label: "Legora Careers (Ashby)", url: "https://jobs.ashbyhq.com/legora/a5cefa32-2f13-42c7-874d-1a4688dffcc5" },
    descriptionSummary: "法律事務所・法務組織のAI導入を、ユースケース設計、展開、利用定着、価値検証まで進める。",
    genbaTake: "導入日程の管理ではなく、弁護士の仕事の変化と利用成果まで責任を持つ変革支援職。",
    compensationReality: "日本の給与、賞与、株式、担当社数、稼働率は未記載。",
    desiredProfile: "企業変革、コンサルティング、顧客導入、複数関係者の合意形成の経験が隣接する。",
  }),
  makeJob({
    id: "legora-legal-engineer-japan-fe248f6a",
    companySlug: "legora",
    title: "Legal Engineer - Japan",
    segment: "Legal Workflow Design / Japan Customer Enablement",
    location: "Tokyo",
    workStyle: "On-site。公式求人でリモート日数の記載なし",
    language: "日本の法務実務と顧客対応に必要な日本語、グローバル連携の英語水準は選考で要確認",
    source: { label: "Legora Careers (Ashby)", url: "https://jobs.ashbyhq.com/legora/fe248f6a-1d3e-4ac1-af36-a09c32d42e95" },
    descriptionSummary: "弁護士の業務と判断を理解し、調査・レビュー・起案をLegora上の再現可能な活用方法へ変える。",
    genbaTake: "法務知識をソフトウェアの導入と業務設計に変換する、法律と製品の境界職。",
    compensationReality: "日本の給与、賞与、株式、業務量、資格手当は未記載。",
    desiredProfile: "弁護士・法務の実務理解、技術への好奇心、顧客と業務を言語化する力が重要。",
  }),
  makeJob({
    id: "legora-director-legal-engineer-japan-3aa07833",
    companySlug: "legora",
    title: "Director Legal Engineer, Japan",
    segment: "Japan Legal Engineering Leadership",
    location: "Tokyo",
    workStyle: "On-site。公式求人でリモート日数の記載なし",
    language: "日本語・英語の詳細要件は公式求人で要確認",
    source: { label: "Legora Careers (Ashby)", url: "https://jobs.ashbyhq.com/legora/3aa07833-d767-4a8c-a7e6-cbe95e3d1d3f" },
    descriptionSummary: "日本のLegal Engineering機能を率い、重要顧客の法務業務設計、導入品質、チーム構築を持つ。",
    genbaTake: "製品売上と利用定着の間にある法務業務の設計を、日本市場の機能として立ち上げる責任者。",
    compensationReality: "日本の年収、賞与、株式、部下人数、評価指標は未記載。",
    desiredProfile: "法務実務、組織・顧客リーダーシップ、AIを業務へ組み込む変革設計の経験が重要。",
  }),
  makeJob({
    id: "rescale-solutions-architect-japan-08a43132",
    companySlug: "rescale",
    title: "Solutions Architect (Japan)",
    segment: "Japan Solutions Architecture / Digital Engineering",
    location: "Tokyo",
    workStyle: "公式求人で出社頻度とリモート条件の詳細は未記載",
    language: "日本語・英語の業務水準は選考で要確認",
    source: { label: "Rescale Careers (Ashby)", url: "https://jobs.ashbyhq.com/rescale/08a43132-a891-42b8-9aa3-feb0a2a49c83" },
    descriptionSummary: "日本の研究開発顧客の計算・ソフトウェア・IT環境を理解し、技術評価、アーキテクチャ、導入と価値説明を担う。",
    genbaTake: "計算資源の販売ではなく、解析ソフト、クラウド、セキュリティ、研究データを研究開発の速度と費用へ結びつける技術提案職。",
    compensationReality: "日本の給与、賞与、株式、目標、出張頻度は未記載。",
    desiredProfile: "HPC、クラウド、CAE・シミュレーション、顧客向け技術設計の経験が隣接する。",
  }),
];
