import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-22";

export const companies20260822JapanFive: Company[] = [
  {
    slug: "workiva",
    name: "Workiva",
    category: "連結報告・開示・リスク統合プラットフォーム",
    broadCategory: "経営管理・FinTech",
    hq: "アイオワ州エイムズ（米国）",
    japanPresence: "東京拠点・日本担当Account Executive求人を確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "財務報告、開示、監査、リスク、サステナビリティのデータと証跡を一つの統制されたworkflowへつなぐ。東京でnew businessと既存顧客拡張を担うAccount Executiveを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://workiva.wd503.myworkdayjobs.com/en-US/careers/job/Account-Executive_R10985",
    tags: ["CFO", "Financial Reporting", "Disclosure", "GRC", "Sustainability", "Enterprise Sales", "Tokyo"],
  },
  {
    slug: "outsystems",
    name: "OutSystems",
    category: "AIアプリ開発・ローコード基盤",
    broadCategory: "AI・データ基盤",
    hq: "ボストン（米国）／リスボン（ポルトガル）",
    japanPresence: "東京office・日本法人・複数の日本向け求人を確認",
    hiringStatus: "積極採用",
    salesRoles: 1,
    description: "mission-critical applicationの新規開発、legacy modernize、AI agent開発とgovernanceを一つのplatformで支える。東京でEnterprise新規開拓を担うSenior Account Executiveを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://outsystems.wd503.myworkdayjobs.com/en-US/OutSystems/job/Senior-Account-Executive_R1544",
    tags: ["Low-code", "AI Development", "App Modernization", "Enterprise", "New Logo", "Partner", "Tokyo"],
  },
  {
    slug: "sailpoint",
    name: "SailPoint",
    category: "Identity Security・アクセスガバナンス",
    broadCategory: "セキュリティ・IT運用",
    hq: "テキサス州オースティン（米国）",
    japanPresence: "東京local office・Japan remoteを含む専門営業求人を確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "人、machine、AI agentがどのdata・applicationへaccessできるかを統制するIdentity Security platform。日本でAgentic Technologyのspecialist AEを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://sailpoint.wd1.myworkdayjobs.com/en-US/SailPoint/job/Strategic-Account-Executive--Agentic-Technologies-Specialist--Japan_R013034-1",
    tags: ["Identity Security", "IGA", "Machine Identity", "Data Access", "Agentic AI", "Overlay Sales", "Japan"],
  },
  {
    slug: "pingcap",
    name: "PingCAP",
    category: "分散SQL・HTAP・cloud database",
    broadCategory: "AI・データ基盤",
    hq: "サンマテオ（米国）",
    japanPresence: "PingCAP株式会社（2021年設立）・東京office・Japan Business Groupを確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "MySQL互換の分散SQL database TiDBで、scale、可用性、transactionとanalyticsの統合を支える。東京でPoC・benchmark・architectureを担うSolution Architectを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.lever.co/pingcap/5de30748-2a1e-45be-bea5-ddf514d3719c",
    tags: ["TiDB", "Distributed SQL", "HTAP", "Cloud Database", "Solution Architect", "PoC", "Tokyo"],
  },
  {
    slug: "think-cell",
    name: "think-cell",
    category: "PowerPoint資料作成・data storytelling生産性",
    broadCategory: "業務自動化・コラボレーション",
    hq: "ベルリン（ドイツ）",
    japanPresence: "東京office・日本向けMarketing求人を確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "PowerPoint内のchart、layout、data link、template運用を自動化し、分析・意思決定へ使う時間を増やす。東京で日本市場のcampaign、event、partner・influencer施策を担うMarketing Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://job-boards.eu.greenhouse.io/think-cell/jobs/4953129101",
    tags: ["PowerPoint", "Productivity", "Data Storytelling", "B2B Marketing", "Events", "Partnerships", "Tokyo"],
  },
];

function careerInsights(domain: string, roleEvidence: string, marketValue: string): Job["careerInsights"] {
  return {
    fit: `${domain}を機能説明で終わらせず、顧客の業務KPIと導入・定着の設計へ変えたい人に向く。`,
    thingsToKnow: "日本のbase、OTE、quota、担当社数、達成率、ramp、昇進・離職の集計は公式求人で確認できない。配属先の分母と期間を面接で確認したい。",
    marketValue,
    tenureAndPromotion: `【Genba仮説】次のscopeは在籍年数より、${roleEvidence}を定量成果として再現できるかで決まる。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習と目標責任を求める。反証・留保: 日本teamの昇進率・離職率、level別の標準在籍期間、評価分布は未公開で、在籍年数だけから昇進可能性は読めない。面接で確認: 直近24カ月の昇進・異動・退職の分母、次levelへ進んだ人の共通成果、performance reviewの周期は。`,
    priorCompanies: `【Genba仮説】${domain}に近い顧客課題、複数stakeholder、目標責任を持ち、複雑な案件を社内専門家と進めた人が隣接する。支持材料: 公式求人はrole固有のdomain、顧客折衝、部門横断の実行、成果責任を要件にする。反証・留保: 日本の同一roleを4件以上の同一条件で集計できず、特定社・特定業界からの採用傾向は断定しない。面接で確認: 直近採用者の前職category上位3つ、採用時に評価した共通skill、入社後に不足しやすい知識、標準ramp期間は。`,
    nextCompanies: `【Genba仮説】${marketValue}を数字と具体例で残せれば、隣接するEnterprise SaaSの専門職、上位segment、leadershipへ接続しやすい。支持材料: 公式求人が顧客成果、複数stakeholder、社内外の協働、目標ownershipを求めており、これらは隣接categoryでも説明可能な実績になる。反証・留保: 公開された日本在籍者の転職先分布ではなく、職務構造からの仮説で、実際の選択肢は担当規模、成果、英語、採用市場で変わる。面接で確認: alumniの次role category、社内異動例、次の職位で必要な定量成果は。`,
  };
}

export const jobs20260822JapanFive: Job[] = [
  {
    id: "workiva-account-executive-japan-r10985",
    companySlug: "workiva",
    title: "Account Executive - Japan",
    segment: "Enterprise / New Business & Expansion",
    location: "東京",
    workStyle: "Flexible work（出社頻度は未記載）",
    language: "公式求人で明記なし",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Workiva Careers (Workday)", url: "https://workiva.wd503.myworkdayjobs.com/en-US/careers/job/Account-Executive_R10985" },
    descriptionSummary: "CFO、CRO、Sustainability等のexecutive buyerへnew businessと既存顧客拡張を進め、Inside Sales、Solution Seller、Partnerと複雑なsales cycleをcloseする。",
    genbaTake: "開示toolを売るだけでなく、決算・監査・risk・sustainabilityで分断したdata、証跡、approvalを経営管理の統制設計として束ねる営業。",
    compensationReality: "日本向けのbase、OTE、equity、quota、accelerator、ramp保証は公式求人で確認できない。",
    desiredProfile: "関連sales経験4年以上、executive buyer向けEnterprise technology・SaaS、複数の複雑商談、valueを保つ価格交渉を求める。出張は最大30%。",
    careerInsights: careerInsights("財務報告・開示・GRC", "new logo、expansion、partner influence、executive sale", "CFO領域、connected reporting、GRC、value selling、partner協業の実績"),
  },
  {
    id: "outsystems-senior-account-executive-enterprise-r1544",
    companySlug: "outsystems",
    title: "Senior Account Executive (Enterprise)",
    segment: "Enterprise / Strategic Named Accounts",
    location: "東京",
    workStyle: "Hybrid / Office-based、正社員",
    language: "日本語native/fluent、英語business level",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "OutSystems Careers (Workday)", url: "https://outsystems.wd503.myworkdayjobs.com/en-US/OutSystems/job/Senior-Account-Executive_R1544" },
    descriptionSummary: "日本のEnterpriseでnew market share獲得とstrategic named accountを担い、technical・business要件の検証、partner co-sell、高額契約の交渉まで進める。",
    genbaTake: "low-codeの開発速度だけでなく、legacy system、内製化、AI agent、governance、SI deliveryを長期のmodernization programへ束ねる営業。",
    compensationReality: "競争力ある報酬との記載はあるが、日本のbase、OTE、equity、quota、pay mixは未確認。",
    desiredProfile: "日本でのEnterprise software direct sales 10年以上、application development・SaaS・PaaS・cloud 3年以上、local/global SIや商社とのco-sell実績を求める。",
    careerInsights: careerInsights("Enterprise application modernization", "new logo、named account、SI ecosystem、complex deal", "AI development platform、legacy modernization、partner-led GTM、大型Enterprise dealの実績"),
  },
  {
    id: "sailpoint-strategic-ae-agentic-technologies-r013034",
    companySlug: "sailpoint",
    title: "Strategic Account Executive, Agentic Technologies Specialist, Japan",
    segment: "Enterprise / Specialist Overlay Sales",
    location: "東京office / Japan remote",
    workStyle: "Local OfficeまたはRemote、Full-time",
    language: "公式求人で明記なし",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "SailPoint Careers (Workday)", url: "https://sailpoint.wd1.myworkdayjobs.com/en-US/SailPoint/job/Strategic-Account-Executive--Agentic-Technologies-Specialist--Japan_R013034-1" },
    descriptionSummary: "Machine Identity、Data Access、Agent Identityを日本で拡張し、primary AE・CS・BDをenableしながらterritory plan、demo、RFP、partner施策、quotaを持つoverlay sales。",
    genbaTake: "AI agentが増えるほど『誰が何へaccessできるか』の主体が人以外へ広がる。security、data、AI、enterprise architectureを一つのrisk storyへ束ねる専門営業。",
    compensationReality: "日本向けのbase、OTE、equity、specialist credit、quota、acceleratorは公式求人で確認できない。",
    desiredProfile: "Identity・cybersecurityに加え、agentic technology、data architecture・governance、cloud、specialist overlay、matrix sellingの経験を重視する。",
    careerInsights: careerInsights("Identity Security・AI governance", "overlay influence、primary AE enablement、identity intelligence pipeline", "Identity・cybersecurity、machine・agent identity、data access governance、specialist salesの実績"),
  },
  {
    id: "pingcap-solution-architect-japan-5de30748",
    companySlug: "pingcap",
    title: "Solution Architect",
    segment: "Pre-Sales / Database Modernization",
    location: "東京",
    workStyle: "Hybrid、Full-time、full flex・remote可",
    language: "日本語business level以上（英語要件は未記載）",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "PingCAP Careers (Lever)", url: "https://jobs.lever.co/pingcap/5de30748-2a1e-45be-bea5-ddf514d3719c" },
    descriptionSummary: "顧客のtechnical advisorとしてarchitectureを設計し、PoC・benchmark、reference architecture、partner支援、製品feedback、community発信を担う。",
    genbaTake: "database機能のdemoではなく、sharding・scale・HA/DR・migration・cloud costをproduction riskとbusiness growthへ翻訳するtechnical sale。",
    compensationReality: "競争力ある給与・応相談との記載はあるが、base、variable、equity、bonus、rangeは未確認。",
    desiredProfile: "AWS/Azure/GCP、Oracle・SQL Server・MySQL・PostgreSQL、sharding、programming、DB設計を求め、consulting sale・新市場開拓・migration経験を歓迎する。",
    careerInsights: careerInsights("分散SQL・database modernization", "PoC、benchmark、architecture、product feedback", "distributed database、cloud migration、HA/DR、technical value selling、community発信の実績"),
  },
  {
    id: "think-cell-customer-enablement-trainer-japan-4727026101",
    companySlug: "think-cell",
    title: "Software Trainer - Japanese-speaking / Customer Enablement Specialist",
    segment: "Customer Enablement / Adoption & Expansion",
    location: "東京",
    workStyle: "Full-time（出社頻度は現行求人本文で未確認）",
    language: "日本語native、英語必須",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "think-cell Careers (Greenhouse)", url: "https://job-boards.eu.greenhouse.io/think-cell/jobs/4727026101" },
    descriptionSummary: "日本・一部APAC顧客へtraining、workshop、best practice、trial・PoCを提供し、AEとaccount growth・churn riskに対応しながらproduct feedbackを還流する。",
    genbaTake: "training回数ではなく、資料作成時間、brand consistency、data更新、利用部門の広がりを測り、seat利用を意思決定の生産性へ変えるrole。",
    compensationReality: "希望給与の入力欄はあるが、base、bonus、equity、range、評価KPIは公式求人で確認できない。",
    desiredProfile: "Customer Enablement・CS・Account Management 5年以上、training設計・実施、demo・trial、CRM、native日本語・英語を求める。",
    careerInsights: careerInsights("資料作成・data storytellingの生産性", "training、adoption、trial、churn対応、account growth", "Customer Enablement、adoption analytics、training design、expansion支援の実績"),
  },
  {
    id: "think-cell-marketing-manager-japan-4953129101",
    companySlug: "think-cell",
    title: "Marketing Manager - Japan",
    segment: "Japan Marketing / B2B Demand & Brand",
    location: "東京",
    workStyle: "Full-time（出社頻度は公式求人で未確認）",
    language: "日本語・英語",
    firstSeen: "2026-08-28",
    lastChecked: "2026-08-28",
    source: { label: "think-cell Careers (Greenhouse)", url: "https://job-boards.eu.greenhouse.io/think-cell/jobs/4953129101" },
    descriptionSummary: "日本市場のmulti-channel campaign、event、partner・influencer施策、sales enablementを企画・実行し、認知、engagement、growthへつなぐ。",
    genbaTake: "global messagingの翻訳ではなく、日本のconsulting・finance・PowerPoint利用者へ届くchannelとeventを作り、campaign performanceを次の投資判断へ戻す役割。",
    compensationReality: "日本向けのbase、bonus、equity、budget、pipeline目標、評価KPIは公式求人で確認できない。",
    desiredProfile: "日本市場のB2B marketing 5年以上、campaign、event、partner・influencer、analysis、Salesforce・Marketo、日本語・英語を求める。",
    careerInsights: careerInsights("B2B productivity software marketing", "campaign、event、partner、brand、sales enablement", "Japan field marketing、demand generation、partner marketing、regional strategyの実績"),
  },
];
