import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内外の専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchFourteen: Job[] = [
  job({
    id: "planet-account-executive-defence-intelligence-japan-current",
    companySlug: "planet",
    title: "Account Executive, Defence & Intelligence",
    segment: "Government / Defence & Intelligence",
    location: "日本",
    workStyle: "日本拠点のフルタイムRemote（office近隣居住者は週3日office）",
    language: "日本語（fluent）／英語（company working language）",
    source: { label: "Planet Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/planetlabs/jobs/7564777" },
    descriptionSummary: "日本政府のIntelligence・Defense・National Security領域でpipeline、partner、政府調達、full-cycle saleを担う。出張は最大10%。",
    genbaTake: "高解像度画像の単品販売でなく、near-daily monitoring、change detection、archive、APIとSAR・UAV・taskingへのcueingを継続的な情報workflowへ組み込む。",
    compensationReality: "日本の給与、base、OTE、pay mix、equity額、quota、attainmentは公式求人で確認できない。応募フォームは希望base salaryの入力のみ。",
    desiredProfile: "公式求人はenterprise solution sales 6年以上、日本政府営業6年以上、政府調達、partner ecosystem、full-cycle・quota責任、日本語と英語を重視。",
    domain: "Earth Observation・Defence Intelligence Sales",
  }),
  job({
    id: "rubrik-customer-experience-manager-japan-current",
    companySlug: "rubrik",
    title: "Customer Experience Manager",
    segment: "Customer Experience / Data Security",
    location: "東京・日本",
    workStyle: "公式求人で明記なし",
    language: "日本語（native・business fluent、JLPT N1相当）／英語（native・business fluent、TOEIC 900+相当）",
    source: { label: "Rubrik Careers (Greenhouse)", url: "https://www.rubrik.com/company/careers/departments/job.8121366?gh_jid=8121366" },
    descriptionSummary: "顧客ライフサイクル、主要案件・escalation、customer advocacy、Rubrik footprint growthを担うCustomer Experience role。状況により標準時間外対応と顧客訪問がある。",
    genbaTake: "support escalationで終わらず、protection coverage、recovery readiness、adoption、executive value、renewal・expansionを同じsuccess planへ置く。",
    compensationReality: "日本の給与、bonus、variable、growth target、担当社数は公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise Customer Experience、technical escalation、executive communication、顧客擁護、日英business fluencyを重視。",
    domain: "Data Security・Customer Experience",
  }),
  job({
    id: "rubrik-mid-market-account-executive-tokyo-current",
    companySlug: "rubrik",
    title: "Mid Market Account Executive | Tokyo",
    segment: "Mid Market / Data Security",
    location: "東京・日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Rubrik Careers (Greenhouse)", url: "https://www.rubrik.com/company/careers/departments/job.8014986?gh_jid=8014986" },
    descriptionSummary: "new opportunity、pipeline、account strategy、existing expansionを担い、distributor・VAR・partnerと共同販売するMid Market AE。",
    genbaTake: "backup更新でなく、immutable protection、clean recovery、identity・SaaS・AI agentのresilienceをbusiness continuityと復旧KPIへ変える。",
    compensationReality: "日本の給与、base、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はIT infrastructure・SaaS technology sales 3年以上、new business、account planning、partner co-sell、forecast ownershipを重視。",
    domain: "Data Security・Mid Market Sales",
  }),
  job({
    id: "replit-founding-account-executive-japan-current",
    companySlug: "replit",
    title: "Founding Account Executive (Japan)",
    segment: "Founding AE / Enterprise AI Software Creation",
    location: "日本",
    workStyle: "当初Remote／local office開設後Hybridへ移行予定（都市は明記なし）",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Replit Careers (Ashby)", url: "https://jobs.ashbyhq.com/replit/bcfdb564-48c9-42c9-ab5b-c901b6babb44" },
    descriptionSummary: "Japanのfull-cycle net-new、demo・hackathon、negotiation、forecast、adoption・expansionを担うFounding AE。出張は最大25%。",
    genbaTake: "AI coding seatでなく、business builderがideaからfull-stack app・deployまで進め、ITがsecurity・governance・handoffを統制できるoperating modelを売る。",
    compensationReality: "Competitive Salary & Equityの定性記載のみ。日本のbase、OTE、pay mix、commission、equity額、quota、attainmentは非公開。",
    desiredProfile: "公式求人はAEまたはSE・technical sales、SaaS・developer tools、quota実績、SDLC・coding理解、AI関心、非技術者向けdemo・hackathonを重視。",
    domain: "AI Software Creation・Founding Enterprise Sales",
  }),
  job({
    id: "saviynt-associate-principal-training-engineer-japan-current",
    companySlug: "saviynt",
    title: "Associate Principal Training Engineer",
    segment: "Customer・Partner Enablement / Identity Security",
    location: "日本",
    workStyle: "Hybrid（出社頻度は非公開）",
    language: "公式求人で必須の人間言語は明記なし（multiple languagesは歓迎）",
    source: { label: "Saviynt Careers (Lever)", url: "https://jobs.lever.co/saviynt/50e5339d-4983-4712-8b90-29334968c8fc" },
    descriptionSummary: "customer・partner・employee向けのlive・virtual技術研修、curriculum、labを設計・提供する。非標準時間対応と最大50%の出張がある。",
    genbaTake: "identity platformの機能説明で終わらず、customer・partnerが導入、運用、認定を自走できるenablement systemを作る。",
    compensationReality: "日本の給与、bonus、equity、target、出張手当は公式求人で確認できない。",
    desiredProfile: "公式求人はidentity securityの技術理解、instructional design、live・virtual training、lab構築、customer・partner enablementを重視。",
    domain: "Identity Security・Technical Enablement",
  }),
  job({
    id: "saviynt-principal-engineer-professional-services-japan-current",
    companySlug: "saviynt",
    title: "Principal Engineer, Professional Services",
    segment: "Professional Services / Identity Governance",
    location: "日本",
    workStyle: "Hybrid（出社頻度は非公開）",
    language: "日本語（proficiency）／英語（adequate verbal・written）",
    source: { label: "Saviynt Careers (Lever)", url: "https://jobs.lever.co/saviynt/1b00bb96-f748-485d-b638-6311bf13b006" },
    descriptionSummary: "IGAの要件、設計、設定、test、deploymentをend-to-endで所有し、customer・partnerへtechnical advisoryを行う。日本在住・就労許可が必要。",
    genbaTake: "JML、SoD、access review、PAMを顧客のidentity source・application・audit processへ実装し、PoCを本番controlへ移す。",
    compensationReality: "日本の給与、bonus、equity、billable target、担当project数は公式求人で確認できない。",
    desiredProfile: "公式求人はIGA設計・実装、customer advisory、configuration・testing・deployment、日英communicationを重視。",
    domain: "Identity Governance・Professional Services",
  }),
  job({
    id: "saviynt-staff-solutions-engineer-japan-current",
    companySlug: "saviynt",
    title: "Staff Solutions Engineer",
    segment: "Pre-sales / Identity Security",
    location: "日本",
    workStyle: "Hybrid（出社頻度は非公開）",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Saviynt Careers (Lever)", url: "https://jobs.lever.co/saviynt/9cbfe1f0-997f-469b-a31e-a96cbd15c47b" },
    descriptionSummary: "discovery、RFP・RFx、POC、technical presentation、opportunity close支援とSE coachingを担う。出張は最大60%。",
    genbaTake: "human・non-human・AI identityの発見、governance、runtime authorizationを顧客環境で検証し、technical criteriaを購買判断へ変える。",
    compensationReality: "日本の給与、base、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise identity securityのdiscovery、architecture、POC、RFP、technical selling、SE coachingを重視。",
    domain: "Identity Security・Solutions Engineering",
  }),
  job({
    id: "saviynt-strategic-account-executive-japan-current",
    companySlug: "saviynt",
    title: "Strategic Account Executive",
    segment: "Strategic Enterprise / Identity Security",
    location: "日本",
    workStyle: "Hybrid（出社頻度は非公開）",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Saviynt Careers (Lever)", url: "https://jobs.lever.co/saviynt/e309fb59-65aa-486d-ada7-6f06fc3c0c58" },
    descriptionSummary: "large enterpriseのpipeline generation・progression、customer・partner、renewalを担う。MEDDPICC・Command of the Messageと12年以上のenterprise salesを重視。",
    genbaTake: "legacy IGA・PAMの置換でなく、human、external、workload、AI agentのaccessをsingle control planeへまとめ、audit・risk・business speedを売る。",
    compensationReality: "competitive total rewardsとdiscretionary bonus eligibilityのみ。日本のbase、OTE、pay mix、quota、attainmentは非公開。",
    desiredProfile: "公式求人はenterprise sales 12年以上、pipeline ownership、MEDDPICC、executive・partner selling、renewalを重視。",
    domain: "Identity Security・Strategic Enterprise Sales",
  }),
];
