import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildPreEntryIntelligence } from "@/lib/company-public-intelligence-pre-entry-wave-two";

const ripplingIntelligence: CompanyPublicIntelligence = buildPreEntryIntelligence({
  slug: "rippling", name: "Rippling", homepage: "https://www.rippling.com/", growthUrl: "https://www.rippling.com/en-AU/careers", careersUrl: "https://www.rippling.com/en-AU/careers/open-roles", customersUrl: "https://www.rippling.com/customers", trustUrl: "https://www.rippling.com/security", apacUrl: "https://www.rippling.com/en-AU/company/about", externalUrl: "https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou.html", linkedinUrl: "https://www.linkedin.com/company/rippling/",
  salesSnapshot: "Ripplingは、経営・HR・Finance・ITに、employee dataを軸に人事、給与、benefits、expense、device、identityを統合するWorkforce Platformを提供する会社。顧客が抱えるのは「国・法人ごとにHRとpayrollが分断する」「入退社の権限・device・支払処理が手作業になる」「従業員dataを使ったworkflowを部門横断で自動化できない」という3つの課題。HRISから入り、global payroll、spend、IT、identity、workflowへ拡張できる点が営業としての面白さ。",
  growthSummary: "6,000人超、累計14億ドル超の調達、前年比3倍の成長を公式careersで発信。SydneyとSingaporeに拠点を持ち、50カ国でglobal employment productを展開する一方、Japan・Tokyo拠点と求人は未確認。",
  verdict: "日本進出の可能性は中。APAC組織と投資余力は強いが、給与・労務のlocalizationが最大障壁", entryNarrative: "Ripplingは6,000人超、累計14億ドル超の資本、Sydney・SingaporeのAPAC足場を持ち、HR・Finance・ITをemployee graphで束ねる明確なplatform valueがある。日本企業の人事・IT分断、入退社automation、外資系企業のmulti-country運用とは親和性が高い。一方、日本の給与計算、社会保険、労務、税、年末調整、マイナンバー、個人情報、local supportは国別に深い実装が必要で、英語UIのcross-border販売だけでは継続利用を作りにくい。まずglobal企業のJapan entityをSingaporeから支援し、payroll partnerまたはEOR連携で国内accuracyとsupportを証明できれば、専任Japan podが現実的になる。",
  headcount: "6,000人超", headcountDetail: "会社公式careersが公表するグローバル社員規模。", apacPresence: "SydneyとSingaporeにofficeを置き、Australia・Singaporeで営業、product、support、採用を展開。", productLanguage: "global employmentを50カ国で提供するが、日本語site、Japan payroll、国内support、国内顧客事例の公式同等性は確認できない。",
  milestones: [{ year: "2016", label: "創業", detail: "employee systemを一つのdata modelで統合する会社として創業。", source: "company" }, { year: "2022", label: "global展開", detail: "Global Payroll・Employer of Record等へ拡張。", source: "growth" }, { year: "2023", label: "Australia launch", detail: "Australia市場へ正式展開。", source: "apac" }, { year: "2025", label: "APAC拡張", detail: "Sydney・Singaporeのregional hiringを拡大。", source: "apac" }, { year: "2026", label: "6,000人超", detail: "累計14億ドル超、3倍成長をcareersで発信。", source: "growth" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "顧客はHRISを入れ替えるだけでなく、onboarding時のpayroll、benefits、app権限、device、expenseをemployee recordから一括automationする。買い手はHRだけでなくFinance・ITへ広がる。" }, { title: "製品の成り立ちから見る課題", body: "複数systemを後からintegrationするのではなく、employee graphとpolicy engineを共通基盤にしてHR・Finance・IT applicationを同じdataで動かす。source of truthの分断そのものを解く設計。" }, { title: "外部環境の要求から見る課題", body: "global hiringとremote workで国別の雇用・給与・権限管理が複雑化する一方、日本では労働・社会保険・税・個人情報のlocal accuracyが必須。global standardと国内制度を同時に満たす必要がある。" }],
  narrative: [{ label: "背景", body: "企業は国と部門ごとにHRIS、payroll、expense、device、identityを増やし、employee dataを重複管理する。" }, { label: "課題", body: "入社・異動・退職のたびに複数teamが同じdataを手入力し、権限剥奪、給与、承認、監査でerrorと遅延が起きる。" }, { label: "解決策", body: "一つのemployee lifecycleでsystem、owner、policyを接続し、onboarding時間、manual task、error、access残存、support ticketを測る。" }, { label: "選定の理由", body: "Workday、SAP、SmartHR、freee、Deel、Oktaとの比較で、HR・Finance・ITを同じemployee graphとworkflowで動かし、globalとlocalを両立できる場合に選ばれる。" }],
  openingHook: "一人の入社・異動・退職で、HR、Finance、ITは同じemployee dataを何systemへ何回入力していますか。", valueHypothesis: "対象lifecycleで処理時間、manual task、payroll error、access残存、device回収、support ticket、admin costを測る。", objection: "日本では既存HR・給与systemと社労士連携で十分。", reframe: "給与機能単体ではなく、employee changeがHR・Finance・ITへ何分で正確に反映されるか、global entityを含めたtotal admin costで比較する。",
  facts: [{ label: "社員", value: "6,000人超", detail: "会社公式careers。", source: "growth" }, { label: "累計調達", value: "14億ドル超", detail: "会社公式careers。", source: "growth" }, { label: "成長", value: "前年比3倍", detail: "会社公式careersの表現。", source: "growth" }, { label: "global雇用", value: "50カ国", detail: "公式global product発表。", source: "company" }, { label: "APAC", value: "Sydney / Singapore", detail: "公式office一覧。", source: "apac" }, { label: "日本求人", value: "未確認", detail: "Japan・Tokyo勤務地を確認できず。", source: "careers" }],
  customers: [{ company: "Clay", products: "Rippling", outcome: "成長企業のHR・IT operations統合を顧客事例で紹介。", implication: "technology企業のhigh-growth motion。" }, { company: "Superhuman", products: "Rippling", outcome: "employee lifecycleのautomationを公開事例化。", implication: "small HR/IT teamのadmin削減。" }, { company: "Chess.com", products: "Rippling", outcome: "distributed workforce管理を顧客事例で紹介。", implication: "multi-location・global expansionへ提案できる。" }],
  externalSignals: [{ label: "日本の雇用制度", value: "国別実装が必要", detail: "厚生労働省は労働、雇用、社会保険に関する制度と手続きを所管。", caveat: "Ripplingが日本制度へ対応済みであることを示さない。" }, { label: "人事DX", value: "data連携需要", detail: "人手不足とhybrid workで入退社・勤怠・権限のautomation需要が増える。", caveat: "効果は既存systemとprocess標準化で異なる。" }],
  entryAssessment: {
    verdict: "進出可能性は中。APAC scaleは十分だがJapan payrollと労務localizationの完成が前提",
    factSignals: [{ title: "APACの現地運営", body: "Sydney・Singaporeにofficeと求人を持ち、Asia Pacificをremote coverageだけでなく現地組織で運営。", sourceIds: ["apac", "careers"] }, { title: "投資余力と組織規模", body: "6,000人超、累計14億ドル超、前年比3倍の会社発表は新countryへ投資できる規模。", sourceIds: ["growth"] }, { title: "global employment product", body: "50カ国向けにglobal employment suiteを展開し、国別運用をproduct化する能力を示す。", sourceIds: ["company"] }, { title: "日本課題との親和", body: "HR・Finance・ITの分断、入退社automation、global entity管理は国内外資・成長企業にも存在する。", sourceIds: ["external", "company"] }],
    hurdles: [{ title: "給与・社会保険localization", body: "日本の給与、社保、税、年末調整、労務手続きに継続的な制度更新とaccuracyが必要。", sourceIds: ["external"] }, { title: "強い国内suite", body: "SmartHR、freee、マネーフォワード、奉行等がlocal機能、partner、brandを持つ。", sourceIds: ["external"] }, { title: "data residencyと個人情報", body: "employee・給与・identity dataの保存、越境、権限、監査を国内顧客へ説明する必要。", sourceIds: ["trust"] }, { title: "platform saleの導入負荷", body: "HRIS置換だけでなくFinance・ITも変えるため、implementationとchange managementが大きい。", sourceIds: ["customers", "company"] }],
    readinessConditions: [{ title: "Japan payroll accuracy", body: "給与・税・社会保険・年末調整をpartnerまたは自社でproduction実証。" }, { title: "lighthouse customers", body: "global企業の日本法人と国内scale-upで継続利用・renewalを証明。" }, { title: "local implementation", body: "日本語support、migration、社労士・payroll partnerを整備。" }, { title: "Japan product scope", body: "HR、Payroll、IT、Spendの提供順と責任範囲を明確化。" }, { title: "dedicated pod", body: "Country lead、AE、Solution、Implementation、Supportを日本専任で配置。" }],
    watchSignals: ["Japan・Tokyo求人", "日本語site", "Japan payroll提供国への追加", "国内payroll・社労士partner", "日本顧客事例", "Singapore teamのJapan territory表記"],
  },
  sourceIds: ["growth", "company", "careers", "customers", "trust", "apac", "external", "linkedin"], salesMotion: "CHRO・CFO・CIOへemployee lifecycleのmanual workから入り、HRIS、global payroll、IT、Spendをphase展開するplatform sale。", careerValue: "HR Tech、FinTech、identity、global employment、country buildを横断する可能性。", leader: { name: "Parker Conrad", role: "CEO / Co-founder", read: "employee systemを単体applicationの集合ではなく、共通dataとpolicyで動くbusiness systemとして再設計。" },
  solutions: [{ name: "Rippling HCM", valueProp: "HRIS、Payroll、Benefits、Timeをemployee graphで統合。", url: "https://www.rippling.com/products/hr", competitors: "Workday、SAP、SmartHR、freee。", differentiation: "Finance・ITと同じdata・workflowを利用。" }, { name: "Global Workforce", valueProp: "global payroll、EOR、contractorを複数国で管理。", url: "https://www.rippling.com/products/global", competitors: "Deel、Remote、Papaya Global。", differentiation: "core HR・IT・Spendと一つのemployee system。" }, { name: "IT / Identity", valueProp: "app権限、device、securityを入退社とautomation。", url: "https://www.rippling.com/products/it", competitors: "Okta、Microsoft、MDM。", differentiation: "HR eventがaccess・device workflowを直接trigger。" }],
  fitTags: ["日本未進出", "HR Tech", "Payroll", "IT", "FinTech", "APAC", "Platform", "Enterprise"], comparisons: [{ arena: "HCM", companies: ["Rippling", "Workday", "SmartHR"], why: "suite、localization、implementation" }, { arena: "Global payroll", companies: ["Rippling", "Deel", "Remote"], why: "country coverageとsystem breadth" }, { arena: "IT lifecycle", companies: ["Rippling", "Okta", "Microsoft"], why: "HR eventとaccess automation" }],
});

const pineconeIntelligence: CompanyPublicIntelligence = buildPreEntryIntelligence({
  slug: "pinecone", name: "Pinecone", homepage: "https://www.pinecone.io/", growthUrl: "https://www.pinecone.io/newsroom/Pinecone-Launches-First-Serverless-Region-in-Asia/", careersUrl: "https://www.pinecone.io/careers/", customersUrl: "https://www.pinecone.io/customers/", trustUrl: "https://www.pinecone.io/security/", apacUrl: "https://www.pinecone.io/launch-week/", externalUrl: "https://www.meti.go.jp/policy/it_policy/ai-governance/index.html", linkedinUrl: "https://www.linkedin.com/company/pinecone-io/",
  salesSnapshot: "Pineconeは、CTO・AI platform・Data・application開発組織に、生成AIがenterprise dataを検索・取得するためのmanaged vector databaseを提供する会社。顧客が抱えるのは「RAGの検索品質がproductionで安定しない」「vector indexのscale・latency・cost運用が重い」「権限やdata freshnessを保ったままAI applicationを増やせない」という3つの課題。developer adoptionから入り、enterprise search、recommendation、agent memory、全社AI platformへ広げられる点が営業としての面白さ。",
  growthSummary: "9,000社超の顧客と80万人超のdeveloperを公式発表し、2023年には1億ドルを7.5億ドル評価で調達。2026年5月にSingaporeへAsia初のserverless regionを開設したが、Japan法人・拠点・求人は未確認。",
  verdict: "日本進出の可能性は中〜高。Singapore regionでinfra障壁は下がったが、Japan GTM proofが不足", entryNarrative: "Pineconeは9,000社超、80万人超のdeveloper community、Shopify・Gong・HubSpot等の顧客proofを持ち、vector databaseのcategory leaderとして十分な規模がある。2026年にSingaporeへAsia初のserverless regionを置いたことは、latencyとregional data要件を重視するAPAC enterpriseへ明確に近づいたシグナル。日本の生成AI・RAG需要とは高い親和性がある一方、Japan・Tokyoのoffice、求人、国内顧客事例、日本語support、国内cloud regionは確認できない。Singaporeから日本の有償usageを積み、SI・cloud partnerがRAGの設計・evaluation・運用を担い、regulated customerがregional hostingを受容できる状態になれば専任進出が現実的になる。",
  headcount: "201〜500人規模", headcountDetail: "LinkedIn企業ページの会社規模レンジ。公式の厳密値ではない。", apacPresence: "2026年5月にSingaporeへAsia初のserverless regionを開設し、APAC顧客向けlatencyとdata locationを改善。", productLanguage: "API・documentation中心のdeveloper productで日本から利用できるが、日本語site・support・Japan region・国内事例は未確認。",
  milestones: [{ year: "2019", label: "創業", detail: "purpose-built vector databaseとして創業。", source: "company" }, { year: "2021", label: "managed service", detail: "vector searchをcloud serviceとして一般提供。", source: "company" }, { year: "2023", label: "Series B", detail: "1億ドル、7.5億ドル評価を発表。", source: "growth" }, { year: "2024", label: "serverless", detail: "usage-based serverless architectureへ拡張。", source: "company" }, { year: "2026.05", label: "Singapore region", detail: "Asia初のserverless regionを開設。", source: "apac" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "Shopify、Gong、HubSpot等はsemantic searchや生成AIのdemoではなく、large-scale dataで低latency、freshness、relevanceを維持するproduction retrievalを求める。AI品質をmodelだけでなくcontext layerで改善する課題。" }, { title: "製品の成り立ちから見る課題", body: "vector searchをlibrary・自前clusterではなくmanaged databaseとして分離し、index、filter、namespace、scale、backupをservice化。AI teamがdatabase運用ではなくapplication qualityへ集中できる設計。" }, { title: "外部環境の要求から見る課題", body: "生成AIがPoCからproductionへ進むほど、hallucination、freshness、権限、latency、cost、evaluationが重要になる。日本企業でも社内dataへ安全にgroundingするretrieval layerが必要。" }],
  narrative: [{ label: "背景", body: "企業はdocument・product・conversationをembedding化するが、prototypeのlocal indexはdata量とuserが増えると不安定になる。" }, { label: "課題", body: "検索品質、freshness、permission、latency、costを同時に管理できず、RAGがdemoからmission-critical workflowへ進まない。" }, { label: "解決策", body: "一つのAI applicationでmanaged index、metadata filter、evaluationを設計し、relevance、latency、cost、freshness、運用時間を測る。" }, { label: "選定の理由", body: "Weaviate、Qdrant、Milvus、Elasticsearch、pgvector、cloud native vector searchとの比較で、運用負荷を抑えながらproduction scaleとretrieval qualityを維持できる場合に選ばれる。" }],
  openingHook: "RAGの回答品質が落ちた時、model、prompt、source data、retrievalのどこが原因か何時間で切り分けられますか。", valueHypothesis: "対象applicationでretrieval relevance、P95 latency、freshness、infra工数、query cost、answer acceptanceを測る。", objection: "pgvectorかElasticsearch、cloud vendorのvector searchで十分。", reframe: "最初のindex構築ではなく、dataとtrafficが10倍になった時のrelevance、latency、operations、developer速度をtotal costで比較する。",
  facts: [{ label: "顧客", value: "9,000社超", detail: "Asia region発表時点。", source: "growth" }, { label: "developer", value: "80万人超", detail: "会社公式発表。", source: "growth" }, { label: "Series B", value: "1億ドル", detail: "2023年。", source: "growth" }, { label: "評価額", value: "7.5億ドル", detail: "Series B時点。", source: "growth" }, { label: "Asia region", value: "Singapore", detail: "2026年5月開設。", source: "apac" }, { label: "日本求人", value: "未確認", detail: "Japan・Tokyo求人なし。", source: "careers" }],
  customers: [{ company: "Shopify", products: "Pinecone", outcome: "commerce dataを使うsemantic search・AI use caseの顧客として紹介。", implication: "large catalogとtrafficのproduction proof。" }, { company: "Gong", products: "Pinecone", outcome: "conversation dataを扱うAI productで利用。", implication: "high-volume unstructured dataのretrieval。" }, { company: "HubSpot", products: "Pinecone", outcome: "customer platform内のAI・search use caseを顧客として紹介。", implication: "SaaS productへのembedded infrastructure。" }],
  externalSignals: [{ label: "AI governance", value: "dataと評価", detail: "AI事業者ガイドラインはrisk管理、透明性、data品質、人間中心を求める。", caveat: "Pineconeの適合性や法的結論を示さない。" }, { label: "国内RAG需要", value: "enterprise data接続", detail: "日本企業は生成AIを社内knowledge・customer support・開発へ接続する段階。", caveat: "需要の存在だけで専用vector databaseの必要性は決まらない。" }],
  entryAssessment: {
    verdict: "進出可能性は中〜高。Singapore regionは強い先行signalだがlocal GTMの採算proofが必要",
    factSignals: [{ title: "Asia infrastructure投資", body: "SingaporeへAsia初のserverless regionを開設し、APAC enterpriseのlatencyとdata locationを明示的に改善。", sourceIds: ["apac", "growth"] }, { title: "category scale", body: "9,000社超、80万人超のdeveloperはself-serveとenterprise双方の需要を示す。", sourceIds: ["growth"] }, { title: "Japan AI課題との親和", body: "enterprise RAG、search、agent memoryは日本企業の生成AI production化と直接重なる。", sourceIds: ["company", "external"] }, { title: "ecosystem leverage", body: "cloud・AI application ecosystemから日本のSI・startupへpartner-ledに入る余地がある。", sourceIds: ["customers", "company"] }],
    hurdles: [{ title: "domestic region不在", body: "Singapore regionは改善だが、国内保存や低latencyを求める顧客にはJapan regionが必要になる可能性。", sourceIds: ["apac", "trust"] }, { title: "cloud bundle競争", body: "AWS、Google Cloud、Azure、Elastic、database vendorがvector searchをbundle提供。", sourceIds: ["company"] }, { title: "developer productのcommercialization", body: "self-serve usageをenterprise contract、security review、supportへ転換するlocal GTMが必要。", sourceIds: ["customers", "careers"] }, { title: "retrieval設計の責任", body: "vector databaseだけでRAG品質は決まらず、data pipeline、evaluation、permission、prompt設計が必要。", sourceIds: ["company", "external"] }],
    readinessConditions: [{ title: "Japan usage proof", body: "Singapore region上で日本顧客のusage、retention、enterprise expansionを確認。" }, { title: "lighthouse customer", body: "国内大手または有力AI productでproduction成果を公開。" }, { title: "delivery ecosystem", body: "SI、consulting、cloud partnerがRAG designとevaluationを提供。" }, { title: "Japanese enterprise readiness", body: "日本語support、security・legal資料、請求、SLAを整備。" }, { title: "dedicated Japan pod", body: "AE、Solution Architect、Developer Relations、Supportを専任化。" }],
    watchSignals: ["Japan・Tokyo求人", "日本語documentation", "国内顧客事例", "Japan cloud region", "国内SI・cloud partner", "Singapore求人のJapan territory表記"],
  },
  sourceIds: ["growth", "company", "careers", "customers", "trust", "apac", "external", "linkedin"], salesMotion: "developer adoptionとproduction workloadから入り、CTO・AI Platformへsecurity、scale、cost、supportをbusiness case化するbottom-up enterprise motion。", careerValue: "AI infrastructure、developer-led growth、consumption sale、APAC country buildを横断する可能性。", leader: { name: "Edo Liberty", role: "Founder / CEO", read: "large-scale ML・searchの経験から、vector retrievalを開発者が運用しやすいmanaged infrastructureへproduct化。" },
  solutions: [{ name: "Pinecone Database", valueProp: "production vector searchをserverlessで提供。", url: "https://www.pinecone.io/product/", competitors: "Weaviate、Qdrant、Milvus、pgvector。", differentiation: "fully managed operationとvector-native architecture。" }, { name: "Pinecone Assistant", valueProp: "file ingestionからgrounded answerまでRAG stackを簡略化。", url: "https://www.pinecone.io/product/assistant/", competitors: "cloud RAG service、Glean、custom framework。", differentiation: "retrieval infrastructureとapplication APIを一体化。" }, { name: "Inference / Rerank", valueProp: "embeddingとrerankingをdatabase workflowへ統合。", url: "https://www.pinecone.io/product/", competitors: "Cohere、Voyage AI、open-source model。", differentiation: "indexing・queryと同じserviceで最適化。" }],
  fitTags: ["日本未進出", "AI Infrastructure", "Vector Database", "Developer", "APAC", "Consumption", "Enterprise", "RAG"], comparisons: [{ arena: "Vector DB", companies: ["Pinecone", "Weaviate", "Qdrant"], why: "managed operation、performance、ecosystem" }, { arena: "Database", companies: ["Pinecone", "Postgres", "Elastic"], why: "vector-nativeと既存stack" }, { arena: "Cloud AI", companies: ["Pinecone", "AWS", "Google Cloud", "Azure"], why: "specialistとbundle" }],
});

const intercomIntelligence: CompanyPublicIntelligence = buildPreEntryIntelligence({
  slug: "intercom", name: "Intercom", homepage: "https://www.intercom.com/", growthUrl: "https://www.intercom.com/blog/fin-ai-engine-for-customer-service/", careersUrl: "https://www.intercom.com/careers", customersUrl: "https://www.intercom.com/customers", trustUrl: "https://www.intercom.com/legal/security", apacUrl: "https://www.intercom.com/blog/remote-team-new-sydney-office/", externalUrl: "https://www.ppc.go.jp/en/legal/", linkedinUrl: "https://www.linkedin.com/company/intercom/",
  salesSnapshot: "Intercomは、Customer Support・CX・Operations・Product組織に、AI agentのFinとhuman support workspaceを統合したcustomer service platformを提供する会社。顧客が抱えるのは「問い合わせ増に採用が追いつかない」「botとhumanの引継ぎでcontextが消える」「AIの解決率・品質・costをbusiness outcomeで管理できない」という3つの課題。chat・help centerから入り、AI resolution、omnichannel、support operations、customer insightへ広げられる点が営業としての面白さ。",
  growthSummary: "2011年創業、1,000人規模のグローバル組織と多数の顧客事例を持ち、SydneyをAPAC拠点として運営。日本語Help Centerと製品情報はあるが、Japan・Tokyoの法人、拠点、求人は未確認。",
  verdict: "日本進出の可能性は中。製品localizationとAPAC基盤はあるが、telephony・support・国内競争が障壁", entryNarrative: "Intercomはcustomer messagingで長い製品実績を持ち、Fin AI Agentへ事業を再集中し、SydneyからAPACを運営している。日本語Help Centerや日本語での製品利用導線があり、SaaS・EC・consumer serviceの問い合わせautomationとは高い親和性がある。一方、日本法人・Tokyo求人・国内顧客事例は確認できず、Intercom Phoneは日本番号に未対応と公式Help Centerに明記されている。Zendesk、Salesforce、HubSpot、KARTE、PKSHA等の既存基盤も強い。日本語のAI解決品質、local channel、data handling、support、partner deliveryを国内referenceで証明し、Sydneyから担当するJapan revenueが専任teamの固定費を超える状態が進出条件になる。",
  headcount: "1,001〜5,000人規模", headcountDetail: "LinkedIn企業ページの会社規模レンジ。公式の厳密値ではない。", apacPresence: "Sydney officeをAPACのsales・support・R&D拠点として公式紹介。", productLanguage: "日本語Help Centerと製品利用情報はあるが、日本の電話番号、国内office、local support、国内顧客事例の同等性は未確認。",
  milestones: [{ year: "2011", label: "創業", detail: "internet business向けcustomer messagingとして創業。", source: "company" }, { year: "2018", label: "Sydney拡張", detail: "APAC officeとregional teamを拡張。", source: "apac" }, { year: "2023", label: "Fin launch", detail: "GPT-4を使うcustomer service AI agentを投入。", source: "company" }, { year: "2025", label: "AI-first再集中", detail: "Fin AI Engineとhelpdeskの統合を拡張。", source: "growth" }, { year: "2026", label: "APAC継続", detail: "Sydneyを中心にregional hiringと顧客支援を継続。", source: "apac" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "顧客事例はFAQ deflectionだけでなく、Finの解決率、human handoff、response time、support cost、CSATを同じplatformで改善する。AIとagent teamを別systemにせず、一つのservice operationとして管理する課題。" }, { title: "製品の成り立ちから見る課題", body: "web・app内messagingからinbox、help center、outbound、AI agentへ拡張。customer conversationとproduct contextを起点に、channelやbotごとに分断したsupport experienceを統合する設計。" }, { title: "外部環境の要求から見る課題", body: "人手不足と24時間対応でAI automationが必要な一方、企業は誤回答、個人情報、escalation、説明責任、品質を管理する必要がある。解決率だけでなく安全なhandoffとreviewが投資条件になる。" }],
  narrative: [{ label: "背景", body: "customer contactがchat、email、web、app、phoneへ広がり、問い合わせ量と期待速度が上がる。" }, { label: "課題", body: "channelごとにhistoryが分断し、agentは検索とcopyに時間を使い、botが解けない時のhandoffで顧客が説明を繰り返す。" }, { label: "解決策", body: "一つの問い合わせcategoryでFin、knowledge、human handoff、QAを設計し、resolution、CSAT、handle time、cost、escalationを測る。" }, { label: "選定の理由", body: "Zendesk、Salesforce Service Cloud、HubSpot、国内chatbot・AI agentとの比較で、AI resolutionとhuman workspaceを一体で速く改善できる場合に選ばれる。" }],
  openingHook: "AIが解決した問い合わせのうち、顧客が再度連絡した割合と、人へ渡すべきだった割合を測れていますか。", valueHypothesis: "対象categoryでAI resolution、repeat contact、CSAT、handle time、escalation、cost per resolutionを測る。", objection: "Zendesk・Salesforceか国内chatbotで十分。", reframe: "botの回答数ではなく、AIが安全に解決し、必要な時だけ全contextを人へ渡し、costとCSATを同時に改善できるかで比較する。",
  facts: [{ label: "創業", value: "2011年", detail: "customer communication platform。", source: "company" }, { label: "会社規模", value: "1,001〜5,000人", detail: "LinkedIn公開レンジ。", source: "company" }, { label: "APAC", value: "Sydney", detail: "regional officeを公式紹介。", source: "apac" }, { label: "AI製品", value: "Fin", detail: "AI AgentとHelpdeskを統合。", source: "company" }, { label: "日本語情報", value: "Help Centerあり", detail: "日本語support articleを公開。", source: "company" }, { label: "日本求人", value: "未確認", detail: "Japan・Tokyo求人なし。", source: "careers" }],
  customers: [{ company: "Atlassian", products: "Intercom", outcome: "customer communication・supportの利用企業として紹介。", implication: "global SaaSのproduct-led support。" }, { company: "Vanta", products: "Fin / Intercom", outcome: "AI customer serviceの成果を顧客事例で公開。", implication: "high-growth SaaSでAI resolutionをexpand。" }, { company: "Anthropic", products: "Intercom", outcome: "AI companyのcustomer support事例として紹介。", implication: "複雑なproduct質問とrapid growthへのproof。" }],
  externalSignals: [{ label: "個人情報保護", value: "conversation data", detail: "個人情報保護法はcustomer conversationの取得・利用・越境・安全管理にも関係する。", caveat: "Intercomの個別適合性や法的結論を示さない。" }, { label: "AI customer service", value: "品質と説明責任", detail: "AI automationが増えるほどknowledge更新、human escalation、monitoringが重要。", caveat: "解決率と顧客満足はuse case・language・knowledge品質で異なる。" }],
  entryAssessment: {
    verdict: "進出可能性は中。APAC・日本語の下地はあるがJapan-specific channelとcommercial proofが不足",
    factSignals: [{ title: "SydneyのAPAC足場", body: "Sales・Support・R&Dを含むSydney officeを持ち、Asia Pacificを現地時間帯で運営。", sourceIds: ["apac"] }, { title: "日本語product導線", body: "日本語Help Centerとproduct guidanceがあり、日本語利用の入口は存在。", sourceIds: ["company"] }, { title: "AI customer serviceの成長領域", body: "Fin AI Agentはsupport人材不足と24時間対応という日本の課題に合う。", sourceIds: ["growth", "external"] }, { title: "global SaaS proof", body: "多数のSaaS・consumer企業事例があり、product-led supportの再現材料を持つ。", sourceIds: ["customers"] }],
    hurdles: [{ title: "Japan telephony gap", body: "Intercom Phoneは日本番号をsupport対象としていないと公式Help Centerに記載。", sourceIds: ["company"] }, { title: "強い既存競合", body: "Zendesk、Salesforce、HubSpot、国内CX・chatbot vendorがinstalled baseとpartnerを持つ。", sourceIds: ["company"] }, { title: "日本語AI品質", body: "Finの日本語解決率、tone、knowledge retrieval、QAを国内productionで示す公開proofがない。", sourceIds: ["customers", "company"] }, { title: "local delivery不在", body: "Japan office、country owner、国内partner、local support SLAを確認できない。", sourceIds: ["careers", "apac"] }],
    readinessConditions: [{ title: "Japan lighthouse", body: "国内SaaS・EC等で日本語Finのresolution、CSAT、cost成果を公開。" }, { title: "channel completeness", body: "日本のphone・messaging要件または明確なnon-voice ICPを確立。" }, { title: "Japanese AI operations", body: "knowledge、QA、escalation、日本語supportをproduction gradeで提供。" }, { title: "local partners", body: "CX consulting、BPO、SI partnerがimplementationとchangeを支援。" }, { title: "dedicated pod", body: "Japan AE、Solution、CS、SupportをSydney hubから専任化。" }],
    watchSignals: ["Japan・Tokyo求人", "日本顧客事例", "Intercom PhoneのJapan対応", "日本語site・Fin benchmark", "国内BPO・SI partner", "Sydney求人のJapan territory表記"],
  },
  sourceIds: ["growth", "company", "careers", "customers", "trust", "apac", "external", "linkedin"], salesMotion: "Support leaderへAI resolutionの限定categoryから入り、human helpdesk、omnichannel、knowledge、QAへexpandするoutcome sale。", careerValue: "AI customer service、PLG、CX operations、APAC country build、usage expansionを横断する可能性。", leader: { name: "Eoghan McCabe", role: "CEO / Co-founder", read: "customer communicationの原点へ戻り、Finを中心にAI-first customer service companyへ再集中。" },
  solutions: [{ name: "Fin AI Agent", valueProp: "knowledgeを使い問い合わせをend-to-endで解決。", url: "https://www.intercom.com/fin", competitors: "Zendesk AI、Salesforce Agentforce、国内AI chatbot。", differentiation: "AI resolutionとhuman handoffを同じconversation layerで扱う。" }, { name: "Intercom Helpdesk", valueProp: "omnichannel inbox、ticket、workflow、reportingを統合。", url: "https://www.intercom.com/helpdesk", competitors: "Zendesk、Salesforce Service Cloud、HubSpot。", differentiation: "product messengerとAI agentをnative統合。" }, { name: "Knowledge Hub", valueProp: "AIとhumanが使うsupport knowledgeを統合管理。", url: "https://www.intercom.com/helpdesk/knowledge-hub", competitors: "help center、Glean、custom RAG。", differentiation: "回答・gap・content改善をservice workflowへ接続。" }],
  fitTags: ["日本未進出", "Customer Service", "AI Agent", "SaaS", "APAC", "CX", "PLG", "Enterprise"], comparisons: [{ arena: "Customer Service", companies: ["Intercom", "Zendesk", "Salesforce"], why: "AI、suite、enterprise運用" }, { arena: "AI Agent", companies: ["Fin", "Agentforce", "国内bot"], why: "resolution、language、handoff" }, { arena: "Messaging", companies: ["Intercom", "HubSpot", "KARTE"], why: "product contextとomnichannel" }],
});

export const preEntryWaveThreeIntelligenceBySlug: Record<string, CompanyPublicIntelligence> = {
  rippling: ripplingIntelligence,
  pinecone: pineconeIntelligence,
  intercom: intercomIntelligence,
};
