import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-15";

export const companies20260815: Company[] = [
  { slug: "stripe", name: "Stripe", category: "Payments Infrastructure / Financial Platform", broadCategory: "経営管理・FinTech", hq: "South San Francisco, US / Dublin, Ireland", japanPresence: "Stripe Japan / Tokyo", hiringStatus: "積極採用", salesRoles: 3, description: "2025年の総取扱額は1.9兆ドル。TokyoでCommercial Hunter、Commercial Grower、Enterprise HunterのAccount Executiveを公式募集。", lastChecked: checkedAt, careersUrl: "https://stripe.com/jobs/search", tags: ["アンカー企業", "Payments", "FinTech", "Enterprise", "Platform", "Japan"] },
  { slug: "aghanim", name: "Aghanim", category: "Mobile Gaming Commerce / Direct-to-Consumer", broadCategory: "コマース・業界特化", hq: "Los Angeles, US / Lisbon, Portugal", japanPresence: "Japan market owner / remote", hiringStatus: "採用中", salesRoles: 1, description: "mobile game向けGame Hub、Merchant of Record、LiveOpsを提供。Head of BD Japanが市場戦略、studio・partner開拓、収益成長を担う。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/aghanim/0b7e0d14-4741-4439-bdba-67dca40af857", tags: ["Gaming", "Payments", "Founding GTM", "Business Development", "Japan"] },
  { slug: "primer", name: "Primer", category: "Unified Payments Infrastructure / Orchestration", broadCategory: "経営管理・FinTech", hq: "London, UK", japanPresence: "日本法人・国内拠点・Japan専任求人を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "2026年に1億ドルのSeries Cを調達したpayments orchestration企業。SingaporeのAPAC体制は拡大中だが、Japan専任GTMは未確認。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/primer.io", tags: ["日本未進出", "Payments", "Orchestration", "Enterprise", "APAC", "FinTech"], entryStatus: "not-entered" },
];

const careerInsights = (category: string): Job["careerInsights"] => ({
  fit: `${category}で複雑なbuyerとpartnerを束ね、市場を作るfull-cycle sellerに向く。`,
  thingsToKnow: "Japan ARR、顧客数、平均ACV、sales cycle、担当社数、quota達成率は非公開。",
  marketValue: `${category}、Enterprise sales、partner orchestration、executive discoveryを横断する経験。`,
  tenureAndPromotion: `【Genba仮説】市場・製品・buyerの複雑さから、初期は昇進より担当scopeの拡大が先になる。支持材料: 求人はnew logoだけでなく複数部門・partnerとの実行を求め、productとmarketの学習蓄積が担当拡張の価値になる。反証・留保: Japan非ユニーク営業職の公開profileを4件以上集計できず、実際の平均在籍年数、離職率、昇進率、内部異動率は不明。面接で確認: 直近24カ月の担当拡張・昇進・退職の件数と、次levelに必要な成果は。`,
  priorCompanies: `【Genba仮説】入社元は社名より、${category}に近いcomplex sale、経営層提案、partner経由のexecution、技術・business buyer間の翻訳が共通項になる。支持材料: 公式求人が求めるfull-cycle ownership、multi-stakeholderの合意形成、pipeline構築、partnerとの実行。反証・留保: LinkedIn公開profileの対象地域・職種で実測母数を確保できておらず、特定company categoryの採用優位を事実としては言えない。面接で確認: 直近の採用者の前職category上位3つ、共通するsales motion、ramp期間は。`,
  nextCompanies: `【Genba仮説】pipeline、受注、expansion、partner寄与を定量化できれば、${category}のEnterprise AE・Sales Lead・Country roleへ接続しやすい。支持材料: 求人が市場構築とend-to-end revenueを求める。反証・留保: 転職先の公開集計ではない。面接で確認: 卒業者の次role categoryと社内のAPAC scope拡張例は。`,
});

export const jobs20260815: Job[] = [
  { id: "stripe-account-executive-commercial-hunter-japan", companySlug: "stripe", title: "Account Executive, Commercial Hunter (Japanese Fluency)", segment: "Commercial / New + Expansion", location: "Tokyo", workStyle: "full-time / 月50%以上をoffice・顧客先", language: "日本語・英語のprofessional fluency", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Stripe Careers", url: "https://stripe.com/careers/listing/account-executive-commercial-hunter-japanese-fluency/7789539" }, descriptionSummary: "日本のCommercial企業で新規獲得と既存userの拡張を担い、discoveryから契約・立ち上げ連携までを主導する。", genbaTake: "決済手数料の比較ではなく、売上機会、承認率、不正、請求、越境展開を経営指標へ束ねるdual-motionのplatform sale。", compensationReality: "公式OTEは年額1,720万〜2,580万円。pay mix、quota、accelerator、equityの詳細は求人で確認できない。", desiredProfile: "3年以上のsales・prospecting経験、日英両言語、経営層との合意形成、自律的なpipeline構築を求める。", careerInsights: careerInsights("Payments / FinTech") },
  { id: "stripe-account-executive-enterprise-hunter-japan", companySlug: "stripe", title: "Account Executive, Enterprise Hunter (Japanese Fluency)", segment: "Enterprise / New Business", location: "Tokyo", workStyle: "full-time / 月50%以上をoffice・顧客先", language: "日本語・英語のprofessional fluency", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Stripe Careers", url: "https://stripe.com/careers/listing/account-executive-enterprise-hunter-japanese-fluency/7528816" }, descriptionSummary: "日本のEnterpriseでcomplex sales cycleを主導し、Engineering、Product、Finance、Partners、Post-Salesと連携して全社導入を進める。", genbaTake: "国内決済の置換ではなく、global commerce、platform business、subscription、treasuryを経営アーキテクチャとして売る。", compensationReality: "公式OTEは年額1,720万〜2,580万円。pay mix、quota、accelerator、equityの詳細は求人で確認できない。", desiredProfile: "10年以上のtechnology sales経験、Enterpriseの長期・複数部門deal、日英両言語、executive relationship、forecastを求める。", careerInsights: careerInsights("Payments / FinTech") },
  { id: "stripe-account-executive-commercial-grower-japan", companySlug: "stripe", title: "Account Executive, Commercial Grower (Japanese Fluency)", segment: "Commercial / Existing Business", location: "Tokyo", workStyle: "full-time / 月50%以上をoffice・顧客先", language: "日本語・英語のprofessional fluency", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Stripe Careers", url: "https://stripe.com/careers/listing/account-executive-commercial-grower-japanese-fluency/8042978" }, descriptionSummary: "日本のCommercial既存顧客で利用拡大と複数製品の採用を進め、長期的な収益成長を担う。", genbaTake: "利用量の増加だけでなく、PaymentsからBilling、Connect、Tax等へ顧客の収益基盤を広げるexpansion sale。", compensationReality: "公式OTEは年額1,720万〜2,580万円。pay mix、quota、accelerator、equityの詳細は求人で確認できない。", desiredProfile: "既存顧客の成長仮説、日英両言語、複数部門の合意形成、usage・expansionのforecastを再現できる人材を想定。", careerInsights: careerInsights("Payments / FinTech") },
  { id: "aghanim-head-of-bd-japan", companySlug: "aghanim", title: "Head of BD, Japan", segment: "Country Build / Business Development", location: "Japan", workStyle: "remote / full-time", language: "日本語・英語に堪能", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Aghanim Careers (Ashby)", url: "https://jobs.ashbyhq.com/aghanim/0b7e0d14-4741-4439-bdba-67dca40af857" }, descriptionSummary: "日本のmarket strategy、pipeline、studio・partner・key account開拓をend-to-endで担い、revenue growthとmarket penetrationで成果を測る。", genbaTake: "game studioへの決済導入ではなく、app store依存、player relationship、margin、loyalty、live operationsをD2Cの事業設計へ変える営業。", compensationReality: "日本のbase、bonus、quota、equity、雇用主体は公式求人で確認できない。", desiredProfile: "5年以上のbusiness development経験、日本のmobile gaming ecosystem理解、日英両言語、幹部提案、partner developmentを求める。", careerInsights: careerInsights("Gaming Commerce / Payments") },
];
