import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchThirteen: Job[] = [
  job({
    id: "nexthink-customer-success-manager-japan-current",
    companySlug: "nexthink",
    title: "Customer Success Manager",
    segment: "Customer Success / Digital Employee Experience",
    location: "東京・日本",
    workStyle: "ハイブリッド",
    language: "日本語・英語（必須）",
    source: { label: "Nexthink Careers (SmartRecruiters)", url: "https://jobs.smartrecruiters.com/Nexthink/744000141703549-customer-success-manager" },
    descriptionSummary: "日本のenterprise顧客でadoption、value realization、executive alignment、renewal・expansionを担うCustomer Success role。",
    genbaTake: "license利用率で終わらず、employee friction、IT ticket、application adoption、service qualityを顧客KPIへ変える。",
    compensationReality: "日本の給与、bonus、variable、renewal・expansion target、担当社数は公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise Customer Success、executive communication、日英での顧客対応、複数stakeholderのvalue realizationを重視。",
    domain: "Digital Employee Experience・Customer Success",
  }),
  job({
    id: "nexthink-solution-consultant-japan-current",
    companySlug: "nexthink",
    title: "Solution Consultant",
    segment: "Pre-sales / Digital Employee Experience",
    location: "東京・日本",
    workStyle: "ハイブリッド",
    language: "日本語・英語（必須）",
    source: { label: "Nexthink Careers (SmartRecruiters)", url: "https://jobs.smartrecruiters.com/Nexthink/744000120870667-solution-consultant" },
    descriptionSummary: "technical discovery、demo、value hypothesis、evaluationをSalesと進め、DEXのbusiness・technical fitを検証するpre-sales role。",
    genbaTake: "device telemetryのdemoでなく、employee experience、IT productivity、software adoptionを導入前後の指標へ落とす。",
    compensationReality: "日本の給与、bonus、variable、OTE、POC KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise pre-sales、IT・endpoint・SaaSのtechnical discovery、日英での顧客対応を重視。",
    domain: "Digital Employee Experience・Solutions Consulting",
  }),
  job({
    id: "nice-account-executive-japan-current",
    companySlug: "nice",
    title: "Account Executive, Japan",
    segment: "Enterprise / CX AI",
    location: "東京・日本",
    workStyle: "NiCE-FLEX（週2日office・週3日remote）",
    language: "日本語・英語（fluent）",
    source: { label: "NiCE Careers (Greenhouse)", url: "https://job-boards.eu.greenhouse.io/nice/jobs/4661611101" },
    descriptionSummary: "new logoとcompetitive displacement、C-level relationship、business case、multi-year plan、partner・presalesを担うenterprise AE。",
    genbaTake: "contact center seatでなく、automation、agent productivity、quality、revenue、complianceを同じCX operating modelへ接続する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はquota超過、大口account、legacy・complex softwareの置換、ROI business case、C-level selling、fluent Japanese・Englishを重視。",
    domain: "CX AI・Enterprise Sales",
  }),
  job({
    id: "nice-director-sales-ai-japan-current",
    companySlug: "nice",
    title: "Director Sales AI",
    segment: "Sales Leadership / CX AI",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "日本語・英語（bilingual）",
    source: { label: "NiCE Careers (Greenhouse)", url: "https://job-boards.eu.greenhouse.io/nice/jobs/4938723101" },
    descriptionSummary: "AI portfolioのsales strategy、pipeline、complex deal、executive engagementを率いるJapan向けSales leadership role。",
    genbaTake: "AI機能の追加販売でなく、customer interaction全体のautomation、quality、governanceを経営caseへ変える。",
    compensationReality: "日本の給与、OTE、pay mix、equity、team quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise AI・software sales、複雑なstakeholder、executive value selling、sales leadership、bilingual Japanese・Englishを重視。",
    domain: "CX AI・Sales Leadership",
  }),
  job({
    id: "nice-senior-business-analyst-japan-current",
    companySlug: "nice",
    title: "Senior Business Analyst",
    segment: "Actimize AML / Professional Services",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "日本語・英語（written・verbal fluent）",
    source: { label: "NiCE Careers (Greenhouse)", url: "https://job-boards.eu.greenhouse.io/nice/jobs/4841640101" },
    descriptionSummary: "NiCE Actimize AMLのProfessional Servicesでcustomer requirement、process、data、solution scopeを整理し、最大20%の出張を伴うdeliveryを進める。",
    genbaTake: "要件一覧で終わらず、AML workflow、data、acceptance、change impact、auditabilityをproduction outcomeへ結ぶ。",
    compensationReality: "日本の給与、bonus、variable、project KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はAML・Financial Crime領域のbusiness analysis、customer workshop、requirement・process設計、fluent Japanese・Englishを重視。",
    domain: "Financial Crime・AML Business Analysis",
  }),
  job({
    id: "nice-senior-solution-engineer-japan-current",
    companySlug: "nice",
    title: "Senior Solution Engineer",
    segment: "Pre-sales / CX AI",
    location: "日本",
    workStyle: "NiCE-FLEX（週2日office・週3日remote）",
    language: "日本語（exceptional）／英語（intermediate、CEFR B2+・IELTS 5.5+）",
    source: { label: "NiCE Careers (Greenhouse)", url: "https://job-boards.eu.greenhouse.io/nice/jobs/4924323101" },
    descriptionSummary: "technical discovery、architecture、demo、POC、proposalをSalesと進め、CXone・AIのtechnical winを担う。",
    genbaTake: "demo機能数でなく、日本語AI、integration、latency、security、migration、agent・customer KPIを同じ評価へ置く。",
    compensationReality: "日本の給与、bonus、variable、OTE、POC KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise solution engineering、contact center・cloud・AI architecture、demo・POC、日本語とintermediate Englishを重視。",
    domain: "CX AI・Solutions Engineering",
  }),
  job({
    id: "patch-enterprise-account-executive-apac-tokyo-current",
    companySlug: "patch",
    title: "Enterprise Account Executive, APAC - Tokyo",
    segment: "Founding AE / Climate Markets",
    location: "東京・日本",
    workStyle: "リモート（東京拠点・remote flexibility）",
    language: "日本語business proficiencyは歓迎要件／英語要件は明記なし",
    source: { label: "Patch Careers (Ashby)", url: "https://jobs.ashbyhq.com/patch.io/1d73e679-d6f7-42c1-9545-74c31e97e7da" },
    descriptionSummary: "APAC初のAEとして日本中心にpipelineとlighthouse dealを作り、sustainability、finance、procurement、trading、legalを束ねる。",
    genbaTake: "creditの数量販売でなく、instrument eligibility、project quality、price、delivery、retirement、claims・auditを一つのportfolio decisionへ設計する。",
    compensationReality: "20万〜30万米ドルのOTEはSan Francisco勤務者向けで、日本条件には転用できない。日本のbase、OTE、pay mix、equityは非公開。",
    desiredProfile: "公式求人はenterprise B2B sales 5〜10年以上、large APAC企業、商社・carbon market、0-to-1 category creation、100%超のquota実績を重視。",
    domain: "Climate Markets・Enterprise Sales",
  }),
  job({
    id: "patsnap-forward-deployed-engineer-japan-current",
    companySlug: "patsnap",
    title: "Forward Deployed Engineer (FDE)",
    segment: "Customer Delivery / Domain AI",
    location: "東京・日本",
    workStyle: "オンサイト / フルタイム",
    language: "日本語・英語のbusiness levelは歓迎要件",
    source: { label: "Patsnap Careers (Lever)", url: "https://jobs.lever.co/patsnap/e80dcb4a-0644-4883-95f3-8e6a0c01e846" },
    descriptionSummary: "customer delivery、implementation、AI solution design、prototype・PoC、agent workflowをProduct・Sales・CSと進める。",
    genbaTake: "agent demoで終わらず、customer gold set、citation、recall・precision、human review、decision lead timeを本番workflowへ組み込む。",
    compensationReality: "日本の給与、bonus、variable、equity、delivery KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はcustomer-facing implementation、AI solution・prototype、cross-functional deliveryを重視。日英はJapan-facing roleの歓迎要件で必須とは記載しない。",
    domain: "Innovation Intelligence・Forward Deployed Engineering",
  }),
  job({
    id: "patsnap-key-account-manager-japan-current",
    companySlug: "patsnap",
    title: "Key Account Manager",
    segment: "Key Accounts / IP & R&D Intelligence",
    location: "東京・日本",
    workStyle: "オンサイト / フルタイム",
    language: "英語（required）／追加のアジア言語は歓迎",
    source: { label: "Patsnap Careers (Lever)", url: "https://jobs.lever.co/patsnap/01f261fd-6c87-4dc6-92f1-b295fa4f43d9" },
    descriptionSummary: "key enterprise portfolioのretention、upsell・cross-sell、stakeholder management、forecastを担うaccount expansion role。",
    genbaTake: "seat更新でなく、R&D・IP・Legalのdecision workflow、利用成果、再調査・外注工数をrenewal・expansionの根拠にする。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、担当社数は公式求人で確認できない。",
    desiredProfile: "公式求人はB2B sales 5年以上、enterprise SaaS・IP・R&D tool、complex account、Englishを重視。Tokyo分類とSingapore・SEA担当本文の不整合は応募前確認が必要。",
    domain: "Innovation Intelligence・Key Account Management",
  }),
  job({
    id: "pendo-enterprise-account-executive-japan-current",
    companySlug: "pendo",
    title: "Account Executive, Enterprise Sales - Japan",
    segment: "Enterprise（従業員1,500人超）",
    location: "東京・日本",
    workStyle: "ハイブリッド（週3日office）",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Pendo Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/pendo/jobs/8518472002" },
    descriptionSummary: "1,500人超のenterpriseへnew pipeline、multi-year account strategy、C-suite・IT・business alignment、complex closeを担う。",
    genbaTake: "analytics seatでなく、user friction、adoption、support・training工数、retention・software ROIをin-app actionまで閉ループ化する。",
    compensationReality: "日本の給与、base、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はcomplex enterprise sale、C-suite・IT・business leadership、MEDDPICC・Force Management、builder mindsetを重視。言語は補完しない。",
    domain: "Software Experience Management・Enterprise Sales",
  }),
];
