import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-15";

export const companies20260815: Company[] = [
  { slug: "stripe", name: "Stripe", category: "Payments Infrastructure / Financial Platform", broadCategory: "経営管理・FinTech", hq: "South San Francisco, US / Dublin, Ireland", japanPresence: "Stripe Japan / Tokyo", hiringStatus: "積極採用", salesRoles: 3, description: "payments、billing、connect、tax、financial servicesを統合。TokyoでCommercial・Enterprise・SMBのAccount Executiveを公式募集。", lastChecked: checkedAt, careersUrl: "https://stripe.com/jobs/search", tags: ["アンカー企業", "Payments", "FinTech", "Enterprise", "Platform", "Japan"] },
  { slug: "aghanim", name: "Aghanim", category: "Mobile Gaming Commerce / Direct-to-Consumer", broadCategory: "コマース・業界特化", hq: "Los Angeles, US", japanPresence: "Japan market owner / remote", hiringStatus: "採用中", salesRoles: 1, description: "mobile game studio向けにweb shop、payments、loyalty、communityを提供。Head of BD Japanを募集し、日本のGTMとpartner開拓を一人目で担う。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/aghanim/0b7e0d14-4741-4439-bdba-67dca40af857", tags: ["Gaming", "Payments", "Founding GTM", "Business Development", "Japan"] },
  { slug: "primer", name: "Primer", category: "Unified Payments Infrastructure / Orchestration", broadCategory: "経営管理・FinTech", hq: "London, UK", japanPresence: "日本法人・国内拠点・Japan専任求人を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "global paymentsを一つのintegrationでorchestrationする非公開企業。SingaporeのAPAC AEから日本顧客・partner・専任GTMのシグナルを継続観測。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/primer.io", tags: ["日本未進出", "Payments", "Orchestration", "Enterprise", "APAC", "FinTech"], entryStatus: "not-entered" },
];

const careerInsights = (category: string): Job["careerInsights"] => ({
  fit: `${category}で複雑なbuyerとpartnerを束ね、市場を作るfull-cycle sellerに向く。`,
  thingsToKnow: "Japan ARR、顧客数、平均ACV、sales cycle、担当社数、quota達成率は非公開。",
  marketValue: `${category}、Enterprise sales、partner orchestration、executive discoveryを横断する経験。`,
  tenureAndPromotion: `【Genba仮説・確度: 中】市場・製品・buyerの複雑さから、初期は昇進より担当scopeの拡大が先になる。支持材料: 求人はnew logoだけでなく複数部門・partnerとの実行を求め、productとmarketの学習蓄積が担当拡張の価値になる。反証・留保: Japan非ユニーク営業職の公開profileを4件以上集計できず、実際の平均在籍年数、離職率、昇進率、内部異動率は不明。面接で確認: 直近24カ月の担当拡張・昇進・退職の件数と、次levelに必要な成果は。`,
  priorCompanies: `【Genba仮説・確度: 中】入社元は社名より、${category}に近いcomplex sale、経営層提案、partner経由のexecution、技術・business buyer間の翻訳が共通項になる。支持材料: 公式求人が求めるfull-cycle ownership、multi-stakeholderの合意形成、pipeline構築、partnerとの実行。反証・留保: LinkedIn公開profileの対象地域・職種で実測母数を確保できておらず、特定company categoryの採用優位を事実としては言えない。面接で確認: 直近の採用者の前職category上位3つ、共通するsales motion、ramp期間は。`,
  nextCompanies: `【Genba仮説・確度: 中】pipeline、受注、expansion、partner寄与を定量化できれば、${category}のEnterprise AE・Sales Lead・Country roleへ接続しやすい。支持材料: 求人が市場構築とend-to-end revenueを求める。反証・留保: 転職先の公開集計ではない。面接で確認: 卒業者の次role categoryと社内のAPAC scope拡張例は。`,
});

export const jobs20260815: Job[] = [
  { id: "stripe-account-executive-commercial-hunter-japan", companySlug: "stripe", title: "Account Executive, Commercial Hunter (Japanese Fluency)", segment: "Commercial / New Business", location: "Tokyo", workStyle: "公式求人で明記なし", language: "日本語要件あり", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Stripe Careers", url: "https://stripe.com/jobs/search?gh_jid=7343534" }, descriptionSummary: "日本のCommercial企業に対し、new logo開拓、discovery、提案、契約、立ち上げの連携までを担う。", genbaTake: "決済手数料の比較ではなく、売上機会、決済承認率、不正、請求、越境展開を経営指標へ束ねるplatform sale。", compensationReality: "日本のbase、OTE、pay mix、quota、accelerator、equityは公式求人で確認できない。", desiredProfile: "日本語での顧客対応、complex sale、経営層との合意形成、自律的なpipeline構築が中核。", careerInsights: careerInsights("Payments / FinTech") },
  { id: "stripe-account-executive-enterprise-hunter-japan", companySlug: "stripe", title: "Account Executive, Enterprise Hunter (Japanese Fluency)", segment: "Enterprise / New Business", location: "Tokyo", workStyle: "公式求人で明記なし", language: "日本語要件あり", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Stripe Careers", url: "https://stripe.com/jobs/search?gh_jid=7115730" }, descriptionSummary: "日本のEnterpriseでnew logoのcomplex sales cycleを主導し、Product・Solutions・Legal・Riskと連携して全社導入を進める。", genbaTake: "国内決済の置換ではなく、global commerce、platform business、subscription、treasuryを経営アーキテクチャとして売る。", compensationReality: "日本のbase、OTE、pay mix、quota、accelerator、equityは公式求人で確認できない。", desiredProfile: "Enterpriseの長期・複数部門deal、executive relationship、forecast、new logo開拓を再現できる人材を想定。", careerInsights: careerInsights("Payments / FinTech") },
  { id: "aghanim-head-of-bd-japan", companySlug: "aghanim", title: "Head of BD, Japan", segment: "Country Build / Business Development", location: "Japan", workStyle: "remote", language: "公式求人で明記なし", firstSeen: checkedAt, lastChecked: checkedAt, source: { label: "Aghanim Careers (Ashby)", url: "https://jobs.ashbyhq.com/aghanim/0b7e0d14-4741-4439-bdba-67dca40af857" }, descriptionSummary: "日本のmarket expansion、sales strategy、pipeline、studio・partner・key account開拓をend-to-endで担う。", genbaTake: "game studioへの決済導入ではなく、app store依存、player relationship、margin、loyalty、live operationsをD2Cの事業設計へ変える営業。", compensationReality: "日本のbase、bonus、quota、equity、雇用形態の詳細は公式求人で確認できない。", desiredProfile: "日本とmobile gamingのecosystem理解、market entry、幹部提案、partner development、自律的な収益責任を求める。", careerInsights: careerInsights("Gaming Commerce / Payments") },
];
