import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-19";

export const companies20260819Daily: Company[] = [
  {
    slug: "gitlab",
    name: "GitLab",
    category: "DevSecOps / AI Software Development Platform",
    broadCategory: "セキュリティ・IT運用",
    hq: "全社リモート（米国法人）",
    japanPresence: "GitLab合同会社・東京都中央区（2020年に日本市場へ本格参入）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "source code、CI/CD、security、planning、AIを一つのDevSecOps platformで提供。日本から勤務するSenior Ecosystem Sales Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://about.gitlab.com/jobs/all-jobs/",
    tags: ["アンカー企業", "DevSecOps", "AI", "Developer Platform", "Ecosystem Sales", "Remote", "Japan"],
  },
  {
    slug: "watchguard",
    name: "WatchGuard Technologies",
    category: "Cybersecurity / MSP Platform / MDR",
    broadCategory: "セキュリティ・IT運用",
    hq: "ワシントン州シアトル（米国）",
    japanPresence: "日本公式サイト・東京のオンサイト求人を確認。国内法人・人員は本調査で特定できず",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "network、endpoint、identity、MDRをMSP・channel向けplatformとして提供。東京で日本事業と営業組織を率いるCountry Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.lever.co/watchguard?team=Sales",
    tags: ["Cybersecurity", "MSP", "MDR", "Channel", "Sales Leadership", "Country Manager", "Japan"],
  },
  {
    slug: "langchain",
    name: "LangChain",
    category: "AI Agent Engineering / Observability / Developer Platform",
    broadCategory: "AI・データ基盤",
    hq: "カリフォルニア州サンフランシスコ／ニューヨーク（米国）",
    japanPresence: "日本法人・国内拠点・Japan求人を確認できず",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "LangChain、LangGraph、LangSmithでAI agentの開発・評価・運用を支援。楽天の国内事例とAPAC region選択は確認したが、日本法人・拠点・専任求人は未確認。",
    lastChecked: checkedAt,
    careersUrl: "https://www.langchain.com/careers",
    tags: ["日本未進出", "AI Agent", "LangGraph", "LangSmith", "Developer Platform", "APAC", "Enterprise"],
    entryStatus: "not-entered",
  },
];

const careerInsights = (title: string, domain: string): Job["careerInsights"] => ({
  fit: `${domain}で顧客・partner・社内専門職を動かし、事業成果を定量化したい人に向く。`,
  thingsToKnow: "日本の個別報酬、quota、達成率、担当範囲、平均ACV、ramp、昇進・離職分布は公式求人で確認できない。",
  marketValue: `${title}の成果をpipeline、受注、partner contribution、顧客KPI、team productivityで示せれば、隣接するEnterprise softwareの上位scopeへ説明しやすい。`,
  tenureAndPromotion: `【Genba仮説】${title}では在籍年数より、個人・team成果、再利用できるplaybook、複数stakeholderを動かした証拠が昇進材料になる。支持材料: 公式求人は事業目標、部門横断の実行、継続的な改善を責任として置く。反証・留保: 日本teamの平均在籍年数、昇進率、manager別離職、社内公募実績は公開されていない。面接で確認: 直近24カ月の昇進・異動・退職件数、次levelへ進んだ人の共通KPI、managerのpromotion実績を聞く。`,
  priorCompanies: `【Genba仮説】${domain}、Enterprise software、consulting、channelでdiscoveryから受注・定着まで進めた人が隣接する。支持材料: ${title}は製品知識だけでなく、複数stakeholder、事業計画、実行責任を求める。反証・留保: 日本teamの入社元企業分布を十分な母数で確認できず、特定企業からの採用傾向は断定できない。面接で確認: 現teamで活躍する人の前職類型、採用時に評価した定量成果、ramp支援を聞く。`,
  nextCompanies: `【Genba仮説】${title}でpipeline、受注、partner contribution、顧客KPI、team成果を定量化できれば、Strategic Sales、Alliance、Country Leadership、APAC Leadershipが隣接する。支持材料: ${domain}は顧客規模、地域、portfolio、team責任を広げる形で上位scopeへ接続する。反証・留保: 実際の退職後転職先や昇給幅を示す日本の公開分布ではない。面接で確認: alumniの代表的な進路、社内の次role、必要なKPIとpeople leadership実績を聞く。`,
});

export const jobs20260819Daily: Job[] = [
  {
    id: "gitlab-senior-ecosystem-sales-manager-japan-8640173002",
    companySlug: "gitlab",
    title: "Senior Ecosystem Sales Manager, Japan",
    segment: "Ecosystem / Alliance Sales",
    location: "日本",
    workStyle: "Remote（日本国内）",
    language: "日本語と英語",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "GitLab Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/gitlab/jobs/8640173002" },
    descriptionSummary: "日本のhyperscaler、GSIs、reseller、technology partnerとjoint business plan、pipeline、co-sell、enablementを進め、ecosystem経由の売上を拡大する。",
    genbaTake: "partner数を増やす役割ではなく、共同account plan、sourced・influenced pipeline、technical delivery、seller activationを再現可能なJapan ecosystemへ変える役割。",
    compensationReality: "日本向けのbase、variable、equity、quota、partner-sourcedとinfluenced revenueのcreditは公式求人で確認できない。",
    desiredProfile: "日本のenterprise technology ecosystem、alliance・channel sales、共同GTM、executive relationship、日本語・英語でのglobal collaborationを担える人。",
    careerInsights: careerInsights("Senior Ecosystem Sales Manager", "DevSecOps・AI software development・Alliance Sales"),
  },
  {
    id: "watchguard-country-manager-japan-31981db1",
    companySlug: "watchguard",
    title: "Country Manager - Japan",
    segment: "Country Leadership / Channel Sales",
    location: "東京",
    workStyle: "オンサイト",
    language: "公式求人で明記なし",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "WatchGuard Careers (Lever)", url: "https://jobs.lever.co/watchguard/31981db1-54fb-4764-9f8c-16b886d176ae" },
    descriptionSummary: "日本のregional sales strategy、売上目標、forecast、営業team、二層distribution、channel・MSP partner、採用・coachingを統括する。",
    genbaTake: "肩書きだけでなく、既存売上とpartner productivityを守りながらnew logo・service attach・team capacityを伸ばすJapan P&Lに近い営業責任。",
    compensationReality: "base、bonus・variable、equity、country quota、現在売上、seller別達成率は公式求人で確認できない。",
    desiredProfile: "日本のcybersecurity vendor sales leadership 10年以上、channel・distribution、forecast、採用・coaching、Salesforce運用を担える人。",
    careerInsights: careerInsights("Country Manager", "Cybersecurity・MSP・Channel Leadership"),
  },
];
