import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-21";

export const companies20260821Daily: Company[] = [
  {
    slug: "dropbox",
    name: "Dropbox",
    category: "コンテンツコラボレーション・クラウドストレージ・企業内検索",
    broadCategory: "業務自動化・コラボレーション",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Dropbox Japan株式会社・東京都千代田区（2014年設立）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "cloud storage、content collaboration、eSignature、AI searchを提供。日本法人28人規模で、Remote JapanのCustomer Success Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.dropbox.com/all-jobs",
    tags: ["アンカー企業", "Content Collaboration", "Cloud Storage", "Enterprise Search", "AI", "Customer Success", "Remote", "Japan"],
  },
  {
    slug: "fastly",
    name: "Fastly",
    category: "エッジクラウド・CDN・アプリケーションセキュリティ",
    broadCategory: "セキュリティ・IT運用",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "ファストリー株式会社・東京都港区（日本法人の被保険者35人）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "delivery、edge compute、Next-Gen WAF、DDoS・API security、observabilityを統合するedge cloud。東京でSenior Account Executiveを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.fastly.com/about/careers/current-openings",
    tags: ["Edge Cloud", "CDN", "Application Security", "DDoS", "Compute", "Enterprise Sales", "Hybrid", "Japan"],
  },
  {
    slug: "webflow",
    name: "Webflow",
    category: "Webサイト体験基盤・ビジュアル開発・CMS",
    broadCategory: "業務自動化・コラボレーション",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "日本法人・常設拠点・Japan求人は未確認",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "visual development、CMS、optimization、localization、enterprise governanceを束ねるwebsite experience platform。日本の利用・partner接点はあるが、公式な国内拠点とJapan求人は未確認。",
    lastChecked: checkedAt,
    careersUrl: "https://webflow.com/company/careers/roles",
    tags: ["日本未進出", "Website Experience Platform", "Visual Development", "CMS", "Localization", "Enterprise", "Remote-first"],
    entryStatus: "not-entered",
  },
];

const careerInsights = (title: string, domain: string): Job["careerInsights"] => ({
  fit: `${domain}で顧客の現状を診断し、複数stakeholderと社内専門職を動かして定量成果を作りたい人に向く。`,
  thingsToKnow: "日本のbase、OTE、equity、quota、担当社数、達成率、ramp、昇進・離職分布は公式求人で確認できない。",
  marketValue: `${title}の成果をpipeline、受注、adoption、retention、expansion、顧客KPIで示せれば、隣接するEnterprise softwareの上位scopeへ説明しやすい。`,
  tenureAndPromotion: `【Genba仮説】${title}では在籍年数より、顧客成果、個人・team成果、再利用できるplaybook、複数stakeholderを動かした証拠が昇進材料になる。支持材料: 公式求人は成果責任と部門横断の実行を求める。反証・留保: 日本teamの平均在籍年数、昇進率、manager別離職は公開されていない。面接で確認: 直近24カ月の昇進・異動・退職件数、次levelへ進んだ人の共通KPIを聞く。`,
  priorCompanies: `【Genba仮説】${domain}、Enterprise software、cloud、security、consultingでdiscoveryから受注・定着まで進めた人が隣接する。支持材料: ${title}は製品知識だけでなく、複数stakeholder、事業計画、実行責任を求める。反証・留保: 日本teamの入社元分布を十分な母数で確認できない。面接で確認: 活躍者の前職類型、採用時に評価した定量成果、ramp支援を聞く。`,
  nextCompanies: `【Genba仮説】${title}でpipeline、受注、adoption、retention、expansion、顧客KPIを定量化できれば、Strategic Sales、CS Leadership、Value Engineering、Country Leadershipが隣接する。支持材料: ${domain}は顧客規模、portfolio、team責任を広げる形で上位scopeへ接続する。反証・留保: 実際の転職先や昇給幅を示す日本の公開分布ではない。面接で確認: alumniの代表的な進路と社内の次roleを聞く。`,
});

export const jobs20260821Daily: Job[] = [
  {
    id: "dropbox-customer-success-manager-japan-6862441",
    companySlug: "dropbox",
    title: "Customer Success Manager - Japan",
    segment: "Enterprise Customer Success / Adoption & Expansion",
    location: "日本",
    workStyle: "Remote（日本国内）／顧客meeting・team offsiteへの出張あり",
    language: "日本語・英語ともbusiness-level",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Dropbox Careers", url: "https://jobs.dropbox.com/listing/6862441" },
    descriptionSummary: "大手顧客のdeployment、product education、usage、adoption、value realizationをSuccess PlanとBusiness Reviewで進め、Salesとretention・growthを支える。",
    genbaTake: "cloud storageの利用定着だけでなく、Dropbox Dashを含むportfolioで情報探索、共有、governanceのworkflowを変え、adoptionをrenewal・expansionの根拠へ変えるpost-sale role。",
    compensationReality: "日本向けのbase、bonus、equity、retention・expansion目標、担当社数、commercial creditは公式求人で確認できない。",
    desiredProfile: "4年以上のB2B SaaS Customer Success、大企業顧客、IT adminからexecutiveまでの関係構築、technical aptitude、定量分析、日本語・英語を担える人。",
    careerInsights: careerInsights("Customer Success Manager", "Content Collaboration・Enterprise Search・Customer Success"),
  },
  {
    id: "fastly-senior-account-executive-japan-6873321",
    companySlug: "fastly",
    title: "Senior Account Executive",
    segment: "Enterprise Sales / Commerce & Finance",
    location: "東京（日本）",
    workStyle: "Tokyo / Remote。東京officeはHybridで週2〜3回出社",
    language: "日本語native／英語business-level",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Fastly Careers (Greenhouse)", url: "https://www.fastly.com/about/jobs/apply?gh_jid=6873321" },
    descriptionSummary: "Commerce・Finance業界を中心にGTM plan、prospecting、discovery、PoC、value proposition、pricing、契約、account managementまでfull-cycleで担当する。",
    genbaTake: "CDNの速度だけでなく、application・API security、DDoS、edge compute、observabilityを、conversion、availability、fraud・attack risk、cloud costのbusiness caseへ変えるenterprise sale。",
    compensationReality: "日本向けのbase、OTE、equity、quota、accelerator、new・expansion・usageのcreditは公式求人で確認できない。",
    desiredProfile: "Security salesでのnew business、CommerceまたはFinanceの日本顧客、C-level商談、cloud・CDN・WAF・DevOps、複雑なEnterprise sales cycleを担える人。",
    careerInsights: careerInsights("Senior Account Executive", "Edge Cloud・Application Security・Enterprise Sales"),
  },
];
