import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchSix: Job[] = [
  job({
    id: "aghanim-customer-success-producer-japan", companySlug: "aghanim", title: "Customer Success Producer (Japan)", segment: "Customer Success / LiveOps", location: "日本", workStyle: "リモート / フルタイム", language: "日本語（fluent）／英語要件は明記なし", source: { label: "Aghanim Careers (Ashby)", url: "https://jobs.ashbyhq.com/aghanim/911b20d1-1a67-4b1f-a899-e64309823fce" },
    descriptionSummary: "日本のmobile game顧客によるDTC移行、価格・offer実験、LiveOps、product analytics、revenue expansionを支援する。", genbaTake: "support対応ではなく、顧客のmonetizationとDTC成果をSQL・実験・運用で作るcommercial delivery role。", compensationReality: "給与・bonus・OTEは非公開。equity benefitの記載はあるが額・条件は非公開。", desiredProfile: "日本在住、fluent Japanese、mobile game・F2P・LiveOps・monetization・product analytics 3年以上、advanced SQL／Google Sheetsを求める。", domain: "Gaming Commerce・Customer Success",
  }),
  job({ id: "airwallex-inbound-sales-representative-japan", companySlug: "airwallex", title: "Inbound Sales Representative, Japan", segment: "SME / Inbound Sales", location: "東京", workStyle: "フルタイム／勤務形態は明記なし", language: "日本語（native）／英語（business）", source: { label: "Airwallex Careers (Ashby)", url: "https://jobs.ashbyhq.com/airwallex/0d5b8edc-b8f3-46fb-af47-c5f8b0700922" }, descriptionSummary: "SME leadをqualifyし、pitch、onboarding、activationまで進める。", genbaTake: "件数だけでなく、online paymentsの適合性とactivationまでをqualifyするinbound motion。", compensationReality: "給与・OTE・quotaは非公開。", desiredProfile: "1年以上の関連経験、native Japanese、business Englishを求める。", domain: "Payments・Inbound Sales" }),
  job({ id: "airwallex-account-manager-japan", companySlug: "airwallex", title: "Account Manager, Japan", segment: "Account Management / Partnerships", location: "東京", workStyle: "オンサイト / フルタイム", language: "日本語・英語", source: { label: "Airwallex Careers", url: "https://careers.airwallex.com/job/2c0631c2-2c45-452c-9b73-c48ac8e13736/" }, descriptionSummary: "既存顧客のupsell・cross-sellと、ecommerce・accounting・startupのreferral partner開拓を担う。", genbaTake: "既存利用の拡張とpartner pipelineを同時に持つcommercial account role。", compensationReality: "給与・OTE・quotaは非公開。", desiredProfile: "3年以上、日本語・英語でのwritten／verbal／in-person communicationを求める。", domain: "Payments・Account Management" }),
  job({ id: "airwallex-sales-manager-sme-growth-japan", companySlug: "airwallex", title: "Sales Manager, SME & Growth", segment: "Sales Leadership", location: "東京", workStyle: "オンサイト / フルタイム", language: "日本語（native）／英語（business）", source: { label: "Airwallex Careers", url: "https://careers.airwallex.com/job/bd889718-0308-484d-8810-48e01c92c09f/sales-manager-sme-growth/" }, descriptionSummary: "日本のSME・Growth sales teamとchannel GTMを率い、pipeline、forecast、coaching、採用を担う。", genbaTake: "個人受注でなく、提供開始直後の市場でdirect・channelの再現性を作るsales leadership。", compensationReality: "給与・OTE・team quotaは非公開。", desiredProfile: "日本市場のsales leadership、native Japanese、business Englishを求める。", domain: "Payments・Sales Leadership" }),
  job({ id: "airwallex-venture-partnerships-manager-japan", companySlug: "airwallex", title: "Venture Partnerships Manager", segment: "Startups / Partnerships", location: "ソウル・東京", workStyle: "フルタイム／勤務形態は明記なし", language: "日本語または韓国語（native）／英語（fluent）", source: { label: "Airwallex Careers (Ashby)", url: "https://jobs.ashbyhq.com/airwallex/bda529ac-4b7b-4d1f-8804-1ed0f1375f29/" }, descriptionSummary: "VC・acceleratorとの関係を構築し、startup向けreferral pipelineとjoint programを作る。", genbaTake: "紹介件数でなく、投資先のactivation、product fit、partner-sourced revenueを運用するecosystem role。", compensationReality: "給与・bonus・targetは非公開。", desiredProfile: "VC・startup ecosystem、partnership、native JapaneseまたはKorean、fluent Englishを求める。", domain: "FinTech・Venture Partnerships" }),
  job({ id: "airwallex-operation-manager-japan", companySlug: "airwallex", title: "Operation Manager, Japan", segment: "Operations / Delivery", location: "東京", workStyle: "オンサイト / フルタイム", language: "日本語・英語（fluent）", source: { label: "Airwallex Careers", url: "https://careers.airwallex.com/job/6336a857-6f7f-4c1d-a3e9-686898482135/operation-manager-japan/" }, descriptionSummary: "KYC・AML／CTF、transaction monitoring、treasury・payment operations、customer support processを構築する。", genbaTake: "販売後のdeliveryだけでなく、規制下のcustomer activationと金融operationを日本で成立させる役割。", compensationReality: "給与・bonus・評価指標は非公開。", desiredProfile: "7年以上、fluent Japanese and English、payments・financial operations・compliance連携を求める。", domain: "FinTech Operations・Compliance Delivery" }),
  job({ id: "anthropic-applied-ai-architect-japan", companySlug: "anthropic", title: "Applied AI Architect", segment: "Applied AI / Architecture", location: "東京", workStyle: "office 25%以上", language: "日本語（native）／英語（business）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5076109008" }, descriptionSummary: "pre-sales evaluationからarchitecture、deploymentまで顧客のClaude production導入を主導する。", genbaTake: "model demoでなく、実業務eval、安全設計、data・tool接続、本番成果をまとめるtechnical role。", compensationReality: "日本の給与・bonus・equity金額は非公開。", desiredProfile: "Applied AI、architecture、顧客対応、日本語native・英語businessを求める。", domain: "Frontier AI・Applied Architecture" }),
  job({ id: "anthropic-partner-solutions-architect-japan", companySlug: "anthropic", title: "Partner Solutions Architect, Applied AI", segment: "Partner / Applied AI", location: "東京", workStyle: "office 25%以上", language: "日本語・英語（fluent）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5222908008" }, descriptionSummary: "SI・cloud partnerをenableし、joint solution、customer evaluation、deploymentを技術面で支える。", genbaTake: "partner trainingで終わらず、再利用できるindustry solutionとco-sell delivery capacityを作る。", compensationReality: "日本の給与・bonus・equity金額は非公開。", desiredProfile: "AI architecture、partner・customer delivery、日本語・英語fluentを求める。", domain: "Frontier AI・Partner Solutions" }),
  job({ id: "anthropic-product-support-specialist-japan", companySlug: "anthropic", title: "Product Support Specialist", segment: "Product Support / Customer", location: "東京", workStyle: "office 25%以上／月〜金10:00〜18:00", language: "日本語（native）／英語（business）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5138042008" }, descriptionSummary: "Claude product・APIのcustomer issueを解決し、APAC pager dutyとProduct・Engineering escalationを担う。", genbaTake: "support ticket処理だけでなく、production reliabilityと再発防止をcustomer trustへ変える。", compensationReality: "給与金額は非公開。", desiredProfile: "technical support、native Japanese、business English、APAC pager duty対応を求める。", domain: "Frontier AI・Product Support" }),
  job({ id: "anthropic-channel-account-manager-japan", companySlug: "anthropic", title: "Channel Account Manager", segment: "Channel / Cloud Partners", location: "東京", workStyle: "office 25%以上", language: "日本語・英語（native／business level）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5291731008" }, descriptionSummary: "AWS・GCP等のpartner enablement、joint solution、co-sell、partner-sourced revenueを担う。", genbaTake: "model referralでなく、cloud consumption・industry solution・deliveryを共同pipelineへ変える。", compensationReality: "給与・OTE・pay mixは非公開。", desiredProfile: "channel account management、cloud ecosystem、日本語・英語を求める。", domain: "Frontier AI・Channel" }),
  job({ id: "anthropic-channel-account-manager-si-reseller-japan", companySlug: "anthropic", title: "Channel Account Manager, SI & Reseller", segment: "Channel / SI & Reseller", location: "東京", workStyle: "office 25%以上", language: "日本語（native／business）／英語要件は明記なし", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5237030008" }, descriptionSummary: "SI・resellerのenablement、共同solution、account planning、partner-sourced revenueを担う。", genbaTake: "国内SIのdelivery capacityとindustry accessをClaudeのproduction adoptionへ変える。", compensationReality: "給与・OTE・pay mixは非公開。", desiredProfile: "SI・reseller channel、日本語native／businessを求める。英語要件は明記しない。", domain: "Frontier AI・SI Channel" }),
  job({ id: "anthropic-customer-success-manager-japan", companySlug: "anthropic", title: "Customer Success Manager", segment: "Customer Success / Expansion", location: "東京", workStyle: "office 25%以上", language: "日本語・英語（fluent）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5387027008" }, descriptionSummary: "日本初CSMとしてClaude API・Enterprise・Codeのusage、seat adoption、ROI、CoE、QBR、expansionを担う。", genbaTake: "利用案内でなく、AI use caseをproduction成果とrenewal・拡張へ結ぶfounding CS role。", compensationReality: "給与・bonus・equity金額は非公開。", desiredProfile: "Enterprise CS、AI adoption、executive QBR、日本語・英語fluentを求める。", domain: "Frontier AI・Customer Success" }),
  job({ id: "anthropic-enterprise-ae-fsi-japan", companySlug: "anthropic", title: "Enterprise Account Executive, FSI", segment: "Enterprise / Financial Services", location: "東京", workStyle: "office 25%以上", language: "日本語・英語（excellent）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5104753008" }, descriptionSummary: "金融業界のnew logoと既存拡張をfull-cycleで担い、risk・compliance・IT・事業部門を束ねる。", genbaTake: "AI seatでなく、regulated workflowのeval、安全、human review、ROIを購入条件へするvertical sale。", compensationReality: "base、commission、equityの記載はあるが日本の金額・OTE・pay mixは非公開。", desiredProfile: "Enterprise sales、FSI domain、C-level・complex deal、日本語・英語excellentを求める。", domain: "Frontier AI・FSI Sales" }),
  job({ id: "anthropic-enterprise-ae-retail-japan", companySlug: "anthropic", title: "Enterprise Account Executive, Retail", segment: "Enterprise / Retail", location: "東京", workStyle: "office 25%以上", language: "日本語・英語（excellent）", source: { label: "Anthropic Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/anthropic/jobs/5104754008" }, descriptionSummary: "Retail大手のnew logoと既存拡張をfull-cycleで担い、customer experience・marketing・supply chain・ITを束ねる。", genbaTake: "汎用AIの説明でなく、retail workflowごとのtask success・unit cost・riskをbusiness caseにする。", compensationReality: "base、commission、equityの記載はあるが日本の金額・OTE・pay mixは非公開。", desiredProfile: "Enterprise sales、Retail domain、C-level・complex deal、日本語・英語excellentを求める。", domain: "Frontier AI・Retail Sales" }),
];
