import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildIntelligence } from "@/lib/company-public-intelligence-wave-two";

const datadogIntelligence: CompanyPublicIntelligence = buildIntelligence({
  slug: "datadog", name: "Datadog", jobUrl: "https://careers.datadoghq.com/ja/detail/6009777/?gh_jid=6009777", officialUrl: "https://www.datadoghq.com/ja/", customersUrl: "https://www.datadoghq.com/ja/customers/", externalUrl: "https://www.meti.go.jp/policy/netsecurity/index.html", financeUrl: "https://investors.datadoghq.com/static-files/0a0cecbd-9dfe-43c8-9174-1bcffad62c20", publicInfo: { ticker: "DDOG", exchange: "NASDAQ", listedSince: "2019年" },
  salesSnapshot: "Datadogは、CTO・SRE・Security・開発組織に、cloud applicationのobservabilityとsecurityを一つのplatformで提供する会社。顧客が抱えるのは「monitoring toolが分断し障害原因を追えない」「cloud利用量と監視費用が増えて投資対効果を説明できない」「開発速度を落とさずsecurityを組み込みたい」という3つの課題。infra監視から入り、APM、log、security、developer experience、AI運用へaccountを広げられる点が営業としての面白さ。",
  growthSummary: "2025年末時点で約32,700顧客を160カ国で支援し、5,000人超の組織を持つ公開企業。東京ではCommercial、Mid-Market、Strategic、Public Sectorまで複数の営業職を採用し、日本GTMをsegment別に拡張。",
  milestones: [{ year: "2010", label: "創業", detail: "cloud-scale monitoring platformとしてNew Yorkで創業。", source: "company" }, { year: "2019", label: "NASDAQ上場", detail: "ticker DDOGで公開企業化。", source: "finance" }, { year: "2024", label: "platform拡張", detail: "Observability、Cloud Security、Digital Experienceを横断するportfolioを展開。", source: "company" }, { year: "2025", label: "32,700顧客", detail: "160カ国の顧客基盤を年次報告書で開示。", source: "finance" }, { year: "2026", label: "Japan segment拡張", detail: "CommercialからPublic Sectorまで複数の営業求人を公式掲載。", source: "job" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "顧客事例に共通するのは、cloud移行で増えたservice・log・traceを一つのcontextで結び、障害時間と運用工数を減らす課題。tool consolidationだけでなく、開発と運用が同じdataで改善を回せる状態が目的。" }, { title: "製品の成り立ちから見る課題", body: "infra monitoringからAPM、log、RUM、security、LLM observabilityへ同じagentとdata modelで拡張した。個別最適のmonitoringではincidentの因果とbusiness impactがつながらない断絶を解く設計。" }, { title: "外部環境の要求から見る課題", body: "cloud native化、生成AI、software supply chainの複雑化で、停止・脆弱性・費用の責任範囲が広がる。経営は開発速度を維持しながらresilienceとsecurityを説明できる運用を求める。" }],
  narrative: [{ label: "背景", body: "cloud、container、SaaS、AI serviceが増え、teamごとにmonitoring toolとdataが分散する。" }, { label: "課題", body: "alertは多いが原因と顧客影響が見えず、war roomの長期化、tool費用、開発者のcontext switchが増える。" }, { label: "解決策", body: "重要serviceを一つ選び、metric・trace・log・user experience・securityを接続し、MTTR、alert、tool費、release影響を測る。" }, { label: "選定の理由", body: "Dynatrace、New Relic、Splunk、cloud native toolとの比較で、広いtelemetryとworkflowを一つのplatformで相関し、team横断で使える場合に選ばれる。" }],
  openingHook: "重大incidentで最初の30分が、原因究明ではなくdataを集める時間になっていませんか。", valueHypothesis: "対象serviceでMTTD、MTTR、alert件数、tool数、ingest費用、release後障害、developer調査時間をbefore/afterで測る。", objection: "AWS・Azure・Google Cloudの標準監視と既存SIEMで十分。", reframe: "個々のcloudが見えるかではなく、multi-cloud・application・user・securityの因果を一つのincidentで追い、運用を自動化できるかで比較する。",
  facts: [{ label: "顧客", value: "約32,700社", detail: "2025年末、160カ国。", source: "finance" }, { label: "社員", value: "5,000人超", detail: "東京office公式紹介のグローバル規模。", source: "company" }, { label: "上場", value: "NASDAQ: DDOG", detail: "2019年上場。", source: "finance" }, { label: "日本拠点", value: "東京", detail: "Sales、Support、Solutions、CS等のGTM機能を配置。", source: "company" }, { label: "営業segment", value: "Commercial〜Public Sector", detail: "複数の日本求人を確認。", source: "job" }, { label: "日本求人", value: "Commercial AE", detail: "東京の公式求人を確認。", source: "job" }],
  customers: [{ company: "Samsung", products: "Datadog Platform", outcome: "大規模digital serviceの観測とincident対応を顧客事例化。", implication: "global scaleと複雑なservice mapが価値の起点。" }, { company: "Mercado Libre", products: "Observability", outcome: "高成長commerce基盤の運用を公開事例で紹介。", implication: "reliabilityを売上影響へつなげる提案。" }, { company: "Toyota Motor North America", products: "Datadog", outcome: "cloud・application運用の可視化を顧客事例として公開。", implication: "大企業の複数teamへland-and-expandできる。" }],
  externalSignals: [{ label: "cybersecurity", value: "経営課題", detail: "経済産業省は企業のcybersecurity経営と継続的なrisk管理を求める。", caveat: "Datadogの採用義務や個別適合性を示さない。" }, { label: "cloud運用", value: "複雑性が増加", detail: "multi-cloudとsoftware化で障害・費用・securityを横断管理する必要が高まる。", caveat: "統合効果はdata量、既存契約、運用成熟度で異なる。" }],
  role: "Commercial顧客のnew logoと既存拡張を持ち、prospecting、technical discovery、business case、SE連携、negotiation、closeを担うAccount Executive。", organization: "東京にSales、Solutions、CS、Support、Marketing、Peopleを置くsegment別GTM組織。", careerValue: "observabilityとsecurityをCTO・CISO・Engineeringへ横断提案し、consumption型platformのland-and-expandを経験できる。", globalHeadcount: "5,000人超", japanPresence: "Tokyo office / 日本GTM組織", japanSince: "日本拠点を公式掲載、設立年は本調査で確定できず",
  solutions: [{ name: "Infrastructure / APM", valueProp: "infraからapplication traceまで障害原因を相関。", url: "https://www.datadoghq.com/ja/product/", competitors: "Dynatrace、New Relic、cloud native monitoring。", differentiation: "広いintegrationと共通tagによる横断context。" }, { name: "Log Management / Observability Pipelines", valueProp: "logを収集・加工・検索し運用と費用を管理。", url: "https://www.datadoghq.com/ja/product/log-management/", competitors: "Splunk、Elastic、Cribl。", differentiation: "metric・trace・securityと同じworkflowで利用。" }, { name: "Cloud Security", valueProp: "cloud posture、workload、application securityを観測dataへ接続。", url: "https://www.datadoghq.com/ja/product/security-platform/", competitors: "Wiz、Palo Alto Networks、native security。", differentiation: "runtime・application contextをsecurity investigationへ持ち込む。" }],
  fitTags: ["Commercial", "Enterprise", "Observability", "Security", "Cloud", "Consumption", "Platform", "Land-and-expand"], comparisons: [{ arena: "Observability", companies: ["Datadog", "Dynatrace", "New Relic"], why: "coverage、automation、enterprise運用" }, { arena: "Log / SIEM", companies: ["Datadog", "Splunk", "Elastic"], why: "検索、security、cost" }, { arena: "Cloud Security", companies: ["Datadog", "Wiz", "Palo Alto Networks"], why: "posture、runtime、application context" }],
});

const scanditIntelligence: CompanyPublicIntelligence = buildIntelligence({
  slug: "scandit", name: "Scandit", jobUrl: "https://www.scandit.com/jp/careers/", officialUrl: "https://www.scandit.com/jp/", customersUrl: "https://www.scandit.com/resources/case-studies/", externalUrl: "https://www.meti.go.jp/policy/economy/distribution/index.html", financeUrl: "https://www.scandit.com/company/",
  salesSnapshot: "Scanditは、小売・物流・製造・航空の業務責任者とITに、smartphone・wearable・droneでbarcodeや現場dataを取得するSmart Data Captureを提供する会社。顧客が抱えるのは「専用scannerの調達と保守が高い」「店舗・倉庫の読み取りが遅く誤りも多い」「現場dataをAI・workflowへリアルタイム接続できない」という3つの課題。棚卸や配送scanから入り、self-scanning、last mile、inventory visibility、AR guidanceへ広げられる点が営業としての面白さ。",
  growthSummary: "世界2,100社超、1.7億台規模のdeviceで利用され、年間500億回規模のscanを処理。東京拠点と日本語siteを持ち、USMH、イオンリテール、ヤマト運輸等の国内事例を基盤にAccount Executive採用を継続。", ipoSummary: "非公開企業。日本売上、ARR、IPO時期は公表されていない。",
  milestones: [{ year: "2009", label: "創業", detail: "ETH Zurich発のcomputer vision企業として創業。", source: "company" }, { year: "2017", label: "global scale", detail: "smartphoneを業務scannerへ変えるenterprise platformを拡張。", source: "company" }, { year: "2022", label: "Series D", detail: "1.5億ドルの資金調達を発表。", source: "finance" }, { year: "2025", label: "国内事例拡大", detail: "小売・物流で大規模deploymentを公開。", source: "company" }, { year: "2026", label: "Tokyo AE採用", detail: "JapanのAccount Executive採用を公式発信。", source: "job" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "USMH、イオンリテール、ヤマト運輸の事例は、scan速度だけでなく、既存smartphoneを使った全店・全拠点展開、顧客体験、現場教育、device保守の削減を同時に求める課題を示す。" }, { title: "製品の成り立ちから見る課題", body: "専用hardwareの性能をsoftwareとcomputer visionで一般端末へ移し、複数barcode、文字、objectをcontext付きで取得する方向へ拡張。data captureを業務automationの入口として設計。" }, { title: "外部環境の要求から見る課題", body: "人手不足、omnichannel、配送量増加で現場は少人数で正確に処理する必要がある。一方、device追加は調達・教育・保守を増やすため、既存端末で標準化できる仕組みが求められる。" }],
  narrative: [{ label: "背景", body: "店舗・倉庫・配送の現場でscan回数と取得dataが増えるが、人員と専用device予算は増えない。" }, { label: "課題", body: "読み取り待ち、入力誤り、battery・故障、教育の負荷が積み上がり、system側に正しい現場dataが届かない。" }, { label: "解決策", body: "一つのworkflowで既存deviceへSmart Data Captureを組み込み、処理時間、誤読、training、device TCO、adoptionを測る。" }, { label: "選定の理由", body: "Zebra・Honeywell等の専用scanner、Apple/Google標準camera、競合SDKとの比較で、精度と速度、enterprise管理、複数use caseへの再利用が揃う場合に選ばれる。" }],
  openingHook: "現場の一回のscanに数秒余計にかかることで、全店舗・全配送員では年間何時間を失っていますか。", valueHypothesis: "対象workflowで1件当たり処理時間、再scan率、training時間、device費、active user、業務完了件数を測る。", objection: "専用handy terminalの方が速くて堅牢。", reframe: "単体の瞬間速度ではなく、調達・故障・教育・software更新を含む全拠点TCOと、workflow拡張性で比較する。",
  facts: [{ label: "顧客", value: "2,100社超", detail: "世界のenterprise顧客。", source: "company" }, { label: "利用device", value: "1.7億台規模", detail: "会社公式の利用規模。", source: "company" }, { label: "年間scan", value: "500億回規模", detail: "会社公式の処理規模。", source: "company" }, { label: "日本拠点", value: "東京", detail: "Tokyo officeを公式掲載。", source: "company" }, { label: "国内事例", value: "小売・物流", detail: "USMH、イオン、ヤマトを公開。", source: "customers" }, { label: "日本求人", value: "Account Executive", detail: "Tokyo採用を公式確認。", source: "job" }],
  customers: [{ company: "USMH", products: "MatrixScan / Self-Scanning", outcome: "約500店舗へ展開し、basket spendの増加を会社事例で紹介。", implication: "consumer experienceと店舗生産性を同時に売れる。" }, { company: "イオンリテール", products: "Scandit Self-Scanning", outcome: "利用拡大と購買成果を公開事例化。", implication: "全国scaleのchange managementが選定条件。" }, { company: "ヤマト運輸", products: "Smart Data Capture", outcome: "最大9,000人規模、1日300scan規模の現場利用を紹介。", implication: "last-mileの処理速度とdevice標準化へ提案できる。" }],
  externalSignals: [{ label: "流通政策", value: "省人化・生産性", detail: "経済産業省は流通の人手不足と生産性向上を政策課題として扱う。", caveat: "Scanditの導入義務や成果保証を示さない。" }, { label: "現場DX", value: "device統合", detail: "業務用smartphone普及でcapture、guidance、communicationを一台へ集約する余地がある。", caveat: "耐久性・offline・security要件は現場別に検証が必要。" }],
  role: "小売・物流等のJapan enterpriseを開拓し、現場業務をquantifyしてsolution consultant・partnerとpilotから全社展開まで担うAccount Executive。", organization: "東京拠点とglobal Product・Solution・Customer Successをつなぐvertical GTM。", careerValue: "softwareとphysical operationをつなぎ、現場ROI、computer vision、large-scale rolloutを売る経験になる。", globalHeadcount: "501〜1,000人規模の公開集計", japanPresence: "Scandit Tokyo office", japanSince: "東京拠点を公式掲載、設立年は本調査で確定できず",
  solutions: [{ name: "Smart Data Capture", valueProp: "barcode、text、ID、objectをsmart deviceで高速取得。", url: "https://www.scandit.com/products/", competitors: "Zebra、Honeywell、Datalogic。", differentiation: "hardware非依存のsoftware platformとcomputer vision。" }, { name: "MatrixScan", valueProp: "複数barcodeを一度に読み取りARで作業を案内。", url: "https://www.scandit.com/products/matrixscan/", competitors: "専用scanner、custom vision。", differentiation: "captureとvisual guidanceを一画面で統合。" }, { name: "ShelfView / ID Bolt", valueProp: "棚・ID確認をcomputer visionでautomation。", url: "https://www.scandit.com/products/", competitors: "画像認識vendor、manual audit。", differentiation: "既存capture platformとenterprise deploymentを再利用。" }],
  fitTags: ["Enterprise", "Retail", "Logistics", "Computer Vision", "Field Sales", "Mobile", "Partner", "Operational ROI"], comparisons: [{ arena: "Data capture", companies: ["Scandit", "Zebra", "Honeywell"], why: "softwareと専用hardwareのTCO" }, { arena: "Computer vision", companies: ["Scandit", "Google", "custom AI"], why: "精度、edge、業務統合" }, { arena: "Field workflow", companies: ["Scandit", "custom app", "handheld terminal"], why: "展開速度と管理" }],
});

const docusignIntelligence: CompanyPublicIntelligence = buildIntelligence({
  slug: "docusign", name: "DocuSign", jobUrl: "https://careers.docusign.com/jobs/29939?lang=en-us", officialUrl: "https://www.docusign.com/ja-jp/company", customersUrl: "https://www.docusign.com/ja-jp/customer-stories", externalUrl: "https://www.digital.go.jp/policies/digitalsign", financeUrl: "https://investor.docusign.com/financial-information/annual-reports-and-proxies", publicInfo: { ticker: "DOCU", exchange: "NASDAQ", listedSince: "2018年" },
  salesSnapshot: "DocuSignは、法務・営業・調達・人事・ITに、契約の作成、合意、署名、管理、分析をつなぐIntelligent Agreement Managementを提供する会社。顧客が抱えるのは「契約締結が紙・email・押印で止まる」「締結後の更新日・義務・riskが見えない」「部門ごとの契約toolがCRM・ERPと分断する」という3つの課題。電子署名から入り、CLM、AI review、identity、workflow、全社agreement dataへ拡張できる点が営業としての面白さ。",
  growthSummary: "世界160カ国超、約160万顧客、10億人超の利用基盤を持つ公開企業。日本ではSMB Account Executiveを含む営業採用を続け、国内企業の電子契約から契約業務全体のplatform化へ提案領域を拡張。",
  milestones: [{ year: "2003", label: "創業", detail: "電子署名serviceとして創業。", source: "company" }, { year: "2015", label: "日本展開", detail: "日本市場での事業・日本語提供を拡張。", source: "company" }, { year: "2018", label: "NASDAQ上場", detail: "ticker DOCUで上場。", source: "finance" }, { year: "2024", label: "IAM発表", detail: "署名からIntelligent Agreement Managementへcategoryを拡張。", source: "company" }, { year: "2026", label: "SMB AE採用", detail: "東京でSMB向けAccount Executiveを募集。", source: "job" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "国内事例は、押印削減だけでなく、Salesforce等との連携、remote onboarding、契約lead time短縮、監査可能性を目的にしている。締結後の検索・更新・義務管理まで残ることが次の課題。" }, { title: "製品の成り立ちから見る課題", body: "電子署名で最後の合意をdigital化し、template、workflow、identity、CLM、AI extractionへ前後工程を拡張。agreementがdocumentとして孤立し、system of recordにならない断絶を解く。" }, { title: "外部環境の要求から見る課題", body: "電子署名制度とremote workが普及した一方、企業は本人確認、証跡、保存、権限、個人情報、契約更新を一貫して管理する必要がある。単なる押印代替からgovernanceへ要求が上がる。" }],
  narrative: [{ label: "背景", body: "営業、調達、人事、法務が異なるtemplateと承認経路で契約し、締結dataが各systemへ散らばる。" }, { label: "課題", body: "署名待ちで売上・採用・調達が遅れ、締結後は更新・義務・riskをspreadsheetと担当者記憶で追う。" }, { label: "解決策", body: "一つの契約typeで作成、承認、本人確認、署名、保存、更新を接続し、lead time、差戻し、検索、更新漏れを測る。" }, { label: "選定の理由", body: "Adobe Acrobat Sign、GMOサイン、クラウドサイン、CLM製品との比較で、global契約と国内運用、integration、締結後管理を一つのplatformへ広げられる場合に選ばれる。" }],
  openingHook: "契約書が送付されてから売上計上できるまで、どの承認・署名・入力で最も日数を失っていますか。", valueHypothesis: "契約type別に作成から締結までの日数、差戻し、manual入力、更新漏れ、検索時間、conversionを測る。", objection: "国内電子契約かPDF署名で十分。", reframe: "一回の署名単価ではなく、global取引、system連携、本人確認、締結後の検索・更新・義務まで含むagreement lifecycleで比較する。",
  facts: [{ label: "顧客", value: "約160万社", detail: "世界の顧客基盤。", source: "company" }, { label: "利用者", value: "10億人超", detail: "160カ国超。", source: "company" }, { label: "上場", value: "NASDAQ: DOCU", detail: "2018年上場。", source: "finance" }, { label: "category", value: "IAM", detail: "Intelligent Agreement Managementへ拡張。", source: "company" }, { label: "日本拠点", value: "東京", detail: "Japan法人・営業組織を運営。", source: "company" }, { label: "日本求人", value: "AE, SMB", detail: "東京の公式求人を確認。", source: "job" }],
  customers: [{ company: "日本航空", products: "DocuSign eSignature", outcome: "契約・申込業務のdigital化を国内事例として公開。", implication: "規制・大企業の証跡と業務変更が鍵。" }, { company: "Woven by Toyota", products: "DocuSign", outcome: "globalな契約workflowでの利用を事例化。", implication: "日本発global組織のstandardization。" }, { company: "ヤマハ", products: "DocuSign", outcome: "契約締結と業務効率化を公開事例で紹介。", implication: "部門導入からgroup展開を提案できる。" }],
  externalSignals: [{ label: "電子署名", value: "政府が制度・利用を案内", detail: "デジタル庁は電子署名・電子委任状等の制度情報を公開。", caveat: "個別契約の法的有効性は用途と運用で確認が必要。" }, { label: "契約governance", value: "締結後管理が重要", detail: "契約のdigital化が進むほど、権限、保存、更新、data連携の統制が必要。", caveat: "投資効果は契約量と業務設計で異なる。" }],
  role: "SMB顧客のnew logoとexpansionを持ち、high-velocityなprospecting、discovery、demo、business case、negotiation、closeを担うAccount Executive。", organization: "Japanのsegment別営業とSE・CS・partnerをglobal agreement platformへ接続するGTM組織。", careerValue: "category認知の高い製品でSMBのvelocity saleを磨きつつ、署名からCLM・AIへplatform expansionを経験できる。", globalHeadcount: "5,001〜10,000人規模の公開集計", japanPresence: "DocuSign Japan / 東京", japanSince: "日本事業を継続、正確な設立年は本調査で確定できず",
  solutions: [{ name: "eSignature", valueProp: "本人確認・証跡を伴う電子署名workflow。", url: "https://www.docusign.com/ja-jp/products/electronic-signature", competitors: "Adobe Acrobat Sign、クラウドサイン、GMOサイン。", differentiation: "global network、integration、agreement platformへの拡張。" }, { name: "Intelligent Agreement Management", valueProp: "契約作成・締結・管理・分析を統合。", url: "https://www.docusign.com/ja-jp/products/intelligent-agreement-management", competitors: "Ironclad、Icertis、国内CLM。", differentiation: "大規模な署名networkと締結dataをlifecycleへ接続。" }, { name: "DocuSign AI / CLM", valueProp: "契約条項・義務の抽出とworkflow管理。", url: "https://www.docusign.com/ja-jp/products/clm", competitors: "Icertis、ContractPodAI、legal AI。", differentiation: "agreement sourceとexecution layerを同じplatformで扱う。" }],
  fitTags: ["SMB", "Enterprise", "Agreement", "Legal", "Sales Tech", "Velocity", "Platform", "AI"], comparisons: [{ arena: "eSignature", companies: ["DocuSign", "Adobe", "クラウドサイン"], why: "global、価格、国内運用" }, { arena: "CLM", companies: ["DocuSign", "Icertis", "Ironclad"], why: "lifecycle、AI、implementation" }, { arena: "Identity / Trust", companies: ["DocuSign", "GMOサイン", "identity provider"], why: "本人確認と証跡" }],
});

const hightouchIntelligence: CompanyPublicIntelligence = buildIntelligence({
  slug: "hightouch", name: "Hightouch", jobUrl: "https://job-boards.greenhouse.io/hightouch/jobs/5836057004?gh_src=c34e5ee54us", officialUrl: "https://hightouch.com/", customersUrl: "https://hightouch.com/customers", externalUrl: "https://www.ppc.go.jp/personalinfo/", financeUrl: "https://hightouch.com/blog/hightouch-funding-series-c",
  salesSnapshot: "Hightouchは、CMO・CRM・Data・Growth組織に、warehouse内の顧客dataを広告・CRM・supportへ同期し、AIで顧客体験を実行するComposable CDPを提供する会社。顧客が抱えるのは「CDPへdataを複製し整備に時間がかかる」「data teamとmarketingの依頼待ちが長い」「AI personalizationを既存dataとgovernanceの上で動かせない」という3つの課題。Reverse ETLから入り、audience、identity、journey、AI decisioning、広告最適化へ広げられる点が営業としての面白さ。",
  growthSummary: "803社の有償顧客を公式掲載し、2025年に8,000万ドルを12億ドル評価で調達。日本を担当する最初のAccount Executiveを募集し、resellerとともにlocal pipelineを作る初期GTM局面。", ipoSummary: "非公開企業。日本法人、日本売上、IPO時期は公表されていない。",
  milestones: [{ year: "2018", label: "創業", detail: "data warehouseからbusiness toolへdataを動かすReverse ETLを開拓。", source: "company" }, { year: "2021", label: "Composable CDP", detail: "既存warehouseをcustomer data基盤として使うcategoryを展開。", source: "company" }, { year: "2023", label: "AI Decisioning", detail: "audience同期からcustomer journey最適化へ拡張。", source: "company" }, { year: "2025", label: "Series C", detail: "8,000万ドル、12億ドル評価を発表。", source: "finance" }, { year: "2026", label: "first Japan AE", detail: "日本市場を担当する最初のAccount Executiveを募集。", source: "job" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "PetSmart等の顧客は、warehouseへ集約したdataを各channelへ安全にactivationし、data teamの統制を保ちながらmarketingの速度を上げる。導入目的はdata収集ではなく、既存投資をcustomer actionへ変えること。" }, { title: "製品の成り立ちから見る課題", body: "Reverse ETLとしてwarehouseのmodelをSaaSへ同期するところから始まり、identity、audience、journey、AI Decisioningへ拡張。別CDPへdataを複製するarchitectureの遅さ・不整合・lock-inを解く。" }, { title: "外部環境の要求から見る課題", body: "cookie制約、個人情報保護、生成AIでpersonalizationはfirst-party dataと同意・目的管理を前提にする。marketing速度だけでなくdata minimizationとaccess controlを両立する必要がある。" }],
  narrative: [{ label: "背景", body: "customer dataはwarehouseへ集まるが、marketing・sales・supportのexecution toolへ届くまで依頼と実装が発生する。" }, { label: "課題", body: "audience作成が週単位で遅れ、CDPへのdata複製でcostとschemaが増え、personalizationが固定ruleに留まる。" }, { label: "解決策", body: "一つのjourneyでwarehouse modelをchannelへ同期し、作成時間、match率、conversion、data cost、manual requestを測る。" }, { label: "選定の理由", body: "Segment、Salesforce Data Cloud、Adobe、Snowflake native機能との比較で、既存warehouseをsource of truthに保ち、activationとAIを速く実装できる場合に選ばれる。" }],
  openingHook: "新しいcustomer segmentを定義してから広告・CRM・supportで実際に使えるまで何日かかっていますか。", valueHypothesis: "対象journeyでaudience作成時間、data request、match率、conversion、warehouse/CDP cost、time-to-launchを測る。", objection: "既存CDPかSnowflake・Databricksの機能で十分。", reframe: "dataを持つ場所ではなく、既存modelを何channelへ安全に動かし、business userが何時間でexperimentできるかで比較する。",
  facts: [{ label: "有償顧客", value: "803社", detail: "公式about page掲載。", source: "company" }, { label: "Series C", value: "8,000万ドル", detail: "2025年。", source: "finance" }, { label: "評価額", value: "12億ドル", detail: "Series C時点。", source: "finance" }, { label: "category", value: "Composable CDP", detail: "Reverse ETLから拡張。", source: "company" }, { label: "日本GTM", value: "first AE", detail: "resellerと市場開拓。", source: "job" }, { label: "日本求人", value: "Enterprise AE", detail: "Japan担当の公式求人を確認。", source: "job" }],
  customers: [{ company: "PetSmart", products: "Hightouch", outcome: "warehouse dataをcustomer engagementへactivationする事例を公開。", implication: "large retailのomnichannel use case。" }, { company: "Warner Music Group", products: "Hightouch", outcome: "fan dataをchannel activationへつなぐ事例を紹介。", implication: "identityとaudience expansionを提案できる。" }, { company: "Chime", products: "Hightouch", outcome: "regulated consumer businessでdata activationを公開。", implication: "speedとgovernanceの両立が選定条件。" }],
  externalSignals: [{ label: "個人情報保護", value: "目的・同意・安全管理", detail: "個人情報保護委員会は個人dataの適正な取扱いと安全管理を求める。", caveat: "Hightouchの適法性や適合性を示さない。" }, { label: "first-party data", value: "activationが課題", detail: "cookie制約で自社dataを複数channelへ正確に利用する重要性が増す。", caveat: "成果はdata品質、同意、offer、channelで異なる。" }],
  role: "日本市場を担当する最初のAccount Executiveとして、enterprise prospecting、reseller、data・marketing executiveへのvalue selling、technical evaluation、closeを担う。", organization: "APAC/global leadershipとresellerをつなぎ、日本のICP、message、reference、pipelineを作るgreenfield GTM。", careerValue: "modern data stackとmarketingを横断し、first sellerとしてcountry playbookとpartner motionを作る経験になる。", globalHeadcount: "201〜500人規模の公開集計", japanPresence: "Japan担当営業を配置、法人・officeは公式未確認", japanSince: "2026年にfirst Japan AE求人を確認",
  solutions: [{ name: "Reverse ETL", valueProp: "warehouseのmodelをSaaS・広告・CRMへ同期。", url: "https://hightouch.com/platform/reverse-etl", competitors: "Census、custom pipeline、native connector。", differentiation: "幅広いdestinationとwarehouse-centric governance。" }, { name: "Customer Studio / CDP", valueProp: "business userがaudienceとjourneyを作成。", url: "https://hightouch.com/platform/customer-studio", competitors: "Segment、Adobe RT-CDP、Salesforce Data Cloud。", differentiation: "dataを別storageへ複製せず既存modelを利用。" }, { name: "AI Decisioning", valueProp: "個人ごとのnext-best actionを継続最適化。", url: "https://hightouch.com/platform/ai-decisioning", competitors: "Braze、Dynamic Yield、in-house ML。", differentiation: "warehouse dataとexperimentをactivationへ直結。" }],
  fitTags: ["Founding AE", "Enterprise", "Composable CDP", "Data", "Marketing", "AI", "Partner", "Japan build"], comparisons: [{ arena: "Composable CDP", companies: ["Hightouch", "Census", "RudderStack"], why: "activation、identity、business UX" }, { arena: "Traditional CDP", companies: ["Hightouch", "Segment", "Adobe"], why: "data copy、time-to-value、suite" }, { arena: "Data cloud", companies: ["Hightouch", "Snowflake", "Salesforce"], why: "storageとactivationの境界" }],
});

const schrodingerIntelligence: CompanyPublicIntelligence = buildIntelligence({
  slug: "schrodinger", name: "Schrödinger", jobUrl: "https://job-boards.greenhouse.io/schrdinger/jobs/6663458003", officialUrl: "https://www.schrodinger.com/schrodinger-kk/", customersUrl: "https://www.schrodinger.com/life-science-learn/", externalUrl: "https://www.meti.go.jp/policy/mono_info_service/healthcare/index.html", financeUrl: "https://investor.schrodinger.com/financial-information/annual-reports", publicInfo: { ticker: "SDGR", exchange: "NASDAQ", listedSince: "2020年" },
  salesSnapshot: "Schrödingerは、製薬・biotech・化学・材料企業のR&D責任者とcomputational scientistに、物理ベースsimulationとAIを統合した創薬・材料設計platformを提供する会社。顧客が抱えるのは「実験候補が多くcostと期間が膨らむ」「AI予測だけでは分子の挙動と再現性を説明しにくい」「研究dataとdesign判断がteam間で分断する」という3つの課題。研究toolから入り、portfolio prioritization、共同研究、enterprise informatics、材料開発へ広げられる点が営業としての面白さ。",
  growthSummary: "800人超のグローバル組織を持つNASDAQ企業で、software事業と自社創薬pipelineを併営。日本法人には2025年時点で21人を置き、Senior Account Managerを含むlife science・materials向け営業を採用。",
  milestones: [{ year: "1990", label: "創業", detail: "physics-based molecular modeling softwareを開発。", source: "company" }, { year: "2002", label: "日本法人", detail: "Schrödinger K.K.を東京に設立。", source: "company" }, { year: "2020", label: "NASDAQ上場", detail: "ticker SDGRで公開企業化。", source: "finance" }, { year: "2025", label: "日本21人", detail: "Corporate Sustainability ReportでJapan人員を開示。", source: "finance" }, { year: "2026", label: "Japan営業採用", detail: "Senior Account Manager等を公式掲載。", source: "job" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "製薬・biotech・材料企業は、候補を闇雲に合成する前にin silicoで優先順位を絞り、研究者間でdesign rationaleを共有する。目的は一つのpredictionではなく、実験cycle全体の速度と成功確率を上げること。" }, { title: "製品の成り立ちから見る課題", body: "量子化学・分子力学を基盤に構造予測、FEP、informatics、machine learningを統合。data相関だけでは外挿と説明に弱く、physicsと実験を閉loopにする設計。" }, { title: "外部環境の要求から見る課題", body: "創薬cost上昇、patent cliff、希少疾患、sustainable materialsでR&Dは速さと再現性を同時に求められる。AI期待が高いほど、実験検証、data品質、scientific explainabilityが投資条件になる。" }],
  narrative: [{ label: "背景", body: "研究者は巨大なchemical spaceから有望候補を選ぶが、合成・試験には長い時間と費用がかかる。" }, { label: "課題", body: "teamごとのtool・data・判断が分散し、候補選定の根拠を再利用できず、fail-fastが遅れる。" }, { label: "解決策", body: "一つのprogramでstructure、FEP、design、experiment dataを接続し、合成数、cycle time、prediction精度、collaborationを測る。" }, { label: "選定の理由", body: "BIOVIA、OpenEye、Cresset、AI創薬企業、内製modelとの比較で、physics accuracy、workflow breadth、scientific support、enterprise collaborationが揃う場合に選ばれる。" }],
  openingHook: "一つの有望候補へ到達するまで、何個の分子を合成し、何cycleの実験をやり直していますか。", valueHypothesis: "対象programで合成候補数、design cycle、predictionと実験の相関、researcher利用率、意思決定時間を測る。", objection: "自社AI modelと既存chemistry softwareで十分。", reframe: "model単体のbenchmarkではなく、physics、experiment、chemist workflow、collaborationを閉loopにして候補数とcycleを減らせるかで比較する。",
  facts: [{ label: "創業", value: "1990年", detail: "computational chemistry企業。", source: "company" }, { label: "社員", value: "800人超", detail: "公式careers掲載。", source: "company" }, { label: "上場", value: "NASDAQ: SDGR", detail: "2020年上場。", source: "finance" }, { label: "日本法人", value: "Schrödinger K.K.", detail: "東京・丸の内。", source: "company" }, { label: "日本社員", value: "21人", detail: "2025 Sustainability Report。", source: "finance" }, { label: "日本求人", value: "Senior Account Manager", detail: "公式求人を確認。", source: "job" }],
  customers: [{ company: "Takeda", products: "Schrödinger Platform", outcome: "drug discovery collaboration・software活用を公開情報で紹介。", implication: "国内製薬のR&D executiveへstrategic account提案。" }, { company: "Bristol Myers Squibb", products: "FEP+ / Platform", outcome: "computational designとdrug discoveryのcollaborationを公表。", implication: "softwareと共同研究の複合motion。" }, { company: "Panasonic", products: "Materials Science", outcome: "材料informatics・simulationの活用領域を公開情報で紹介。", implication: "life science以外のJapan manufacturingへ展開。" }],
  externalSignals: [{ label: "創薬競争力", value: "R&D生産性", detail: "経済産業省はhealthcare・創薬産業の競争力とinnovationを政策課題に置く。", caveat: "Schrödingerの採用義務や個別成果を示さない。" }, { label: "AI・simulation", value: "検証可能性", detail: "R&DでAI利用が増えるほど実験検証とdomain expertの判断を組み込む必要がある。", caveat: "成功確率はtarget、data、研究designで大きく異なる。" }],
  role: "製薬・biotechのJapan accountで研究課題を理解し、scientific specialistとsoftware・serviceの採用、renewal、expansionを担うSenior Account Manager。", organization: "東京の21人規模組織とglobal scientific・product teamを結ぶ専門性の高いaccount model。", careerValue: "一般SaaSとは異なるscientific value selling、長期R&D account、softwareとserviceの複合提案を経験できる。", globalHeadcount: "800人超", japanPresence: "Schrödinger K.K. / 東京・丸の内", japanSince: "2002年に日本法人設立",
  solutions: [{ name: "FEP+", valueProp: "候補分子のbinding affinityをphysics-based simulationで予測。", url: "https://www.schrodinger.com/platform/products/fep/", competitors: "Cresset、OpenEye、AI model、実験screening。", differentiation: "physics accuracyとdrug discovery workflowの統合。" }, { name: "LiveDesign", valueProp: "design、property、experiment dataを研究teamで共有。", url: "https://www.schrodinger.com/platform/products/livedesign/", competitors: "BIOVIA、Dotmatics、internal informatics。", differentiation: "modeling結果とchemist decisionを同じcollaboration layerへ置く。" }, { name: "Materials Science", valueProp: "battery、polymer、semiconductor等の材料特性をsimulation。", url: "https://www.schrodinger.com/materials-science/", competitors: "BIOVIA Materials Studio、quantum chemistry、lab-only R&D。", differentiation: "atomistic physicsとenterprise workflowを統合。" }],
  fitTags: ["Life Science", "Materials", "Scientific Sales", "Enterprise", "R&D", "Simulation", "AI", "Account Management"], comparisons: [{ arena: "Drug discovery", companies: ["Schrödinger", "BIOVIA", "OpenEye"], why: "physics、workflow、support" }, { arena: "AI創薬", companies: ["Schrödinger", "insilico AI", "in-house"], why: "explainabilityとexperiment loop" }, { arena: "Materials", companies: ["Schrödinger", "BIOVIA", "lab workflow"], why: "simulationと研究data" }],
});

export const waveFourIntelligenceBySlug: Record<string, CompanyPublicIntelligence> = {
  datadog: datadogIntelligence,
  scandit: scanditIntelligence,
  docusign: docusignIntelligence,
  hightouch: hightouchIntelligence,
  schrodinger: schrodingerIntelligence,
};
