import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildPreEntryIntelligence } from "@/lib/company-public-intelligence-pre-entry-wave-two";
import { buildIntelligence } from "@/lib/company-public-intelligence-wave-two";

const checkedAt = "2026-08-17";

const serviceNowIntelligence = buildIntelligence({
  checkedAt,
  slug: "servicenow",
  name: "ServiceNow",
  jobUrl: "https://careers.servicenow.com/jobs/?search=&country=Japan",
  officialUrl: "https://www.servicenow.com/jp/",
  customersUrl: "https://www.servicenow.com/jp/customers.html",
  externalUrl: "https://www.ipa.go.jp/digital/chousa/dx-trend/dx-trend-2026.html",
  financeUrl: "https://investor.servicenow.com/news/news-details/2026/ServiceNow-Reports-Second-Quarter-2026-Financial-Results/default.aspx",
  publicInfo: { ticker: "NOW", exchange: "NYSE", listedSince: "2012年" },
  salesSnapshot: "ServiceNowは、IT部門だけでなく人事、顧客対応、営業、製造などに散らばる申請・判断・実行を、共通dataとAI agentを使うworkflowへ変える会社。日本の現行対象26求人は、new business、industry specialist、partner、presales、architecture、customer successまで顧客lifecycleを広く覆う。単一moduleを売るより、経営課題をworkflowへ分解し、複数年のplatform adoptionへつなぐ仕事が中心。",
  growthSummary: "Q2 2026は売上39.87億ドル（約6,282億円）、GAAP営業利益1.62億ドル（約255億円）、FCF 6.34億ドル（約999億円）。ServiceNow AIのACVは10億ドルを超えた。1ドル=157.56円で概算。日本単体の売上・ARR・達成率は非公開。",
  milestones: [
    { year: "2004", label: "創業", detail: "cloud-nativeなIT service workflowから開始。", source: "company" },
    { year: "2012", label: "NYSE上場", detail: "ticker NOWで上場。", source: "finance" },
    { year: "2013", label: "日本法人", detail: "ServiceNow Japanを設立し、東京・大阪で事業展開。", source: "company" },
    { year: "2023", label: "日本体制強化", detail: "鈴木正敏氏が日本法人社長へ就任。", source: "company" },
    { year: "2026.08", label: "日本で26対象求人", detail: "Sales、Presales、CS、Architecture、Partner、GTMを公式確認。", source: "job" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "資生堂はIT serviceの60%集約と人事業務月40時間削減を公表。顧客はticket toolではなく、global標準、従業員体験、運用工数、意思決定速度を同時に変える目的で導入している。" },
    { title: "製品の成り立ちから見る課題", body: "IT service managementから始まり、ITOM、HR、CRM、Security、Creator、industry workflowsへ拡張した。現在は共通data modelとAI agentで、部門別systemをまたぐ仕事そのものを動かすplatformを目指す。" },
    { title: "外部環境の要求から見る課題", body: "日本企業ではlegacy、DX人材不足、SaaS乱立、生成AIの業務組込みとgovernanceが同時課題。AIを追加するだけでなく、権限、data、承認、human handoff、成果指標を既存業務へ埋め込む必要がある。" },
  ],
  narrative: [
    { label: "背景", body: "大企業の仕事は部門別system、email、spreadsheet、portalに分散し、AI agentの導入対象も急増している。" },
    { label: "課題", body: "申請から判断・実行までのcontextがsystem間で切れ、待ち時間、二重入力、owner不在、audit不足が残る。個別AI導入はこの分断を増やし得る。" },
    { label: "解決策", body: "優先workflowを選び、ServiceNowの共通data、automation、AI agent、human approvalへ移し、cycle time、self-service、case deflection、agent productivity、adoptionを測る。" },
    { label: "選定の理由", body: "Salesforce、Microsoft、SAP、Oracle、Atlassian、個別ITSM・BPM、内製との比較で、部門横断workflow、enterprise governance、既存導入基盤、partner deliveryを一つのoperating modelにできる場合に選ぶ。" },
  ],
  openingHook: "重要な申請や顧客対応で、入力から承認・実行まで何system、何handoff、何日かかり、どこでownerが見えなくなりますか。",
  valueHypothesis: "cycle time、handoff、manual hours、self-service、deflection、MTTR、case backlog、employee・customer satisfaction、AI completion・escalationをbaseline比較する。",
  objection: "既に各部門にSaaSとMicrosoft・Salesforce・SAPがあり、ServiceNowを広げるとplatform costが増える。",
  reframe: "license単価ではなく、system間handoff、integration保守、manual work、audit、AI governance、重複toolを含むworkflow単位の3年TCOと成果で比較する。",
  facts: [
    { label: "Q2 2026売上", value: "39.87億ドル", secondaryValue: "約6,282億円", detail: "前年比24%増。1ドル=157.56円で概算。", source: "finance" },
    { label: "Q2 GAAP営業利益", value: "1.62億ドル", secondaryValue: "約255億円", detail: "GAAP営業利益率4%。", source: "finance" },
    { label: "Q2 FCF", value: "6.34億ドル", secondaryValue: "約999億円", detail: "non-GAAP FCF margin 16%。", source: "finance" },
    { label: "AI ACV", value: "10億ドル超", detail: "Q2 2026時点の会社発表。認識売上ではない。", source: "finance" },
    { label: "RPO", value: "290億ドル", detail: "契約済み将来収益であり当期売上ではない。", source: "finance" },
    { label: "日本の対象求人", value: "26件", detail: "公式画面27件からTechnical Support 1件を除外。", source: "job" },
  ],
  customers: [
    { company: "資生堂", products: "ServiceNow platform", outcome: "IT servicesの60%を集約し、人事workflowで月40時間を削減。", implication: "global企業でITとemployee workflowを同じplatformへ広げる国内proof。" },
    { company: "国内大企業グループ", products: "ServiceNow platform", outcome: "115社・17万人の意思決定processを統一した事例を日本顧客hubで紹介。", implication: "group-wide governanceとworkflow標準化のscaleを示す。" },
    { company: "国内企業", products: "ServiceNow workflow", outcome: "契約処理で年144時間かかった作業をゼロにした事例を日本顧客hubで紹介。", implication: "manual workを定量化してbusiness caseを作る入口。" },
  ],
  externalSignals: [
    { label: "DX動向2026", value: "成果測定が課題", detail: "IPAはDXの実施拡大に対し、成果指標、legacy、人材、AIの業務組込みを主要論点として整理。", caveat: "公的調査はServiceNowの採用や成果を保証しない。" },
    { label: "AI governance", value: "workflowへの組込み", detail: "生成AI・agentの利用では権限、data、human oversight、記録を既存業務と一緒に設計する必要がある。", caveat: "製品導入だけで適法性・安全性が確保されるわけではない。" },
  ],
  role: "日本ではEnterprise・Commercial・Mid-Market AE、industry・CRM specialist、BDR、Partner、Presales、Architecture、Customer Success、Deal Operationsを同時採用。役割ごとにpipeline、technical win、adoption、ecosystem、commercial governanceの責任が異なる。",
  organization: "ServiceNow Japanは東京・大阪を起点に、segment、industry、product specialist、Solution Consulting、Customer Success、Partnerをmatrixで組み合わせる成熟GTM。",
  careerValue: "Enterprise Workflow、AI platform、C-level transformation、industry selling、partner ecosystem、customer value realizationを、職種ごとの専門性で積める。",
  globalHeadcount: "26,000人超",
  japanPresence: "ServiceNow Japan / 東京・大阪、日本法人社長 鈴木正敏氏",
  japanSince: "2013年に日本法人を設立",
  solutions: [
    { name: "ServiceNow AI Platform", valueProp: "部門をまたぐdata、workflow、AI agent、human approvalを共通基盤で動かす。", url: "https://www.servicenow.com/jp/products/now-platform.html", competitors: "Microsoft、Salesforce、SAP、Oracle、内製workflow。", differentiation: "enterprise workflowと共通data model、AI governanceの連続性。" },
    { name: "IT Workflows", valueProp: "IT service、operations、asset、security responseをつなぎ、運用を可視化・自動化する。", url: "https://www.servicenow.com/jp/solutions/it-workflows.html", competitors: "Atlassian、BMC、Ivanti、Microsoft、個別ITSM。", differentiation: "ITSMからoperations・security・assetまでのplatform breadth。" },
    { name: "CRM / Customer Service", valueProp: "顧客接点からcase、field service、order・fulfillmentまでをworkflowで接続する。", url: "https://www.servicenow.com/jp/products/customer-service-management.html", competitors: "Salesforce、Dynamics 365、Zendesk、Genesys。", differentiation: "front officeとback-office fulfillmentの一体化。" },
  ],
  fitTags: ["アンカー企業", "Enterprise Workflow", "AI Platform", "ITSM", "CRM", "Customer Success", "Partner", "Japan"],
  comparisons: [
    { arena: "Enterprise Workflow", companies: ["ServiceNow", "Microsoft", "Salesforce"], why: "workflow breadth、data、AI governance、ecosystem" },
    { arena: "IT Operations", companies: ["ServiceNow", "Atlassian", "BMC", "Ivanti"], why: "ITSM、ITOM、asset、automation、TCO" },
    { arena: "CRM・Customer Service", companies: ["ServiceNow", "Salesforce", "Dynamics 365", "Zendesk"], why: "engagementからfulfillment、AI、integration" },
  ],
});

serviceNowIntelligence.leadership = {
  name: "鈴木 正敏",
  role: "ServiceNow Japan 代表取締役社長",
  read: "2023年就任。日本を独立reporting regionとして成長を担う。求人は成熟したsegment・industry・lifecycle組織を示す一方、日本のquota達成率とteam別headcountは非公開。",
  sourceId: "servicenow-company",
};
const toolsForHumanityIntelligence = buildIntelligence({
  checkedAt,
  jobConfirmed: false,
  slug: "tools-for-humanity",
  name: "Tools for Humanity (World)",
  jobUrl: "https://jobs.ashbyhq.com/Tools%20for%20Humanity",
  officialUrl: "https://www.toolsforhumanity.com/",
  customersUrl: "https://world.org/blog/announcements/tinder-verification-proof-of-human-dating",
  externalUrl: "https://www.digital.go.jp/policies/mynumber",
  financeUrl: "https://world.org/blog/announcements/world-raises-135m",
  salesSnapshot: "Tools for Humanityは、AI・botが増えるinternetで『相手が一人の人間であること』を、氏名などを共有せず証明するWorld IDと、wallet・Mini Appsを含むWorld Appを作る会社。日本ではTinderの人間・年齢認証とマイナンバーカードcredentialを確認できるが、現行公式求人は米国・ドイツの24件のみ。日本事業の実運用はある一方、採用再開時期とlocal組織は読めない。",
  growthSummary: "Tools for Humanity公式は500人超、World Appは3,900万人超、World IDは2026年4月時点でOrb認証約1,800万人を公表。2025年の1.35億ドルtoken saleはnetwork拡大資金で、売上・利益・企業評価額ではない。認識売上、利益、FCF、日本売上は非公開。",
  milestones: [
    { year: "2019", label: "創業", detail: "Alex Blania氏とSam Altman氏が創業。", source: "company" },
    { year: "2023", label: "Worldcoin launch", detail: "World ID、World App、WLDを含むnetworkを公開。", source: "company" },
    { year: "2025", label: "network拡大資金", detail: "a16zとBain Capital Cryptoから1.35億ドルを調達。", source: "finance" },
    { year: "2025", label: "Tinder Japan pilot", detail: "World IDによるproof of human・年齢認証を日本で開始。", source: "company" },
    { year: "2026.08", label: "Japan求人0", detail: "公式ATS 24件はSan Francisco・Munichのみ。", source: "job" },
  ],
  issueLenses: [
    { title: "既存利用の目的から見る課題", body: "Tinderはbot・なりすましを減らし、18歳以上の年齢をprivacy-preservingに確認する目的でJapan pilotを実施。Worldは平均約2分、既認証者は秒単位と説明する。" },
    { title: "製品の成り立ちから見る課題", body: "一人一つのproof of humanをOrbや公的credentialで作り、必要な事実だけをzero-knowledge proofで共有する。World App、Mini Apps、World Chainと組み合わせ、人間向けのdigital networkを狙う。" },
    { title: "外部環境の要求から見る課題", body: "生成AI、bot、deepfake、複数accountが増えるほど、年齢・人間性・一意性を確認しつつ個人dataを過剰収集しない設計がplatform、広告、gaming、ticketingの課題になる。" },
  ],
  narrative: [
    { label: "背景", body: "online serviceではAI agentと人間の区別、複数account、不正、年齢確認が難しくなっている。" },
    { label: "課題", body: "従来のID提出やphone・email認証は個人dataを多く渡すか、一人一accountを十分に証明できない。" },
    { label: "解決策", body: "限定use caseでWorld IDを接続し、verification completion、fraud・bot、drop-off、verification time、privacy reviewをbaseline比較する。" },
    { label: "選定の理由", body: "公的ID eKYC、phone verification、passkey、CAPTCHA、platform内verificationとの比較で、一意な人間性、選択的開示、user reach、integration、regulatory acceptanceが合う場合に採用する。" },
  ],
  openingHook: "利用者の氏名やID画像を保持せずに、『一人の人間』『18歳以上』『一人一account』だけを証明できますか。",
  valueHypothesis: "verification completion・時間、bot・fraud、duplicate account、user drop-off、manual review、privacy・compliance工数を測る。",
  objection: "公的eKYC、phone認証、CAPTCHA、passkeyで足り、Orbやtokenを伴う仕組みは過剰。",
  reframe: "全本人確認の置換ではなく、どのuse caseでunique human proofと選択的開示が既存手段よりfriction・fraud・data liabilityを下げるかを限定検証する。",
  facts: [
    { label: "World App users", value: "3,900万人超", detail: "Tools for Humanity公式の動的掲載値。", source: "company" },
    { label: "Orb認証", value: "約1,800万人", detail: "2026年4月のWorld公式発表。", source: "company" },
    { label: "Mini Apps", value: "400超", detail: "Tools for Humanity公式。", source: "company" },
    { label: "資金", value: "1.35億ドル", secondaryValue: "約212.7億円", detail: "2025年token sale。売上ではない。", source: "finance" },
    { label: "日本use case", value: "Tinder", detail: "proof of humanと18歳以上の年齢確認。", source: "customers" },
    { label: "現行Japan求人", value: "0件", detail: "公式Ashby全24件を照合。", source: "job" },
  ],
  customers: [
    { company: "Tinder Japan", products: "World ID", outcome: "人間バッジと年齢認証を提供。既存認証は約2分、認証済みuserは秒単位とTinder幹部が説明。", implication: "日本発のuse caseが米国拡大のproofになった。" },
    { company: "World App users", products: "World ID Credentials", outcome: "日本のNFC対応マイナンバーカードで年齢等のcredentialを追加できる。", implication: "Orb以外のlocal credentialとの接続を示す。" },
    { company: "Mini App ecosystem", products: "World App / World ID", outcome: "400超のMini Appsを公式掲載。", implication: "identityだけでなくdistribution・transaction layerへ広げる構想。" },
  ],
  externalSignals: [
    { label: "AI・bot増加", value: "人間性の証明", detail: "AI生成account・contentが増え、platformはreal human、年齢、一意性を確認する必要がある。", caveat: "需要の存在はWorld IDの法的適合・採用優位を証明しない。" },
    { label: "マイナンバー", value: "公的credential", detail: "日本では公的個人認証と民間本人確認の制度・運用が整備されている。", caveat: "World IDの各利用が公的認証と同じ法的効果を持つわけではない。" },
  ],
  role: "日本ではWorld IDの実利用を確認できるが、現行Japan求人は0件。旧検索結果を採用中とせず、事業開発・operations・policy・engineeringの採用再開を継続観測する。",
  organization: "Tools for HumanityがWorld AppやOrb等を開発し、World Foundationがprotocol stewardshipを担う。日本の法人、country leader、headcount、reporting lineは公式情報で確定できない。",
  careerValue: "Digital Identity、zero-knowledge proof、consumer fintech、hardware operations、AI trustを横断する希少性がある一方、日本で応募可能な現行roleはない。",
  globalHeadcount: "500人超",
  japanPresence: "World IDを日本で提供。Tinder Japanとマイナンバーカードcredentialを確認",
  japanSince: "2025年までにTinder Japan pilotを開始",
  solutions: [
    { name: "World ID", valueProp: "氏名等を共有せず、一人の人間・年齢・credentialを証明する。", url: "https://world.org/ja-jp/world-id", competitors: "公的eKYC、phone verification、passkey、CAPTCHA。", differentiation: "proof of humanとzero-knowledgeによる選択的開示。" },
    { name: "World App", valueProp: "World ID、wallet、Mini Apps、transactionを一つのconsumer appで提供。", url: "https://www.toolsforhumanity.com/world-app", competitors: "digital wallets、super apps、crypto wallets。", differentiation: "verified-human networkとMini App distribution。" },
    { name: "Orb", valueProp: "一人一つのWorld IDを作るための専用verification hardware。", url: "https://www.toolsforhumanity.com/the-orb", competitors: "公的ID、生体認証vendor、device-based identity。", differentiation: "global uniqueness verificationを目的に設計。" },
  ],
  fitTags: ["Proof of Human", "Digital Identity", "Privacy", "AI Trust", "World ID", "Japan"],
  comparisons: [
    { arena: "Identity Verification", companies: ["World ID", "公的eKYC", "phone verification"], why: "uniqueness、privacy、acceptance、friction" },
    { arena: "Bot・Abuse対策", companies: ["World ID", "CAPTCHA", "device・behavioral risk"], why: "human proof、coverage、false positive、UX" },
    { arena: "Consumer Identity Network", companies: ["World", "platform account", "wallet ecosystem"], why: "reach、developer adoption、governance、regulation" },
  ],
});

toolsForHumanityIntelligence.leadership = {
  name: "Alex Blania / Sam Altman",
  role: "Co-founder & CEO / Co-founder & Chairman",
  read: "Tools for Humanityは2019年創業。日本のcountry leaderと現地組織責任者は公式に確認できない。",
  sourceId: "tools-for-humanity-company",
};

const lovableIntelligence = buildPreEntryIntelligence({
  checkedAt,
  slug: "lovable",
  name: "Lovable",
  homepage: "https://lovable.dev/",
  growthUrl: "https://lovable.dev/blog/series-c",
  careersUrl: "https://jobs.ashbyhq.com/lovable",
  customersUrl: "https://lovable.dev/blog/series-c",
  trustUrl: "https://lovable.dev/security",
  apacUrl: "https://jobs.ashbyhq.com/lovable",
  externalUrl: "https://www.ipa.go.jp/digital/chousa/dx-trend/dx-trend-2026.html",
  linkedinUrl: "https://www.linkedin.com/company/lovable-dev/",
  salesSnapshot: "事業部門・Product・ITが抱えるのは「小規模な業務アプリも開発部門の順番待ちになる」「外注や既製SaaSでは要件変更に時間と費用がかかる」「生成AIで試作してもsecurity reviewと本番運用を越えられない」という3つの課題。自然言語からUIだけでなくbackend、database、auth、payments、deployment、security scanningまで扱うfull-stack softwareを作る。日本では日本語siteはあるが、法人・office・Japan求人は未確認。進出前に見るべきはvibe codingの話題性ではなく、国内のbusiness builderがproduction・security review・運用まで到達するか。",
  growthSummary: "2026年8月12日に4億ドルのSeries Cを133億ドル評価で発表。launchから約21カ月で6,000万超のprojects、月9億超のapp visits、Fortune 500の約3分の2に利用者がいると公表。売上、ARR、profit、FCF、日本売上は非公開。",
  verdict: "進出可能性は中。利用入口はあるが、Japan Enterprise deliveryの証拠が不足",
  entryNarrative: "日本語siteからself-serve利用は可能で、AI・内製化・DX人材不足という需要も強い。一方、公式ATS 74件はStockholm、London、Boston、New York、San Francisco、Lund、Remoteに限られ、Japan・APAC sales、法人、office、責任者、国内named caseは確認できない。まずglobal・self-serveから日本の有償利用を測り、security・support・partnerの成立条件が揃ってからlocal teamへ進む可能性が高い。",
  headcount: "2026年に約450人を目標",
  headcountDetail: "Series C発表で年内約450人へ拡大する計画を記載。現在人数の厳密値ではない。",
  apacPresence: "公式求人の拠点は欧米中心で、Japan・Singapore・APAC hubを確認できない。Series CにはWorld Innovation Lab等のAsia投資家が参加。",
  productLanguage: "日本語siteと日本語入力は利用できるが、日本語support、国内data residency、契約主体、local implementationの同等性は公式情報で確定できない。",
  milestones: [
    { year: "2024.11", label: "launch", detail: "Lovableを一般公開。", source: "company" },
    { year: "2025.11", label: "成長", detail: "1年で2,500万超のprojectsと2億ドルARRを公表。", source: "growth" },
    { year: "2025.12", label: "Series B", detail: "3.3億ドルを66億ドル評価で調達。", source: "growth" },
    { year: "2026.08", label: "Series C", detail: "4億ドルを133億ドル評価で調達。", source: "growth" },
    { year: "2026.08", label: "Japan求人0", detail: "公式ATS 74件にJapan・APAC勤務地なし。", source: "apac" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "Nursaはcore platformを12倍速く再構築し、10 SaaSを廃止中と会社事例で説明。Checkrはoperations teamのQA処理を10倍へ拡大。目的はprototypeだけでなく、現場固有のinternal softwareとSaaS置換。" },
    { title: "製品の成り立ちから見る課題", body: "non-developerがideaをappへ変えるchat interfaceから始まり、Cloud、database、auth、payments、connectors、security、governanceへ拡張。buildするだけでなくbusinessをrunするplatformを志向する。" },
    { title: "外部環境の要求から見る課題", body: "日本企業はDX人材不足とbusiness backlogを抱える一方、生成codeのsecurity、個人data、ownership、maintenance、shadow ITを統制する必要がある。speedとproduction responsibilityを同時に満たすことが投資条件。" },
  ],
  narrative: [
    { label: "背景", body: "現場には小規模app・automationの需要が多いが、central engineeringとSIのpriority待ちになる。" },
    { label: "課題", body: "従来no-codeは柔軟性、AI code toolはproduction運用とgovernance、SaaS購入は業務fitとcostで詰まりやすい。" },
    { label: "解決策", body: "低risk workflowでbusiness builderがappを作り、ITがidentity、data、security、publish、ownershipをreviewするpilotを行う。" },
    { label: "選定の理由", body: "Replit、Microsoft Power Apps、Mendix、Cursor、v0、Bolt、Base44、SI・内製との比較で、nontechnical accessibilityとfull-stack production、governance、handoffが両立する場合に選ぶ。" },
  ],
  openingHook: "現場が必要とする小規模appのうち、中央ITやSIの優先順位待ちで3カ月以上止まっているものは何件ありますか。",
  valueHypothesis: "idea-to-first-use、build hours、backlog、SaaS削減、active users、workflow completion、security findings、maintenance hoursを測る。",
  objection: "Power Apps、Replit、既存AI coding、SIで十分。business userにproduction appを作らせるのは危険。",
  reframe: "作れる速さだけでなく、backend、auth、payments、deployment、security、publishing control、GitHub handoff、運用ownerを同じpilotで比較する。",
  facts: [
    { label: "Series C", value: "4億ドル", detail: "2026年8月12日発表。資金調達であり売上ではない。", source: "growth" },
    { label: "評価額", value: "133億ドル", detail: "Series C時点。現在の売上・利益ではない。", source: "growth" },
    { label: "projects", value: "6,000万超", detail: "2024年11月launch以降。", source: "company" },
    { label: "app visits", value: "月9億超", detail: "Lovable-built appsへの訪問。paid customer数ではない。", source: "company" },
    { label: "Fortune 500", value: "約3分の2", detail: "利用者がいる企業の比率で、enterprise契約率ではない。", source: "growth" },
    { label: "Japan求人", value: "0件", detail: "公式ATS 74件を照合。", source: "careers" },
  ],
  customers: [
    { company: "Nursa", products: "Lovable", outcome: "core platformを12倍速く再構築し、200人超へ展開、10 SaaSを廃止中と会社発表。", implication: "prototypeからenterprise internal platformへ広げるglobal proof。" },
    { company: "Checkr", products: "Lovable", outcome: "operations teamのQA workflowで10倍のreportsを処理。", implication: "non-engineering teamがbusiness processを直接改善するproof。" },
    { company: "Adidas・NVIDIA・Deutsche Telekom", products: "Lovable", outcome: "critical workflow、既存tool置換、新規productで利用と会社発表。", implication: "大企業内利用はあるが、日本法人のcaseではない。" },
  ],
  externalSignals: [
    { label: "DX人材不足", value: "継続", detail: "IPAは日本企業のDX・AI人材不足、legacy、内製化、成果測定を課題として整理。", caveat: "人材不足はLovableの導入効果を保証しない。" },
    { label: "AI governance", value: "production責任", detail: "AI生成softwareでもsecurity、privacy、human review、説明責任、運用ownerが必要。", caveat: "platform利用だけで品質・適法性は保証されない。" },
  ],
  entryAssessment: {
    verdict: "日本語self-serveは可能。local Enterprise GTMは需要証拠とdelivery条件待ち",
    factSignals: [
      { title: "高いglobal growth", body: "Series C 4億ドル、133億ドル評価、6,000万超projects、月9億超visitsを公式発表。", sourceIds: ["growth"] },
      { title: "日本語の利用入口", body: "日本語siteと日本語promptでself-serve利用でき、正式進出前でもproduct usageを作れる。", sourceIds: ["company"] },
      { title: "Enterprise use case", body: "Nursa、Checkr、Adidas等でinternal software、SaaS置換、business workflowの利用を公開。", sourceIds: ["customers"] },
      { title: "日本の構造需要", body: "DX人材不足と現場backlogは、business builderによるsoftware creationと親和する。", sourceIds: ["external"] },
    ],
    hurdles: [
      { title: "local commercial proofがない", body: "Japan paid customer、ARR、named case、partner、pipelineは未確認。self-serve利用が現地固定費を支えるか分からない。", sourceIds: ["customers", "careers"] },
      { title: "data・support・契約のlocalization", body: "日本のdata residency、日本語support、契約主体、請求、incident response、security reviewの対応範囲を確定できない。", sourceIds: ["trust", "company"] },
      { title: "production qualityとownership", body: "AI outputの正確性・完全性は保証されず、generated appのsecurity、保守、IP、退職者appのownerを顧客側で設計する必要がある。", sourceIds: ["trust", "company"] },
      { title: "強いbundle・platform競争", body: "Microsoft、Replit、Mendix、AI coding tool、SI、既存SaaSの組合せに対し、追加platformのTCOを示す必要がある。", sourceIds: ["company"] },
    ],
    readinessConditions: [
      { title: "日本の有償利用とreference", body: "self-serveからJapan paid usage、production apps、SaaS置換、renewalを確認できること。" },
      { title: "local deliveryの成立", body: "日本語support、security review、partner、contract・billing、data handlingをAPACまたは日本で回せること。" },
      { title: "Enterprise repeatability", body: "single appのbuild速度ではなく、portfolio governance、ownership、maintenance、3年TCOを日本顧客で証明できること。" },
    ],
    watchSignals: ["Japan・APACを勤務地または担当市場とする公式求人", "日本企業のnamed production caseと定量成果", "日本語support・国内partner・data residencyの発表", "Japan entity・office・country leaderの公式発表"],
  },
  sourceIds: ["growth", "company", "careers", "trust", "external"],
  salesMotion: "現時点でJapan求人はない。進出する場合はself-serve usageを起点に、Enterprise AE、Solutions・Forward Deployed、Customer Success、Security、partnerを段階的に置く可能性がある。",
  careerValue: "AI software creation、PLG-to-enterprise、business builder enablement、security governanceを横断する0→1経験。ただし日本で応募可能な現行roleはない。",
  leader: { name: "Anton Osika / Fabian Hedin", role: "Co-founders", read: "Stockholmを中心に欧米拠点を拡大。Japan・APAC責任者は未確認。" },
  solutions: [
    { name: "Lovable", valueProp: "自然言語からUI、backend、database、authを含むfull-stack appを作る。", url: "https://lovable.dev/", competitors: "Replit、Bolt、Base44、v0、Cursor。", differentiation: "nontechnical builder向けのend-to-end creationとpublish。" },
    { name: "Lovable Cloud", valueProp: "database、auth、storage、serverless、deploymentをplatform内で提供。", url: "https://lovable.dev/support", competitors: "Supabase、Firebase、Vercel、cloud-native内製。", differentiation: "build flowとbackend・hostingを一体化。" },
    { name: "Enterprise", valueProp: "SSO、workspace governance、publishing controls、security visibilityを組織へ提供。", url: "https://lovable.dev/enterprise-landing", competitors: "Power Apps、Mendix、Replit Enterprise、SI。", differentiation: "business-led creationとcentral governanceを同じworkspaceで扱う。" },
  ],
  fitTags: ["日本未進出", "AI Coding", "Full-stack", "Enterprise", "Developer Tools", "PLG"],
  comparisons: [
    { arena: "AI App Creation", companies: ["Lovable", "Replit", "Bolt", "Base44"], why: "full-stack、deployment、UX、governance" },
    { arena: "Enterprise Low-code", companies: ["Lovable", "Power Apps", "Mendix"], why: "business user、complexity、security、TCO" },
    { arena: "Developer AI", companies: ["Lovable", "Cursor", "GitHub Copilot", "v0"], why: "target user、code ownership、production handoff" },
  ],
});

export const daily20260817IntelligenceBySlug: Record<string, CompanyPublicIntelligence> = {
  servicenow: serviceNowIntelligence,
  "tools-for-humanity": toolsForHumanityIntelligence,
  lovable: lovableIntelligence,
};
