import type { Company } from "@/lib/market-data";

const batchTwoCompanyPatches: Record<string, Partial<Company>> = {
  rippling: {
    category: "人事・給与・IT・支出統合Workforce Platform",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Japan向けEOR・採用guide（日本法人・office・現行求人は確認不能）",
    description: "HCM、Payroll、Global Workforce、IT・Identity、Spendを統合。日本向けproduct activityはあるが、現行Japan求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  tines: {
    category: "セキュリティ・ITワークフロー自動化",
    hq: "ダブリン（アイルランド）／ボストン（米国）",
    japanPresence: "日本法人・office・現行Japan求人は確認不能",
    description: "Stories、Cases、Workbench、Agentsでsecurity・IT workflowを自動化。公式Careersの現行25求人にJapanは0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  uipath: {
    category: "エージェンティックオートメーション・業務自動化",
    hq: "ニューヨーク（米国）",
    japanPresence: "UiPath株式会社・東京／大阪（2017年設立）",
    description: "AI agents、robots、humansをMaestroで編成するautomation platform。東京でSales・BDR・金融Sales Associate・Specialist SEの4求人を公式確認。",
    hiringStatus: "積極採用",
    salesRoles: 4,
    lastChecked: "2026-08-17",
  },
  vanta: {
    category: "セキュリティコンプライアンス・Trust Management",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "国内顧客caseあり（日本法人・office・現行求人は確認不能）",
    description: "compliance automation、Trust Center、TPRM、AI security・privacyを統合。Fujitsu Launchpadの国内caseはあるがJapan求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  wiz: {
    category: "クラウド・AIセキュリティ・CNAPP",
    hq: "ニューヨーク（米国、Google傘下）",
    japanPresence: "Wiz Cloud Japan・東京office",
    description: "Wiz Code、Cloud、Defendでcode-to-cloud-to-runtime riskを統合。現行Japan 9求人のうち営業・partner・SE・TAM・delivery 8件を掲載。",
    hiringStatus: "積極採用",
    salesRoles: 8,
    lastChecked: "2026-08-17",
  },
  writer: {
    category: "企業向け生成AI・Agent Platform",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Singapore APJ hub（日本法人・office・現行求人は確認不能）",
    description: "WRITER Agent、Skills、Playbooks、Knowledge Graph、Palmyra、governanceを統合。APJ体制はあるが現行Japan求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  mongodb: {
    category: "アプリケーションデータ基盤・クラウドデータベース",
    hq: "ニューヨーク（米国）",
    japanPresence: "MongoDB Japan合同会社・東京（現行Japan求人は確認不能）",
    description: "document database、Atlas、Search、Vector Search、AI retrievalを提供。日本法人・国内事例はあるが、公式現行Japan求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  pinecone: {
    category: "ベクトルデータベース・AI検索／Knowledge Engine",
    hq: "ニューヨーク（米国）",
    japanPresence: "Singapore Asia region（日本法人・office・現行Japan求人は確認不能）",
    description: "vector database、Assistant、Inference・Rerank、Nexusを提供。三菱電機名は公式掲載するが、国内定量caseとJapan求人は未確認。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  postman: {
    category: "AIネイティブAPI開発・ガバナンス基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "東京・新丸の内ビル10階（現行Japan求人は0件）",
    description: "API design、test、docs、catalog、governance、AI Engineer・Agent Modeを提供。東京officeはあるが、旧SMB AEは終了。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  primer: {
    category: "決済オーケストレーション・Unified Payments Infrastructure",
    hq: "ロンドン（英国）",
    japanPresence: "Singapore APAC体制（日本法人・office・現行Japan求人は確認不能）",
    description: "checkout、routing、Fallbacks、reconciliation、treasury、AIを統合。Series C後もJapan専任求人・国内caseは未確認。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  retool: {
    category: "内製業務ソフトウェア・AIアプリ基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "GxP exclusive official partner・国内case（Retool日本法人・officeは確認不能）",
    description: "Apps、Workflows、Mobile、Agents、AppGenを提供。伊勢丹三越の国内定量caseはあるが、公式Careersは全社0求人。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  island: {
    category: "エンタープライズブラウザ・セキュアワークスペース",
    hq: "テキサス州ダラス（米国）／テルアビブ（イスラエル）",
    japanPresence: "日本法人・office・現行Japan求人を確認できず",
    description: "browserへsecurity、network、data、application、AI controlを統合。公式Careersの現行Japan・Tokyo求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  klaviyo: {
    category: "B2C CRM・マーケティング／サービス基盤",
    hq: "マサチューセッツ州ボストン（米国）",
    japanPresence: "Sydney／Singapore APAC拠点（日本法人・office・現行Japan求人は確認不能）",
    description: "customer data、Marketing、Service、AIをB2C CRMで統合。公式Careers・Greenhouseの現行Japan・Tokyo求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  lucanet: {
    category: "CFOプラットフォーム・連結／経営管理",
    hq: "ベルリン（ドイツ）",
    japanPresence: "東京local team（2026年正式進出、Country Manager Makoto Yabushita）",
    description: "連結、planning、開示、ESG、税務、treasury、AI agentをCFO Solution Platformで統合。現行Japan求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  "mistral-ai": {
    category: "基盤モデル・エンタープライズAI／ソブリンAI",
    hq: "パリ（フランス）",
    japanPresence: "Singapore APAC体制（日本法人・office・現行Japan求人は確認不能）",
    description: "frontier・open-weight models、Studio、Agents、Forge、Computeを提供。公式Ashbyの現行Japan・Tokyo求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  "monday-com": {
    category: "AIワークプラットフォーム・業務管理／CRM",
    hq: "テルアビブ（イスラエル）／ニューヨーク（米国）",
    japanPresence: "monday.com株式会社・東京／丸の内（2022年本格参入）",
    description: "work management、CRM、service、dev、AI agentを一つのWork Platformで提供。公式Careersの現行Japan・Tokyo求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  fireblocks: {
    category: "デジタル資産インフラ・決済・トークン化",
    hq: "ニューヨーク（米国）／テルアビブ（イスラエル）",
    japanPresence: "Fireblocks東京office（2024年開設）",
    description: "wallet、treasury、payments、tokenization、networkを統合。日本でbilingual Project Managerを公式募集し、週3日出社のHybrid。",
    hiringStatus: "採用中",
    salesRoles: 1,
    lastChecked: "2026-08-17",
    tags: ["Digital Assets", "FinTech", "Payments", "Tokenization", "Japan Office"],
  },
  gong: {
    category: "Revenue AI・収益インテリジェンス",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Singapore APAC office（日本法人・office・現行Japan求人は確認不能）",
    description: "customer conversation、pipeline、forecast、enablementをRevenue AI OSで統合。公式Greenhouseの現行98求人にJapan・Tokyoは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  halcyon: {
    category: "ランサムウェア耐性・サイバーレジリエンス",
    hq: "テキサス州オースティン（米国）",
    japanPresence: "Halcyon Japan株式会社・東京都渋谷区（2026年設立）",
    description: "endpoint prevention、key capture・decryption、data exfiltration protection、recovery supportを統合。公式Greenhouseの現行Japan求人は0件。",
    hiringStatus: "継続観測",
    salesRoles: 0,
    lastChecked: "2026-08-17",
    tags: ["Ransomware", "Cyber Resilience", "Japan Entity", "Partner", "Security"],
  },
  harvey: {
    category: "法務AI・プロフェッショナルサービスAI",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Singapore APAC office（日本法人・office・現行Japan求人は確認不能）",
    description: "legal research、drafting、knowledge、contract workflowをdomain AIで統合。公式Ashbyの現行391求人にJapan・Tokyoは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  intercom: {
    name: "Intercom / Fin",
    category: "AIカスタマーサービス・ヘルプデスク",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Sydney APAC office（日本法人・office・現行Japan求人は確認不能）",
    description: "2026年に会社名をFinへ変更し、Intercomをcustomer service softwareとして継続。公式Greenhouseの現行118求人にJapan・Tokyoは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  airtable: {
    category: "ノーコード業務アプリ・AIワークフロー",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Sydney APAC office（日本法人・office・現行Japan求人は確認不能）",
    description: "relational data、app building、automation、AI、governanceを統合。公式Greenhouseの現行17求人にJapan・Tokyoは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  "apollo-io": {
    category: "GTMデータ・セールスエンゲージメント・収益AI",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "日本法人・office・現行Japan求人を確認できず",
    description: "B2B data、prospecting、engagement、dialer、AIを統合。ARR 1.5億米ドルを発表するが、公式Greenhouseの現行43求人にJapan・Tokyoは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  attio: {
    category: "AIネイティブCRM・GTMオーケストレーション",
    hq: "ロンドン（英国）",
    japanPresence: "日本法人・office・現行Japan求人を確認できず",
    description: "柔軟なrelationship data、automation、AI agent、Developer Platformを統合。公式Ashbyの現行37求人にJapan・Tokyoは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  clay: {
    category: "GTMエンジニアリング・データ／AIオーケストレーション",
    hq: "ニューヨーク州ニューヨーク（米国）",
    japanPresence: "日本法人・office・現行Japan求人を確認できず",
    description: "data、AI、signals、sequencingを組み合わせるGTM orchestration platform。ARR 1億米ドル・14,000顧客を発表するが、公式Ashbyの現行73求人にJapanは0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  cribl: {
    category: "テレメトリ基盤・セキュリティ／オブザーバビリティデータ",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Remote Japan・市場立ち上げ（法人・office・責任者は確認不能）",
    description: "Stream、Edge、Search、Lakeでtelemetryを収集・整形・保存・検索。日本でPartner、Sales Director、Enterprise sellerの3求人を公式募集。",
    hiringStatus: "積極採用",
    salesRoles: 3,
    entryStatus: undefined,
    tags: ["Japan Entry", "Telemetry", "Observability", "Security", "Channel", "Enterprise"],
    lastChecked: "2026-08-17",
  },
  zscaler: {
    category: "ゼロトラスト・SSE・AIセキュリティ",
    hq: "カリフォルニア州サンノゼ（米国）",
    japanPresence: "ゼットスケーラー株式会社・東京／大阪",
    description: "Zero Trust Exchangeでinternet・private access、data、workload、AIを保護。日本でSales、SE、Value、Renewal、Transformationの29対象求人を公式確認。",
    salesRoles: 29,
    lastChecked: "2026-08-17",
  },
  "1password": {
    category: "統合アクセス管理・Identity Security",
    hq: "トロント（カナダ）",
    japanPresence: "日本語siteあり（日本法人・office・現行Japan求人は確認不能）",
    description: "password、device trust、SaaS accessをUnified Access Managementで統合。公式Ashbyの現行Japan求人は0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  sixsense: {
    category: "GTMインテリジェンス・収益AI・AIエージェント",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "日本法人・office・現行Japan求人を確認できず",
    description: "buyer signal、intent、account intelligence、AI agentをGTM workflowへ統合。公式Careerは米国・Indiaのみで、現行Japan求人は0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  "abnormal-ai": {
    category: "行動AI・メール／アイデンティティセキュリティ",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "日本Remote・市場立ち上げ（法人・office・責任者は確認不能）",
    description: "behavioral AIでemail、identity、insider、AI riskを防御。日本市場を立ち上げるEnterprise Account Executiveを公式募集。",
    salesRoles: 1,
    hiringStatus: "採用中",
    entryStatus: undefined,
    tags: ["Japan Entry", "Email Security", "AI Security", "Enterprise", "APJ"],
    lastChecked: "2026-08-17",
  },
  addepar: {
    category: "WealthTech・投資データ／AI基盤",
    hq: "カリフォルニア州マウンテンビュー（米国）",
    japanPresence: "Singapore APAC hub（日本法人・office・現行Japan求人は確認不能）",
    description: "複雑なportfolio、ownership、alternative assetのdata・analysis・reportingを統合。公式Greenhouseの現行Japan求人は0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  ubiquiti: {
    category: "ネットワーク・物理IT・統合運用",
    hq: "ニューヨーク州ニューヨーク（米国）",
    japanPresence: "日本Remote・東京優先（法人・officeは確認不能）",
    description: "UniFiでnetwork、security camera、access、VoIP、storage、ProAVを統合。日本でAccount Executiveと初のSales Solution Engineerを公式募集。",
    salesRoles: 2,
    lastChecked: "2026-08-17",
  },
  veeva: {
    category: "ライフサイエンス業界クラウド・データ基盤",
    hq: "カリフォルニア州プレザントン（米国）",
    japanPresence: "Veeva Japan・東京／大阪",
    description: "製薬・MedTechのR&D、Clinical、Safety、Quality、Regulatory、Medical、Commercialを業界cloudで統合。日本33求人のうちProduct Supportを除く32職種を掲載。",
    salesRoles: 32,
    lastChecked: "2026-08-17",
  },
  wasabi: {
    category: "クラウドストレージ・データ保護",
    hq: "マサチューセッツ州ボストン（米国）",
    japanPresence: "Wasabi Technologies Japan合同会社・東京",
    description: "S3互換のHot Cloud Storageを固定的なpricingとpartner modelで提供。日本でInside Sales Representativeを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  workato: {
    category: "業務統合・自動化・AIオーケストレーション",
    hq: "カリフォルニア州マウンテンビュー（米国）",
    japanPresence: "Workato株式会社・東京都千代田区丸の内（2021年日本法人）",
    description: "iPaaS、workflow automation、Enterprise MCP、AI agent orchestrationを統合。日本でPartner Sales Managerを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  zadara: {
    category: "ソブリンクラウド・エッジ・ストレージ",
    hq: "カリフォルニア州アーバイン（米国）",
    japanPresence: "日本語公式site・国内顧客・東京Remote（法人・officeは確認不能）",
    description: "500超のedge locationでcompute、storage、network、sovereign AI基盤をconsumption modelで提供。東京RemoteのSenior Technical Account Managerを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  schrodinger: {
    category: "計算化学・分子設計・創薬／材料R&D",
    hq: "ニューヨーク州ニューヨーク（米国）",
    japanPresence: "Schrödinger K.K.・東京（2002年設立）",
    description: "physics-based simulationとAIで創薬・材料設計を支援。東京でMaterials Account ManagerとApplications Scientistを公式募集。",
    salesRoles: 2,
    lastChecked: "2026-08-17",
  },
  "sensor-tower": {
    category: "デジタル市場・広告・競合インテリジェンス",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "東京office・東京都荒川区（2021年にJapan team開始）",
    description: "mobile、web、広告、gaming、audienceの市場dataを提供。東京でAgency Partner、Account Director、AM Director、APAC PMMの5 ATS recordを公式掲載。",
    salesRoles: 5,
    lastChecked: "2026-08-17",
  },
  shopify: {
    category: "コマース・決済・小売プラットフォーム",
    hq: "オタワ（カナダ）／Digital by Design",
    japanPresence: "日本Remote・日本市場組織",
    description: "online、POS、B2B、payments、international commerceを統合。日本RemoteでProduct Partnerships Leadを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  sierra: {
    category: "顧客対応AIエージェント・Agent OS",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "東京office（2025年開設、2026年Opera Tech買収）",
    description: "customer-facing AI agentの設計・運用基盤を提供。公式ATSのTokyo求人はRecruiting 2件のみで、現行の営業・導入対象求人は0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  sysdig: {
    category: "クラウドネイティブセキュリティ・CNAPP",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "日本語公式site・国内顧客（current office・責任者は確認不能）",
    description: "runtime insightを核にcloud・container securityを統合。2026年8月17日時点で公式Leverの日本求人は0件。",
    salesRoles: 0,
    lastChecked: "2026-08-17",
  },
  planet: {
    category: "地球観測・衛星データ・地理空間インテリジェンス",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Planet Labs Japan株式会社・東京都港区六本木（設立年は確認不能）",
    description: "near-daily Monitoring、Tasking、analytics、APIを提供。日本Remoteで防衛・情報機関向けAccount Executiveを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  replit: {
    category: "AIソフトウェア作成・Agentic Development",
    hq: "カリフォルニア州フォスターシティ（米国）",
    japanPresence: "日本Remoteで市場立ち上げ（日本法人・office・責任者は確認不能）",
    description: "Agent 4でideaからfull-stack application、test、deployまでを一体化。日本市場でFounding Account ExecutiveとGrowth Leadを公式募集。",
    salesRoles: 2,
    lastChecked: "2026-08-17",
  },
  rubrik: {
    category: "データセキュリティ・サイバーレジリエンス",
    hq: "カリフォルニア州パロアルト（米国）",
    japanPresence: "Rubrik Japan株式会社・東京都港区（2016年設立）",
    description: "data、identity、SaaS、AI agentの保護・脅威分析・clean recoveryを提供。東京でMid Market AEとCustomer Experience Managerを公式募集。",
    salesRoles: 2,
    lastChecked: "2026-08-17",
  },
  saviynt: {
    category: "アイデンティティセキュリティ・IGA・PAM",
    hq: "カリフォルニア州エルセグンド（米国）",
    japanPresence: "Saviynt Japan株式会社・東京都港区六本木（Ashisuto出資手続きは2026年6月時点未完了）",
    description: "human、external、workload、AI agentのidentity governanceとprivileged accessを統合。日本でSales、SE、Professional Services、Trainingの4求人を公式確認。",
    salesRoles: 4,
    lastChecked: "2026-08-17",
  },
  scandit: {
    category: "スマートデータキャプチャ・コンピュータビジョン",
    hq: "チューリッヒ（スイス）",
    japanPresence: "スキャンディット合同会社・東京（2020年設立、公式ページ間でoffice住所不一致）",
    description: "barcode、text、ID、labelをsmart deviceで取得し、Retail・物流workflowを支援。2026年8月17日時点の現行日本求人は0件。",
    salesRoles: 0,
    hiringStatus: "継続観測",
    lastChecked: "2026-08-17",
  },
  nexthink: {
    category: "デジタル従業員体験・IT運用自動化",
    hq: "ローザンヌ（スイス）／ボストン（米国）",
    japanPresence: "Nexthink合同会社・東京都港区赤坂（2025年設立）",
    description: "端末・network・application・従業員feedbackからDEXを観測し、診断・修復・adoptionへ接続。東京でCustomer Success ManagerとSolution Consultantを公式募集。",
    salesRoles: 2,
    lastChecked: "2026-08-17",
  },
  nice: {
    category: "顧客体験AI・コンタクトセンター・金融犯罪対策",
    hq: "ラアナナ（イスラエル）／ホーボーケン（米国）",
    japanPresence: "ナイスジャパン株式会社・東京都港区赤坂（2004年設立）",
    description: "CXoneでcustomer interaction・AI・WEMを統合し、ActimizeでAML・fraudを支援。東京でSales、AI leadership、SE、AML deliveryの4求人を公式確認。",
    salesRoles: 4,
    lastChecked: "2026-08-17",
  },
  patch: {
    category: "気候金融・環境市場・脱炭素調達",
    hq: "カリフォルニア州サンフランシスコ（米国）／ロンドン（英国）",
    japanPresence: "東京Remote・APAC市場開発（日本法人・常設officeは確認不能）",
    description: "carbon、再生可能energy、SAF等のstrategy、sourcing、diligence、purchase、portfolio管理を統合。東京でAPAC初のEnterprise AEを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  patsnap: {
    category: "研究開発・知財インテリジェンス・ドメインAI",
    hq: "シンガポール",
    japanPresence: "東京office・東京都港区新橋（2023年までに日本展開を公式確認）",
    description: "patent・science・chemical・clinical dataとdomain AI agentでR&D・IP判断を支援。東京でForward Deployed EngineerとKey Account Managerを公式募集。",
    salesRoles: 2,
    lastChecked: "2026-08-17",
  },
  pendo: {
    category: "ソフトウェア体験管理・プロダクト分析・デジタル定着",
    hq: "ノースカロライナ州ローリー（米国）",
    japanPresence: "Pendo.io Japan株式会社・東京都渋谷区（2020年設立）",
    description: "analytics、session、feedback、in-app guide、AI・agent analyticsを統合。東京HybridでEnterprise Account Executiveを公式募集。",
    salesRoles: 1,
    lastChecked: "2026-08-17",
  },
  marqvision: {
    category: "ブランド保護・知財インテリジェンス",
    hq: "ロサンゼルス（米国）",
    japanPresence: "東京・渋谷スクランブルスクエア（2025年本格展開）",
    description: "AIと法務運用で偽造品、なりすまし、海賊版の検知・執行を支援。東京でAccount Executive、Brand Protection、Customer Successの3求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  mendix: {
    category: "エンタープライズLow-code・Agentic App開発",
    hq: "ロッテルダム（オランダ）／ボストン（米国）・Siemens傘下",
    japanPresence: "東京・小田急サザンタワー（法人設立年・現責任者は確認不能）",
    description: "low-code、AI agent、orchestration、governanceを統合。東京でPartner Sales、Presales Solution Consultant、Specialized Account Executiveの3求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  miro: {
    category: "AIイノベーション・ビジュアル協働基盤",
    hq: "アムステルダム（オランダ）／サンフランシスコ（米国）",
    japanPresence: "ミロ・ジャパン合同会社・東京（2021年設立）",
    description: "strategy、discovery、design、planning、deliveryをvisual canvasとAI workflowで接続。東京でSales、BDR、SE、SA、TAMの現行8求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  netskope: {
    category: "SSE・SASE・データ・AIセキュリティ",
    hq: "カリフォルニア州サンタクララ（米国）",
    japanPresence: "Netskope Japan株式会社・東京（2017年設立）",
    description: "network、cloud、app、data、AIのsecurityをNetskope OneとNewEdgeで統合。日本でSales、Channel、SE、SA、TAMの現行12求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  "neural-concept": {
    category: "設計AI・CAE・デザインCopilot",
    hq: "ローザンヌ（スイス）",
    japanPresence: "2021年販売開始・東京office開設準備（法人・住所は確認不能）",
    description: "simulation dataとphysics-aware AIで設計・CAE iterationを高速化。東京でSales、SE、TAM、Application Engineerの現行4求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  ideals: {
    category: "仮想データルーム・M&A案件管理",
    hq: "グローバル分散（契約主体例はルツェルン、スイス）",
    japanPresence: "東京・丸の内のground team（日本法人・責任者は確認不能）",
    description: "M&A・fundraisingの機密document、権限、Q&A、redaction、auditを統合。東京でAE、BDA、Premium Solutionsの3機能roleを公式確認。",
    lastChecked: "2026-08-17",
  },
  knowbe4: {
    category: "ヒューマンリスク管理・セキュリティ教育",
    hq: "フロリダ州クリアウォーター（米国）",
    japanPresence: "KnowBe4 Japan合同会社・東京ミッドタウン（2020年設立）",
    description: "training、phishing simulation、report・triage、behavior・risk scoringを統合。東京でSales、SE、CS、Advisor、Partnerの対象6求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  lakera: {
    category: "AIセキュリティ・LLM・エージェント制御",
    hq: "チューリッヒ（スイス）・サンフランシスコ（米国）／Check Point傘下",
    japanPresence: "過去Japan AE採用は確認。Lakera専用の日本法人・office・責任者は確認不能",
    hiringStatus: "継続観測",
    description: "prompt injection、RAG poisoning、data leakage、agent tool misuseをred-team・runtimeで制御。2026年8月17日時点の公式求人は0件。",
    lastChecked: "2026-08-17",
  },
  lighthouse: {
    category: "宿泊業の商用インテリジェンス・収益管理",
    hq: "ロンドン（英国）・ヘント（ベルギー）",
    japanPresence: "Greater Tokyo・Remote（日本法人・office・責任者は確認不能）",
    description: "hotelのpricing、performance、direct、distribution、commercial dataを統合。日本RemoteでBusiness Development Manager（AE）を公式募集。",
    lastChecked: "2026-08-17",
  },
  mambu: {
    category: "コンポーザブル・コアバンキング基盤",
    hq: "アムステルダム（オランダ）",
    japanPresence: "JP-Remote・Employee of Record（日本法人・office・責任者は確認不能）",
    description: "Deposits、Lending、Paymentsをcomposable SaaS coreで提供。Japan Remoteでreseller-ledのSenior Account Executive（Channel）を公式募集。",
    lastChecked: "2026-08-17",
  },
  figma: {
    category: "プロダクトDesign・Developer Workflow・AI協働",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "日本法人・Tokyo Hub（2022年3月開設、street addressは確認不能）",
    description: "design、Dev Mode、FigJam、Sites、Make、MCP・agentを統合。東京でSales、SC、Onboarding、Enablement、TAMの対象8求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  fivetran: {
    category: "Data Movement・ELT・Analytics Engineering基盤",
    hq: "カリフォルニア州オークランド（米国）",
    japanPresence: "Fivetran Japan株式会社・Remote Japan（登記住所はlaw office、実officeは確認不能）",
    description: "ELT・CDC、Hybrid、dbt transformation、activationを統合。日本RemoteでBDR、Customer Solutions、Partner Sales、Sales Directorの4求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  "grafana-labs": {
    category: "Open Observability・Telemetry・障害対応",
    hq: "ニューヨーク（米国）・distributed company",
    japanPresence: "グラファナラボ日本合同会社・東京（2025年11月設立、住所・EBC稼働は確認不能）",
    description: "Grafana Cloud、LGTM、k6、IRM・SLO、AIをOpenTelemetry-nativeで提供。日本RemoteでEnterprise AEとSenior Solutions Engineerを公式募集。",
    lastChecked: "2026-08-17",
  },
  gurobi: {
    category: "数理最適化・Decision Intelligence",
    hq: "オレゴン州ビーバートン（米国）",
    japanPresence: "株式会社Gurobi Japan・東京都府中市（2010年設立、2025年社名変更）",
    description: "Optimizer、Compute Server、Instant Cloud、Intelligence Hubを提供。国内定量事例はあるが、2026年8月17日時点の現行日本求人は0件。",
    lastChecked: "2026-08-17",
  },
  hightouch: {
    category: "Composable CDP・Reverse ETL・AIマーケティング",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Japan partner・reseller motion（日本法人・office・責任者は確認不能）",
    description: "warehouse-native CDP、activation、AI Decisioning、Agentic Marketingを提供。Australia・SingaporeからJapan市場を担当するEnterprise AEを公式募集。",
    lastChecked: "2026-08-17",
  },
  dialpad: {
    category: "AIコミュニケーション・クラウド電話・Contact Center",
    hq: "カリフォルニア州サンラモン（米国）",
    japanPresence: "東京office・渋谷（2016年SoftBank提携で日本提供開始）",
    description: "voice、meeting、contact center、sales coachingを会話AIで統合。東京でMid-Market AEとSales Engineerの対象2求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  docusign: {
    category: "契約ライフサイクル・電子署名・Agreement AI",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Docusign Japan K.K.・東京都港区虎ノ門（2015年設立）",
    description: "eSignatureから契約作成・締結・管理・AI分析を担うIAMへ拡張。東京でAE、Partner、Marketing、MDRの対象7求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  dragos: {
    category: "OT・ICSサイバーセキュリティ",
    hq: "メリーランド州ハノーバー（米国）",
    japanPresence: "日本Remote team・Macnica partner（2023年参入、日本法人・officeは確認不能）",
    description: "工場・重要インフラのasset可視化、脆弱性優先度、脅威検知・対応を提供。日本でEnterprise AEとAdvisory Solutions Architectを公式募集。",
    lastChecked: "2026-08-17",
  },
  elastic: {
    category: "Search AI・Observability・Security基盤",
    hq: "アムステルダム（オランダ）・distributed company",
    japanPresence: "Elasticsearch株式会社・東京都千代田区（2014年9月設立）",
    description: "Elasticsearchを共通engineにSearch AI、Observability、Securityを提供。東京でRetail Sales 2件とSolutions Architecture leadershipの3求人を公式確認。",
    tags: ["Search AI", "Observability", "Security", "Retail", "Solutions Architecture", "Platform Sale"],
    lastChecked: "2026-08-17",
  },
  "extreme-networks": {
    category: "クラウドネットワーク・Fabric・Network Security",
    hq: "ノースカロライナ州モリスビル（米国）",
    japanPresence: "Extreme Networks株式会社・東京都千代田区霞が関（法人設立1993年）",
    description: "wired、wireless、fabric、SD-WAN、NAC・ZTNAをPlatform ONEで統合。東京でSE、Services Sales、Premier Deliveryの対象4求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  cohere: {
    category: "企業向け生成AI・Private AI基盤",
    hq: "トロント（カナダ）",
    japanPresence: "東京Remote team・富士通との日本語AI提携（日本法人・office・責任者は確認不能）",
    description: "enterprise LLM、retrieval、agent applicationをprivate deploymentを含め提供。東京RemoteでAE、Partner Development、FDEの現行3求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  contentsquare: {
    category: "デジタル体験分析・プロダクトアナリティクス",
    hq: "パリ（フランス）",
    japanPresence: "Contentsquare Japan合同会社・東京都千代田区丸の内（2022年4月設立）",
    description: "journey、session、heatmap、error、product analytics、VoCを統合。国内定量事例はあるが、2026年8月17日時点の現行日本求人は0件。",
    lastChecked: "2026-08-17",
  },
  datadog: {
    category: "オブザーバビリティ・クラウドセキュリティ",
    hq: "ニューヨーク（米国）",
    japanPresence: "Datadog Japan合同会社・東京都千代田区丸の内（2018年進出、2023年東京data center）",
    description: "metrics、traces、logs、experience、security、FinOps、AI Observabilityを統合。東京でSales、SE、CS、Support、Partner等の対象22求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  "dbt-labs": {
    category: "Analytics Engineering・Trusted Data基盤",
    hq: "米国（Fivetranとの統合会社）",
    japanPresence: "日本・APAC Remote team（日本法人・office・責任者は確認不能）",
    description: "dbtのtransformation、test、lineage、semanticとFivetran ingestionを統合。日本RemoteでPartner Sales、BDR、Customer Solutions、Sales Directorの4求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  deel: {
    category: "グローバル雇用・Payroll・HR基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Deel Japan株式会社・東京都（2022年2月設立）",
    description: "EOR、contractor、Global Payroll、HR、IT、Mobilityを提供。日本でSDR、Onboarding、Payroll Operationsの掲載対象4職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  cambly: {
    category: "法人英語研修・AI学習",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "APAC team・東京は現行求人のsecondary location（日本法人・officeは確認不能）",
    description: "native tutorとの会話、AI練習、CEFR、法人管理を提供。上海・東京を勤務地とするAPAC Sales Directorを公式募集。",
    lastChecked: "2026-08-17",
  },
  "cato-networks": {
    category: "SASE・クラウドネットワークセキュリティ",
    hq: "テルアビブ（イスラエル）",
    japanPresence: "Cato Networks株式会社・東京都千代田区大手町（2020年10月設立）",
    description: "networkとsecurityをsingle cloud platformへ統合。日本でSales、Presales、Customer Success、Supportの現行10求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  censys: {
    category: "インターネットインテリジェンス・攻撃対象領域管理",
    hq: "ミシガン州アナーバー（米国）",
    japanPresence: "日本市場team・Remote（日本法人・office・責任者は確認不能）",
    description: "internet assetの継続観測、Exposure Management、脅威調査、APIを提供。日本でAEとSenior Solutions Engineerを公式募集。",
    lastChecked: "2026-08-17",
  },
  cloudflare: {
    category: "Connectivity Cloud・ネットワーク・セキュリティ",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Cloudflare Japan株式会社・東京都千代田区丸の内（2020年日本法人設立）",
    description: "Application、Network、SASE、Developer Platformをglobal networkで提供。日本関連のSales、Partner、Supportの現行5求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  cognition: {
    category: "AIソフトウェアエンジニアリング",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Cognition Japan team・東京（2026年4月launch、法人商号・office住所は確認不能）",
    description: "Devin Cloud・Desktop・Review・Securityでsoftware taskをagent実行。東京でSales、Partnerships、Deployed、Support、GTM Opsの現行7求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  aghanim: {
    category: "モバイルゲームD2C・決済・LiveOps",
    hq: "ロサンゼルス（米国）／リスボン（ポルトガル）",
    japanPresence: "日本向けRemote team（日本法人・officeは確認不能）",
    description: "mobile game向けGame Hub、Merchant of Record、LiveOpsを提供。日本でHead of BDとCustomer Success Producerを公式募集する一方、国内顧客・売上は非公開。",
    lastChecked: "2026-08-17",
  },
  airwallex: {
    category: "グローバル決済・金融インフラ",
    hq: "サンフランシスコ（米国）／シンガポール",
    japanPresence: "Airwallex Japan株式会社・東京都港区（2023年電子決済等代行業、2025年第二種資金移動業登録）",
    description: "payments、FX、account、card、treasury、embedded financeをglobal展開。日本はonline決済を提供し、営業・partner・operationsの対象6求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  amplitude: {
    category: "プロダクトアナリティクス・実験基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Amplitude Analytics GK・東京（現住所・設立年月・人数は非公開）",
    description: "product analytics、session replay、experimentation、feature management、AIを提供。2026年8月17日時点で日本の現行公式求人は0件。",
    lastChecked: "2026-08-17",
  },
  anthropic: {
    category: "フロンティアAI・Enterprise AI基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Anthropic Japan GK・東京（2025年10月開設）",
    description: "Claude、API、Code、Enterprise、MCPを提供。東京の現行12求人のうち、Sales、Channel、Applied AI、CS、Supportの対象9件を公式確認。",
    lastChecked: "2026-08-17",
  },
  asana: {
    category: "ワークマネジメント・AI協働基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "アサナジャパン株式会社・東京都千代田区丸の内（2019年に日本語版・東京office）",
    description: "Goal、Portfolio、Project、Task、workflow、AI TeammatesをWork Graphで接続。東京でCorporate Account Executiveを公式募集。",
    lastChecked: "2026-08-17",
  },
  okta: {
    category: "アイデンティティ・アクセス管理・セキュリティ",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Okta Japan株式会社・東京／大阪（2020年9月設立）",
    description: "Workforce IdentityとAuth0 Customer Identityを提供。日本でOkta・Auth0のAE、Marketing、Auth0 TAMの現行実求人5件を公式確認。",
    lastChecked: "2026-08-17",
  },
  pagerduty: {
    category: "インシデント管理・オペレーショナルレジリエンス",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "PagerDuty株式会社・東京都港区（2022年にJapan Cloudとの提携で設立）",
    description: "incident response、on-call、AIOps、runbook automationを提供。日本でSales、BDR、Solutions、Professional Servicesの現行6求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  sonar: {
    category: "コード品質・アプリケーションセキュリティ",
    hq: "ジュネーブ（スイス）／オースティン（米国）",
    japanPresence: "東京GTM・日本語公式サイト（日本法人・責任者・進出年は非公開）",
    description: "IDE・PR・CIでcode qualityとsecurityを継続検証するSonarQubeを提供。東京でEnterprise Territory ManagerとPartner Business Managerを公式募集。",
    lastChecked: "2026-08-17",
  },
  zendesk: {
    category: "AIカスタマーサービス・コンタクトセンター",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "株式会社Zendesk・東京都中央区（2013年参入）",
    description: "ticket、messaging、voice、knowledge、AI Agent、CopilotをResolution Platformで提供。東京でCommercial AE、Senior Sales Engineer、BDRの現行3求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  zilliz: {
    category: "ベクトルデータベース・AIデータ基盤",
    hq: "カリフォルニア州レッドウッドシティ（米国）",
    japanPresence: "東京Hybridのfounding team・Tokyo cloud region（日本法人・責任者・officeは非公開）",
    description: "Milvusを起点にmanaged vector databaseとBYOCを提供。東京でEnterprise Account ExecutiveとFounding Field Engineerを公式募集。",
    lastChecked: "2026-08-17",
  },
  deepl: {
    category: "言語AI・翻訳・文章支援",
    hq: "ケルン（ドイツ）",
    japanPresence: "DeepL Japan・東京（日本向け法人サービスと営業体制を展開）",
    description: "翻訳、文章作成、音声通訳、APIを企業向けに提供するLanguage AI企業。東京で営業、CS、Solutions、Enablement、Product GTMの対象7職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  elevenlabs: {
    category: "音声AI・会話型AI・コンテンツ制作",
    hq: "ロンドン（英国）／ニューヨーク（米国）",
    japanPresence: "ElevenLabs Japan合同会社・東京（2025年4月設立）",
    description: "音声生成、音声認識、dubbing、会話型AI AgentとAPIを提供。日本で新規開拓のAccount Executiveと拡張を担うAccount Managerを公式募集。",
    lastChecked: "2026-08-17",
  },
  mirakl: {
    category: "企業向けマーケットプレイス・コマース基盤",
    hq: "パリ（フランス）／ボストン（米国）",
    japanPresence: "Mirakl株式会社・東京（2022年設立）",
    description: "Marketplace、Dropship、seller・catalog管理、決済、広告を企業向けに提供。日本でSenior Account ExecutiveとSolution Consultantを公式募集。",
    lastChecked: "2026-08-17",
  },
  "new-relic": {
    category: "オブザーバビリティ・DevOps・クラウド運用",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "New Relic株式会社・東京（2018年8月設立）",
    description: "metrics、logs、traces、errors、digital experienceを統合するobservability基盤。日本でEnterprise sales、SDR、Technical Success、Solutionsの7 requisitionsを公式確認。",
    lastChecked: "2026-08-17",
  },
  notion: {
    category: "AIワークスペース・ナレッジ・協働",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Notion Japan・東京（2020年に日本GTMを開始、2021年に日本語版提供）",
    description: "文書、Wiki、project、enterprise search、meeting notes、AI Agentを一つのworkspaceで提供。東京で営業、Solutions、Outcomes、導入技術の対象12職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  verkada: {
    category: "クラウド型物理セキュリティ・IoT",
    hq: "カリフォルニア州サンマテオ（米国）",
    japanPresence: "Verkada Japan株式会社・東京都渋谷区（2021年に国内partnerが提供開始、法人設立日は非公開）",
    description: "camera、access control、sensor、intercom等をcloud管理する物理セキュリティ基盤。日本で東京・大阪のAE、Channel、Field Marketing、Sales Operationsの7職種を公式募集。",
    lastChecked: "2026-08-17",
  },
  walkme: {
    category: "デジタル定着・業務変革",
    hq: "テルアビブ（イスラエル）",
    japanPresence: "WalkMe株式会社・東京都中央区日本橋（2019年2月設立）",
    description: "業務application上の案内、analytics、automation、AIでsoftwareの利用定着と業務完了を支援。日本でCS、Professional Services、Solution、Partner・Allianceの7職種を公式掲載。",
    lastChecked: "2026-08-17",
  },
  celonis: {
    category: "プロセスインテリジェンス・業務変革",
    hq: "ミュンヘン（ドイツ）／ニューヨーク（米国）",
    japanPresence: "Celonis株式会社・東京都千代田区丸の内（2019年設立）",
    description: "企業systemのevent dataからprocessの停滞・価値機会を可視化し、改善actionへ接続。東京の現行6求人のうち、営業・partner・delivery関連5職種を掲載（People & Culture職は対象外）。",
    lastChecked: "2026-08-17",
  },
  confluent: {
    category: "データストリーミング・クラウドデータ基盤",
    hq: "カリフォルニア州マウンテンビュー（米国）",
    japanPresence: "Confluent Japan合同会社・東京都新宿区（2021年4月に日本operations開始）",
    description: "Apache Kafkaを基盤に、リアルタイムdata streamの接続・処理・governanceを提供。2026年8月17日時点で公式Careerの日本求人を再現確認できず、旧求人は現行扱いしていない。",
    lastChecked: "2026-08-17",
  },
  dataiku: {
    category: "企業向けAI・データサイエンス基盤",
    hq: "ニューヨーク（米国）／パリ（フランス）",
    japanPresence: "Dataiku Japan株式会社・東京（日本市場で業界別GTMを展開）",
    description: "data準備、機械学習、生成AI・Agent、governanceを一つのplatformで提供。日本で金融、Retail・Telecom向けEnterprise AEとField Marketing Internを公式掲載。",
    lastChecked: "2026-08-17",
  },
  glean: {
    category: "企業向けAI・社内検索",
    hq: "カリフォルニア州（米国）",
    japanPresence: "日本市場チーム・リモート（2023年に国内販売開始、2026年に日本カントリーマネージャー就任）",
    description: "企業内の情報を権限付きで横断する検索、AIアシスタント、業務エージェントを提供。日本ではStrategic AE、Enterprise AE、SDRを公式募集。",
    lastChecked: "2026-08-17",
  },
  hubspot: {
    category: "顧客管理・マーケティング・営業・AI",
    hq: "マサチューセッツ州ケンブリッジ（米国）",
    japanPresence: "HubSpot Japan株式会社・東京都千代田区丸の内（2016年2月設立、同年7月営業開始）",
    description: "CRMを中心にマーケティング、営業、サービス、コンテンツ、データ、コマースとAIを統合。日本ではAE3職に加え、BDR、営業マネージャー、Solutions Engineer、Field Marketerを公式募集。",
    lastChecked: "2026-08-17",
  },
  qualtrics: {
    category: "顧客体験・従業員体験・市場調査",
    hq: "ユタ州プロボ／ワシントン州シアトル（米国）",
    japanPresence: "クアルトリクス合同会社・東京都千代田区丸の内（2016年法人設立、2018年事業開始）",
    description: "顧客・従業員・製品・ブランドの体験データを収集・分析し、改善行動へつなぐXM基盤。2026年8月17日時点で日本の現行公式求人は確認できない。",
    lastChecked: "2026-08-17",
  },
  speak: {
    category: "AI英会話・法人向け人材育成",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "スピークジャパン合同会社・東京都渋谷区（2022年日本soft launch、2024年8月法人設立）",
    description: "音声AIによる英語発話練習と法人管理を提供。東京でAccount Executive、Customer Success Manager、B2B Marketing Managerを公式募集。",
    lastChecked: "2026-08-17",
  },
  stripe: {
    category: "決済・金融インフラ・収益管理",
    hq: "サンフランシスコ（米国）／ダブリン（アイルランド）",
    japanPresence: "ストライプジャパン株式会社・東京（2016年提供開始、2020年開発拠点開設）",
    description: "決済、請求、プラットフォームの資金移動、不正対策、税・データ基盤を提供。東京でCommercial Hunter・Grower、Enterprise Hunterの3つのAE職を公式募集。",
    lastChecked: "2026-08-17",
  },
  servicenow: {
    category: "企業向け業務ワークフロー・AI基盤",
    hq: "カリフォルニア州サンタクララ（米国）",
    japanPresence: "ServiceNow Japan合同会社・東京／大阪（2013年設立）",
    description: "IT、人事、顧客対応、営業、製造の申請・判断・実行を共通データとAIでつなぐ業務基盤。日本で営業、BDR、Partner、Presales、Architecture、Customer Success、Deal Operationsの対象26職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  "tools-for-humanity": {
    category: "人間性証明・デジタル本人確認・消費者向けアプリ",
    hq: "カリフォルニア州サンフランシスコ（米国）／ミュンヘン（ドイツ）",
    japanPresence: "World IDを日本で提供。Tinder Japanとマイナンバーカード連携を確認（日本法人・現行求人は未確認）",
    description: "AIやbotが増えるインターネットで、氏名を渡さず一人の人間・年齢等を証明するWorld IDとWorld Appを開発。日本で実利用はあるが、公式ATSの現行Japan求人は0件。",
    lastChecked: "2026-08-17",
  },
  lovable: {
    category: "AIソフトウェア開発・業務アプリ作成",
    hq: "ストックホルム（スウェーデン）",
    japanPresence: "日本語サイトは提供。日本法人・国内拠点・Japan求人は未確認",
    description: "自然言語から画面、バックエンド、データベース、認証、決済、公開まで含むアプリを作るAI開発基盤。公式ATS 74件にJapan・APAC勤務地はなく、日本未進出として継続観測。",
    lastChecked: "2026-08-17",
  },
  atlassian: {
    category: "チームワーク・業務管理・DevOps・ITサービス管理",
    hq: "シドニー（オーストラリア）／サンフランシスコ（米国）",
    japanPresence: "アトラシアン株式会社・横浜（2013年6月設立）",
    description: "Jira、Confluence、Jira Service Management、LoomとAIで開発・業務・IT運用の協働を支援。横浜で日本語対応Senior Customer Success Managerを公式募集。",
    lastChecked: "2026-08-18",
  },
  dynatrace: {
    category: "オブザーバビリティ・AIOps・アプリケーションセキュリティ",
    hq: "マサチューセッツ州ボストン（米国）",
    japanPresence: "Dynatrace合同会社・東京（2015年設立）",
    description: "application、infrastructure、log、顧客体験、securityをAIで相関し、障害原因と事業影響を可視化。東京でEnterprise Solutions Engineerを公式募集。",
    lastChecked: "2026-08-18",
  },
  vercel: {
    category: "AIクラウド・フロントエンドクラウド・開発者基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Tokyo・Osaka compute regionを提供（日本法人・office・Japan求人は未確認）",
    description: "Next.js、AI SDK、v0とglobal application infrastructureを提供。APAC求人はSydney等を対象とし、日本法人・国内拠点・Japan専任求人は未確認。",
    lastChecked: "2026-08-18",
  },
  gitlab: {
    category: "DevSecOps・AIソフトウェア開発基盤",
    hq: "全社リモート（米国法人）",
    japanPresence: "GitLab合同会社・東京都中央区日本橋（2020年に日本市場へ本格進出）",
    description: "source code、CI/CD、security、planning、AIを一つのDevSecOps platformで提供。日本からRemoteのSenior Ecosystem Sales Managerを公式募集。",
    lastChecked: "2026-08-19",
  },
  watchguard: {
    category: "サイバーセキュリティ・MSP基盤・MDR",
    hq: "ワシントン州シアトル（米国）",
    japanPresence: "日本公式サイト・東京onsite求人（国内法人・人員は確認不能）",
    description: "network、endpoint、identity、MDRをMSP・channel向けplatformで提供。東京で日本事業を率いるCountry Managerを公式募集。",
    lastChecked: "2026-08-19",
  },
  langchain: {
    category: "AIエージェント開発・評価／オブザーバビリティ基盤",
    hq: "カリフォルニア州サンフランシスコ／ニューヨーク（米国）",
    japanPresence: "楽天の国内事例・APAC region選択（日本法人・office・Japan求人は未確認）",
    description: "LangChain、LangGraph、LangSmithでAI agentの開発・評価・運用を支援。国内事例はあるが日本法人・拠点・専任求人は未確認。",
    lastChecked: "2026-08-19",
  },
};

export function standardizeRolloutCompany(company: Company): Company {
  const patch = batchTwoCompanyPatches[company.slug];
  return patch ? { ...company, ...patch } : company;
}
