import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchTwelve: Job[] = [
  job({
    id: "marqvision-account-executive-japan-current",
    companySlug: "marqvision",
    title: "Account Executive, Japan",
    segment: "Enterprise / Brand Protection",
    location: "東京",
    workStyle: "remote・flexibleを尊重、頻度・分類は非公開",
    language: "英語（business）／日本語要件は明記なし",
    source: { label: "MarqVision Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/marqvision/jobs/4986795008" },
    descriptionSummary: "enterprise new logoを開拓し、IP・Brand・Ecommerce・executiveを束ね、PoCから3〜6カ月でannual contractへcloseする。",
    genbaTake: "takedown件数でなく、侵害露出、再出品、action time、analyst工数、authorized channelへの影響をbusiness caseにする。",
    compensationReality: "給与、base、OTEは非公開。ACV 5万〜20万米ドルの記載は契約規模であり報酬ではない。",
    desiredProfile: "公式求人はenterprise B2B SaaS 5年以上、complex sale、PoC、business Englishを重視。日本語要件は記載しない。",
    domain: "Brand Protection・Enterprise Sales",
  }),
  job({
    id: "marqvision-brand-protection-specialist-japan-current",
    companySlug: "marqvision",
    title: "Brand Protection Specialist, Japan",
    segment: "Brand Protection Operations / Delivery",
    location: "東京",
    workStyle: "remote・flexibleを尊重、頻度・分類は非公開",
    language: "日本語（native）／英語（business）、韓国語は歓迎",
    source: { label: "MarqVision Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/marqvision/jobs/5151623008" },
    descriptionSummary: "AI調査、human validation、takedown申請を実行し、Sales・Customer Successと顧客のIP protection outcomeを作る。",
    genbaTake: "検知量を増やすだけでなく、false positive、証拠、申請、再出品を優先順位付きのenforcement workflowにする。",
    compensationReality: "日本の給与、bonus、variable、delivery KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はnative Japanese、business English、調査・分析、IP・brand protectionへの関心を重視。",
    domain: "Brand Protection・Enforcement Operations",
  }),
  job({
    id: "marqvision-customer-success-manager-japan-current",
    companySlug: "marqvision",
    title: "Customer Success Manager, Japan",
    segment: "Customer Success / Renewal & Expansion",
    location: "東京",
    workStyle: "勤務形態の詳細は公式求人で明記なし",
    language: "日本語（native）／英語（business、read・write・speak）",
    source: { label: "MarqVision Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/marqvision/jobs/5064808008" },
    descriptionSummary: "onboarding、QBR、training、renewal、upsell、churn riskを担い、enforcement dataを顧客のbusiness outcomeへつなぐ。",
    genbaTake: "削除件数のreportingで終わらず、重点SKU・市場の露出、再発、action timeを更新・拡張の根拠にする。",
    compensationReality: "日本の給与、bonus、variable、renewal・expansion targetは公式求人で確認できない。",
    desiredProfile: "公式求人はcustomer success、stakeholder management、native Japanese、business Englishを重視。",
    domain: "Brand Protection・Customer Success",
  }),
  job({
    id: "mendix-partner-sales-executive-japan-current",
    companySlug: "mendix",
    title: "Partner Sales Executive",
    segment: "Partner Sales / Enterprise Low-code",
    location: "東京・日本",
    workStyle: "オンサイト",
    language: "日本語・英語とも公式求人で明記なし",
    source: { label: "Mendix Careers (Lever)", url: "https://jobs.lever.co/mendix/6c126d1d-2053-436d-ac33-5bd7c4388a4e" },
    descriptionSummary: "partner recruitment・onboarding・health、joint plan、co-sell、channel revenueを担い、企業app・agent deliveryをecosystemで拡張する。",
    genbaTake: "partner数でなく、再利用可能なindustry solution、certified delivery、sourced・influenced pipelineと顧客outcomeを作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、partner quotaは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise software channel 3年以上、partner business plan、co-sell、travelを重視。",
    domain: "Enterprise Low-code・Partner Sales",
  }),
  job({
    id: "mendix-senior-presales-solution-consultant-japan-current",
    companySlug: "mendix",
    title: "Senior Presales Solution Consultant",
    segment: "Pre-sales / Low-code & Agentic Automation",
    location: "東京・日本",
    workStyle: "ハイブリッド",
    language: "日本語・英語とも公式求人で明記なし",
    source: { label: "Mendix Careers (Lever)", url: "https://jobs.lever.co/mendix/2875479e-d154-4f1f-9cbe-4ff6c73bd389" },
    descriptionSummary: "Mendix・RapidMiner、GenAI・agentic automationのarchitecture workshop、demo、PoCをAPAC顧客へ提供する。",
    genbaTake: "画面生成の速さでなく、legacy integration、governance、model・agent orchestration、production lifecycleを実workloadで検証する。",
    compensationReality: "日本の給与、bonus、variable、OTE、PoC KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はaPaaS・PaaS・cloud 5年以上、architecture、workshop・PoC、APAC travelを重視。",
    domain: "Enterprise Low-code・Solutions Consulting",
  }),
  job({
    id: "mendix-specialized-account-executive-japan-current",
    companySlug: "mendix",
    title: "Specialized Account Executive",
    segment: "Enterprise / Application Modernization",
    location: "東京・日本",
    workStyle: "オンサイト",
    language: "日本語・英語とも公式求人で明記なし",
    source: { label: "Mendix Careers (Lever)", url: "https://jobs.lever.co/mendix/e6a4788f-a823-412f-bde9-44a926043011" },
    descriptionSummary: "本文上のEnterprise AEとしてexecutive relationship、自力pipeline、channel、negotiation・procurement、closeを担う。",
    genbaTake: "low-code seatでなく、legacy backlog、business・IT協働、portfolio governance、3年TCOをapplication transformationへ翻訳する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise selling、executive relation、pipeline discipline、channel、complex negotiationを重視。",
    domain: "Enterprise Low-code・Enterprise Sales",
  }),
  job({
    id: "miro-solutions-architect-japan-8546570002-current",
    companySlug: "miro",
    title: "Solutions Architect",
    segment: "Customer Experience / Professional Services",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "日本語（near-native）／英語（business）",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8546570002?gh_jid=8546570002" },
    descriptionSummary: "MOST年間240時間を含むprofessional services、solution design、workshop、enterprise adoptionを担う。",
    genbaTake: "canvas導入でなく、発見・意思決定・deliveryを一つのworkflowへ設計し、会議・handoff・reworkを減らす。",
    compensationReality: "日本の給与、bonus、variable、OTE、delivery KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise solution architecture、facilitation、near-native Japanese、business Englishを重視。",
    domain: "AI Innovation Workspace・Solutions Architecture",
  }),
  job({
    id: "miro-technical-account-manager-japan-current",
    companySlug: "miro",
    title: "Technical Account Manager, Japan",
    segment: "Customer Experience / Technical Success",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "日本語（native-level）／英語（business-level）",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8620756002?gh_jid=8620756002" },
    descriptionSummary: "enterprise adoption、technical governance、integration、risk解消、renewal・expansionを支えるtechnical account role。",
    genbaTake: "active usersだけでなく、workflow adoption、meeting hours、decision lead time、governance exceptionを改善する。",
    compensationReality: "日本の給与、bonus、variable、portfolio数、renewal KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise TAM、technical stakeholder、native Japanese、business Englishを重視。",
    domain: "AI Innovation Workspace・Technical Account Management",
  }),
  job({
    id: "miro-solutions-architect-japan-8645883002-current",
    companySlug: "miro",
    title: "Solutions Architect",
    segment: "Customer Experience / Professional Services",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "日本語（near-native）／英語（business）",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8645883002?gh_jid=8645883002" },
    descriptionSummary: "同名の別requisitionとしてenterprise workflow設計、workshop、professional services、adoptionを担う。",
    genbaTake: "別IDの現行headcountとして保持し、担当segment・account数・採用背景を面接で確認する。",
    compensationReality: "日本の給与、bonus、variable、OTE、delivery KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise solution architecture、facilitation、near-native Japanese、business Englishを重視。",
    domain: "AI Innovation Workspace・Solutions Architecture",
  }),
  job({
    id: "miro-commercial-account-executive-japan-current",
    companySlug: "miro",
    title: "Commercial Account Executive",
    segment: "Commercial / New & Expansion",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "日本語（professional-level）／英語水準は明記なし",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8385450002?gh_jid=8385450002" },
    descriptionSummary: "従業員500〜3,000人segmentでnew logoとexpansion、pipeline、multi-threaded saleを担う。",
    genbaTake: "whiteboard seatでなく、product・DX workflowのcycle time、meeting、handoffを改善するland-and-expandを作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式応募設問は法人顧客との日本語business discussion・meeting・文書対応を確認。",
    domain: "AI Innovation Workspace・Commercial Sales",
  }),
  job({
    id: "miro-strategic-account-executive-japan-8460222002-current",
    companySlug: "miro",
    title: "Strategic Account Executive",
    segment: "Strategic / Fortune 500 & Global 2000",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "日本語（native-level）／英語（conversational）",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8460222002?gh_jid=8460222002" },
    descriptionSummary: "Fortune 500・Global 2000の3〜10 named accountsをaccount CEOとして開拓・拡張する。",
    genbaTake: "tool standardizationでなく、複数部門のinnovation workflowとdata residency・governanceをexecutive caseにする。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic enterprise sale、native Japanese、conversational English、cross-functional leadershipを重視。",
    domain: "AI Innovation Workspace・Strategic Sales",
  }),
  job({
    id: "miro-strategic-account-executive-japan-8622524002-current",
    companySlug: "miro",
    title: "Strategic Account Executive",
    segment: "Strategic Enterprise",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8622524002?gh_jid=8622524002" },
    descriptionSummary: "同名の別requisitionとしてstrategic enterpriseのaccount plan、new・expansion、executive engagementを担う。",
    genbaTake: "別IDの現行headcountとして保持し、territory・named accounts・languageを選考で確認する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic enterprise selling、account planning、executive engagementを重視。言語は補完しない。",
    domain: "AI Innovation Workspace・Strategic Sales",
  }),
  job({
    id: "miro-business-development-representative-japan-current",
    companySlug: "miro",
    title: "Business Development Representative",
    segment: "Business Development / Enterprise Pipeline",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "日本語（native-level・JLPT N1相当）／英語（conversational）",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8568681002?gh_jid=8568681002" },
    descriptionSummary: "enterprise・strategic AEとoutbound、account research、qualification、meeting・pipeline創出を担う。",
    genbaTake: "meeting数だけでなく、部門横断workflowの仮説とqualified pipelineへの転換を再現可能にする。",
    compensationReality: "日本の給与、OTE、pay mix、equity、meeting・pipeline quotaは公式求人で確認できない。",
    desiredProfile: "公式求人はoutbound、native-level Japanese、日常業務のconversational Englishを重視。",
    domain: "AI Innovation Workspace・Business Development",
  }),
  job({
    id: "miro-solutions-engineer-japan-current",
    companySlug: "miro",
    title: "Solutions Engineer",
    segment: "Pre-sales / Enterprise",
    location: "東京・日本",
    workStyle: "hub-centric hybrid（role別日数は非公開）",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Miro Careers", url: "https://miro.com/careers/vacancy/8503593002?gh_jid=8503593002" },
    descriptionSummary: "large dealのtechnical discovery、demo、solution design、security・integration objectionをSalesと支援する。",
    genbaTake: "feature demoでなく、identity、integration、data residency、AI governanceをtarget workflowのoutcomeへつなぐ。",
    compensationReality: "日本の給与、bonus、variable、OTE、POC KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はtechnical pre-sales、enterprise demo・solution design、cross-functional executionを重視。言語は補完しない。",
    domain: "AI Innovation Workspace・Solutions Engineering",
  }),
  job({
    id: "netskope-channel-solutions-engineer-japan-current",
    companySlug: "netskope",
    title: "Channel Solutions Engineer",
    segment: "Channel / Solutions Engineering",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7861730" },
    descriptionSummary: "partner SEのenablement、demo、POC、technical validationを担い、channelのdelivery能力を拡張する。",
    genbaTake: "certification数でなく、partnerがSSE・SASE・data・AI securityを自力で設計・検証・導入できる状態を作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、partner KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はSolutions Engineering 7年以上、partner enablement、demo・POCを重視。",
    domain: "SSE・SASE・Channel Solutions Engineering",
  }),
  job({
    id: "netskope-regional-sales-manager-japan-6020279-current",
    companySlug: "netskope",
    title: "Regional Sales Manager",
    segment: "Enterprise / Regional Sales",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=6020279" },
    descriptionSummary: "F1000・C-levelへnew logo、territory、retention・expansionをchannelと進める別requisition。",
    genbaTake: "CASB単品でなく、user・app・data・AI contextをsecurity、latency、運用TCOの共通caseにする。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise cyber sales 10年以上、C-level、channel、regional travelを重視。",
    domain: "SSE・SASE・Enterprise Sales",
  }),
  job({
    id: "netskope-regional-sales-manager-japan-7493456-current",
    companySlug: "netskope",
    title: "Regional Sales Manager",
    segment: "Enterprise / Regional Sales",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7493456" },
    descriptionSummary: "別ATS IDでenterprise new logo、territory、retention・expansion、channel・C-level saleを担う。",
    genbaTake: "同名別headcountとして保持し、territory・segment・採用背景を選考で確認する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise cyber sales、complex cycle、C-level、channel executionを重視。",
    domain: "SSE・SASE・Enterprise Sales",
  }),
  job({
    id: "netskope-solutions-architect-japan-current",
    companySlug: "netskope",
    title: "Solutions Architect",
    segment: "Architecture / Strategic Pre-sales",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7457549" },
    descriptionSummary: "complex architecture、lab、POC、partner・customer validationを担うsenior technical role。",
    genbaTake: "diagramで終わらず、inline data context、latency、migration、privacy、operational ownershipを実trafficで立証する。",
    compensationReality: "日本の給与、bonus、variable、OTE、architecture KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はarchitecture・security 10年以上、lab・POC、partner、complex enterpriseを重視。",
    domain: "SSE・SASE・Solutions Architecture",
  }),
  job({
    id: "netskope-solutions-engineer-osaka-current",
    companySlug: "netskope",
    title: "Solutions Engineer",
    segment: "Pre-sales / Cloud Security",
    location: "大阪・日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=8015290" },
    descriptionSummary: "大阪を基点にpresales、demo、POC、customer advocacyを担い、出張を伴うtechnical salesを進める。",
    genbaTake: "security controlだけでなく、NewEdge経由のuser experience、migration、policy運用をPoCで比較する。",
    compensationReality: "日本の給与、bonus、variable、OTE、POC KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はSolutions Engineering 7年以上、demo・POC、customer advocacy、heavy travelを重視。",
    domain: "SSE・SASE・Solutions Engineering",
  }),
  job({
    id: "netskope-senior-channel-sales-manager-japan-current",
    companySlug: "netskope",
    title: "Sr. Channel Sales Manager",
    segment: "Channel Sales / Japan",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7840729" },
    descriptionSummary: "partner recruitment、enablement、joint plan、channel revenue、pipelineを担う。",
    genbaTake: "reseller数でなく、SSE・SASE・DLP・AI securityを売り切るtechnical・managed service能力を作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、partner quota、credit ruleは公式求人で確認できない。",
    desiredProfile: "公式求人はcyber channel sales、partner recruitment・enablement、revenue ownershipを重視。",
    domain: "SSE・SASE・Channel Sales",
  }),
  job({
    id: "netskope-strategic-sales-manager-japan-8028233-current",
    companySlug: "netskope",
    title: "Strategic Sales Manager",
    segment: "Strategic / F1000",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=8028233" },
    descriptionSummary: "large strategic・F1000 accountsのnew・existing、C-level、multi-product expansionを担う。",
    genbaTake: "strategic accountのnetwork・security・data・AIを共通architectureとmulti-year outcomeへ束ねる。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic enterprise sales 10年以上、C-level、complex cycle、travelを重視。",
    domain: "SSE・SASE・Strategic Sales",
  }),
  job({
    id: "netskope-strategic-sales-manager-japan-7734651-current",
    companySlug: "netskope",
    title: "Strategic Sales Manager",
    segment: "Strategic Enterprise",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7734651" },
    descriptionSummary: "同名別requisitionとしてlarge strategic accountのnew・expansion、C-level engagementを担う。",
    genbaTake: "別IDの現行headcountとして保持し、named accounts・territory・採用背景を確認する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic enterprise sales、C-level、complex cyber transformationを重視。",
    domain: "SSE・SASE・Strategic Sales",
  }),
  job({
    id: "netskope-technical-account-manager-japan-current",
    companySlug: "netskope",
    title: "Technical Account Manager",
    segment: "Technical Success / Adoption & Growth",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "英語（written・spoken proficiency）／日本語水準は明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=8121108" },
    descriptionSummary: "adoption、value realization、technical success、retention・growthを担うpost-sales role。",
    genbaTake: "ticket対応でなく、policy tuning、product adoption、risk・UX・admin KPIをQBRとrenewalへつなぐ。",
    compensationReality: "日本の給与、bonus、variable、portfolio数、renewal・growth KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はtechnical account management、adoption、value realization、English proficiencyを重視。",
    domain: "SSE・SASE・Technical Account Management",
  }),
  job({
    id: "netskope-territory-sales-manager-commercial-japan-current",
    companySlug: "netskope",
    title: "Territory Sales Manager (Commercial)",
    segment: "Commercial / New & Expansion",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7457717" },
    descriptionSummary: "commercial・midmarketのacquisition、expansion、quota、forecastを担う。",
    genbaTake: "enterprise architectureを小さく模倣せず、customer resourceに合うpackage、partner delivery、time-to-valueを設計する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はdirect sales 4年以上、cyber・SaaS経験、acquisition・expansion、forecastを重視。",
    domain: "SSE・SASE・Commercial Sales",
  }),
  job({
    id: "netskope-territory-sales-manager-midmarket-japan-7742450-current",
    companySlug: "netskope",
    title: "Territory Sales Manager (Mid-Market)",
    segment: "Mid-Market / Territory Sales",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7742450" },
    descriptionSummary: "midmarketのnew・expansion、channel、quota、forecastを担う別requisition。",
    genbaTake: "fast-cycleとpartner leverageを保ちながら、data・app contextを削りすぎないcommercial motionを作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はdirect sales 4年以上、cyber・SaaS、channel、territory managementを重視。",
    domain: "SSE・SASE・Mid-Market Sales",
  }),
  job({
    id: "netskope-territory-sales-manager-midmarket-japan-7309895-current",
    companySlug: "netskope",
    title: "Territory Sales Manager (Mid-Market)",
    segment: "Mid-Market / Territory Sales",
    location: "日本",
    workStyle: "公式求人で明記なし",
    language: "公式求人で人間言語の明記なし",
    source: { label: "Netskope Careers (Greenhouse)", url: "https://www.netskope.com/company/careers/open-positions/?gh_jid=7309895" },
    descriptionSummary: "同名別IDでmidmarket new・expansion、channel、quota、forecastを担う。",
    genbaTake: "別headcountとして保持し、territory、segment split、採用背景、partner creditを選考で確認する。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、attainmentは公式求人で確認できない。",
    desiredProfile: "公式求人はdirect sales、cyber・SaaS、channel、territory managementを重視。",
    domain: "SSE・SASE・Mid-Market Sales",
  }),
  job({
    id: "neural-concept-regional-sales-director-japan-current",
    companySlug: "neural-concept",
    title: "Regional Sales Director (Japan)",
    segment: "Japan Leadership / Engineering AI",
    location: "東京・日本",
    workStyle: "ハイブリッド（remote 30%）",
    language: "日本語（native）／英語（fluent）",
    source: { label: "Neural Concept Careers (Ashby)", url: "https://jobs.ashbyhq.com/neuralconcept/9b018838-aad4-48a6-8d6b-f2a544e0fbed" },
    descriptionSummary: "日本の新規・既存顧客、revenue、strategic partnershipを率い、9〜12カ月・10万〜100万米ドル超のtechnical enterprise cycleを担う。",
    genbaTake: "AI modelの精度だけでなく、CAD・CAEのfeedback lead time、再検証rule、engineer工数を経営と開発の共通caseにする。",
    compensationReality: "competitive salaryのみ記載。金額、base・variable、OTE、equity、quotaは非公開。",
    desiredProfile: "公式求人はtechnical enterprise SaaS 10年以上、engineering background、Japan market、native Japanese、fluent Englishを重視。",
    domain: "Engineering AI・Japan Sales Leadership",
  }),
  job({
    id: "neural-concept-technical-account-manager-japan-current",
    companySlug: "neural-concept",
    title: "Technical Account Manager",
    segment: "Technical Account Management / Expansion",
    location: "東京・日本",
    workStyle: "ハイブリッド / flexible hours",
    language: "日本語・英語（fluent、strict requirement）",
    source: { label: "Neural Concept Careers (Ashby)", url: "https://jobs.ashbyhq.com/neuralconcept/3836fecc-0a11-460a-8a99-9f5c86e95345" },
    descriptionSummary: "既存顧客portfolioのadoption、usage、renewal・expansion、demo、onboarding、workshop、project delivery、KPIを担う。",
    genbaTake: "PoCの高速化で終わらず、複数programへ安全に再利用されるmodel lifecycleとengineering adoptionを成果にする。",
    compensationReality: "competitive salaryのみ記載。金額、bonus、variable、portfolio数、renewal targetは非公開。",
    desiredProfile: "公式求人はengineering degree、CAD・CAE、customer-facing・project/account management 6年以上、fluent Japanese・Englishを重視。",
    domain: "Engineering AI・Technical Account Management",
  }),
  job({
    id: "neural-concept-solution-engineer-japan-current",
    companySlug: "neural-concept",
    title: "Solution Engineer - Japan",
    segment: "Pre-sales / Engineering AI",
    location: "東京・日本",
    workStyle: "リモート表記 / 日本国内出張あり",
    language: "求人本文は韓国語・英語を必須記載。Japan title・勤務地と不整合のため企業確認が必要",
    source: { label: "Neural Concept Careers (Ashby)", url: "https://jobs.ashbyhq.com/neuralconcept/a51fd145-b0ba-434a-b1b4-f9000db89fab" },
    descriptionSummary: "discovery、demo、technical roadmap、steering committee、signed SOW、adoption・upsellまでを支援するpre-sales role。",
    genbaTake: "同一dataでholdout・OOD精度、time-to-result、integration、security、再検証ruleを既存CAE・内製surrogateと比較する。",
    compensationReality: "competitive salaryのみ記載。金額、OTE、pay mix、POC KPIは非公開。",
    desiredProfile: "公式求人はtechnical discovery、demo、SOW、engineering AIを重視。ただし韓国語要件がJapan求人と矛盾し、応募前確認が必要。",
    domain: "Engineering AI・Solutions Engineering",
  }),
  job({
    id: "neural-concept-application-engineer-japanese-current",
    companySlug: "neural-concept",
    title: "Application Engineer (Japanese-speaking)",
    segment: "Application Engineering / Delivery",
    location: "東京・日本",
    workStyle: "ハイブリッド",
    language: "日本語・英語（fluent、日本語はnativeが望ましい）",
    source: { label: "Neural Concept Careers (Ashby)", url: "https://jobs.ashbyhq.com/neuralconcept/76aa9c5c-61f8-41db-9c42-0006a8a063ef" },
    descriptionSummary: "日本顧客とのproject・PoC、training、Engineering AI workflow構築を担うcustomer-facing application engineer。",
    genbaTake: "modelを渡すだけでなく、simulation data、Python・deep learning、CAD・CAEを現場の設計判断へ組み込む。",
    compensationReality: "competitive salaryのみ記載。金額、bonus、variable、delivery KPIは非公開。",
    desiredProfile: "公式求人はEngineering・Applied Math・Physicsの修士/博士、ML・Python・simulation、customer-facing、日本語・英語を重視。",
    domain: "Engineering AI・Application Engineering",
  }),
];
