import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-27";

export const companies20260827Daily: Company[] = [
  {
    slug: "glance",
    name: "Glance",
    category: "AIコマース・端末組み込み型ショッピング体験",
    broadCategory: "コマース・業界特化",
    hq: "シンガポール",
    japanPresence: "Glance Japan株式会社、東京拠点、Sharp・Samsungとの国内展開、Tokyo求人を公式確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "生成AIと視覚情報を使い、スマートフォンやテレビ上で発見から商品遷移までをつなぐ。日本では端末・小売・super-app・TVの流通提携を作るDirectorを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://job-boards.greenhouse.io/glance/jobs/7938622",
    tags: ["AI Commerce", "Consumer Tech", "Partnerships", "Business Development", "Tokyo", "Bilingual"],
  },
  {
    slug: "getyourguide",
    name: "GetYourGuide",
    category: "旅行体験マーケットプレイス・供給者向け成長基盤",
    broadCategory: "コマース・業界特化",
    hq: "ベルリン（ドイツ）",
    japanPresence: "東京オフィスとTokyo求人2件を公式Careersで確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "旅行者とツアー・体験・観光施設を結ぶマーケットプレイス。東京で日本の体験供給者を開拓・契約・掲載開始まで担うBusiness Development Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://getyourguide.careers/location/tokyo",
    tags: ["Travel Tech", "Marketplace", "Supplier Acquisition", "Business Development", "Tokyo Hybrid", "Japanese"],
  },
  {
    slug: "antithesis",
    name: "Antithesis",
    category: "決定論的シミュレーション・ソフトウェア信頼性検証",
    broadCategory: "セキュリティ・IT運用",
    hq: "バージニア州ウィーン（米国）",
    japanPresence: "日本法人・国内拠点・Japan求人を公式確認できず。SingaporeでAPAC向け営業・Solutions Engineerを採用中",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "本番に近い分散システムを決定論的に再現し、障害注入、原因特定、完全再現を自動化。SingaporeのGTM採用を日本進出の成立条件を観測するAPACシグナルとして掲載。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/antithesis",
    tags: ["日本未進出", "Developer Tools", "Distributed Systems", "Testing", "Software Reliability", "APAC", "Singapore"],
    entryStatus: "not-entered",
  },
];

export const jobs20260827Daily: Job[] = [
  {
    id: "glance-director-distribution-partnerships-bd-tokyo-7938622",
    companySlug: "glance",
    title: "Director, Distribution Partnerships and Business Development - Tokyo, Japan",
    segment: "Distribution Partnerships / Business Development",
    location: "東京",
    workStyle: "東京を拠点とするcountry team（出社頻度は未公開）",
    language: "ビジネスレベルの日本語・英語",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Glance Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/glance/jobs/7938622" },
    descriptionSummary: "小売・franchise、super-app、widget、TV OSの日本流通戦略を作り、役員交渉、収益分配、最低保証、activation目標、unit economics、Japan P&Lの利用者成長側を担う。",
    genbaTake: "広告枠販売ではなく、日本固有のconsumer surfaceをゼロから選び、提携条件とP&Lを同時に設計するcountry-building型のBD責任者。",
    compensationReality: "給与額は未公開。competitive base、meaningful equity、提携・端末／利用者activationに連動するannual bonus、標準的な日本の福利厚生を記載。",
    desiredProfile: "日本のmobile、internet、advertising、retail／consumer tech、mediaで12年以上のBDまたはdistribution partnership経験。大手小売、super-app、OEM／device、TV platformのいずれかでP&Lと役員契約の実績を求める。",
    careerInsights: {
      fit: "国内の大手流通・internet platformとゼロから提携を作り、契約条件、activation、unit economics、P&Lまで持ちたい人に向く。",
      thingsToKnow: "Japan team人数、reporting line、既存pipeline、目標device数、base・bonus・equity額、出社頻度は未公開。面接で確認したい。",
      marketValue: "consumer platformのdistribution strategy、executive negotiation、revenue share、unit economics、country P&Lを横断する実績。",
      tenureAndPromotion: "【Genba仮説】次のscopeは在籍年数より、複数surfaceで署名契約をactivationとunit economicsへつなげた成果で決まる。支持材料: 公式求人はJapan distribution roadmap、役員交渉、activation target、P&Lを同じroleへ置く。反証・留保: 日本teamの昇進・離職・level分布は非公開。面接で確認: 直近24カ月の昇進・異動・退職、次levelの定量基準は。",
      priorCompanies: "【Genba仮説】super-app、internet platform、端末、TV OS、大手小売で役員提携とP&Lを持った人が隣接する。支持材料: 求人は小売、super-app、OEM、TV platformでのsigned agreementとmulti-channel P&Lを求める。反証・留保: 直近採用者の前職分布は未公開。面接で確認: Japan teamの直近採用者の前職category、失敗しやすい背景、標準ramp期間は。",
      nextCompanies: "【Genba仮説】署名契約を利用者activationと収益へ変えた成果を残せれば、consumer platform、AI commerce、marketplace、mediaのJapan GM・APAC Partnerships leadershipへ接続しやすい。支持材料: distribution、commercial framework、unit economics、country P&Lを横断する職務構造。反証・留保: 公開alumni分布ではなく求人責任からの仮説。面接で確認: 過去の同level人材の次role、社内異動、GMへの昇格例は。",
    },
  },
  {
    id: "getyourguide-new-business-development-manager-japanese-8050667",
    companySlug: "getyourguide",
    title: "New Business Development Manager (Japanese Speaker)",
    segment: "Supplier Acquisition / Business Development",
    location: "東京",
    workStyle: "Hybrid（原則月・火・木はoffice、年30日は国外から勤務可）",
    language: "日本語native、英語proficiency",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "GetYourGuide Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/getyourguide/jobs/8050667" },
    descriptionSummary: "日本のtour・experience provider・attractionを発掘し、outreach、交渉、契約、onboardingまでのsales funnelを持ち、quota達成と供給拡大を担う。国内出張は最大25%。",
    genbaTake: "企業ITの大口商談ではなく、地域ごとの優良体験を供給者から獲得し、旅行者に買える状態まで載せるmarketplace側のfull-cycle営業。",
    compensationReality: "給与range、bonus、virtual share額は未公開。transport・fitness allowance、年30日の国外勤務、hybrid、learning budget等を記載。",
    desiredProfile: "B2B sales 3年以上、quota超過、CRM／sales enablement活用、日本語native・英語proficiency。objection handling、dataでの優先順位付け、最大25%の出張を求める。",
    careerInsights: {
      fit: "地域の観光事業者を発掘し、交渉から掲載開始まで一気通貫で持ち、供給の質と量を市場成果へ変えたい人に向く。",
      thingsToKnow: "quota、supplier数、手数料条件、平均sales cycle、既存portfolio、cancel率・品質KPI、給与・bonus、Japan team人数は未公開。面接で確認したい。",
      marketValue: "marketplace supplier acquisition、地域開拓、commercial negotiation、onboarding、portfolio qualityを横断する実績。",
      tenureAndPromotion: "【Genba仮説】次のscopeは在籍年数より、獲得数だけでなくlisting activation、予約、品質まで再現可能にした成果で決まる。支持材料: 公式求人はsupplier発掘から交渉、契約、onboarding、quota、sustainable growthまでを同じroleへ置く。反証・留保: 日本の昇進・離職・level分布は非公開。面接で確認: 直近24カ月の昇進・異動・退職、次levelの定量基準は。",
      priorCompanies: "【Genba仮説】旅行、hotel、restaurant、local marketplace、広告の新規開拓で多数の中小事業者を持った人が隣接する。支持材料: 求人はB2B sales 3年以上、data-drivenなfunnel管理、objection handling、supplier acquisition、最大25%の出張を求める。反証・留保: 日本teamの採用履歴は未公開。面接で確認: 直近採用者の前職category、担当件数、標準ramp期間は。",
      nextCompanies: "【Genba仮説】supplier acquisitionをlisting activation、予約、品質、repeatまで数字で残せれば、Travel Tech、local commerce、platform partnerships、regional sales leadershipへ接続しやすい。支持材料: 地域開拓、commercial negotiation、onboarding、marketplace供給KPIを横断する職務構造。反証・留保: 公開alumni分布ではなく求人責任からの仮説。面接で確認: Japan teamの社内異動、昇格、alumniの次roleは。",
    },
  },
];
