import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-13";

export const companies20260813WaveTwo: Company[] = [
  { slug: "wiz", name: "Wiz", category: "Cloud & AI Security / CNAPP", broadCategory: "セキュリティ・IT運用", hq: "New York, US", japanPresence: "Remote Japan / Japan field sales", hiringStatus: "積極採用", salesRoles: 1, description: "code・cloud・runtimeを共通contextで結ぶcloud security platform。日本でMid-Market Account Executiveを募集。", lastChecked: checkedAt, careersUrl: "https://www.wiz.io/careers/job/4650055006/mid-market-account-executive-japan", tags: ["Cloud Security", "CNAPP", "AI Security", "Mid-Market", "Enterprise"] },
  { slug: "dbt-labs", name: "dbt Labs", category: "Analytics Engineering / Data Infrastructure", broadCategory: "AI・データ基盤", hq: "Philadelphia, US", japanPresence: "日本語公式サイト / Remote Japan GTM", hiringStatus: "積極採用", salesRoles: 2, description: "analytics engineeringを標準化し、data transformation・quality・catalogを統合。統合後の採用ページでJapan向けBDR、Sales Director等を募集。", lastChecked: checkedAt, careersUrl: "https://www.getdbt.com/about-us/careers", tags: ["Analytics Engineering", "Data Platform", "Open Source", "BDR", "Enterprise"] },
  { slug: "gurobi", name: "Gurobi Optimization", category: "Mathematical Optimization / Decision Intelligence", broadCategory: "AI・データ基盤", hq: "Beaverton, US", japanPresence: "Gurobi Japan / Tokyo-Remote", hiringStatus: "積極採用", salesRoles: 1, description: "数理最適化で生産・物流・配分などの意思決定を支援。日本でRegional Sales Directorを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/GurobiOptimization/79a51557-6123-4373-acd7-50adc3a0cfa2", tags: ["Optimization", "Decision Intelligence", "Manufacturing", "Sales Director", "Enterprise"] },
  { slug: "neural-concept", name: "Neural Concept", category: "Engineering AI / Simulation", broadCategory: "AI・データ基盤", hq: "Lausanne, Switzerland", japanPresence: "Tokyo hybrid / Japan commercial role", hiringStatus: "積極採用", salesRoles: 1, description: "3D engineering dataとsimulationへAI copilotを組み込み、設計探索を高速化。東京でRegional Sales Directorを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/neuralconcept/9b018838-aad4-48a6-8d6b-f2a544e0fbed", tags: ["Engineering AI", "Simulation", "Manufacturing", "Automotive", "Sales Director"] },
  { slug: "patch", name: "Patch", category: "Climate Finance / Environmental Markets", broadCategory: "コマース・業界特化", hq: "San Francisco, US", japanPresence: "Tokyo remote / APAC market entry", hiringStatus: "積極採用", salesRoles: 1, description: "carbon credit等のenvironmental marketをtechnologyとmarket expertiseで接続。東京でAPAC初のEnterprise AEを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/patch.io/1d73e679-d6f7-42c1-9545-74c31e97e7da", tags: ["Climate Tech", "Carbon Markets", "APAC", "Founding AE", "Enterprise"] },
  { slug: "veeva", name: "Veeva Systems", category: "Life Sciences Industry Cloud", broadCategory: "コマース・業界特化", hq: "Pleasanton, US", japanPresence: "Veeva Japan / Tokyo・Osaka", hiringStatus: "積極採用", salesRoles: 2, description: "life sciencesのR&D・quality・commercial dataとworkflowをindustry cloudで統合。日本でMedTech向けAccount Partner等を募集。", lastChecked: checkedAt, careersUrl: "https://jobs.lever.co/veeva?location=Japan+-+Tokyo", tags: ["Life Sciences", "Industry Cloud", "MedTech", "Account Partner", "Enterprise"] },
  { slug: "lakera", name: "Lakera", category: "AI Security / LLM Guardrails", broadCategory: "セキュリティ・IT運用", hq: "Zurich, Switzerland", japanPresence: "Remote Japan / Tokyo preferred", hiringStatus: "積極採用", salesRoles: 1, description: "LLM application・agentをprompt attackやunsafe outputから守るAI security platform。日本でEnterprise AEを募集。", lastChecked: checkedAt, careersUrl: "https://jobs.ashbyhq.com/lakera.ai/150abd1d-60a3-49ce-87b1-7a61806ab56e", tags: ["AI Security", "LLM", "Guardrails", "Japan Build", "Enterprise"] },
  { slug: "tines", name: "Tines", category: "Workflow Automation / Security Operations", broadCategory: "業務自動化・コラボレーション", hq: "Dublin, Ireland", japanPresence: "日本法人・国内拠点・Japan求人を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "security・IT team向けにno-code workflowとAIを提供。Australiaを含むregional展開からJapan進出条件を継続観測。", lastChecked: checkedAt, careersUrl: "https://www.tines.com/careers/", tags: ["日本未進出", "Automation", "Security Operations", "AI", "APAC"], entryStatus: "not-entered" },
  { slug: "attio", name: "Attio", category: "AI-Native CRM", broadCategory: "CRM・顧客体験", hq: "London, UK", japanPresence: "日本法人・国内拠点・Japan求人を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "柔軟なdata modelとautomationを備えるAI-native CRM。欧米での成長からJapan進出条件を継続観測。", lastChecked: checkedAt, careersUrl: "https://attio.com/careers", tags: ["日本未進出", "CRM", "AI", "PLG", "GTM"], entryStatus: "not-entered" },
  { slug: "retool", name: "Retool", category: "Internal Software / AI App Platform", broadCategory: "業務自動化・コラボレーション", hq: "San Francisco, US", japanPresence: "日本法人・国内拠点・Japan求人を確認できず", hiringStatus: "継続観測", salesRoles: 0, description: "enterprise dataへ接続するinternal app・workflow・agent基盤。豪州Komatsu事例はあるがJapan local体制は未確認。", lastChecked: checkedAt, careersUrl: "https://retool.com/careers", tags: ["日本未進出", "Internal Tools", "AI Agents", "Low Code", "Enterprise"], entryStatus: "not-entered" },
];

type JobSeed = {
  slug: string; title: string; segment: string; location: string; workStyle: string; language: string; url: string;
  summary: string; take: string; profile: string; fit: string; marketValue: string; compensation?: string;
};

const jobSeeds: JobSeed[] = [
  { slug: "wiz", title: "Mid-Market Account Executive, Japan", segment: "Mid-Market / Cloud Security", location: "Remote - Japan", workStyle: "remote", language: "公式求人で明記を確認できず", url: "https://www.wiz.io/careers/job/4650055006/mid-market-account-executive-japan", summary: "Japanのmid-marketへcloud securityをfull-cycleで提案し、CISO relationship、partner、pipeline、forecast、社内SE・CS連携を担う。", take: "脆弱性の件数ではなく、code・cloud・runtimeの関係から実際に到達可能なriskを優先し、開発速度とsecurityを同じbusiness caseへ置く。", profile: "公式求人はcloud/securityで5年以上のclosing、hunting、CISOへのadvisory、partner ecosystem、複数案件のmanagementを重視。", fit: "cloud securityの技術文脈を経営riskへ変え、自らpipelineを作るsellerに向く。", marketValue: "CNAPP、AI security、CISO sales、partner-led mid-marketの複合経験。" },
  { slug: "dbt-labs", title: "Business Development Representative, Commercial", segment: "Commercial / Business Development", location: "Remote, Japan, APAC", workStyle: "remote", language: "公式求人一覧で明記を確認できず", url: "https://www.getdbt.com/about-us/careers", summary: "Japanのcommercial accountへanalytics engineeringとdata infrastructureの課題を啓蒙し、qualified pipelineを作るbusiness development role。", take: "data toolの機能紹介ではなく、AI・analyticsへ使うdataの信頼性、変更管理、developer workflowの分断を仮説化して初回商談を作る。", profile: "公式採用ページでJapan remoteのCommercial BDRを確認。詳細な経験年数・言語要件は一覧から確定できないため補完しない。", fit: "open source communityとenterprise data buyerの間でcategory educationを磨きたい人に向く。", marketValue: "Analytics Engineering、data platform、PLG-to-enterprise、APAC pipeline creationの経験。" },
  { slug: "gurobi", title: "Regional Sales Director (Japan)", segment: "Japan Leadership / Decision Intelligence", location: "Tokyo - Remote", workStyle: "remote", language: "Business Japanese / Professional English", url: "https://jobs.lever.co/GurobiOptimization/79a51557-6123-4373-acd7-50adc3a0cfa2", summary: "日本のenterprise sales strategy、team、strategic account、pipeline、forecast、partnerを統括し、自ら重要案件も担当するsales leadership role。", take: "solver速度ではなく、生産計画・物流・配分等の意思決定を制約と目的関数へ翻訳し、利益・時間・資源利用の改善を経営案件にする。", profile: "公式求人はenterprise software sales 10年以上、people management 5年以上、日本市場でのquota実績、complex cycle、executive relationshipを求める。", fit: "製造・supply chain・analyticsの複雑な課題と営業組織buildを同時に担いたいleaderに向く。", marketValue: "Mathematical Optimization、Decision Intelligence、Japan sales leadership、SI ecosystemの経験。" },
  { slug: "neural-concept", title: "Regional Sales Director (Japan)", segment: "Japan Leadership / Engineering AI", location: "Tokyo, Japan", workStyle: "hybrid（remote 30%）", language: "Native Japanese / Fluent English", url: "https://jobs.ashbyhq.com/neuralconcept/9b018838-aad4-48a6-8d6b-f2a544e0fbed", summary: "日本の製造・automotive等へEngineering AIを提案し、revenue、strategic partnership、existing customer、new businessを率いる。", take: "AI model単体ではなく、CAE simulationとdesign iterationにかかる時間・計算資源・handoffを削減し、開発cycleそのものを変える。", profile: "公式求人はtechnical enterprise SaaS 10年以上、9〜12カ月cycle、$100K〜$1M超deal、engineering background、Japan market experienceを重視。", fit: "高度なengineering buyerへAIの事業価値を売り、country growthを作るtechnical sellerに向く。", marketValue: "Engineering AI、CAD/CAE、industrial enterprise sales、Japan market leadershipの経験。" },
  { slug: "patch", title: "Enterprise Account Executive, APAC - Tokyo", segment: "Founding AE / Climate Markets", location: "Tokyo", workStyle: "remote flexibility", language: "Japaneseはbonus要件 / 英語要件は公式求人で明記なし", url: "https://jobs.ashbyhq.com/patch.io/1d73e679-d6f7-42c1-9545-74c31e97e7da", summary: "APAC初のEnterprise AEとしてJapan中心にpipelineをゼロから作り、商社・大企業のsustainability、finance、procurement、trading、legalを束ねる。", take: "carbon creditの数量販売ではなく、claim risk、project quality、commodity調達、portfolio governanceを一つのclimate finance programへ設計する。", profile: "公式求人はenterprise B2B sales 5〜10年以上、large APAC企業のmulti-stakeholder deal、商社、carbon market、0-to-1 category creationを重視。", fit: "既存territoryを引き継ぐより、専門市場のlighthouse dealとplaybookを作りたいbuilderに向く。", marketValue: "Climate finance、environmental commodities、founding AE、APAC market makingの経験。", compensation: "求人掲載の$200K〜$300K OTEはSan Francisco based employees向け。日本のbase、OTE、equity、quotaへ転用できず、日本条件は選考で確認が必要。" },
  { slug: "veeva", title: "Account Partner - MedTech Japan", segment: "Enterprise / MedTech", location: "Japan - Tokyo", workStyle: "on-site", language: "Native Japanese / Business English", url: "https://jobs.lever.co/veeva/7d586942-3a78-45cf-a240-3a960dde4430", summary: "日本のMedTech企業へVault applicationを提案し、new business、strategic relationship、pipeline、revenue target、complex cycleを担う。", take: "generic CRMや文書管理ではなく、Clinical・Quality・Regulatory・Commercialを規制対応と患者へのspeedという共通outcomeへつなぐ。", profile: "公式求人はenterprise software sales 10年以上、MedTech関連5年以上、C-levelを含むcomplex cycle、strategic account planningを求める。", fit: "life sciencesの業務・規制知識を軸にlarge accountを長期で開拓するsellerに向く。", marketValue: "Life Sciences cloud、MedTech、regulated industry、multi-product strategic sellingの専門性。" },
  { slug: "lakera", title: "Enterprise Account Executive, Japan (Tokyo)", segment: "Enterprise / AI Security", location: "Remote Japan（Tokyo preferred）", workStyle: "hybrid / remote Japan", language: "Professional Japanese / English", url: "https://jobs.ashbyhq.com/lakera.ai/150abd1d-60a3-49ce-87b1-7a61806ab56e", summary: "日本のAI security marketでnew logo、sales strategy、partner、complex pilot、product feedback、playbookをゼロから作るEnterprise AE。", take: "prompt attack検知だけでなく、employee AI、customer-facing LLM、agent actionをどこまで許可し、どのguardrailとtestで安全にproduction化するかを売る。", profile: "公式求人はB2B sales 5年以上、日本市場、early-stage build、AI/LLMまたはcybersecurity、distribution・marketplace partner、complex dealを重視。", fit: "未成熟なAI security categoryで顧客教育とsales processを同時に作りたいsellerに向く。", marketValue: "AI security、LLM guardrails、Japan GTM、partner、technical enterprise saleの経験。" },
];

export const jobs20260813WaveTwo: Job[] = jobSeeds.map((seed) => ({
  id: `${seed.slug}-${seed.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")}`,
  companySlug: seed.slug, title: seed.title, segment: seed.segment, location: seed.location, workStyle: seed.workStyle, language: seed.language,
  firstSeen: checkedAt, lastChecked: checkedAt, source: { label: `${seed.slug} official careers`, url: seed.url }, descriptionSummary: seed.summary, genbaTake: seed.take,
  compensationReality: seed.compensation ?? "日本のbase、OTE、equity、quota、acceleratorは公開求人で確認できない。選考でramp、credit rule、達成率まで確認したい。",
  desiredProfile: seed.profile,
  careerInsights: { fit: seed.fit, thingsToKnow: "日本ARR、顧客数、ramped seller達成率、平均ACV、sales cycle、担当社数は非公開。", marketValue: seed.marketValue, tenureAndPromotion: "日本teamの平均在籍年数、離職率、昇進実績は公開情報で確認できない。", priorCompanies: "公開profileの十分な母数は未確認。求人要件に近いenterprise software、SaaS、各専門categoryの経験者が候補になる。", nextCompanies: "公開集計は未確認。担当categoryでの定量成果は、隣接するenterprise softwareのAE、partner、sales leadershipへつながり得る（仮説）。" },
}));
