import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-14";

export const companies20260814WaveTwo: Company[] = [
  {
    slug: "shopify",
    name: "Shopify",
    category: "Unified Commerce / Ecommerce Platform",
    broadCategory: "CRM・顧客体験",
    hq: "Ottawa, Canada",
    japanPresence: "日本語公式サイト / 日本向けRemote GTM / 国内導入事例",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "millionsのmerchantを175カ国超で支えるcommerce platform。国内574件の導入事例を掲載し、日本でProduct Partnerships Leadを募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.shopify.com/careers/product-partnerships-lead_d9993b7d-d973-409c-9da3-0c8d48cff776",
    tags: ["認知企業", "Commerce", "Ecommerce", "Partner", "Enterprise", "Japan"],
  },
  {
    slug: "zilliz",
    name: "Zilliz",
    category: "Vector Database / AI Data Infrastructure",
    broadCategory: "AI・データ基盤",
    hq: "Redwood City, US",
    japanPresence: "Tokyo hybrid / Japan founding team / 日本語公式サイト",
    hiringStatus: "積極採用",
    salesRoles: 2,
    description: "Milvusを起点にproduction AI向けvector databaseを提供。東京でEnterprise AEとFounding Field Engineerを同時募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.lever.co/zilliz",
    tags: ["Vector Database", "AI Infrastructure", "Open Source", "Founding Team", "Enterprise", "Japan"],
  },
  {
    slug: "airtable",
    name: "Airtable",
    category: "No-code App Platform / AI Workflows",
    broadCategory: "業務自動化・コラボレーション",
    hq: "San Francisco, US",
    japanPresence: "日本法人・Tokyo拠点・Japan求人を確認できず",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "50万組織が利用するno-code app platform。SydneyにAPAC拠点を持つ一方、日本拠点・専任求人・日本語UIは未確認。",
    lastChecked: checkedAt,
    careersUrl: "https://job-boards.greenhouse.io/airtable",
    tags: ["日本未進出", "No-code", "AI Workflows", "Enterprise", "Sydney", "APAC"],
    entryStatus: "not-entered",
  },
];

export const jobs20260814WaveTwo: Job[] = [
  {
    id: "shopify-product-partnerships-lead-japan",
    companySlug: "shopify",
    title: "Product Partnerships Lead",
    segment: "Strategic Partnerships / Commerce Ecosystem",
    location: "Japan",
    workStyle: "remote",
    language: "日本語（native）/ 英語要件は明記なし",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: {
      label: "Shopify Careers",
      url: "https://www.shopify.com/careers/product-partnerships-lead_d9993b7d-d973-409c-9da3-0c8d48cff776",
    },
    descriptionSummary: "日本のmarketplace、決済、物流、marketing、vertical SaaSのstrategic technology partnerを開拓し、executive relationship、契約交渉、integration、共同roadmapを推進する。",
    genbaTake: "partner数を増やす役割ではなく、日本固有のcommerce要件をShopifyのproduct roadmapへ戻し、merchantの選択肢と成功をecosystemで増幅するplatform sale。Product・Sales・Legal・Financeをまたぐ合意形成が核になる。",
    compensationReality: "日本のbase、bonus、equity、target、partner-sourced revenueの評価方法は公式求人で確認できない。選考ではcommercial KPIとproduct KPIの比重、契約credit、出張頻度を確認したい。",
    desiredProfile: "公式求人はcommerce・technology・SaaS partnershipの実績、複雑なmulti-stakeholder契約、日本のcommerce・SaaS市場と商習慣、API integrationへの理解、native Japanese、国内networkを重視。",
    careerInsights: {
      fit: "日本のcommerce ecosystemで、単独製品の販売よりplatform価値をpartnerと共同で作りたい人に向く。",
      thingsToKnow: "partner portfolio、年間契約件数、merchant impactの定義、product roadmapへの決定権、Japan team規模は非公開。",
      marketValue: "Commerce platform、strategic partnerships、API ecosystem、cross-border product localizationを横断する経験。",
      tenureAndPromotion: "LinkedIn公開プロフィール（日本GTMの非ユニーク職種、2026年8月、経歴を確認できた4件）では、Shopify在籍は1年未満から4年超まで幅がある。Partnershipsで4年超在籍した例と、SDRで約1年後にMid-MarketからEnterpriseへ担当拡張した例を確認でき、外部採用だけでなく社内でscopeを広げる経路もある。【Genba仮説・確度: 中】Partnershipsはpartner資産が蓄積するため複数年在籍の合理性が高いが、日本teamの管理職枠は限られ、昇進より担当拡張か他社leadershipへの転職が増えやすい。支持材料: 長期在籍例とSDRの内部異動例が同時にあり、求人もProduct・Sales・Legal・Financeをまたぐscope拡張型である。反証・留保: 4件の小標本で平均在籍年数・離職率は算出できず、職種別の昇進率も不明。面接で確認: 直近24か月のPartnerships IC人数、昇進・担当拡張・退職の件数と、次のlevelの要件は何か。",
      priorCompanies: "LinkedIn公開プロフィール（日本GTMの非ユニーク職種、2026年8月、前職を確認できた3件）では、入社元・経験領域に、hyperscalerのpartner program、collaboration SaaSのBusiness Development、国内大手ITのcorporate strategy・alliance、AdTechのSDRが見られた。社名の単純な共通性より、ecosystem構築、共同GTM、法人新規開拓、日本企業との複雑な合意形成が共通項。【Genba仮説・確度: 中】本求人ではCommerce専業出身に限らず、platform企業・SI・consulting・FinTechでAPI提携とpartner revenueを作った人材が有力。支持材料: 実測サンプルの職歴がpartner／BD／allianceに集中し、求人もmarketplace・payments・logistics・vertical SaaSとの複雑な契約を求める。反証・留保: 3件の小標本で採用全体の分布ではなく、公開プロフィールの偏りもある。面接で確認: 直近のPartnerships採用者の前職category上位3つと、Commerce未経験者がrampするまでの期間は何か。",
      nextCompanies: "日本の非ユニークなPartnerships職に絞ったLinkedIn公開プロフィールでは、転職先を傾向として扱える母数を2026年8月時点で確保できない。【Genba仮説・確度: 中】merchant impact、partner-sourced revenue、API integration、複雑契約を定量化できれば、Commerce・FinTech・platform企業のPartnerships Lead、Channel Director、Japan事業開発へ接続しやすい。支持材料: 本求人の成果がpartner契約数ではなくproduct roadmapとmerchant successまで及び、隣接platformでも再現可能な経験になる。反証・留保: 実際の転職先集計ではなく、Shopify固有のremote組織・product operating modelが他社でそのまま評価されるとは限らない。面接で確認: 直近24か月の退職者が選んだ次のrole categoryと、社内でAPAC scopeまたはleadershipへ進んだ実例はあるか。",
    },
  },
  {
    id: "zilliz-enterprise-account-executive-japan",
    companySlug: "zilliz",
    title: "Enterprise Account Executive - Japan",
    segment: "Enterprise / AI Data Infrastructure",
    location: "Tokyo",
    workStyle: "hybrid",
    language: "公式求人で明記なし",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: {
      label: "Zilliz Careers (Lever)",
      url: "https://jobs.lever.co/zilliz/8144e236-2836-4980-92cf-b6501ce0f81c",
    },
    descriptionSummary: "outboundとinbound qualificationからpipelineを作り、Marketing・Solutions Architect・Partnerと連携。MEDDICとsolution sellingでbusiness impactを定量化し、engagementからclose、ACV/TCV forecast、既存拡張まで担う。",
    genbaTake: "vector databaseのbenchmarkを売るのではなく、RAG・semantic search・AI agentをPoCからproductionへ移す際のlatency、reliability、governance、運用TCOをbusiness caseにする。developer起点のMilvus利用をEnterprise契約へ変える力が問われる。",
    compensationReality: "日本のbase、OTE、pay mix、quota、accelerator、equityは公式求人で確認できない。open-source由来とinboundの比率、new logoとexpansionのcredit、rampを確認したい。",
    desiredProfile: "公式求人はdatabase・data infrastructure営業5年以上、startup・high-growth環境、自律性、open sourceとAI/MLへの関心、complex Enterprise saleを重視。日本語・英語要件は明記なし。",
    careerInsights: {
      fit: "technical buyerとexecutive buyerをつなぎ、日本のAI infrastructure categoryを立ち上げたいhunterに向く。",
      thingsToKnow: "Japan ARR、active customer、平均ACV、sales cycle、territory、quota達成率、Milvus-to-Cloud転換率は非公開。",
      marketValue: "Vector Database、RAG、open-source commercialisation、MEDDIC、founding GTMの経験。",
      tenureAndPromotion: "Japan founding teamの平均在籍年数、離職率、昇進実績は公開情報で確認できない。",
      priorCompanies: "個人profileの十分な集計は未確認。求人要件からdatabase、data platform、cloud infrastructureのEnterprise sellerが隣接する。",
      nextCompanies: "公開集計は未確認。PoC-to-productionとdeveloper-to-executive saleを成果化できればAI・data infrastructureのStrategic AEやCountry leadershipへつながり得る（仮説）。",
    },
  },
  {
    id: "zilliz-founding-field-engineer-japan",
    companySlug: "zilliz",
    title: "Founding Field Engineer, Japan",
    segment: "Customer Engineering / Production Adoption",
    location: "Tokyo",
    workStyle: "hybrid",
    language: "日本語（native / fluent）・英語（business）",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: {
      label: "Zilliz Careers (Lever)",
      url: "https://jobs.lever.co/zilliz/9f2e2541-9945-47a9-bca7-6d123128ca50",
    },
    descriptionSummary: "Japan founding teamのengineering側窓口としてtechnical discovery、PoC、onboarding、go-live、production adoption、post-sales、escalationを担当し、日本固有の知見とproduct feedbackをEngineeringへ戻す。",
    genbaTake: "traditionalなpre-sales専任ではなく、顧客のdatabase・distributed system・AI workloadへ入り、評価からproduction successまで技術責任を持つrole。日本の最初期顧客からreference architectureと再現可能な導入playbookを作る。",
    compensationReality: "日本のbase、bonus、equity、on-call、出張、commercial targetは公式求人で確認できない。PoC件数、同時担当社数、post-sales ownership、escalation時間を確認したい。",
    desiredProfile: "公式求人はdatabase・distributed system・cloud・Kubernetes・storage・SREのhands-on経験、production reliability、troubleshooting、顧客communication、business sense、日本語、business Englishを重視。",
    careerInsights: {
      fit: "core engineeringの深さを保ちながら顧客に近づき、日本市場のproduct fitを作りたいengineerに向く。",
      thingsToKnow: "AE・SA・Supportとの境界、custom engineering比率、success metric、escalation rotation、Japan固有開発の裁量は非公開。",
      marketValue: "Production AI、distributed database、field engineering、PoC-to-production、founding customer experienceを横断する経験。",
      tenureAndPromotion: "新設roleのため、日本での昇進実績・平均在籍年数はまだ公開情報で確認できない。",
      priorCompanies: "公式求人からdatabase engineer、SRE、platform engineer、Solutions Architect、Technical Account Manager等が隣接する。個人profileの傾向は断定しない。",
      nextCompanies: "公開集計は未確認。production adoptionとproduct feedbackを成果化できればAI infrastructureのField Engineering、Solutions leadership、Product Engineeringへ広げやすい（仮説）。",
    },
  },
];
