import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-09-04";

export const companies20260904Daily: Company[] = [
  {
    slug: "canva",
    name: "Canva",
    category: "ビジュアルコミュニケーション・AIデザイン",
    broadCategory: "業務自動化・コラボレーション",
    hq: "シドニー（オーストラリア）",
    japanPresence: "Canva Japan株式会社・東京。gBizINFOの事業所被保険者数16人",
    hiringStatus: "積極採用",
    salesRoles: 2,
    description: "デザイン、動画、文書、Web、ブランド管理をAIと共同編集で一体化。日本で販売パートナー営業と成長マーケティングを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.lifeatcanva.com/en/jobs/",
    tags: ["Anchor", "AI", "Design", "Collaboration", "Enterprise", "Tokyo"],
  },
  {
    slug: "monotype",
    name: "Monotype",
    category: "フォント管理・ブランドガバナンス",
    broadCategory: "業務自動化・コラボレーション",
    hq: "ウォバーン（米国）",
    japanPresence: "Monotype株式会社・東京。gBizINFOの事業所被保険者数78人",
    hiringStatus: "積極採用",
    salesRoles: 6,
    description: "HelveticaやTimes New Romanを含む書体資産を、探索、配布、ライセンス、ブランド統制まで一元管理。東京で営業・顧客成功6職種を公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://monotype.wd1.myworkdayjobs.com/olapic",
    tags: ["Font", "Brand Governance", "Digital Asset", "Enterprise", "Tokyo"],
  },
  {
    slug: "supabase",
    name: "Supabase",
    category: "Postgres開発基盤・Backend as a Service",
    broadCategory: "AI・データ基盤",
    hq: "サンフランシスコ（米国）",
    japanPresence: "日本法人・国内拠点・日本専任公式求人は未確認。全社は完全リモート",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "Postgresを中心にデータベース、認証、ストレージ、リアルタイム、APIをまとめるオープンソースの開発基盤。",
    lastChecked: checkedAt,
    careersUrl: "https://supabase.com/careers",
    entryStatus: "not-entered",
    tags: ["Postgres", "Database", "Developer Platform", "Open Source", "AI", "Pre-entry"],
  },
];

type JobDraft = Pick<Job, "id" | "companySlug" | "title" | "segment" | "location" | "workStyle" | "language" | "source" | "descriptionSummary" | "genbaTake" | "desiredProfile">;

function makeJob(draft: JobDraft): Job {
  return {
    ...draft,
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    compensationReality: "日本の給与、変動報酬、株式、目標、担当範囲は公式求人で十分に確認できない。提示条件と評価方法を面接で確認したい。",
    careerInsights: {
      fit: `${draft.segment}で、顧客や市場の課題を確認し、複数部門を動かして成果まで担いたい人に向く。`,
      thingsToKnow: "担当範囲、評価指標、支援体制、給与・賞与・株式、日本組織の職種別人数は十分に公開されていない。面接で確認したい。",
      marketValue: `${draft.segment}の成果を商談、導入、利用、顧客KPIで定量化できれば、隣接する企業向けソフトウェアの同職種・上位職へ再現性を説明しやすい。`,
      tenureAndPromotion: `【Genba仮説】${draft.segment}では在籍年数より、担当範囲の成果と再利用できる実行の型が次の職位を左右する。支持材料: 公式求人は顧客成果と部門横断の実行を求める。反証・留保: 日本の昇進率・離職率・職位別基準は未公開で、公開された個人別データではなく職務構造からの仮説。面接で確認: 直近24カ月の昇進・異動・退職と次の職位に必要な定量成果は。`,
      priorCompanies: `【Genba仮説】${draft.segment}に近い顧客課題、複数の意思決定者、目標責任を持った人材が隣接する。支持材料: 公式求人は社名より顧客の意思決定を前へ進めた経験を重視する。反証・留保: 日本の採用者を同じ条件で十分に集計できず、特定企業からの採用傾向を断定しない。面接で確認: 直近採用者の前職領域、共通スキル、立ち上がり期間は。`,
      nextCompanies: `【Genba仮説】${draft.segment}の成果を数字で残せれば、同領域の専門職、より大きな顧客層、Lead・管理職へ広げやすい。支持材料: 公式求人が成果責任と部門横断の実行を置く。反証・留保: 公開された転職先分布ではなく職務構造からの仮説で、実際の移動先は個人の成果と募集状況で変わる。面接で確認: 退職者の次職種と社内で担当範囲を広げた実例は。`,
    },
  };
}

export const jobs20260904Daily: Job[] = [
  makeJob({
    id: "canva-japan-channel-account-manager-6000000001187132",
    companySlug: "canva",
    title: "Japan Channel Account Manager",
    segment: "Channel Sales / Enterprise Design",
    location: "東京都",
    workStyle: "Hybrid。出社日数は公式求人で確認できず",
    language: "日本語・英語での業務遂行",
    source: { label: "Canva Careers", url: "https://www.lifeatcanva.com/en/jobs/6000000001187132/japan-channel-account-manager/" },
    descriptionSummary: "SoftBank C&Sと販売会社網を担当し、新規パートナー開拓、教育、共同案件、予測、売上目標を通じて日本でのCanva導入を広げる。",
    genbaTake: "販売会社数を増やすだけでなく、利用部門、ブランド統制、権限、作成時間の改善を共同提案へ変え、販売会社が自走できる型を作る役割。",
    desiredProfile: "公式求人は日本の販売網を育てた経験、SoftBank C&S等との協業、売上予測と目標管理、顧客向け営業、日本語・英語を重視する。",
  }),
  makeJob({
    id: "canva-japan-growth-marketing-lead-6000000001289995",
    companySlug: "canva",
    title: "Japan Growth Marketing Lead",
    segment: "Growth Marketing / Japan",
    location: "東京都",
    workStyle: "Hybrid。渋谷オフィスを拠点とする",
    language: "日本語ネイティブ級、英語ビジネス級",
    source: { label: "Canva Careers", url: "https://www.lifeatcanva.com/en/jobs/6000000001289995/japan-growth-marketing-lead/" },
    descriptionSummary: "認知から獲得、利用開始、継続、売上まで日本の成長施策を一貫して持ち、広告運用、実験、予算配分、効果測定を担う。",
    genbaTake: "広告獲得だけでなく、日本の利用者行動を登録・継続・有料化までつなぎ、増分効果と収益性で投資判断を変える成長責任。",
    desiredProfile: "公式求人は日本のデジタル広告運用、実験設計、CAC・CPA・ROAS・転換率の改善、予算管理、日本語・英語を重視する。",
  }),
  makeJob({
    id: "monotype-senior-manager-enterprise-sales-r0004683",
    companySlug: "monotype",
    title: "Senior Manager, Enterprise Sales",
    segment: "Enterprise Sales Leadership / Brand Governance",
    location: "東京都",
    workStyle: "Hybrid。週3日出社",
    language: "日本語・英語での業務遂行",
    source: { label: "Monotype Careers (Workday)", url: "https://monotype.wd1.myworkdayjobs.com/en-US/olapic/job/Tokyo/Senior-Manager--Enterprise-Sales_R0004683-1" },
    descriptionSummary: "日本の大規模案件へ入りながら、営業戦略、案件品質、予測精度、営業手法、育成を通じてエンタープライズ営業組織を強化する。",
    genbaTake: "個人案件の管理に閉じず、ブランド・IT・法務・調達を跨ぐ複雑商談の勝率を上げ、日本で再利用できる営業基盤を作る管理職。",
    desiredProfile: "公式求人は複雑な企業向け営業、大型案件の戦略支援、MEDDPICC、チーム指導、英語でのグローバル連携を重視する。",
  }),
  makeJob({
    id: "monotype-enterprise-account-executive-japan-r0004832",
    companySlug: "monotype",
    title: "Enterprise Account Executive, Japan",
    segment: "Enterprise Sales / New Logo",
    location: "東京都",
    workStyle: "Hybrid。出社日数は公式求人で確認できず",
    language: "日本語ネイティブ級、英語での会議・読み書き",
    source: { label: "Monotype Careers (Workday)", url: "https://monotype.wd1.myworkdayjobs.com/en-US/olapic/job/Tokyo/Enterprise-Account-Executive--Japan_R0004832" },
    descriptionSummary: "日本の大企業へ新規開拓を行い、ブランド、マーケティング、IT、デザイン、調達、法務を束ねて提案から契約まで担う。",
    genbaTake: "書体の選定ではなく、無許諾利用、ライセンス、ブランド一貫性、制作速度を経営課題へ変え、複数部門の合意を作る営業。",
    desiredProfile: "公式求人は大企業への新規開拓、複数の意思決定者を動かす提案、IT・SaaS・無形商材営業、日本語・英語を重視する。",
  }),
  makeJob({
    id: "monotype-customer-success-manager-japan-r0004736",
    companySlug: "monotype",
    title: "Customer Success Manager, Japan",
    segment: "Customer Success / Enterprise",
    location: "東京都",
    workStyle: "Hybrid。顧客訪問の出張20〜30%",
    language: "日本語ネイティブ級、英語ビジネス級",
    source: { label: "Monotype Careers (Workday)", url: "https://monotype.wd1.myworkdayjobs.com/en-US/olapic/job/Tokyo/Customer-Success-Manager--Japan_R0004736" },
    descriptionSummary: "日本の企業顧客を導入、利用定着、教育、業務レビュー、更新、拡大まで担当し、利用状況と顧客成果を改善する。",
    genbaTake: "関係維持ではなく、書体の配布・利用・権利管理を日常業務へ定着させ、リスク低減と制作効率を更新・拡大の根拠にする役割。",
    desiredProfile: "公式求人は顧客成功・アカウント管理、企業顧客、利用データと健全性指標、部門横断の問題解決、日本語・英語を重視する。",
  }),
  makeJob({
    id: "monotype-enterprise-sales-executive-r0004302",
    companySlug: "monotype",
    title: "Enterprise Sales Executive",
    segment: "Enterprise Sales / Fonts & Brand",
    location: "東京都",
    workStyle: "柔軟な勤務制度。出社頻度は公式求人で確認できず",
    language: "日本語・英語での業務遂行",
    source: { label: "Monotype Careers (Workday)", url: "https://monotype.wd1.myworkdayjobs.com/en-US/olapic/job/Tokyo/Enterprise-Sales-Executive_R0004302-1" },
    descriptionSummary: "大企業とデザイン会社へ新規・既存の提案を行い、担当地域計画、見込み顧客開拓、提案、交渉、CRM管理を担う。",
    genbaTake: "書体数を売るのではなく、ブランド接点ごとの利用実態とライセンスリスクを可視化し、管理・制作の共通基盤へ変える営業。",
    desiredProfile: "公式求人は法人営業、新規開拓、目標達成、ブランド・広告・デザインまたはソフトウェア領域、日本語・英語を重視する。",
  }),
  makeJob({
    id: "monotype-enterprise-sales-executive-r0004301",
    companySlug: "monotype",
    title: "Enterprise Sales Executive",
    segment: "Enterprise Sales / Fonts & Brand",
    location: "東京都",
    workStyle: "柔軟な勤務制度。出社頻度は公式求人で確認できず",
    language: "日本語・英語での業務遂行",
    source: { label: "Monotype Careers (Workday)", url: "https://monotype.wd1.myworkdayjobs.com/en-US/olapic/job/Tokyo/Enterprise-Sales-Executive_R0004301" },
    descriptionSummary: "企業顧客・デザイン会社の開拓と既存拡大を担い、フォントとブランド技術の提案、見積、交渉、受注まで進める。",
    genbaTake: "制作現場だけでなく、ブランド、IT、法務、調達の要求を一つにし、書体利用の速度と統制を同時に改善する営業。",
    desiredProfile: "公式求人は法人営業、担当地域計画、見込み顧客開拓、目標達成、日本語・英語での提案と交渉を重視する。",
  }),
  makeJob({
    id: "monotype-enterprise-account-executive-r0004300",
    companySlug: "monotype",
    title: "Enterprise Account Executive",
    segment: "Enterprise Sales / Fonts & Brand",
    location: "東京都",
    workStyle: "柔軟な勤務制度。出社頻度は公式求人で確認できず",
    language: "日本語・英語での業務遂行",
    source: { label: "Monotype Careers (Workday)", url: "https://monotype.wd1.myworkdayjobs.com/en-US/olapic/job/Tokyo/Enterprise-Account-Executive_R0004300" },
    descriptionSummary: "日本の大企業とデザイン会社へ新規開拓を行い、ブランド・制作・IT・調達の関係者へ提案し、契約と既存拡大を担う。",
    genbaTake: "有名書体の認知を入口に、分散したファイル、利用権、制作手順、ブランド基準を企業横断の運用へ変える営業。",
    desiredProfile: "公式求人は法人営業、企業顧客の開拓、提案・交渉、CRMによる案件管理、ソフトウェア・広告・デザイン経験、日本語・英語を重視する。",
  }),
];
