import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-10-07";

export const companies20261007Daily: Company[] = [
  {
    slug: "blackpanda",
    name: "Blackpanda",
    category: "サイバーインシデント対応・サイバー保険",
    broadCategory: "セキュリティ・IT運用",
    hq: "シンガポール",
    japanPresence: "Blackpanda Japan株式会社。東京拠点と、日本を勤務地とする公式求人4件を確認",
    hiringStatus: "積極採用",
    salesRoles: 2,
    description: "24時間365日のサイバー緊急対応を、定額契約、診断、保険まで含むIR-1として提供。日本で営業、顧客成功、インシデント対応を採用。",
    lastChecked: checkedAt,
    careersUrl: "https://blackpanda.bamboohr.com/careers",
    tags: ["Cyber Incident Response", "DFIR", "Cyber Insurance", "Japan", "Tokyo"],
  },
  {
    slug: "streamhub",
    name: "Streamhub",
    category: "動画・広告オーディエンス計測",
    broadCategory: "AI・データ基盤",
    hq: "ロンドン（英国）",
    japanPresence: "東京オフィスを運営。東京勤務の公式求人2件を確認し、会社公式求人は全社20〜50人規模と記載",
    hiringStatus: "採用中",
    salesRoles: 2,
    description: "放送・配信動画の視聴データを統合し、コンテンツ、広告、会員施策の判断へ変える分析基盤。東京で営業開拓と技術顧客支援を募集。",
    lastChecked: checkedAt,
    careersUrl: "https://streamhub.breezy.hr/",
    tags: ["Video Analytics", "Audience Data", "Advertising", "Broadcasters", "Tokyo"],
  },
  {
    slug: "solace",
    name: "Solace",
    category: "リアルタイムデータ配信・イベント駆動基盤",
    broadCategory: "AI・データ基盤",
    hq: "オタワ（カナダ）",
    japanPresence: "日本法人・常設拠点・国内求人は未確認。シンガポールで日本・韓国市場専任の初のSDR求人を確認",
    hiringStatus: "継続観測",
    salesRoles: 1,
    description: "企業内のアプリ、機器、クラウド、AIエージェント間でリアルタイムにデータを配信するイベント駆動基盤。日本市場専任の営業開拓を採用。",
    lastChecked: checkedAt,
    careersUrl: "https://solace.com/careers/",
    tags: ["日本進出兆候", "Event Mesh", "Real-time Data", "Enterprise AI", "Singapore"],
    entryStatus: "pre-entry-signal",
  },
];

type JobDraft = Pick<Job, "id" | "companySlug" | "title" | "segment" | "location" | "workStyle" | "language" | "source" | "descriptionSummary" | "genbaTake" | "desiredProfile" | "compensationReality">;

function makeJob(draft: JobDraft): Job {
  return {
    ...draft,
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    careerInsights: {
      fit: `${draft.segment}で、専門知識を顧客・組織の具体的な成果へ変えたい人に向く。`,
      thingsToKnow: "目標、達成率、担当範囲、国内支援体制、評価・昇進、報酬構成は公開情報だけでは十分に分からない。",
      marketValue: `${draft.segment}の成果を商談、導入、運用、顧客KPIで定量化できれば、隣接する海外テクノロジー企業へ再現性を説明しやすい。`,
      tenureAndPromotion: "在籍年数だけでなく、担当拡張、顧客・組織成果、再利用できる実行の型が次の役割の土台になる。",
      priorCompanies: "企業向け営業、顧客支援、技術運用、複数の意思決定者を動かす業務の経験が隣接する。",
      nextCompanies: "担当市場と成果を数字で残せれば、企業営業、地域リード、顧客成功、技術責任者へ広げやすい。",
    },
  };
}

export const jobs20261007Daily: Job[] = [
  makeJob({
    id: "blackpanda-junior-incident-responder-51",
    companySlug: "blackpanda",
    title: "Junior Incident Responder",
    segment: "Japan Cyber Incident Response",
    location: "Japan",
    workStyle: "公式求人で出社・リモート条件の詳細は未確認",
    language: "日本語・英語の具体的な水準は公式求人で要確認",
    source: { label: "Blackpanda Careers (BambooHR)", url: "https://blackpanda.bamboohr.com/careers/51" },
    descriptionSummary: "サイバー攻撃を受けた顧客の初動、証拠保全、調査、封じ込め、復旧を上位担当者と進める。",
    genbaTake: "平時の監視ではなく、被害が進む局面で事実を集め、顧客の事業継続へつなぐインシデント対応職。",
    desiredProfile: "デジタルフォレンジック、セキュリティ運用、ログ分析、顧客との緊急時コミュニケーションが隣接する。",
    compensationReality: "給与、待機・夜間対応、手当、評価KPI、担当件数は公開求人で確認できない。",
  }),
  makeJob({
    id: "blackpanda-senior-incident-responder-56",
    companySlug: "blackpanda",
    title: "Senior Incident Responder",
    segment: "Japan Senior Cyber Incident Response",
    location: "Japan",
    workStyle: "公式求人で出社・リモート条件の詳細は未確認",
    language: "日本語・英語の具体的な水準は公式求人で要確認",
    source: { label: "Blackpanda Careers (BambooHR)", url: "https://blackpanda.bamboohr.com/careers/56" },
    descriptionSummary: "重大なサイバーインシデントの調査方針、顧客への判断支援、技術品質、若手支援を担う。",
    genbaTake: "解析だけでなく、限られた情報から復旧優先順位と経営判断を支え、対応品質を再利用できる型へ変える役割。",
    desiredProfile: "インシデント対応、フォレンジック、マルウェア・ログ分析、顧客説明、チーム指導が隣接する。",
    compensationReality: "給与、待機・夜間対応、手当、評価KPI、部下人数は公開求人で確認できない。",
  }),
  makeJob({
    id: "blackpanda-customer-success-manager-67",
    companySlug: "blackpanda",
    title: "Customer Success Manager",
    segment: "Japan Cybersecurity Customer Success",
    location: "Japan",
    workStyle: "公式求人で出社・リモート条件の詳細は未確認",
    language: "日本語・英語の具体的な水準は公式求人で要確認",
    source: { label: "Blackpanda Careers (BambooHR)", url: "https://blackpanda.bamboohr.com/careers/67" },
    descriptionSummary: "契約顧客の導入、平時の準備、診断結果の活用、更新・拡大を支え、緊急時に対応チームへつなぐ。",
    genbaTake: "利用促進だけでなく、事故前の準備を整え、事故時に契約価値が発揮される状態を顧客と作る顧客成功職。",
    desiredProfile: "企業向け顧客成功、サイバーセキュリティ、経営・IT部門との調整、更新・拡大の経験が隣接する。",
    compensationReality: "給与、変動給、更新率、担当社数、緊急時の関与範囲は公開求人で確認できない。",
  }),
  makeJob({
    id: "blackpanda-partner-sales-manager-73",
    companySlug: "blackpanda",
    title: "Partner Sales Manager",
    segment: "Japan Cybersecurity Partner Sales",
    location: "Japan",
    workStyle: "公式求人で出社・リモート条件の詳細は未確認",
    language: "日本語・英語の具体的な水準は公式求人で要確認",
    source: { label: "Blackpanda Careers (BambooHR)", url: "https://blackpanda.bamboohr.com/careers/73" },
    descriptionSummary: "販売・保険・セキュリティのパートナーを開拓し、共同提案、案件化、売上拡大を担う。",
    genbaTake: "単純な再販管理ではなく、緊急対応、定額契約、保険を日本の販売網で届ける市場設計職。",
    desiredProfile: "セキュリティのパートナー営業、共同案件、経営層提案、販売計画の経験が隣接する。",
    compensationReality: "給与、変動給、目標、達成率、担当パートナー数は公開求人で確認できない。",
  }),
  makeJob({
    id: "streamhub-account-manager-business-development-12576e9b1cf801",
    companySlug: "streamhub",
    title: "Account Manager / Business Development",
    segment: "Japan Media Data Sales",
    location: "Tokyo",
    workStyle: "Hybrid。週3日出社",
    language: "日本語は母語水準。英語は社内連携に必要な業務水準",
    source: { label: "Streamhub Careers (Breezy)", url: "https://streamhub.breezy.hr/p/12576e9b1cf801-account-manager-business-development" },
    descriptionSummary: "放送局、配信事業者、広告会社へ分析・データ基盤を提案し、既存顧客の拡大と新規案件を担う。",
    genbaTake: "分析画面の販売ではなく、視聴データを編成、広告、会員施策の意思決定へ組み込む営業開拓職。",
    desiredProfile: "企業営業4年以上、メディア・広告・データ基盤、APIやデータ処理への理解、顧客課題の構造化が重要。",
    compensationReality: "年収750万円以上を公式求人に記載。賞与、目標、達成率、担当社数、株式の付与条件は要確認。",
  }),
  makeJob({
    id: "streamhub-technical-account-manager-3647b69d9d0b01",
    companySlug: "streamhub",
    title: "Technical Account Manager",
    segment: "Japan Technical Account Management",
    location: "Tokyo",
    workStyle: "Hybrid。週3日出社",
    language: "日本語と業務上十分な英語",
    source: { label: "Streamhub Careers (Breezy)", url: "https://streamhub.breezy.hr/p/3647b69d9d0b01-technical-account-manager" },
    descriptionSummary: "顧客の視聴データ、API、分析要件を整理し、導入、利用定着、技術課題、契約拡大を一貫して支える。",
    genbaTake: "問い合わせ対応ではなく、放送・配信のデータ流通を設計し、分析が事業判断に使われるまでを持つ技術顧客責任者。",
    desiredProfile: "技術顧客支援、データ処理・API、AI、プロジェクト推進、商用拡大をつなぐ経験が重要。",
    compensationReality: "年収1,000万円以上と販売賞与を公式求人に記載。目標、担当社数、賞与比率、株式の付与条件は要確認。",
  }),
  makeJob({
    id: "solace-sdr-japanese-korean-singapore-20261007",
    companySlug: "solace",
    title: "Sales Development Representative (Japanese & Korean speaking)",
    segment: "Japan & Korea Sales Development",
    location: "シンガポール",
    workStyle: "シンガポール勤務。会社公式はハイブリッド制度を案内するが、この職種の出社頻度は要確認",
    language: "日本語・韓国語・英語とも完全な業務水準",
    source: { label: "Solace Careers", url: "https://solace.com/careers/" },
    descriptionSummary: "日本・韓国企業へ電話、メール、SNS、イベントで接点を作り、案件を見極めて営業担当との商談へつなぐ。",
    genbaTake: "既存市場の問い合わせ処理ではなく、日本・韓国専任の初の営業開拓として、誰に何をどう伝えるかから作る役割。",
    desiredProfile: "日韓英の3言語、見込み顧客開拓、企業向けソフトウェア、CRM運用、曖昧な市場での自律性が重要。",
    compensationReality: "給与、変動給、目標、達成率、日本と韓国の配分、雇用条件は公開情報で確認できない。",
  }),
];
