import type { Company } from "@/lib/market-data";

const batchTwoCompanyPatches: Record<string, Partial<Company>> = {
  dialpad: {
    category: "AIコミュニケーション・クラウド電話・Contact Center",
    hq: "カリフォルニア州サンラモン（米国）",
    japanPresence: "東京office・渋谷（2016年SoftBank提携で日本提供開始）",
    description: "voice、meeting、contact center、sales coachingを会話AIで統合。東京でMid-Market AEとSales Engineerの対象2求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  docusign: {
    category: "契約ライフサイクル・電子署名・Agreement AI",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Docusign Japan K.K.・東京都港区虎ノ門（2015年設立）",
    description: "eSignatureから契約作成・締結・管理・AI分析を担うIAMへ拡張。東京でAE、Partner、Marketing、MDRの対象7求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  dragos: {
    category: "OT・ICSサイバーセキュリティ",
    hq: "メリーランド州ハノーバー（米国）",
    japanPresence: "日本Remote team・Macnica partner（2023年参入、日本法人・officeは確認不能）",
    description: "工場・重要インフラのasset可視化、脆弱性優先度、脅威検知・対応を提供。日本でEnterprise AEとAdvisory Solutions Architectを公式募集。",
    lastChecked: "2026-08-17",
  },
  elastic: {
    category: "Search AI・Observability・Security基盤",
    hq: "アムステルダム（オランダ）・distributed company",
    japanPresence: "Elasticsearch株式会社・東京都千代田区（2014年9月設立）",
    description: "Elasticsearchを共通engineにSearch AI、Observability、Securityを提供。東京でRetail Sales 2件とSolutions Architecture leadershipの3求人を公式確認。",
    tags: ["Search AI", "Observability", "Security", "Retail", "Solutions Architecture", "Platform Sale"],
    lastChecked: "2026-08-17",
  },
  "extreme-networks": {
    category: "クラウドネットワーク・Fabric・Network Security",
    hq: "ノースカロライナ州モリスビル（米国）",
    japanPresence: "Extreme Networks株式会社・東京都千代田区霞が関（法人設立1993年）",
    description: "wired、wireless、fabric、SD-WAN、NAC・ZTNAをPlatform ONEで統合。東京でSE、Services Sales、Premier Deliveryの対象4求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  cohere: {
    category: "企業向け生成AI・Private AI基盤",
    hq: "トロント（カナダ）",
    japanPresence: "東京Remote team・富士通との日本語AI提携（日本法人・office・責任者は確認不能）",
    description: "enterprise LLM、retrieval、agent applicationをprivate deploymentを含め提供。東京RemoteでAE、Partner Development、FDEの現行3求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  contentsquare: {
    category: "デジタル体験分析・プロダクトアナリティクス",
    hq: "パリ（フランス）",
    japanPresence: "Contentsquare Japan合同会社・東京都千代田区丸の内（2022年4月設立）",
    description: "journey、session、heatmap、error、product analytics、VoCを統合。国内定量事例はあるが、2026年8月17日時点の現行日本求人は0件。",
    lastChecked: "2026-08-17",
  },
  datadog: {
    category: "オブザーバビリティ・クラウドセキュリティ",
    hq: "ニューヨーク（米国）",
    japanPresence: "Datadog Japan合同会社・東京都千代田区丸の内（2018年進出、2023年東京data center）",
    description: "metrics、traces、logs、experience、security、FinOps、AI Observabilityを統合。東京でSales、SE、CS、Support、Partner等の対象22求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  "dbt-labs": {
    category: "Analytics Engineering・Trusted Data基盤",
    hq: "米国（Fivetranとの統合会社）",
    japanPresence: "日本・APAC Remote team（日本法人・office・責任者は確認不能）",
    description: "dbtのtransformation、test、lineage、semanticとFivetran ingestionを統合。日本RemoteでPartner Sales、BDR、Customer Solutions、Sales Directorの4求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  deel: {
    category: "グローバル雇用・Payroll・HR基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Deel Japan株式会社・東京都（2022年2月設立）",
    description: "EOR、contractor、Global Payroll、HR、IT、Mobilityを提供。日本でSDR、Onboarding、Payroll Operationsの掲載対象4職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  cambly: {
    category: "法人英語研修・AI学習",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "APAC team・東京は現行求人のsecondary location（日本法人・officeは確認不能）",
    description: "native tutorとの会話、AI練習、CEFR、法人管理を提供。上海・東京を勤務地とするAPAC Sales Directorを公式募集。",
    lastChecked: "2026-08-17",
  },
  "cato-networks": {
    category: "SASE・クラウドネットワークセキュリティ",
    hq: "テルアビブ（イスラエル）",
    japanPresence: "Cato Networks株式会社・東京都千代田区大手町（2020年10月設立）",
    description: "networkとsecurityをsingle cloud platformへ統合。日本でSales、Presales、Customer Success、Supportの現行10求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  censys: {
    category: "インターネットインテリジェンス・攻撃対象領域管理",
    hq: "ミシガン州アナーバー（米国）",
    japanPresence: "日本市場team・Remote（日本法人・office・責任者は確認不能）",
    description: "internet assetの継続観測、Exposure Management、脅威調査、APIを提供。日本でAEとSenior Solutions Engineerを公式募集。",
    lastChecked: "2026-08-17",
  },
  cloudflare: {
    category: "Connectivity Cloud・ネットワーク・セキュリティ",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Cloudflare Japan株式会社・東京都千代田区丸の内（2020年日本法人設立）",
    description: "Application、Network、SASE、Developer Platformをglobal networkで提供。日本関連のSales、Partner、Supportの現行5求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  cognition: {
    category: "AIソフトウェアエンジニアリング",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Cognition Japan team・東京（2026年4月launch、法人商号・office住所は確認不能）",
    description: "Devin Cloud・Desktop・Review・Securityでsoftware taskをagent実行。東京でSales、Partnerships、Deployed、Support、GTM Opsの現行7求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  aghanim: {
    category: "モバイルゲームD2C・決済・LiveOps",
    hq: "ロサンゼルス（米国）／リスボン（ポルトガル）",
    japanPresence: "日本向けRemote team（日本法人・officeは確認不能）",
    description: "mobile game向けGame Hub、Merchant of Record、LiveOpsを提供。日本でHead of BDとCustomer Success Producerを公式募集する一方、国内顧客・売上は非公開。",
    lastChecked: "2026-08-17",
  },
  airwallex: {
    category: "グローバル決済・金融インフラ",
    hq: "サンフランシスコ（米国）／シンガポール",
    japanPresence: "Airwallex Japan株式会社・東京都港区（2023年電子決済等代行業、2025年第二種資金移動業登録）",
    description: "payments、FX、account、card、treasury、embedded financeをglobal展開。日本はonline決済を提供し、営業・partner・operationsの対象6求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  amplitude: {
    category: "プロダクトアナリティクス・実験基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Amplitude Analytics GK・東京（現住所・設立年月・人数は非公開）",
    description: "product analytics、session replay、experimentation、feature management、AIを提供。2026年8月17日時点で日本の現行公式求人は0件。",
    lastChecked: "2026-08-17",
  },
  anthropic: {
    category: "フロンティアAI・Enterprise AI基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Anthropic Japan GK・東京（2025年10月開設）",
    description: "Claude、API、Code、Enterprise、MCPを提供。東京の現行12求人のうち、Sales、Channel、Applied AI、CS、Supportの対象9件を公式確認。",
    lastChecked: "2026-08-17",
  },
  asana: {
    category: "ワークマネジメント・AI協働基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "アサナジャパン株式会社・東京都千代田区丸の内（2019年に日本語版・東京office）",
    description: "Goal、Portfolio、Project、Task、workflow、AI TeammatesをWork Graphで接続。東京でCorporate Account Executiveを公式募集。",
    lastChecked: "2026-08-17",
  },
  okta: {
    category: "アイデンティティ・アクセス管理・セキュリティ",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Okta Japan株式会社・東京／大阪（2020年9月設立）",
    description: "Workforce IdentityとAuth0 Customer Identityを提供。日本でOkta・Auth0のAE、Marketing、Auth0 TAMの現行実求人5件を公式確認。",
    lastChecked: "2026-08-17",
  },
  pagerduty: {
    category: "インシデント管理・オペレーショナルレジリエンス",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "PagerDuty株式会社・東京都港区（2022年にJapan Cloudとの提携で設立）",
    description: "incident response、on-call、AIOps、runbook automationを提供。日本でSales、BDR、Solutions、Professional Servicesの現行6求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  sonar: {
    category: "コード品質・アプリケーションセキュリティ",
    hq: "ジュネーブ（スイス）／オースティン（米国）",
    japanPresence: "東京GTM・日本語公式サイト（日本法人・責任者・進出年は非公開）",
    description: "IDE・PR・CIでcode qualityとsecurityを継続検証するSonarQubeを提供。東京でEnterprise Territory ManagerとPartner Business Managerを公式募集。",
    lastChecked: "2026-08-17",
  },
  zendesk: {
    category: "AIカスタマーサービス・コンタクトセンター",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "株式会社Zendesk・東京都中央区（2013年参入）",
    description: "ticket、messaging、voice、knowledge、AI Agent、CopilotをResolution Platformで提供。東京でCommercial AE、Senior Sales Engineer、BDRの現行3求人を公式確認。",
    lastChecked: "2026-08-17",
  },
  zilliz: {
    category: "ベクトルデータベース・AIデータ基盤",
    hq: "カリフォルニア州レッドウッドシティ（米国）",
    japanPresence: "東京Hybridのfounding team・Tokyo cloud region（日本法人・責任者・officeは非公開）",
    description: "Milvusを起点にmanaged vector databaseとBYOCを提供。東京でEnterprise Account ExecutiveとFounding Field Engineerを公式募集。",
    lastChecked: "2026-08-17",
  },
  deepl: {
    category: "言語AI・翻訳・文章支援",
    hq: "ケルン（ドイツ）",
    japanPresence: "DeepL Japan・東京（日本向け法人サービスと営業体制を展開）",
    description: "翻訳、文章作成、音声通訳、APIを企業向けに提供するLanguage AI企業。東京で営業、CS、Solutions、Enablement、Product GTMの対象7職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  elevenlabs: {
    category: "音声AI・会話型AI・コンテンツ制作",
    hq: "ロンドン（英国）／ニューヨーク（米国）",
    japanPresence: "ElevenLabs Japan合同会社・東京（2025年4月設立）",
    description: "音声生成、音声認識、dubbing、会話型AI AgentとAPIを提供。日本で新規開拓のAccount Executiveと拡張を担うAccount Managerを公式募集。",
    lastChecked: "2026-08-17",
  },
  mirakl: {
    category: "企業向けマーケットプレイス・コマース基盤",
    hq: "パリ（フランス）／ボストン（米国）",
    japanPresence: "Mirakl株式会社・東京（2022年設立）",
    description: "Marketplace、Dropship、seller・catalog管理、決済、広告を企業向けに提供。日本でSenior Account ExecutiveとSolution Consultantを公式募集。",
    lastChecked: "2026-08-17",
  },
  "new-relic": {
    category: "オブザーバビリティ・DevOps・クラウド運用",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "New Relic株式会社・東京（2018年8月設立）",
    description: "metrics、logs、traces、errors、digital experienceを統合するobservability基盤。日本でEnterprise sales、SDR、Technical Success、Solutionsの7 requisitionsを公式確認。",
    lastChecked: "2026-08-17",
  },
  notion: {
    category: "AIワークスペース・ナレッジ・協働",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Notion Japan・東京（2020年に日本GTMを開始、2021年に日本語版提供）",
    description: "文書、Wiki、project、enterprise search、meeting notes、AI Agentを一つのworkspaceで提供。東京で営業、Solutions、Outcomes、導入技術の対象12職種を公式確認。",
    lastChecked: "2026-08-17",
  },
  verkada: {
    category: "クラウド型物理セキュリティ・IoT",
    hq: "カリフォルニア州サンマテオ（米国）",
    japanPresence: "Verkada Japan株式会社・東京都渋谷区（2021年に国内partnerが提供開始、法人設立日は非公開）",
    description: "camera、access control、sensor、intercom等をcloud管理する物理セキュリティ基盤。日本で東京・大阪のAE、Channel、Field Marketing、Sales Operationsの7職種を公式募集。",
    lastChecked: "2026-08-17",
  },
  walkme: {
    category: "デジタル定着・業務変革",
    hq: "テルアビブ（イスラエル）",
    japanPresence: "WalkMe株式会社・東京都中央区日本橋（2019年2月設立）",
    description: "業務application上の案内、analytics、automation、AIでsoftwareの利用定着と業務完了を支援。日本でCS、Professional Services、Solution、Partner・Allianceの7職種を公式掲載。",
    lastChecked: "2026-08-17",
  },
  celonis: {
    category: "プロセスインテリジェンス・業務変革",
    hq: "ミュンヘン（ドイツ）／ニューヨーク（米国）",
    japanPresence: "Celonis株式会社・東京都千代田区丸の内（2019年設立）",
    description: "企業systemのevent dataからprocessの停滞・価値機会を可視化し、改善actionへ接続。東京の現行6求人のうち、営業・partner・delivery関連5職種を掲載（People & Culture職は対象外）。",
    lastChecked: "2026-08-17",
  },
  confluent: {
    category: "データストリーミング・クラウドデータ基盤",
    hq: "カリフォルニア州マウンテンビュー（米国）",
    japanPresence: "Confluent Japan合同会社・東京都新宿区（2021年4月に日本operations開始）",
    description: "Apache Kafkaを基盤に、リアルタイムdata streamの接続・処理・governanceを提供。2026年8月17日時点で公式Careerの日本求人を再現確認できず、旧求人は現行扱いしていない。",
    lastChecked: "2026-08-17",
  },
  dataiku: {
    category: "企業向けAI・データサイエンス基盤",
    hq: "ニューヨーク（米国）／パリ（フランス）",
    japanPresence: "Dataiku Japan株式会社・東京（日本市場で業界別GTMを展開）",
    description: "data準備、機械学習、生成AI・Agent、governanceを一つのplatformで提供。日本で金融、Retail・Telecom向けEnterprise AEとField Marketing Internを公式掲載。",
    lastChecked: "2026-08-17",
  },
  glean: {
    category: "企業向けAI・社内検索",
    hq: "カリフォルニア州（米国）",
    japanPresence: "日本市場チーム・リモート（2023年に国内販売開始、2026年に日本カントリーマネージャー就任）",
    description: "企業内の情報を権限付きで横断する検索、AIアシスタント、業務エージェントを提供。日本ではStrategic AE、Enterprise AE、SDRを公式募集。",
    lastChecked: "2026-08-17",
  },
  hubspot: {
    category: "顧客管理・マーケティング・営業・AI",
    hq: "マサチューセッツ州ケンブリッジ（米国）",
    japanPresence: "HubSpot Japan株式会社・東京都千代田区丸の内（2016年2月設立、同年7月営業開始）",
    description: "CRMを中心にマーケティング、営業、サービス、コンテンツ、データ、コマースとAIを統合。日本ではAE3職に加え、BDR、営業マネージャー、Solutions Engineer、Field Marketerを公式募集。",
    lastChecked: "2026-08-17",
  },
  qualtrics: {
    category: "顧客体験・従業員体験・市場調査",
    hq: "ユタ州プロボ／ワシントン州シアトル（米国）",
    japanPresence: "クアルトリクス合同会社・東京都千代田区丸の内（2016年法人設立、2018年事業開始）",
    description: "顧客・従業員・製品・ブランドの体験データを収集・分析し、改善行動へつなぐXM基盤。2026年8月17日時点で日本の現行公式求人は確認できない。",
    lastChecked: "2026-08-17",
  },
  speak: {
    category: "AI英会話・法人向け人材育成",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "スピークジャパン合同会社・東京都渋谷区（2022年日本soft launch、2024年8月法人設立）",
    description: "音声AIによる英語発話練習と法人管理を提供。東京でAccount Executive、Customer Success Manager、B2B Marketing Managerを公式募集。",
    lastChecked: "2026-08-17",
  },
  stripe: {
    category: "決済・金融インフラ・収益管理",
    hq: "サンフランシスコ（米国）／ダブリン（アイルランド）",
    japanPresence: "ストライプジャパン株式会社・東京（2016年提供開始、2020年開発拠点開設）",
    description: "決済、請求、プラットフォームの資金移動、不正対策、税・データ基盤を提供。東京でCommercial Hunter・Grower、Enterprise Hunterの3つのAE職を公式募集。",
    lastChecked: "2026-08-17",
  },
};

export function standardizeRolloutCompany(company: Company): Company {
  const patch = batchTwoCompanyPatches[company.slug];
  return patch ? { ...company, ...patch } : company;
}
