import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildIntelligence, type Profile } from "@/lib/company-public-intelligence-wave-two";

const checkedAt = "2026-08-15";

const profiles: Profile[] = [
  {
    checkedAt, slug: "stripe", name: "Stripe", jobUrl: "https://stripe.com/jobs/search?gh_jid=7343534", officialUrl: "https://stripe.com/jp", customersUrl: "https://stripe.com/jp/customers", externalUrl: "https://www.meti.go.jp/policy/it_policy/statistics/outlook/ie_outlook.html", financeUrl: "https://stripe.com/annual-updates/2025",
    salesSnapshot: "Stripeは、Digital・Finance・Product・ITが抱える決済承認率、不正、請求、越境展開の課題をpaymentsからfinancial platformまでのAPIで解く会社。TokyoでCommercial、Enterprise、SMBのAccount Executiveを募集し、hunterとgrowerを分けた複数segmentのGTMを組む。決済の置換からBilling、Connect、Tax、Radarへ広げ、企業の収益基盤へ入る営業が面白い。",
    growthSummary: "Stripeは2025 annual updateでinternet上の広い事業基盤とpayments以外のproduct expansionを継続公開。非公開企業のため、日本売上とsegment別ARRは非公開。", ipoSummary: "非公開企業。IPO時期と日本単体の財務は公表されていない。",
    milestones: [{ year: "2010", label: "創業", detail: "developer-firstのonline payments APIを構築。", source: "company" }, { year: "2010年代", label: "global expansion", detail: "決済手段と対応地域を拡大。", source: "company" }, { year: "2020年代", label: "financial platform化", detail: "Billing、Connect、Tax、Issuing、Treasury等へ拡張。", source: "company" }, { year: "2025", label: "annual update", detail: "AI・global commerce・financial servicesの成長を公開。", source: "finance" }, { year: "2026.08", label: "Japan sales採用", detail: "Tokyoの複数AE求人を確認。", source: "job" }],
    issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "公式事例は、決済導入だけでなく、global expansion、subscription、platform payout、fraud、finance operationを一つの収益基盤で変える目的を示す。" }, { title: "製品の成り立ちから見る課題", body: "developerが数行でpaymentsを組み込むAPIから始まり、決済の周囲で事業者が自前で抱えるbilling、tax、risk、payoutへ責任範囲を広げた。" }, { title: "外部環境の要求から見る課題", body: "commerceの越境化、subscription化、marketplace化、AI agent経由の購買により、企業は決済率・不正・税・規制・会計を同時に説明しながら新市場へ速く出る要求がある。" }],
    narrative: [{ label: "背景", body: "企業は国・channel・product・課金モデルを増やしている。" }, { label: "課題", body: "決済、fraud、billing、tax、payout、reportingが分断し、売上取得の速度と統制の両方が落ちる。" }, { label: "解決策", body: "優先use caseを1つ選び、authorization、conversion、fraud、reconciliation、launch time、unit economicsを共通指標で再設計する。" }, { label: "選定の理由", body: "Adyen、PayPal/Braintree、国内PSP、複数vendor内製と比べ、API、global coverage、product breadth、developer speed、total operating costが合う場合に選ばれる。" }],
    openingHook: "新しい国・課金モデル・platformを立ち上げるたび、何カ月と何vendorの追加が必要ですか。", valueHypothesis: "authorization率、conversion、fraud loss、checkout completion、reconciliation time、new-market launch time、payment costを測る。", objection: "国内PSPと銀行、既存gatewayで十分。", reframe: "現在の手数料だけでなく、次の国・商材・課金モデルを追加する時間、売上取りこぼし、開発・経理・リスク運用のTCOで比較する。",
    facts: [{ label: "創業", value: "2010年", detail: "payments infrastructureから開始。" }, { label: "日本拠点", value: "Tokyo", detail: "Stripe JapanとTokyo求人を確認。", source: "job" }, { label: "製品", value: "Payments + Financial Platform", detail: "Billing、Connect、Tax、Radar等へ拡張。" }, { label: "GTM", value: "Hunter / Grower", detail: "Commercial、Enterprise、SMBの求人で分業。", source: "job" }, { label: "対象", value: "startupからEnterprise", detail: "segment別sales roleを公式掲載。", source: "job" }, { label: "現行求人", value: "複数AE", detail: "TokyoのJapanese fluency指定を確認。", source: "job" }],
    customers: [{ company: "Amazon", products: "Stripe platform", outcome: "global payments infrastructureの顧客事例として公開。", implication: "Enterprise scaleの複雑性に対するproof。" }, { company: "Shopify", products: "Stripe infrastructure", outcome: "platform commerceとseller paymentsの長期連携事例。", implication: "platform buyerのmulti-party paymentを話せる。" }, { company: "OpenAI", products: "Payments / Billing", outcome: "AI productのmonetizationを支える公式事例。", implication: "高成長digital businessのcategory proof。" }],
    externalSignals: [{ label: "越境EC", value: "国・通貨・決済手段", detail: "電子商取引の拡大は決済と税・不正・現地化を同時課題にする。", caveat: "市場成長はStripeの個別成果を保証しない。" }, { label: "platform economy", value: "multi-party money movement", detail: "marketplaceとSaaS platformの増加でonboarding、KYC、split payout、reportingが事業設計になる。", caveat: "必要な許認・契約は事業ごとに異なる。" }],
    role: "Commercial・EnterpriseのHunterとSMB Growerがsegment別にnew logo、expansion、複数product adoptionを担う。", organization: "Sales、Solutions、Product、Risk、Legal、Financeを案件ごとに束ねるmatrix GTM。", careerValue: "Payments、FinTech、API platform、global commerce、Enterprise transformationを横断する経験。", globalHeadcount: "8,000人超規模", japanPresence: "Stripe Japan / Tokyo、日本語製品・導入事例・複数営業求人", japanSince: "日本市場で継続展開",
    solutions: [{ name: "Stripe Payments", valueProp: "online・対面の決済受付と最適化。", url: "https://stripe.com/jp/payments", competitors: "Adyen、PayPal/Braintree、国内PSP。", differentiation: "API、global payment methods、optimization、product integration。" }, { name: "Stripe Billing", valueProp: "subscription・usage-based billingとrevenue workflowを管理。", url: "https://stripe.com/jp/billing", competitors: "Zuora、Chargebee、ERP・内製。", differentiation: "paymentsとbilling・tax・revenue dataの連続性。" }, { name: "Stripe Connect", valueProp: "platformのonboarding、money movement、payoutを構築。", url: "https://stripe.com/jp/connect", competitors: "Adyen for Platforms、PayPal、銀行・内製。", differentiation: "global compliance operationとprogrammable platform model。" }],
    fitTags: ["アンカー企業", "Payments", "FinTech", "Enterprise", "API", "Platform", "Japan"], comparisons: [{ arena: "Global Payments", companies: ["Stripe", "Adyen", "PayPal/Braintree"], why: "coverage、authorization、API、手数料、operation" }, { arena: "Billing", companies: ["Stripe Billing", "Zuora", "Chargebee"], why: "pricing flexibility、revenue workflow、integration" }, { arena: "Platform Payments", companies: ["Stripe Connect", "Adyen for Platforms", "内製"], why: "onboarding、compliance、payout、global expansion" }],
  },
  {
    checkedAt, slug: "aghanim", name: "Aghanim", jobUrl: "https://jobs.ashbyhq.com/aghanim/0b7e0d14-4741-4439-bdba-67dca40af857", officialUrl: "https://aghanim.com/", customersUrl: "https://aghanim.com/", externalUrl: "https://www.meti.go.jp/policy/mono_info_service/contents/downloadfiles/report/game_202503.pdf", financeUrl: "https://aghanim.com/",
    salesSnapshot: "Aghanimは、mobile game studioが抱えるapp store依存、player dataの分断、margin、loyaltyの課題をD2C web shopとcommunity基盤で解く会社。Head of BD Japanを募集し、studio開拓、partner、pipeline、market strategyを一人目で持つ。paymentsだけでなくlive operationsとplayer relationshipへ提案を広げる営業が面白い。",
    growthSummary: "非公開企業。公式求人で日本のmarket expansionとrevenue ownershipを確認できるが、ARR、顧客数、日本売上は非公開。", ipoSummary: "非公開企業。IPOと日本法人の詳細は未確認。",
    milestones: [{ year: "2023", label: "創業", detail: "mobile gaming D2C基盤を開発。", source: "company" }, { year: "2024", label: "platform拡張", detail: "web shop、payments、loyalty、communityを統合。", source: "company" }, { year: "2025", label: "studio adoption", detail: "game studio向けcommercial deploymentを拡大。", source: "company" }, { year: "2026", label: "Japan expansion", detail: "日本のGTMとrevenue責任者を募集。", source: "job" }, { year: "2026.08", label: "Head of BD Japan", detail: "remote Japanの現行公式求人を確認。", source: "job" }],
    issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "studioがweb shopを作る目的は、単なる手数料削減ではなく、playerとの直接接点、offer実験、loyalty、community、lifetime valueを自社で改善すること。" }, { title: "製品の成り立ちから見る課題", body: "mobile gameのD2Cを個別開発するとpayments、catalog、fraud、CRM、live opsが分断するため、専用platformとmanaged operationに束ねる設計。" }, { title: "外部環境の要求から見る課題", body: "mobile gameのacquisition costとplatform ruleの変化は、studioに収益性とplayer relationshipの説明責任を生み、store外導線のcompliance、conversion、retentionを事業投資として測る要求になる。" }],
    narrative: [{ label: "背景", body: "studioはapp storeに販売・決済・player接点を強く依存している。" }, { label: "課題", body: "marginとplayer dataが制約され、offer実験、loyalty、cross-title relationshipが蓄積しない。" }, { label: "解決策", body: "優先titleでweb shop、payments、catalog、CRMを導入し、migration、conversion、AOV、repeat、marginを測る。" }, { label: "選定の理由", body: "Xsolla、Coda Payments、決済事業者+内製と比べ、gaming-specific operation、立ち上げ速度、player experience、運用支援が合う場合に選ばれる。" }],
    openingHook: "現在のplayer売上のうち、自社が関係・購買data・次のofferを直接管理できる比率はどれくらいですか。", valueHypothesis: "web shop adoption、conversion、AOV、repeat rate、payment success、fraud、net revenue、live-ops cycleを測る。", objection: "自社開発か決済事業者のcheckoutで十分。", reframe: "checkout開発費だけでなく、catalog、promotion、player identity、loyalty、fraud、supportを継続運用するTCOとnet revenueで比較する。",
    facts: [{ label: "対象", value: "mobile game studios", detail: "D2C commerceとplayer relationshipを提供。" }, { label: "製品", value: "Web Shop / Payments", detail: "loyaltyとcommunityも統合。" }, { label: "Japan role", value: "Head of BD", detail: "market strategyからrevenueまで担当。", source: "job" }, { label: "勤務地", value: "Japan remote", detail: "公式Ashbyで確認。", source: "job" }, { label: "日本顧客", value: "非公開", detail: "公式事例で十分に確認できない。", source: "customers" }, { label: "現行求人", value: "1件", detail: "Head of BD Japan。", source: "job" }],
    customers: [{ company: "公式公開studio", products: "D2C Web Shop", outcome: "web経由の販売とplayer engagementを運用。", implication: "store外購買とdirect relationshipを同時に設計する。" }, { company: "mobile game publishers", products: "Payments / Loyalty", outcome: "会社公式はcategory別の価値を紹介。", implication: "個別の日本成果は面接で検証が必要。" }, { company: "game communities", products: "Community / Live Ops", outcome: "commerceとengagementを一つの導線で運用。", implication: "payments単体との差分をretentionで語る。" }],
    externalSignals: [{ label: "日本のgame産業", value: "global IPとmobile運用", detail: "経産省の関連資料は、ゲーム産業の海外展開と競争力を重要テーマとして扱う。", caveat: "Aghanimの個別導入を支持する資料ではない。" }, { label: "platform policy", value: "D2Cの機会と統制", detail: "store外販売の機会が増えるほど、規約、年齢、返金、tax、fraud、supportの運用責任が増える。", caveat: "国・platform・titleごとに条件が異なる。" }],
    role: "Head of BD Japanがmarket strategy、studio・partner開拓、pipeline、close、local feedbackをend-to-endで持つ。", organization: "global leadershipと連携しながら日本GTMを現地で作る初期組織。", careerValue: "Gaming、Payments、D2C Commerce、Country Build、partner ecosystemを横断する経験。", globalHeadcount: "非公開", japanPresence: "Head of BD Japanのremote求人を確認。日本法人・オフィスは未確認。", japanSince: "2026年にJapan expansion roleを確認",
    solutions: [{ name: "Aghanim Web Shop", valueProp: "mobile gameのD2C catalog・checkout・offerを運用。", url: "https://aghanim.com/", competitors: "Xsolla、Coda Payments、内製web shop。", differentiation: "gaming-specific commerceとmanaged operation。" }, { name: "Payments Infrastructure", valueProp: "global payment methodsとtransaction operationを提供。", url: "https://aghanim.com/", competitors: "Stripe、Adyen、PSP直接統合。", differentiation: "game commerce workflowとの一体運用。" }, { name: "Loyalty / Community", valueProp: "player relationshipとrepeat purchaseを自社接点で構築。", url: "https://aghanim.com/", competitors: "CRM、Discord、内製loyalty。", differentiation: "transactionとengagementを同じplayer journeyで扱う。" }],
    fitTags: ["Gaming", "Payments", "D2C", "Founding GTM", "Business Development", "Japan"], comparisons: [{ arena: "Gaming Web Shop", companies: ["Aghanim", "Xsolla", "Coda Payments"], why: "launch speed、payment coverage、managed operation、player UX" }, { arena: "Build vs Buy", companies: ["Aghanim", "PSP+内製", "publisher内製"], why: "TCO、control、data、live ops" }, { arena: "Japan entry", companies: ["Aghanim", "global coverage", "local partner"], why: "studio proof、support、commercial model" }],
  },
  {
    checkedAt, jobConfirmed: false, slug: "primer", name: "Primer", jobUrl: "https://jobs.ashbyhq.com/primer.io/767e0eeb-ffac-457e-9017-994253a0f372", officialUrl: "https://primer.io/", customersUrl: "https://primer.io/customers", externalUrl: "https://www.meti.go.jp/policy/it_policy/statistics/outlook/ie_outlook.html", financeUrl: "https://primer.io/company",
    salesSnapshot: "Primerは、Payments・Finance・Product・Engineeringが抱えるPSPの分断、決済成功率、fraud、routing、reconciliationの課題をUnified Payments Infrastructureで解く会社。SingaporeでAPAC Enterprise AEを募集する一方、Japan・Tokyoの専任求人、国内拠点、日本語siteは確認できない。APAC coverageと日本の有償顧客・PSP・partnerを分けて進出条件を観測する。",
    growthSummary: "公式はglobal enterprise向けのpayment orchestrationと顧客事例、SingaporeのAPAC AEを公開。非公開企業でARR、顧客数、APAC・Japan売上は非公開。", ipoSummary: "非公開企業。IPO時期と日本単体の財務は未公表。",
    milestones: [{ year: "2020", label: "創業", detail: "payment integrationとorchestrationの分断解消を目的に創業。", source: "company" }, { year: "2021", label: "fundingと拡張", detail: "global payments infrastructureの製品開発を拡大。", source: "finance" }, { year: "2023", label: "Enterprise use cases", detail: "routing、recovery、fraud、reconciliationを拡張。", source: "company" }, { year: "2025", label: "APAC coverage", detail: "Singaporeを起点にregional GTMを推進。", source: "job" }, { year: "2026.08", label: "Japan観測", detail: "APAC AEは確認、Japan専任求人は未確認。", source: "job" }],
    issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "公式顧客事例は、PSPを増やすことではなく、payment success、routing、fraud、recovery、新市場展開を自社で制御する目的を示す。" }, { title: "製品の成り立ちから見る課題", body: "payment providerごとのintegration、workflow、data、error handlingが固定化する問題を、single integrationとno-code workflowで切り離す設計。" }, { title: "外部環境の要求から見る課題", body: "cross-border commerce、地域ごとの決済手段、不正、データ規制の変化は、buyerにPSPを固定せずperformanceとresilienceを説明できる設計を求める。" }],
    narrative: [{ label: "背景", body: "global merchantは国・通貨・payment methodごとに複数PSPとrisk toolを使う。" }, { label: "課題", body: "integrationが個別実装となり、routing、recovery、可視化、provider変更が遅くなる。" }, { label: "解決策", body: "一つのmarketとpayment flowで複数providerを接続し、authorization、latency、failure、cost、operator timeを比較する。" }, { label: "選定の理由", body: "Spreedly、Gr4vy、Adyen、Stripe、内製orchestrationと比べ、provider neutrality、workflow control、observability、integration speedが合う場合に選ばれる。" }],
    openingHook: "主要PSPが落ちた時、何分で別routeへ切り替え、売上影響を説明できますか。", valueHypothesis: "authorization、payment recovery、routing uplift、provider integration time、downtime、fraud、operator hours、costを測る。", objection: "主要PSPの機能か内製routingで十分。", reframe: "現在のprovider数ではなく、次の国・決済手段・fraud toolを追加する速度、outage、lock-in、運用工数を含むTCOで比較する。",
    facts: [{ label: "創業", value: "2020年", detail: "London発のpayments infrastructure企業。" }, { label: "製品", value: "Unified Payments Infrastructure", detail: "orchestration、routing、recovery、observabilityを提供。" }, { label: "APAC求人", value: "Singapore AE", detail: "Enterprise AEのrevenue roleを確認。", source: "job" }, { label: "Japan求人", value: "未確認", detail: "当日の公式careersでJapan専任を確認できず。", source: "job" }, { label: "日本語site", value: "未確認", detail: "本調査でlocal product・resource導線を確認できず。" }, { label: "日本顧客", value: "未確認", detail: "公式customer storiesでJapan referenceを確認できず。", source: "customers" }],
    customers: [{ company: "Global merchants", products: "Payment Orchestration", outcome: "provider接続とroutingをsingle integrationで運用。", implication: "multi-PSPの複雑性をbusiness KPIに変える。" }, { company: "FinTech / Commerce", products: "Unified Payments Infrastructure", outcome: "routing、recovery、fraud、observabilityをworkflow化。", implication: "payments engineeringとFinance operationの両方に価値を作る。" }, { company: "APAC prospects", products: "Primer platform", outcome: "Singapore AEがAPACのEnterprise salesを担当。", implication: "regional coverageはあるがJapan proofとは分ける。" }],
    externalSignals: [{ label: "cross-border commerce", value: "payment methodと規制の分断", detail: "国境をまたぐECはlocal payment、currency、fraud、tax、dataの調整を必要とする。", caveat: "PrimerのJapan参入を直接示すものではない。" }, { label: "payment resilience", value: "single-provider risk", detail: "paymentsが売上基盤になるほど、outage、performance、provider concentrationの説明責任が増える。", caveat: "multi-PSPは常に経済合理性があるとは限らない。" }],
    role: "SingaporeのAPAC AEがEnterpriseのend-to-end salesを担う。Japan専任のAE、SE、CS、partner managerは未確認。", organization: "APACはSingaporeからregional coverageする段階と読めるが、Japanの固定組織は公開情報で確定できない。", careerValue: "Payments orchestration、Enterprise FinTech、APAC market development、multi-provider architectureを横断する可能性。", globalHeadcount: "201〜500人規模（LinkedIn公開レンジ、留保付き）", japanPresence: "日本法人、Tokyo拠点、Japan専任求人を未確認。", japanSince: "日本進出は未確認",
    solutions: [{ name: "Universal Checkout", valueProp: "複数PSP・payment methodを一つのcheckoutへ統合。", url: "https://primer.io/products", competitors: "Stripe、Adyen、自礼heckout。", differentiation: "provider-neutral orchestrationとworkflow control。" }, { name: "Payments Orchestration", valueProp: "routing、fallback、recovery、fraudをルール化。", url: "https://primer.io/products", competitors: "Spreedly、Gr4vy、PSP-native routing。", differentiation: "no-code workflowと広いconnector構成。" }, { name: "Observability", valueProp: "transaction performanceとprovider差を可視化。", url: "https://primer.io/products", competitors: "PSP dashboard、BI内製、payment analytics。", differentiation: "orchestrationと同じdata layerで改善を回す。" }],
    fitTags: ["日本未進出", "Payments", "Orchestration", "FinTech", "Enterprise", "Singapore", "APAC"], comparisons: [{ arena: "Payment Orchestration", companies: ["Primer", "Spreedly", "Gr4vy"], why: "connector、workflow、observability、cost" }, { arena: "PSP-native", companies: ["Primer", "Stripe", "Adyen"], why: "neutrality、coverage、optimization、stack complexity" }, { arena: "Japan entry", companies: ["Primer", "Singapore regional coverage", "local partner"], why: "customer proof、PSP ecosystem、support economics" }],
  },
];

const built = Object.fromEntries(profiles.map((profile) => [profile.slug, buildIntelligence(profile)])) as Record<string, CompanyPublicIntelligence>;

if (built.primer.marketStatus.japanGrowth) {
  built.primer.marketStatus.japanGrowth.entryAssessment = {
    verdict: "進出可能性は中。SingaporeのAPAC営業基盤とglobal payment課題の親和性はあるが、Japan顧客・専任人材・日本語・国内PSP連携が未確認",
    factSignals: [
      { title: "APACの営業基盤", body: "SingaporeでAPAC Enterprise AEを募集し、regional pipelineを作る投資を確認。", sourceIds: ["primer-job"] },
      { title: "global commerceの製品適合", body: "複数PSP、routing、recovery、fraud、observabilityをsingle integrationで扱う。", sourceIds: ["primer-company"] },
      { title: "Japan buyerの課題と親和", body: "越境ECとdigital serviceはlocal payment、resilience、provider管理を必要とする。", sourceIds: ["primer-external"] },
      { title: "Enterprise導入に必要な統制", body: "workflowとtransaction observabilityはperformanceと障害の説明基盤になる。", sourceIds: ["primer-company", "primer-customers"] },
    ],
    hurdles: [
      { title: "Japan commercial proof不足", body: "Japan ARR、有償顧客、renewal、pipelineを公式情報で確認できない。", sourceIds: ["primer-customers", "primer-job"] },
      { title: "local PSP・payment method", body: "日本で必要なPSP、国内決済手段、契約・返金運用の対応範囲が未確認。", sourceIds: ["primer-company", "primer-external"] },
      { title: "language・support gap", body: "日本語UI、documentation、support、security・契約資料の同等性が未確認。", sourceIds: ["primer-company", "primer-job"] },
      { title: "強い既存選択肢", body: "Stripe、Adyen、国内PSP、Spreedly、内製が既存契約とintegrationを持つ。", sourceIds: ["primer-company"] },
    ],
    readinessConditions: [
      { title: "Japan paid cohort", body: "複数の日本Enterpriseでproduction volume、renewal、routing upliftを確認する。" },
      { title: "local connector coverage", body: "日本の主要PSP・payment method・fraud・会計への対応を揃える。" },
      { title: "Japan-ready operation", body: "日本語、契約、security、support、incident responseを日本時間で運用する。" },
      { title: "local GTM pod", body: "AE、Solution、CS、PartnerをJapan territoryに専任化する。" },
      { title: "repeatable economics", body: "ACV、sales cycle、implementation負荷、retentionがlocal固定費を正当化する。" },
    ],
    watchSignals: ["Japan・Tokyo専任求人", "日本語site・documentation", "国内顧客事例", "国内PSP・partner連携", "Tokyo拠点・日本法人", "Japan time support・incident体制"],
  };
}

export const daily20260815IntelligenceBySlug = built;
