import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchNine: Job[] = [
  job({
    id: "docusign-partner-account-manager-sap-japan",
    companySlug: "docusign",
    title: "Partner Account Manager (SAP Japan)",
    segment: "Partner Sales / SAP",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）／出張最大25%",
    language: "日本語・英語（professional）",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/29184?lang=en-us" },
    descriptionSummary: "SAP Japanとのjoint plan、enablement、co-sell、pipeline・revenueを担う。",
    genbaTake: "紹介件数でなく、契約作成・署名・管理をSAP業務processへ組み込み、partner-sourced outcomeを再現可能にする。",
    compensationReality: "給与、OTE、pay mix、partner target、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic partner management、joint GTM、日本語・英語professional、出張最大25%を重視。",
    domain: "Agreement Management・Partner Sales",
  }),
  job({
    id: "docusign-account-executive-smb-japan-29255",
    companySlug: "docusign",
    title: "Account Executive, SMB",
    segment: "SMB / Agreement Management",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）",
    language: "日本語（native）／英語（intermediate reading・writing）",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/29255?lang=en-us" },
    descriptionSummary: "Japan SMBのnew logo・既存拡張をprospecting、discovery、demo、negotiation、closeまで担う。",
    genbaTake: "署名seatでなく、契約lead time、conversion、manual入力、保存・更新管理をIAM expansionのbusiness caseへする。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はquota sales 4年以上、high-velocity full-cycle、native Japanese、intermediate English reading・writingを重視。",
    domain: "Agreement Management・SMB Sales",
  }),
  job({
    id: "docusign-partner-account-manager-salesforce-japan",
    companySlug: "docusign",
    title: "Partner Account Manager (Salesforce Japan)",
    segment: "Partner Sales / Salesforce",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）／出張最大25%",
    language: "日本語・英語（professional）",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/29277?lang=en-us" },
    descriptionSummary: "Salesforce Japanとのjoint plan、enablement、co-sell、pipeline・revenueを担う。",
    genbaTake: "eSignature connectorで終わらず、CRM上のagreement workflow、data、renewalを共同solutionへする。",
    compensationReality: "給与、OTE、pay mix、partner target、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic alliance、ecosystem selling、日本語・英語professional、出張最大25%を重視。",
    domain: "Agreement Management・Partner Sales",
  }),
  job({
    id: "docusign-account-executive-enterprise-japan",
    companySlug: "docusign",
    title: "Account Executive, Enterprise",
    segment: "Enterprise / Agreement Management",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）／出張通常10%",
    language: "日本語（fluent）／英語（business level）",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/29893?lang=en-us" },
    descriptionSummary: "大手顧客のnew logo・expansionを複数stakeholderと進め、eSignatureからIAMへfull-cycleで広げる。",
    genbaTake: "署名機能でなく、Legal・Sales・Procurement・ITをまたぐagreement lifecycle、risk、cycle timeをexecutive business caseへする。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise sales 12年以上、complex account、fluent Japanese、business-level Englishを重視。",
    domain: "Agreement Management・Enterprise Sales",
  }),
  job({
    id: "docusign-field-marketing-specialist-japan",
    companySlug: "docusign",
    title: "Field Marketing Specialist",
    segment: "Field Marketing / Japan",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）",
    language: "日本語（native）／英語（working level）",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/29935?lang=en-us" },
    descriptionSummary: "日本のfield campaign、event、demand generationを営業と連携し、pipelineへつなぐ。",
    genbaTake: "event件数でなく、eSignature利用者をIAM categoryへ教育し、engagement、qualified pipeline、revenue influenceを測る。",
    compensationReality: "給与、bonus、pipeline targetは公式求人で確認できない。",
    desiredProfile: "公式求人はB2B field marketing、campaign execution、native Japanese、working-level Englishを重視。",
    domain: "Agreement Management・Field Marketing",
  }),
  job({
    id: "docusign-account-executive-smb-japan-29939-current",
    companySlug: "docusign",
    title: "Account Executive, SMB",
    segment: "SMB / Agreement Management",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）",
    language: "日本語（native）／英語（intermediate reading・writing）",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/29939?lang=en-us" },
    descriptionSummary: "Japan SMBのnew logoと既存拡張をprospecting、discovery、demo、commercial negotiation、closeまで担う。",
    genbaTake: "契約件数でなく、lead time、conversion、保存・検索、renewalを短いcycleで定量化しIAMへexpandする。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はquota sales 4年以上、native Japanese、intermediate English reading・writingを重視。",
    domain: "Agreement Management・SMB Sales",
  }),
  job({
    id: "docusign-market-development-representative-japan",
    companySlug: "docusign",
    title: "Market Development Representative",
    segment: "Market Development / Pipeline",
    location: "東京",
    workStyle: "ハイブリッド（office最低週2日）",
    language: "公式求人で言語名の明記なし",
    source: { label: "Docusign Careers", url: "https://careers.docusign.com/jobs/30021?lang=en-us" },
    descriptionSummary: "outbound prospecting、qualification、meeting・pipeline creationを担う。",
    genbaTake: "署名への関心でなく、draft、approval、signature、repository、renewalの分断をaccount固有のIAM課題へ変える。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はoutbound sales 2年以上、prospecting、qualification、CRMを重視。人間言語要件は明記なし。",
    domain: "Agreement Management・Market Development",
  }),
  job({
    id: "dialpad-account-executive-mid-market-japan-current",
    companySlug: "dialpad",
    title: "Account Executive, Mid-Market",
    segment: "Mid-Market / AI Communications",
    location: "東京",
    workStyle: "公式求人で明記なし",
    language: "公式求人で明記なし",
    source: { label: "Dialpad Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/dialpad/jobs/8606879002" },
    descriptionSummary: "Japan Mid-Marketのprospecting、discovery、demo、negotiation、closeまでを担い、RVP Japan Salesへreportする。",
    genbaTake: "電話systemの置換でなく、会話dataをsupport品質、seller coaching、after-call作業、顧客体験へつなぐplatform sale。",
    compensationReality: "competitive salaryの定性記載のみ。給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はfull-cycle sales 3〜5年、pipeline、multi-stakeholder executionを重視。勤務形態・日本語・英語要件は明記なし。",
    domain: "AI Communications・Mid-Market Sales",
  }),
  job({
    id: "dialpad-sales-engineer-iii-japan",
    companySlug: "dialpad",
    title: "Sales Engineer III",
    segment: "Sales Engineering / AI Communications",
    location: "東京",
    workStyle: "ハイブリッド／出張最大50%",
    language: "公式求人で明記なし",
    source: { label: "Dialpad Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/dialpad/jobs/8633657002" },
    descriptionSummary: "顧客課題のtechnical discovery、solution design、demo、validationを担い、AI communicationsのtechnical winを作る。",
    genbaTake: "通話機能のdemoでなく、日本語AI精度、録音・privacy、番号移行、integration、uptime、運用TCOを顧客環境で検証する。",
    compensationReality: "給与、bonus、OTE、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はcustomer-facing technical role 3〜5年、solution・presales、東京officeとのHybrid、出張最大50%を重視。言語要件は明記なし。",
    domain: "AI Communications・Sales Engineering",
  }),
  job({
    id: "dragos-advisory-solutions-architect-japan-current",
    companySlug: "dragos",
    title: "Advisory Solutions Architect (Japan)",
    segment: "Solutions Architecture / OT Security",
    location: "日本",
    workStyle: "リモート / フルタイム",
    language: "日本語（fluent）／英語（professional proficiency）",
    source: { label: "Dragos Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/dragos/jobs/5193467008" },
    descriptionSummary: "pre-sales、solution design、PoC、post-sales guidance、partner enablementを担う日本初のtechnical hire。",
    genbaTake: "alert demoでなく、asset accuracy、OT文脈付き優先度、調査時間、停止を避ける導入、既存SOC連携をtechnical winへ変える。",
    compensationReality: "公式OTEは最大3,000万円。base・variable内訳、quota、equity額は非公開。",
    desiredProfile: "公式求人はOT・ICS security、customer lifecycle、PoC、partner、日本語fluency、英語professional proficiencyを重視。",
    domain: "OT Security・Solutions Architecture",
  }),
  job({
    id: "dragos-senior-enterprise-account-executive-japan-current",
    companySlug: "dragos",
    title: "Senior Enterprise Account Executive JPN",
    segment: "Enterprise / OT Security",
    location: "日本",
    workStyle: "リモート / フルタイム",
    language: "日本語・英語（fluent）",
    source: { label: "Dragos Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/dragos/jobs/5254855008" },
    descriptionSummary: "energy、water、transport、manufacturingを担当し、distribution partnerと日本territoryのpipeline・revenueを作る。",
    genbaTake: "security eventでなく、操業停止、安全、asset visibility、incident readinessを工場責任者とCISOの共通business caseへする。",
    compensationReality: "公式表記は最大3,184万円OTE。base・variable内訳、quota、equity額は非公開で、固定給額とは解釈しない。",
    desiredProfile: "公式求人はenterprise cyber sales、Japan market、partner management、critical infrastructure、日本語・英語fluencyを重視。",
    domain: "OT Security・Enterprise Sales",
  }),
  job({
    id: "elastic-enterprise-account-executive-retail-japan-current",
    companySlug: "elastic",
    title: "Enterprise Account Executive - Retail Market",
    segment: "Enterprise / Retail",
    location: "東京",
    workStyle: "オンサイト",
    language: "日本語・英語（fluent）",
    source: { label: "Elastic Careers", url: "https://jobs.elastic.co/jobs/sales/tokyo-japan/enterprise-account-executive-retail-market/7882324" },
    descriptionSummary: "retail enterpriseのnew logoと既存拡張を担い、Search、Observability、SecurityをMEDDPICCでfull-cycle提案する。",
    genbaTake: "search engineの販売でなく、customer experience、system reliability、security dataを共通platformの投資理由へ束ねる。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise SaaS sales、retail、MEDDPICC、日本語・英語fluencyを重視。",
    domain: "Search AI・Retail Enterprise Sales",
  }),
  job({
    id: "elastic-senior-manager-solutions-architecture-japan",
    companySlug: "elastic",
    title: "Senior Manager, Solutions Architecture (Pre-sales)",
    segment: "Solutions Architecture Leadership",
    location: "東京",
    workStyle: "オンサイト／regional travel 10〜30%",
    language: "日本語・英語（fluent）",
    source: { label: "Elastic Careers", url: "https://jobs.elastic.co/jobs/sa/tokyo-japan/senior-manager-solutions-architecture-pre-sales-/8108464" },
    descriptionSummary: "日本のstrategic・global account向けSolutions Architecture teamを率い、technical strategyとpartner motionを担う。",
    genbaTake: "demo管理でなく、Search・Observability・SecurityのPoC quality、technical win、partner leverage、architect育成をteamの再現性へする。",
    compensationReality: "給与、bonus、OTE、team quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はpre-sales architecture leadership、strategic account、partner、日本語・英語、regional travel 10〜30%を重視。",
    domain: "Search AI・Solutions Architecture Leadership",
  }),
  job({
    id: "elastic-account-executive-retail-japan-current",
    companySlug: "elastic",
    title: "アカウント営業／リテール",
    segment: "Retail・Manufacturing / Enterprise Sales",
    location: "東京",
    workStyle: "オンサイト",
    language: "公式求人で明記なし",
    source: { label: "Elastic Careers", url: "https://jobs.elastic.co/jobs/sales/tokyo-japan/-/8090490" },
    descriptionSummary: "retail・manufacturingの新規・既存顧客へSearch、Observability、Securityを提案し、TCO・ROIでfull-cycleを進める。",
    genbaTake: "単一use caseでなく、顧客検索、system reliability、security dataを共通engineとbusiness outcomeへ束ねる。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise sales、MEDDPICC・Challenger・Value Engineering、TCO・ROIを重視。人間言語要件は明記なし。",
    domain: "Search AI・Enterprise Sales",
  }),
  job({
    id: "extreme-networks-senior-systems-engineer-tokyo-current",
    companySlug: "extreme-networks",
    title: "Sr. Systems Engineer - Tokyo Area",
    segment: "Sales Engineering / Network Platform",
    location: "東京",
    workStyle: "リモート / フルタイム",
    language: "日本語（fluent・native・business）／英語（proficient）",
    source: { label: "Extreme Networks Careers (Lever)", url: "https://jobs.lever.co/extremenetworks/64824246-9ad5-4bff-979c-f7476e0f2f9a" },
    descriptionSummary: "顧客・partner向けdemo、RFP・RFI、architecture、PoCを担い、network・securityのtechnical winを作る。",
    genbaTake: "製品demoで終わらず、wired・wireless・fabric・NAC・ZTNAの変更時間、risk、運用工数、5年TCOを顧客環境で検証する。",
    compensationReality: "公式OTEは年1,600万〜1,900万円、base・variable 70:30。資格・経験で変動し、equity・quotaは非公開。",
    desiredProfile: "公式求人はnetwork presales、architecture・PoC、partner支援、日本語と英語での顧客対応を重視。",
    domain: "Cloud Networking・Sales Engineering",
  }),
  job({
    id: "extreme-networks-systems-engineer-tokyo-current",
    companySlug: "extreme-networks",
    title: "Systems Engineer - Tokyo Area",
    segment: "Sales Engineering / Network Platform",
    location: "東京",
    workStyle: "リモート",
    language: "日本語（fluent・native・business）／英語（proficient）",
    source: { label: "Extreme Networks Careers (Lever)", url: "https://jobs.lever.co/extremenetworks/b2bb5e7a-e890-4ff2-9dfd-8b57c5cdd071" },
    descriptionSummary: "顧客demo labを含むtechnical presales、RFP・RFI、architecture、PoC、partner支援を担う。",
    genbaTake: "network構成の説明でなく、重要siteのexperience、segmentation、change error、MTTR、運用負荷をtechnical acceptanceへ変える。",
    compensationReality: "公式OTEは年1,000万〜1,400万円、base・variable 70:30。equity・quotaは非公開。",
    desiredProfile: "公式求人はnetwork presales、lab・demo、architecture、fluent Japaneseとproficient Englishを重視。",
    domain: "Cloud Networking・Sales Engineering",
  }),
  job({
    id: "extreme-networks-sr-services-sales-account-executive-tokyo-current",
    companySlug: "extreme-networks",
    title: "Sr. Services Sales Account Executive - Tokyo",
    segment: "Services Sales / Channel",
    location: "東京・日本全国",
    workStyle: "ハイブリッド / フルタイム／出張あり",
    language: "日本語・英語（business fluent）",
    source: { label: "Extreme Networks Careers (Lever)", url: "https://jobs.lever.co/extremenetworks/a7e470eb-5893-40ee-a2e8-8454b1ff701c" },
    descriptionSummary: "Professional、Premier、Managed Services、support更新、onboardingをnetwork案件へ組み込み、channel pipelineを作る。",
    genbaTake: "hardware・subscriptionのattachではなく、design、migration、operation、supportのriskとtime-to-valueをlifecycle business caseへする。",
    compensationReality: "給与、OTE、pay mix、services attach・renewal targetは公式求人で確認できない。",
    desiredProfile: "公式求人はservices sales、channel、networking、pipeline・renewal、日本語・英語、国内出張を重視。",
    domain: "Cloud Networking・Services Sales",
  }),
  job({
    id: "extreme-networks-premier-service-delivery-engineer-japan",
    companySlug: "extreme-networks",
    title: "Premier Service Delivery Engineer",
    segment: "Premier Services / Customer Delivery",
    location: "東京",
    workStyle: "ハイブリッド / フルタイム",
    language: "日本語（business必須）／英語（plus）",
    source: { label: "Extreme Networks Careers (Lever)", url: "https://jobs.lever.co/extremenetworks/b5cef82d-d3a7-4761-bf0f-407f00faa41b" },
    descriptionSummary: "専任顧客のnetwork設計、導入、運用支援を担い、Sales、PLM、Engineering、Customerを調整する。",
    genbaTake: "resident supportで終わらず、change success、incident、knowledge transfer、lifecycle riskを顧客KPIへつなぐ。",
    compensationReality: "確定給与は非公開。日本語mirrorにある0円表示はATS placeholderで、給与0円を意味しない。",
    desiredProfile: "公式求人はenterprise network delivery、顧客調整、business Japaneseを重視。Englishはplus。",
    domain: "Cloud Networking・Premier Service Delivery",
  }),
];
