import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-18";

export const companies20260818Daily: Company[] = [
  {
    slug: "atlassian",
    name: "Atlassian",
    category: "Teamwork / Work Management / DevOps / ITSM",
    broadCategory: "業務自動化・コラボレーション",
    hq: "Sydney, Australia / San Francisco, US",
    japanPresence: "アトラシアン株式会社・横浜（2013年設立）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "Jira、Confluence、Jira Service Management、LoomとAIを通じて開発・業務・IT運用の協働を支援。横浜で日本語対応のSenior Customer Success Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://join.atlassian.com/atlassian-talent-community/jobs/21718?lang=en-us",
    tags: ["アンカー企業", "Work Management", "DevOps", "ITSM", "AI", "Customer Success", "Japan"],
  },
  {
    slug: "dynatrace",
    name: "Dynatrace",
    category: "Observability / AIOps / Application Security",
    broadCategory: "セキュリティ・IT運用",
    hq: "Boston, US",
    japanPresence: "Dynatrace合同会社・東京",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "application、infrastructure、log、user experience、securityをAIで相関し、障害原因と事業影響を可視化。東京でJapan Enterprise Solutions Engineerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://apply.careers.dynatrace.com/job/Tokyo-Sr-Solutions-Engineer-Toky-100-0005/1390103700/",
    tags: ["Observability", "AIOps", "Application Security", "Solutions Engineering", "Enterprise", "Japan"],
  },
  {
    slug: "vercel",
    name: "Vercel",
    category: "AI Cloud / Frontend Cloud / Developer Platform",
    broadCategory: "AI・データ基盤",
    hq: "San Francisco, US",
    japanPresence: "日本法人・国内拠点・Japan求人を確認できず",
    hiringStatus: "継続観測",
    salesRoles: 0,
    description: "Next.js、AI SDK、v0とglobal application infrastructureを提供。APAC営業求人はSydney等を対象とし、日本法人・国内拠点・Japan専任求人は未確認のため日本未進出として継続観測。",
    lastChecked: checkedAt,
    careersUrl: "https://vercel.com/careers",
    tags: ["日本未進出", "AI Cloud", "Developer Platform", "Next.js", "AI SDK", "APAC", "Enterprise"],
    entryStatus: "not-entered",
  },
];

const careerInsights = (title: string, domain: string): Job["careerInsights"] => ({
  fit: `${domain}で、顧客の技術課題を業務成果と定着計画へ翻訳したい人に向く。`,
  thingsToKnow: "日本の個別報酬、quota、担当社数、達成率、平均ACV、ramp、昇進・離職分布は公式求人で確認できない。",
  marketValue: `${title}の成果を顧客KPI、adoption、technical win、renewal・expansionで定量化できれば、同領域の上位scopeへ転用しやすい。`,
  tenureAndPromotion: `【Genba仮説】${title}では在籍年数より、顧客成果、再利用できるplaybook、複数stakeholderを動かした証拠が昇進材料になる。支持材料: 公式求人は顧客課題の発見、部門横断の実行、価値実現を責任として置き、成果scopeを広げる職務構造を示す。反証・留保: 日本teamの平均在籍年数、昇進率、manager別離職、社内公募の実績は公開されておらず、global制度を配属先の実態へ一般化できない。面接で確認: 直近24カ月の昇進・異動・退職件数、次levelへ進んだ人の共通KPI、managerのpromotion実績を具体例で聞く。`,
  priorCompanies: `【Genba仮説】${domain}、Enterprise software、consulting、IT運用でdiscoveryから導入・定着まで進めた人が隣接する。支持材料: ${title}は製品名の暗記より、technical・business discovery、複数stakeholder、value realizationを求めるため、隣接categoryで同じ販売・顧客成果を作った経験を移しやすい。反証・留保: 日本teamの実際の入社元企業分布、職種別採用比率、業界未経験者の通過率は公開されておらず、特定企業からの採用傾向は断定できない。面接で確認: 現teamで活躍する人の前職類型、採用時に評価した定量成果、足りない経験を入社後どうrampするかを聞く。`,
  nextCompanies: `【Genba仮説】${title}で顧客KPI、adoption、technical win、renewal・expansionの成果を定量化できれば、Strategic Customer Success、Principal Solutions、Value Consulting、Manager、Japan・APAC leadershipが隣接する。支持材料: ${domain}は顧客規模、technical depth、portfolio、team責任を一段上げる形で上位scopeへ接続できる職務構造を持つ。反証・留保: 実際の退職後転職先、昇給幅、転職成功率を示す日本の公開分布ではなく、職務構造からの推定である。面接で確認: alumniの代表的な進路、社内で次に狙えるrole、必要なKPI・certification・people leadership、異動実績を聞く。`,
});

export const jobs20260818Daily: Job[] = [
  {
    id: "atlassian-senior-customer-success-manager-japanese-21718",
    companySlug: "atlassian",
    title: "Senior Customer Success Manager (Japanese Speaking)",
    segment: "Enterprise Customer Success / Adoption & Value",
    location: "横浜（日本）",
    workStyle: "Team Anywhere方針。対象求人の固定出社日数は明記なし",
    language: "日本語と英語で顧客・global teamへ対応",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Atlassian Careers", url: "https://join.atlassian.com/atlassian-talent-community/jobs/21718?lang=en-us" },
    descriptionSummary: "日本のstrategic customersにsuccess plan、adoption、value realization、executive alignmentを提供し、製品活用をbusiness outcomeへつなぐ。",
    genbaTake: "利用率だけでなく、開発・service・knowledge workflowの変化を顧客KPIへ落とし、renewal・expansionの再現性を作るpost-sales role。",
    compensationReality: "日本向けのbase、bonus、equity、目標値は公式求人で確認できない。",
    desiredProfile: "Enterprise softwareのCustomer Success、複雑なstakeholder管理、value realization、日本語・英語での顧客対応を担える人。",
    careerInsights: careerInsights("Senior Customer Success Manager", "Work Management・DevOps・ITSM"),
  },
  {
    id: "dynatrace-japan-enterprise-solutions-engineer-1390103700",
    companySlug: "dynatrace",
    title: "Japan Enterprise Solutions Engineer",
    segment: "Enterprise Presales / Observability & Security",
    location: "東京（日本）",
    workStyle: "Flex勤務。固定出社日数は公式求人で明記なし",
    language: "日本語・英語の顧客／global collaboration水準は選考で確認",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Dynatrace Careers", url: "https://apply.careers.dynatrace.com/job/Tokyo-Sr-Solutions-Engineer-Toky-100-0005/1390103700/" },
    descriptionSummary: "Enterprise顧客のapplication・cloud・log・security課題をdiscoveryし、demo、workshop、technical validation、business value設計を通じてtechnical winを作る。",
    genbaTake: "監視toolの比較ではなく、障害時間、運用工数、digital revenue、AI reliabilityを一つのobservability business caseへ翻訳するpresales role。",
    compensationReality: "日本向けのbase、bonus・variable、equity、目標値は公式求人で確認できない。",
    desiredProfile: "Enterprise observability、cloud、application performance、securityの技術理解と、経営・IT双方へのvalue communicationを持つ人。",
    careerInsights: careerInsights("Japan Enterprise Solutions Engineer", "Observability・AIOps・Application Security"),
  },
];
