import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildIntelligence, type Profile } from "@/lib/company-public-intelligence-wave-two";
import { applyStandard, buildCompactPatch, type CompactPatchInput } from "@/lib/company-page-rollout-standard-helpers";

const checkedAt = "2026-08-22";
const thinkCellCheckedAt = "2026-08-28";

function build(profile: Profile, patch: CompactPatchInput) {
  const intelligence = buildIntelligence(profile);
  applyStandard(intelligence, buildCompactPatch(patch));
  intelligence.researchedAt = checkedAt;
  if (intelligence.cultureDeepDive) intelligence.cultureDeepDive.researchedAt = "2026.08.22";
  return intelligence;
}

function publicMarketRead(slug: "workiva" | "sailpoint", metrics: Array<{ label: string; value: string; change: string; interpretation: string }>) {
  return {
    asOf: checkedAt,
    metrics: metrics.map((metric) => ({ ...metric, sourceId: `${slug}-finance` })),
    growthDrivers: [{ title: "既存基盤からの拡張", evidence: "最新の会社公式開示と顧客基盤を確認。", japanMeaning: "日本ではglobal scaleではなく、local pipelineと導入後の拡張が投資継続の鍵になる。", sourceIds: [`${slug}-finance`, `${slug}-customers`] }],
    risks: [{ title: "競争と日本GTMの実行", disclosedRisk: "大手suite・cloud・専門vendorとの競争が続く。", companyResponse: "製品portfolioと市場投資を拡張している。", genbaRead: "日本売上、顧客数、達成率が未公開のため、global成長を国内territoryの容易さへ置き換えない。", sourceIds: [`${slug}-finance`, `${slug}-company`] }],
    japanCommitment: {
      verdict: "現行Japan求人は確認できるが、国内売上・顧客数・達成率は未公開。",
      summary: "公式求人、顧客事例、製品投資をsignalとして扱い、global決算だけから日本の成長を断定しない。",
      signals: [{ year: "2026", title: "現行Japan求人", detail: "公式Careerで日本向けroleを確認。", sourceIds: [`${slug}-job`] }],
      unknowns: ["日本売上・ARR", "国内顧客数・segment別pipeline", "quota・達成率・採用計画"],
    },
    scenarios: [
      { scenario: "基本" as const, title: "既存基盤から選択的に拡張", body: "明確なuse caseとbuyerで国内pipelineを作る。" },
      { scenario: "上振れ" as const, title: "複数製品の定着が加速", body: "国内proofと導入capacityが増え、new logoとexpansionが同時に伸びる。" },
      { scenario: "下振れ" as const, title: "競合と実装負荷で停滞", body: "bundling、価格、移行、運用負荷でsales cycleとadoptionが悪化する。" },
    ],
    sourceIds: [`${slug}-finance`, `${slug}-company`, `${slug}-customers`, `${slug}-job`],
  };
}

const workivaIntelligence = build({
  checkedAt,
  slug: "workiva",
  name: "Workiva",
  jobUrl: "https://workiva.wd503.myworkdayjobs.com/en-US/careers/job/Account-Executive_R10985",
  officialUrl: "https://www.workiva.com/company/about",
  customersUrl: "https://www.workiva.com/customers",
  externalUrl: "https://www.fsa.go.jp/policy/kaiji/",
  financeUrl: "https://investor.workiva.com/financial-information/annual-reports",
  publicInfo: { ticker: "WK", exchange: "NYSE", listedSince: "2014年" },
  salesSnapshot: "財務報告、法定開示、監査、risk、sustainabilityで散在するdataと証跡を一つの統制されたworkflowへつなぐ会社。日本のAEはCFO・CRO等へ、決算速度だけでなくaccuracy、traceability、controlのbusiness caseを売る。",
  growthSummary: "NYSE上場企業。2025年通期売上は約8.85億ドル、顧客6,624社、gross retention 97.2%を公式発表。日本の売上、顧客数、team人数、seller達成率は非公開。",
  milestones: [
    { year: "2008", label: "創業", detail: "複雑なbusiness reportingをcloudで共同作業する発想から設立。", source: "company" },
    { year: "2014", label: "NYSE上場", detail: "ticker WKで上場。", source: "finance" },
    { year: "2021", label: "ESG reporting拡張", detail: "財務以外のsustainability reportingをplatformへ統合。", source: "company" },
    { year: "2025", label: "売上約8.85億ドル", detail: "通期決算の会社公式発表。", source: "finance" },
    { year: "2026.08", label: "日本事業開始済みを確認", detail: "東京のAccount Executive応募導線を公式ATSで確認。日本事業の開始年自体は未確認。", source: "job" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "公式事例は、spreadsheet、email、documentへ分散した数値・文章・approvalをつなぎ、reporting期間、手戻り、version差異、audit対応を減らす目的を示す。" },
    { title: "製品の成り立ちから見る課題", body: "WorkivaはSEC reportingの共同作業から始まり、財務、GRC、sustainabilityへ拡張した。核はsource dataから最終報告までのlink、権限、変更履歴を切らさないこと。" },
    { title: "外部環境の要求から見る課題", body: "開示制度とsustainability基準が変わり、CFOは短いclose期間の中で複数部門のdataを集め、数値根拠、承認、内部統制を説明する必要がある。" },
  ],
  narrative: [
    { label: "背景", body: "財務・risk・sustainability報告のdata ownerとsystemが増え、締切と説明責任は厳しくなる。" },
    { label: "課題", body: "copy-and-pasteとemail approvalではversion差異、手戻り、audit evidenceの探索が増え、経営判断と開示が遅れる。" },
    { label: "解決策", body: "一つの高頻度reportでsource link、collaboration、approval、audit trailを統合し、作成時間と修正件数を測る。" },
    { label: "選定の理由", body: "Microsoft 365、ERP・CPM、GRC、point reporting toolとの比較で、複数報告を同じcontrol modelで運用できる場合に選ぶ。" },
  ],
  openingHook: "決算・開示の締切前に、最新値の確認と根拠資料の回収へ何人が何時間使っていますか。",
  valueHypothesis: "report作成日数、manual link数、修正件数、approval時間、audit evidence探索時間を導入前後で比較する。",
  objection: "Excel、PowerPoint、ERP、既存開示toolで足りており、新しいplatformは運用を増やす。",
  reframe: "authoring機能ではなく、source-to-reportのlink、version、権限、control、複数報告の再利用を含む総工数とriskで比較する。",
  facts: [
    { label: "創業", value: "2008年", detail: "米国Iowa発。", source: "company" },
    { label: "上場", value: "NYSE: WK", detail: "2014年上場。", source: "finance" },
    { label: "2025年売上", value: "約8.85億ドル", detail: "会社公式の通期決算。", source: "finance" },
    { label: "顧客", value: "6,624社", detail: "2025年末の会社公式発表。", source: "finance" },
    { label: "Gross retention", value: "97.2%", detail: "2025年末。顧客拡張を含まない指標。", source: "finance" },
    { label: "日本求人", value: "Account Executive 1件", detail: "東京の公式求人を確認。", source: "job" },
  ],
  customers: [
    { company: "Deschutes County", products: "Workiva Financial Reporting", outcome: "budget book作成で60〜65%の時間削減見込みを公式事例で紹介。", implication: "複数sourceとnarrative collaborationを同じworkflowへ統合するproof。" },
    { company: "公開顧客事例群", products: "Financial Reporting / GRC / Sustainability", outcome: "財務、risk、sustainabilityの複数use caseを公式顧客一覧で公開。", implication: "一部署のpoint toolではなく複数reporting processへ拡張できる。" },
  ],
  externalSignals: [
    { label: "企業開示", value: "制度変更への継続対応", detail: "金融庁は企業開示に関する制度・様式・審議情報を継続更新している。", caveat: "適用要件と時期は企業・市場で異なる。" },
    { label: "sustainability", value: "非財務dataの統制", detail: "sustainability情報でも財務報告に近いdata ownership、証跡、reviewが必要になる。", caveat: "platform導入だけで開示適合を保証しない。" },
  ],
  role: "東京のAccount Executiveがnew businessとcustomer expansionを持ち、Inside Sales、Solution Seller、Partnerとexecutive buyerのsales cycleを進める。",
  organization: "Tokyo full-time role。flexible workと最大30%の出張を記載するが、日本team人数、雇用主体、reporting line、出社頻度は未公開。",
  careerValue: "CFO・CRO・Sustainability buyer、connected reporting、GRC、multi-solution expansionを一つのEnterprise sales motionで扱う経験。",
  globalHeadcount: "2,500人超",
  japanPresence: "東京拠点・Japan Account Executiveを確認",
  japanSince: "日本事業開始年は一次情報で未確認",
  solutions: [
    { name: "Workiva Platform", valueProp: "source dataから報告、approval、audit trailまでを接続する。", url: "https://www.workiva.com/platform", competitors: "Microsoft 365、ERP・CPM、point reporting tool。", differentiation: "linked dataとcontrolled collaborationを複数報告へ再利用。" },
    { name: "Financial Reporting", valueProp: "決算・法定開示・management reportingを統制する。", url: "https://www.workiva.com/solutions/financial-reporting", competitors: "ERP reporting、CPM、開示専用tool。", differentiation: "数値とnarrativeを同じcontrolで管理。" },
    { name: "GRC", valueProp: "risk、control、audit、evidenceをつなぐ。", url: "https://www.workiva.com/solutions/governance-risk-and-compliance", competitors: "ServiceNow GRC、AuditBoard、spreadsheet。", differentiation: "reportingとrisk dataを同じplatformへ接続。" },
  ],
  fitTags: ["CFO", "Enterprise", "Financial Reporting", "GRC", "Sustainability", "New Business", "Expansion"],
  comparisons: [
    { arena: "Connected reporting", companies: ["Workiva", "Microsoft 365", "ERP・CPM"], why: "data link、control、collaboration、総工数" },
    { arena: "GRC", companies: ["Workiva", "ServiceNow GRC", "AuditBoard"], why: "risk dataとreportingの統合" },
    { arena: "Disclosure", companies: ["Workiva", "開示専用tool", "manual workflow"], why: "証跡、変更管理、制度対応" },
  ],
}, {
  slug: "workiva", leaderName: "Julie Iskow", leaderLabel: "President / CEO", leaderUrl: "https://www.workiva.com/company/leadership", localName: "未確認", localLabel: "Japan責任者", localUrl: "https://workiva.wd503.myworkdayjobs.com/en-US/careers/job/Account-Executive_R10985",
  companyId: "workiva-company", jobId: "workiva-job", customersId: "workiva-customers", externalId: "workiva-external", financeId: "workiva-finance",
  targets: ["経理・財務・開示部門", "内部監査・risk部門", "Sustainability・ESG reporting部門"],
  heroSummary: "決算・開示・risk・sustainabilityのdataと証跡がspreadsheet、email、複数systemへ分かれ、締切前の手戻りと説明riskが増える課題を解決する。source-to-reportをlinkし、変更、approval、controlを同じworkflowで管理する。",
  competitors: "Microsoft 365、ERP・CPM、GRC、開示専用toolとの比較では、data link、control、複数報告の再利用、導入負荷を見る。",
  feature: "Financial Reporting、GRC、Sustainabilityをlinked data、collaboration、approval、audit trailで統合する。",
  advantage: "数値とnarrativeをsourceから最終reportまでつなぎ、同じdataを複数の規制・経営報告へ再利用できる。",
  benefit: "reporting期間、manual link、修正、approval、audit evidence探索を減らし、締切と説明責任を両立する。",
  evidence: "Deschutes Countyの公式事例はbudget book作成で60〜65%の時間削減見込みを示す。国内named caseは今回の一次調査で確認できず。",
  marketVerdict: "開示・統制需要とglobal retentionは強い一方、日本の顧客数、territory、team、達成率を面接で分けて確認したい。",
  marketParagraphs: ["企業開示とsustainability報告が変化するほど、data lineage、approval、audit evidenceを保ったreporting workflowが必要になる。", "日本では既存のExcel・ERP・開示toolを置き換えるのではなく、分断をつなぐ価値とchange managementを定量化できるかが成長条件になる。"],
  cultureHeadline: "CFO領域の複数solutionを、partnerと専門sellerを束ねて売るEnterprise matrix role。",
  classification: "未確認", displayLabel: "Flexible work（出社頻度は未確認）", officeDays: "Tokyo officeの利用頻度は未記載", remoteOnly: "remote専任ではない", flexibility: "最大30%の出張を記載",
  goodFor: ["CFO・GRCへ複数solutionを売りたい人", "new logoとexpansionを両方持ちたい人"], cautionFor: ["単一productの短期saleだけを望む人", "既存territoryの完成を前提にする人"],
  unresolved: [
    ["territory", "new businessとexpansionを担当する。", "日本のnamed account、既存顧客、white space、担当社数は何ですか。"],
    ["quota", "複数のcomplex sales cycleを持つ。", "quota、pay mix、ACV、cycle、coverage、ramped seller達成率は。"],
    ["pipeline", "Inside Sales・Partnerと協働する。", "self-source、marketing、partnerのpipeline構成とcredit ruleは。"],
    ["delivery", "複数solutionを扱う。", "Solution Seller、SE、CS、Professional Servicesの日本coverageは。"],
    ["career", "Japan teamの公開集計はない。", "直近24カ月の昇進・異動・退職と次levelの基準は。"],
  ],
});

workivaIntelligence.marketStatus.capitalMarketRead = publicMarketRead("workiva", [
  { label: "FY2025売上", value: "8.846億ドル", change: "通期公式値", interpretation: "顧客基盤と複数solutionの拡張余地を持つ。" },
  { label: "Gross retention", value: "97.2%", change: "2025年末", interpretation: "高い継続率だが、日本の達成率を示す指標ではない。" },
]);

const outsystemsIntelligence = build({
  checkedAt,
  slug: "outsystems",
  name: "OutSystems",
  jobUrl: "https://outsystems.wd503.myworkdayjobs.com/en-US/OutSystems/job/Senior-Account-Executive_R1544",
  officialUrl: "https://www.outsystems.com/company/",
  customersUrl: "https://www.outsystems.com/case-studies/toyota-low-code-journey",
  externalUrl: "https://www.meti.go.jp/policy/it_policy/dx/dx.html",
  financeUrl: "https://www.outsystems.com/company/",
  salesSnapshot: "legacy applicationの保守負荷と開発backlogを、AI・low-codeの開発速度、enterprise architecture、governanceで解く会社。日本のEnterprise AEはnew logoとnamed accountをSI ecosystemと作る。",
  growthSummary: "2001年創業の非公開企業。公式求人は1,700人、900K超のdeveloper community、600超のpartner、75カ国超の顧客を表示。日本売上とteam人数は非公開。",
  ipoSummary: "非公開企業。売上、ARR、企業価値、IPO時期、日本単体業績は公表されていない。",
  milestones: [
    { year: "2001", label: "創業", detail: "Paulo Rosadoがenterprise application開発の複雑さを減らすため設立。", source: "company" },
    { year: "2014", label: "Toyota導入開始", detail: "小規模PoCからToyota Groupへ拡張。", source: "company" },
    { year: "2024", label: "Toyota 10周年", detail: "23社・70超projectへの展開を公式事例で紹介。", source: "company" },
    { year: "2026", label: "AI Development Platform", detail: "agentic systemとlegacy modernizationを一つのplatform storyへ拡張。", source: "company" },
    { year: "2026.08", label: "日本事業開始済みを確認", detail: "AE、BDR、SA、CS、Alliance等の東京求人を確認。日本事業の開始年自体は未確認。", source: "job" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "Toyotaはlegacy modernizationと開発生産性を目的に小規模利用から23社・70超projectへ拡張し、従来開発比で工数30%削減を公式事例で示す。" },
    { title: "製品の成り立ちから見る課題", body: "OutSystemsはmodel-drivenなrapid application developmentから、full lifecycle、architecture、AI agent、governanceへ拡張した。核は速度とenterprise-grade運用を両立すること。" },
    { title: "外部環境の要求から見る課題", body: "legacy systemとIT人材不足が残る中、生成AIでprototypeは速くなっても、security、integration、maintenance、governanceを満たしてproductionへ運ぶ責任が残る。" },
  ],
  narrative: [
    { label: "背景", body: "legacy更新と新規digital serviceの需要が同時に増え、developerとSI deliveryが不足する。" },
    { label: "課題", body: "個別codeとpoint AI toolを増やすと、開発速度は上がってもintegration、security、保守、governanceの負債が残る。" },
    { label: "解決策", body: "一つの重要applicationを対象に、開発、integration、test、deploy、運用をplatform化し、lead timeと品質を測る。" },
    { label: "選定の理由", body: "custom development、ServiceNow・Microsoft Power Platform、Mendix、AI coding toolとの比較で、mission-critical用途の速度、統制、拡張性に優位がある場合に選ぶ。" },
  ],
  openingHook: "最優先のapplication改修が要件確定からproductionまで何カ月待ちになっていますか。",
  valueHypothesis: "development lead time、工数、release頻度、defect、legacy retirement、developer productivityをbaseline比較する。",
  objection: "low-codeは複雑な基幹systemに向かず、AI codingと既存SIで十分。",
  reframe: "code生成速度ではなく、integration、security、governance、運用、変更容易性、全lifecycle costで比較する。",
  facts: [
    { label: "創業", value: "2001年", detail: "Portugal発。", source: "company" },
    { label: "従業員", value: "1,700人", detail: "2026年公式求人記載。", source: "company" },
    { label: "Developer community", value: "900K超", detail: "公式求人記載。", source: "company" },
    { label: "Partner", value: "600超", detail: "公式求人記載。", source: "company" },
    { label: "Toyota", value: "23社・70超project", detail: "Toyota Groupの公式事例。", source: "customers" },
    { label: "日本求人", value: "複数職種", detail: "AE、BDR、SA、CS、Alliance等を確認。", source: "job" },
  ],
  customers: [
    { company: "Toyota Motor Corporation", products: "OutSystems Platform", outcome: "23のToyota Group企業、70超projectへ拡張し、初期projectで工数30%削減。", implication: "国内Enterpriseでsmall startからCoEへ広げるproof。" },
    { company: "Medtronic", products: "OutSystems", outcome: "80,000人規模のemployee portalを公式事例で紹介。", implication: "大規模なinternal applicationとintegrationのproof。" },
    { company: "Dah Chong Hong", products: "OutSystems", outcome: "repair order processを週・月単位から日単位へ短縮した公式事例。", implication: "operation lead timeをbusiness outcomeへ変換できる。" },
  ],
  externalSignals: [
    { label: "legacy system", value: "modernization継続", detail: "経産省はlegacy systemとDX推進の遅れを継続課題として扱う。", caveat: "全systemをlow-codeへ移すことを意味しない。" },
    { label: "生成AI開発", value: "production governance", detail: "AIで開発が速くなるほど、data、security、test、approval、運用の統制が投資条件になる。", caveat: "効果はapplication種別で異なる。" },
  ],
  role: "東京のSenior AEがEnterprise新規市場とstrategic named accountを持ち、local・global SI、商社、technical teamを束ねて高額契約をcloseする。",
  organization: "Japan officeのHybrid・正社員。AE以外にもBDR、SA、CS、Alliance等の採用を確認するが、team人数とreporting lineは非公開。",
  careerValue: "application modernization、AI development、SI ecosystem、named account、複雑なEnterprise契約を横断する経験。",
  globalHeadcount: "1,700人",
  japanPresence: "東京office・日本法人・Japan team",
  japanSince: "日本進出年は一次情報で未確認",
  solutions: [
    { name: "OutSystems AI Development Platform", valueProp: "enterprise applicationとagentを設計・開発・運用する。", url: "https://www.outsystems.com/platform/", competitors: "Mendix、Microsoft Power Platform、custom development。", differentiation: "speedとenterprise architecture・governanceを一体化。" },
    { name: "App Modernization", valueProp: "legacy applicationを段階的に刷新する。", url: "https://www.outsystems.com/solutions/app-modernization/", competitors: "SI rebuild、package導入、rehost。", differentiation: "既存system連携と反復release。" },
    { name: "AI Agent Workbench", valueProp: "enterprise dataとworkflowへagentを接続し統制する。", url: "https://www.outsystems.com/", competitors: "AI coding tool、agent builder、custom framework。", differentiation: "application lifecycleと同じgovernanceへ載せる。" },
  ],
  fitTags: ["Enterprise", "Low-code", "AI Development", "App Modernization", "New Logo", "Partner", "Named Accounts"],
  comparisons: [
    { arena: "Enterprise low-code", companies: ["OutSystems", "Mendix", "Microsoft Power Platform"], why: "complexity、governance、delivery ecosystem" },
    { arena: "Modernization", companies: ["OutSystems", "custom rebuild", "package・rehost"], why: "lead time、risk、changeability" },
    { arena: "AI application", companies: ["OutSystems", "AI coding tools", "custom agent framework"], why: "production、integration、governance" },
  ],
}, {
  slug: "outsystems", leaderName: "Paulo Rosado", leaderLabel: "Founder / CEO", leaderUrl: "https://www.outsystems.com/company/leadership/", localName: "未確認", localLabel: "Japan責任者", localUrl: "https://outsystems.wd503.myworkdayjobs.com/en-US/OutSystems/job/Senior-Account-Executive_R1544",
  companyId: "outsystems-company", jobId: "outsystems-job", customersId: "outsystems-customers", externalId: "outsystems-external", financeId: "outsystems-finance",
  targets: ["CIO・application開発部門", "DX・内製化責任者", "legacy modernization・AI推進部門"],
  heroSummary: "legacy applicationの保守と新規開発backlogが増え、生成AIのprototypeもproductionのsecurity・integration・運用へ進めない課題を解決する。開発からdeploy・governanceまでをplatform化し、速度とenterprise-grade運用を両立する。",
  competitors: "Mendix、Microsoft Power Platform、custom development、SI、AI coding toolとの比較では、complexity、integration、governance、lifecycle costを見る。",
  feature: "model-driven development、integration、deployment、monitoring、AI agent、governanceを一つのplatformで提供する。",
  advantage: "prototype速度だけでなく、mission-critical applicationを長期運用するarchitectureと統制を同じlifecycleへ組み込む。",
  benefit: "development lead time、工数、release待ち、legacy maintenanceを減らし、business changeへの対応を速める。",
  evidence: "Toyotaは国内公式事例で23社・70超projectへ展開し、初期projectで工数30%削減を示す。",
  marketVerdict: "複数のJapan求人とToyota proofは強い。急速な採用がterritoryとdelivery capacityに見合うかを確認したい。",
  marketParagraphs: ["legacy systemとIT人材不足が続くほど、開発速度だけでなく保守・security・governanceを含むmodernization基盤が必要になる。", "日本ではSI ecosystemと内製化を対立させず、顧客・partnerが継続運用できるCoEを作れるかが成長条件になる。"],
  cultureHeadline: "Japan teamを複数職種で拡張し、named accountとpartner ecosystemを同時に作る局面。",
  classification: "ハイブリッド", displayLabel: "Tokyo Hybrid / Office-based", officeDays: "具体的な出社日数は未記載", remoteOnly: "remote専任ではない", flexibility: "国内顧客訪問の出張あり",
  goodFor: ["large-scale modernizationを売りたい人", "SIと内製化の両方を動かしたい人"], cautionFor: ["短いpoint solution saleだけを望む人", "partner coordinationを避けたい人"],
  unresolved: [
    ["segment", "Enterprise named accountを担当する。", "named account数、既存顧客、white space、industry境界は。"],
    ["quota", "高額Enterprise契約をcloseする。", "quota、ACV、cycle、coverage、ramped seller達成率は。"],
    ["partner", "SI・商社とのco-sellを重視する。", "partner-sourced比率、seller credit、delivery品質の責任者は。"],
    ["delivery", "JapanでSA・CS等も採用する。", "案件数に対するSA、CS、services、support capacityは。"],
    ["career", "teamを急速に拡張中。", "直近24カ月の昇進・異動・退職とmanagement spanは。"],
  ],
});

const sailpointIntelligence = build({
  checkedAt,
  slug: "sailpoint",
  name: "SailPoint",
  jobUrl: "https://sailpoint.wd1.myworkdayjobs.com/en-US/SailPoint/job/Strategic-Account-Executive--Agentic-Technologies-Specialist--Japan_R013034-1",
  officialUrl: "https://www.sailpoint.com/why-us/about-us",
  customersUrl: "https://www.sailpoint.com/customers",
  externalUrl: "https://www.nisc.go.jp/policy/group/general/zerotrust.html",
  financeUrl: "https://investor.sailpoint.com/",
  publicInfo: { ticker: "SAIL", exchange: "NASDAQ", listedSince: "2025年再上場" },
  salesSnapshot: "employeeだけでなくcontractor、machine、AI agentまで、誰が何のapplication・dataへaccessできるかを発見・承認・監査する会社。日本のspecialist AEはIdentity SecurityをAI・data governanceの投資へ広げる。",
  growthSummary: "2025年にNASDAQへ再上場。公式求人はFortune 500の約半数を顧客に含むと説明する。日本のARR、顧客数、team人数、Agentic製品の売上構成は非公開。",
  milestones: [
    { year: "2005", label: "創業", detail: "Mark McClainらがidentity governanceの複雑さを解くため設立。", source: "company" },
    { year: "2017", label: "NYSE上場", detail: "最初の株式公開。", source: "finance" },
    { year: "2022", label: "Thoma Bravo非公開化", detail: "買収により非公開化。", source: "finance" },
    { year: "2025", label: "NASDAQ再上場", detail: "ticker SAILで公開市場へ復帰。", source: "finance" },
    { year: "2026.08", label: "日本事業開始済みを確認", detail: "東京office・Japan remoteのspecialist AEを確認。日本事業の開始年自体は未確認。", source: "job" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "公式事例は、joiner・mover・leaverのaccessを自動化し、manual request、過剰権限、audit evidence回収を減らす目的を示す。" },
    { title: "製品の成り立ちから見る課題", body: "SailPointはidentity governanceから始まり、cloud access、data access、machine identity、agent identityへ対象を拡張した。核はidentityをsecurity controlの中心に置くこと。" },
    { title: "外部環境の要求から見る課題", body: "cloud、SaaS、API、AI agentでaccess主体と権限が増え、企業はleast privilege、継続的なreview、退職・異動時の削除、監査証跡を説明する必要がある。" },
  ],
  narrative: [
    { label: "背景", body: "人、外部委託、service account、machine、AI agentが複数cloud・SaaS・dataへ接続する。" },
    { label: "課題", body: "manual approvalとsystem別管理ではaccessのownerが見えず、過剰権限、orphan account、audit工数が増える。" },
    { label: "解決策", body: "high-riskな一部identityとapplicationから、discovery、request、approval、certification、revocationを統合して測る。" },
    { label: "選定の理由", body: "Microsoft Entra、Okta、CyberArk、Saviynt、manual IAMとの比較で、identity全体のvisibility、governance、automationに優位がある場合に選ぶ。" },
  ],
  openingHook: "退職者、外部委託、service account、AI agentが今どのdataへaccessできるか、何時間で証明できますか。",
  valueHypothesis: "provisioning日数、manual ticket、certification工数、orphan account、excess privilege、audit evidence時間を比較する。",
  objection: "Microsoft Entra、Okta、PAM、既存IAMで十分で、identity toolを増やしたくない。",
  reframe: "authentication機能ではなく、全identity・resourceのvisibility、policy、approval、certification、revocationのcoverageで比較する。",
  facts: [
    { label: "創業", value: "2005年", detail: "Austin発。", source: "company" },
    { label: "上場", value: "NASDAQ: SAIL", detail: "2025年再上場。", source: "finance" },
    { label: "顧客構成", value: "Fortune 500の約半数", detail: "公式求人記載。", source: "company" },
    { label: "領域", value: "Identity Security", detail: "人・machine・agent・data accessを対象。", source: "company" },
    { label: "勤務地", value: "Tokyo / Japan remote", detail: "現行求人。", source: "job" },
    { label: "日本求人", value: "Agentic specialist AE 1件", detail: "公式ATSで確認。", source: "job" },
  ],
  customers: [
    { company: "Globe Telecom", products: "SailPoint Identity Security", outcome: "新入社員のidentityを入社5日前にprovisionしday one accessを実現した公式事例。", implication: "employee lifecycleをbusiness productivityへつなぐproof。" },
    { company: "Pima Community College", products: "SailPoint", outcome: "145,210 identityを対象にhomegrown systemからmodernizeした公式事例。", implication: "大規模identityのvisibilityとscale。" },
    { company: "公式顧客事例群", products: "Identity Security Cloud", outcome: "education、healthcare、manufacturing、energy、technologyの事例を公開。", implication: "industryを跨ぐgovernance需要。" },
  ],
  externalSignals: [
    { label: "Zero Trust", value: "identity中心のaccess判断", detail: "NISCは境界依存ではなくresourceごとのaccess controlを含むZero Trust情報を公開する。", caveat: "特定製品の採用を要求するものではない。" },
    { label: "AI agent", value: "non-human identity増加", detail: "agentがdataとtoolを操作するほど、owner、権限、credential、行動証跡の管理が必要になる。", caveat: "市場規模と導入優先度は企業ごとに異なる。" },
  ],
  role: "Japan specialist AEがMachine Identity、Data Access、Agent Identityを担当し、primary AE・CS・BDのenablement、partner施策、territory、demo、RFP、quotaを持つ。",
  organization: "Tokyo local officeまたはJapan remoteのfull-time overlay role。日本team人数、specialist credit、reporting line、出社頻度は非公開。",
  careerValue: "Identity Security、AI・data governance、specialist overlay、primary seller enablement、Enterprise matrix sellingを横断する経験。",
  globalHeadcount: "2,500人超",
  japanPresence: "東京local office・Japan remote",
  japanSince: "日本事業開始年は一次情報で未確認",
  solutions: [
    { name: "Identity Security Cloud", valueProp: "identityの発見、access request、certification、provisioningを統合する。", url: "https://www.sailpoint.com/products/identity-security-cloud", competitors: "Saviynt、Microsoft Entra ID Governance、manual IAM。", differentiation: "identity dataとgovernance workflowのcoverage。" },
    { name: "Machine Identity Security", valueProp: "service account・machine identityのownerとlifecycleを管理する。", url: "https://www.sailpoint.com/products/machine-identity-security", competitors: "PAM、secrets management、custom inventory。", differentiation: "human identityと同じgovernanceへ接続。" },
    { name: "Data Access Security", valueProp: "unstructured dataへのaccessを可視化・統制する。", url: "https://www.sailpoint.com/products/data-access-security", competitors: "DSPM、DLP、manual entitlement review。", differentiation: "identity contextとdata accessを関連付ける。" },
  ],
  fitTags: ["Identity Security", "Agentic AI", "Data Governance", "Machine Identity", "Specialist Sales", "Overlay", "Japan"],
  comparisons: [
    { arena: "Identity governance", companies: ["SailPoint", "Saviynt", "Microsoft Entra"], why: "coverage、automation、ecosystem" },
    { arena: "Machine identity", companies: ["SailPoint", "PAM", "secrets management"], why: "discovery、owner、lifecycle" },
    { arena: "Data access", companies: ["SailPoint", "DSPM・DLP", "manual review"], why: "identity contextとpolicy" },
  ],
}, {
  slug: "sailpoint", leaderName: "Mark McClain", leaderLabel: "Founder / CEO", leaderUrl: "https://www.sailpoint.com/why-us/leadership", localName: "未確認", localLabel: "Japan責任者", localUrl: "https://sailpoint.wd1.myworkdayjobs.com/en-US/SailPoint/job/Strategic-Account-Executive--Agentic-Technologies-Specialist--Japan_R013034-1",
  companyId: "sailpoint-company", jobId: "sailpoint-job", customersId: "sailpoint-customers", externalId: "sailpoint-external", financeId: "sailpoint-finance",
  targets: ["CISO・Identity Security部門", "IAM・IT運用部門", "Data・AI governance部門"],
  heroSummary: "employee、外部委託、machine、AI agentが増え、誰がどのapplication・dataへaccessできるか説明できず、過剰権限とaudit工数が増える課題を解決する。identity lifecycleとaccess governanceを自動化し、least privilegeと事業速度を両立する。",
  competitors: "Saviynt、Microsoft Entra、Okta、CyberArk、manual IAMとの比較では、identity coverage、governance、automation、導入責任を見る。",
  feature: "Identity Security Cloud、Machine Identity、Data Access、Agent Identityでaccess lifecycleを統合する。",
  advantage: "authenticationやPAMの一点ではなく、人・machine・agentとapplication・dataの関係を同じidentity governanceへ接続する。",
  benefit: "provisioning、certification、revocation、audit evidenceを速め、過剰権限とmanual ticketを減らす。",
  evidence: "Globe Telecomは公式事例で入社5日前のprovisioningとday one accessを紹介。国内named caseは今回の一次調査で確認できず。",
  marketVerdict: "AI agentとmachine identityは追い風だが、specialist製品のJapan pipeline、primary AEとのcredit、delivery readinessが成否を分ける。",
  marketParagraphs: ["cloud・SaaS・AI agentが増えるほど、authentication後のentitlementと継続的なaccess reviewがsecurity controlの中心になる。", "日本では既存IAM・Microsoft・PAMとの役割を明確にし、段階導入でauditとbusiness productivityの両方を示す必要がある。"],
  cultureHeadline: "primary AEをenableしながら新categoryを作る、専門性と影響力が必要なoverlay role。",
  classification: "未確認", displayLabel: "Tokyo officeまたはJapan remote", officeDays: "選択肢はあるが頻度は未記載", remoteOnly: "remote専任ではない", flexibility: "Japan内の勤務選択肢を公式求人で確認",
  goodFor: ["IdentityとAI governanceを横断したい人", "overlayでsellerをscaleしたい人"], cautionFor: ["単独ownershipだけを望む人", "成熟済みcategoryだけを売りたい人"],
  unresolved: [
    ["credit", "primary AEを支援するoverlay role。", "specialist quota、co-prime credit、primary AEとの優先順位は。"],
    ["pipeline", "Agentic関連製品を日本で拡張する。", "既存customer attach、新規logo、partner別のpipeline構成は。"],
    ["product readiness", "machine・data・agent identityを扱う。", "Japanでproduction導入済みの製品別件数とreference architectureは。"],
    ["delivery", "technical resourceをleadする。", "日本語SE、CS、services、supportのcoverageと責任分界は。"],
    ["career", "新しいspecialist category。", "次role、昇進基準、直近の異動・退職、global teamへのpathは。"],
  ],
});

sailpointIntelligence.marketStatus.capitalMarketRead = publicMarketRead("sailpoint", [
  { label: "NASDAQ再上場", value: "2025年", change: "公開市場へ復帰", interpretation: "成長投資と収益性を公開市場で継続確認する段階。" },
  { label: "顧客構成", value: "Fortune 500の約半数", change: "公式求人記載", interpretation: "Enterprise proofは強いが、日本の顧客数は未公開。" },
]);

const pingcapIntelligence = build({
  checkedAt,
  slug: "pingcap",
  name: "PingCAP",
  jobUrl: "https://jobs.lever.co/pingcap/5de30748-2a1e-45be-bea5-ddf514d3719c",
  officialUrl: "https://pingcap.co.jp/",
  customersUrl: "https://pingcap.co.jp/case-study/",
  externalUrl: "https://www.digital.go.jp/resources/standard_guidelines",
  financeUrl: "https://www.pingcap.com/about-us/",
  salesSnapshot: "MySQL workloadがscale、sharding、HA/DR、運用costで限界になる課題を、distributed SQLとcloud databaseで解く会社。日本のSolution ArchitectはPoC・benchmarkでtechnical riskをbusiness growthへ翻訳する。",
  growthSummary: "2015年創業の非公開企業。公式求人はTiDBがglobalで3,000社超に採用と説明。PingCAP株式会社は2021年3月設立。売上、ARR、日本team人数は非公開。",
  ipoSummary: "非公開企業。売上、ARR、企業価値、IPO時期、日本単体業績は公表されていない。",
  milestones: [
    { year: "2015", label: "創業", detail: "distributed database TiDBの開発会社として設立。", source: "company" },
    { year: "2015", label: "TiDB open source", detail: "MySQL互換のdistributed SQL databaseを公開。", source: "company" },
    { year: "2021.03", label: "日本法人設立", detail: "PingCAP株式会社を東京・大手町に設立。公式求人の会社概要で確認。", source: "company" },
    { year: "2024", label: "国内production事例拡大", detail: "Tokyo Gas、MIXI等の国内事例を公開。", source: "company" },
    { year: "2026.08", label: "Japan SA採用", detail: "東京のSolution Architectを公式Leverで確認。", source: "job" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "Tokyo GasやMIXI等の公式事例は、MySQL互換を保ちながらscale、可用性、運用負荷、cloud migrationを改善する目的を示す。" },
    { title: "製品の成り立ちから見る課題", body: "TiDBはCAP定理の制約下でscaleとconsistencyを両立するdistributed SQLとして生まれ、HTAPとmanaged cloudへ拡張した。" },
    { title: "外部環境の要求から見る課題", body: "digital serviceとAI workloadでtransaction・data量が増え、企業は停止を抑えながらdatabaseをscaleし、cloud cost、data residency、backup、DR、auditを説明する必要がある。" },
  ],
  narrative: [
    { label: "背景", body: "trafficとdata量が増え、単一MySQLとmanual shardingの運用が複雑になる。" },
    { label: "課題", body: "scaleのたびにapplication改修、rebalancing、planned downtime、HA/DR設計、specialist工数が増える。" },
    { label: "解決策", body: "一つのproduction候補workloadでcompatibility、throughput、latency、failover、migration、costをPoC・benchmarkする。" },
    { label: "選定の理由", body: "Aurora、Cloud Spanner、AlloyDB、CockroachDB、MySQL shardingとの比較で、compatibility、scale、HTAP、運用に優位がある場合に選ぶ。" },
  ],
  openingHook: "次のtraffic peakとdata増加に備え、MySQLのshard追加・failover・maintenanceへ何人月を見込んでいますか。",
  valueHypothesis: "throughput、p95 latency、failover、planned downtime、sharding工数、DB cost、migration工数を比較する。",
  objection: "AuroraやCloud Spanner、既存MySQLのscale-upで十分で、新しいdistributed databaseはriskが高い。",
  reframe: "benchmark速度だけでなく、compatibility、failure mode、運用人材、migration、cloud lock-in、3年TCOで比較する。",
  facts: [
    { label: "創業", value: "2015年", detail: "TiDB開発会社として設立。", source: "company" },
    { label: "国内法人", value: "PingCAP株式会社", detail: "2021年3月15日設立。", source: "company" },
    { label: "global採用", value: "3,000社超", detail: "公式求人記載。", source: "company" },
    { label: "database", value: "MySQL互換distributed SQL", detail: "scale、consistency、HTAPを提供。", source: "company" },
    { label: "国内事例", value: "Tokyo Gas・MIXI・iStyle等", detail: "公式事例一覧で確認。", source: "customers" },
    { label: "日本求人", value: "Solution Architect 1件", detail: "東京の公式求人を確認。", source: "job" },
  ],
  customers: [
    { company: "Tokyo Gas", products: "TiDB Cloud Dedicated", outcome: "myTOKYOGASのmicroservice databaseへ2024年11月にproduction導入。", implication: "国内critical serviceでcompatibility、availability、auditを検証したproof。" },
    { company: "MIXI", products: "TiDB", outcome: "mixi2を4人の小規模teamで開発し、release時のaccess増加を支えた公式事例。", implication: "small teamでscaleを運用する価値。" },
    { company: "iStyle", products: "TiDB", outcome: "SQL Serverからのmigrationで日本語supportと修正対応を評価した公式事例。", implication: "migrationとlocal supportが選定理由になる。" },
  ],
  externalSignals: [
    { label: "cloud・system標準", value: "可用性と運用設計", detail: "政府systemの標準guidelineはavailability、security、backup、monitoring、移行を設計事項として扱う。", caveat: "民間企業の具体要件は業界とsystemで異なる。" },
    { label: "AI・real-time data", value: "transactionとanalyticsの接近", detail: "real-time personalizationとAI applicationは最新transaction dataへ低latencyでaccessする要求を増やす。", caveat: "HTAPが全workloadの最適解とは限らない。" },
  ],
  role: "東京のSolution Architectがtrusted advisor、solution design、PoC・benchmark、technical content、partner支援、product feedback、event発信を担う。",
  organization: "Japan Business GroupのHybrid full-time。full flexとremote可を記載。PingCAP株式会社と東京officeは確認できるがteam人数は非公開。",
  careerValue: "distributed database、cloud migration、HA/DR、benchmark、technical value selling、communityを横断する経験。",
  globalHeadcount: "501〜1,000人",
  japanPresence: "PingCAP株式会社・東京office・Japan Business Group",
  japanSince: "2021年3月15日法人設立",
  solutions: [
    { name: "TiDB", valueProp: "MySQL互換のdistributed SQLでhorizontal scaleと高可用性を提供する。", url: "https://pingcap.co.jp/tidb/", competitors: "MySQL sharding、CockroachDB、Cloud Spanner。", differentiation: "MySQL compatibilityとHTAP。" },
    { name: "TiDB Cloud Dedicated", valueProp: "managed TiDBをdedicated environmentで提供する。", url: "https://pingcap.co.jp/tidb-cloud/", competitors: "Aurora、AlloyDB、Cloud SQL、self-managed TiDB。", differentiation: "managed operationとdistributed scale。" },
    { name: "TiDB Cloud Starter", valueProp: "serverless型で小さく開始する。", url: "https://pingcap.co.jp/tidb-cloud/", competitors: "serverless Postgres・MySQL、cloud-native DB。", differentiation: "TiDB ecosystemへの低摩擦な入口。" },
  ],
  fitTags: ["Database", "Distributed SQL", "TiDB", "Solution Architect", "PoC", "Cloud", "Japan Business Group"],
  comparisons: [
    { arena: "Distributed SQL", companies: ["TiDB", "CockroachDB", "Cloud Spanner"], why: "compatibility、scale、consistency、運用" },
    { arena: "Cloud database", companies: ["TiDB Cloud", "Aurora", "AlloyDB"], why: "migration、cost、HA、lock-in" },
    { arena: "MySQL scale", companies: ["TiDB", "manual sharding", "scale-up"], why: "application改修、運用工数、growth ceiling" },
  ],
}, {
  slug: "pingcap", leaderName: "Max Liu", leaderLabel: "Co-Founder / CEO", leaderUrl: "https://www.pingcap.com/about-us/", localName: "Eric Han", localLabel: "PingCAP株式会社 代表者", localUrl: "https://jobs.lever.co/pingcap/5de30748-2a1e-45be-bea5-ddf514d3719c",
  companyId: "pingcap-company", jobId: "pingcap-job", customersId: "pingcap-customers", externalId: "pingcap-external", financeId: "pingcap-finance",
  targets: ["Database・platform engineering部門", "cloud・application modernization責任者", "SRE・data platform部門"],
  heroSummary: "trafficとdata量の増加でMySQLのsharding、scale、failover、maintenanceが複雑になり、開発速度と可用性を制限する課題を解決する。MySQL互換のdistributed SQLでhorizontal scaleと運用の単純化を狙う。",
  competitors: "Aurora、Cloud Spanner、AlloyDB、CockroachDB、manual shardingとの比較では、compatibility、failure mode、運用、migration、3年TCOを見る。",
  feature: "TiDB、TiDB CloudでMySQL互換のdistributed SQL、HTAP、managed operationを提供する。",
  advantage: "applicationのMySQL modelを活かしながら、transaction workloadをhorizontal scaleし、analyticsも同じdataへ近づける。",
  benefit: "sharding工数、planned downtime、scale対応、DB運用負荷を減らし、service growthへの対応を速める。",
  evidence: "Tokyo Gas、MIXI、iStyle等の国内公式事例でproduction導入、scale、migration、local supportを確認。",
  marketVerdict: "国内production proofとlocal entityは明確。PoCをproductionへ変える率とcloud各社に対する勝因を確認したい。",
  marketParagraphs: ["digital serviceとAI workloadでdata量が増えるほど、databaseのscale、availability、migration、costをapplication計画と一緒に設計する必要がある。", "日本ではbenchmarkの速さだけでなく、failure時の挙動、運用人材、local support、migration riskを説明できることが成長条件になる。"],
  cultureHeadline: "technical advisorとしてPoCからproduct feedback・communityまで持つJapan Business GroupのSA role。",
  classification: "ハイブリッド", displayLabel: "Hybrid・full flex・remote可", officeDays: "固定の出社日数は未記載", remoteOnly: "remote専任ではない", flexibility: "core timeなしのfull flex",
  goodFor: ["databaseをbusiness riskへ翻訳したい人", "PoCとcommunityの両方を持ちたい人"], cautionFor: ["standard demoだけを望む人", "production責任の議論を避けたい人"],
  unresolved: [
    ["PoC", "PoC・benchmarkをleadする。", "年間PoC数、production転換率、平均期間、勝敗理由は。"],
    ["account", "顧客・partnerのtechnical advisor。", "担当社数、industry、AE・Partner SEとの責任分界は。"],
    ["competition", "複数cloud databaseと競合する。", "Aurora、Spanner、CockroachDBへの直近の勝因・敗因は。"],
    ["delivery", "migrationとproduction設計が重要。", "services、support、on-call、escalationのJapan coverageは。"],
    ["career", "architecture・product・communityを横断する。", "評価KPI、promotion、次role、直近24カ月の異動・退職は。"],
  ],
});

pingcapIntelligence.sources.push({
  id: "pingcap-linkedin-company-size",
  label: "LinkedIn TiDB, powered by PingCAP",
  url: "https://www.linkedin.com/company/pingcap",
  kind: "外部集計",
  scope: "会社規模レンジ（global 501〜1,000人）",
  checkedAt,
});
pingcapIntelligence.companyStats.globalHeadcount = {
  value: "501〜1,000人",
  detail: "LinkedInの会社規模レンジ。個別の公開profile数や正確な在籍人数ではなく、外部集計による範囲表示。2026-08-22確認。",
  sourceId: "pingcap-linkedin-company-size",
};

const thinkCellIntelligence = build({
  checkedAt: thinkCellCheckedAt,
  slug: "think-cell",
  name: "think-cell",
  jobUrl: "https://job-boards.eu.greenhouse.io/think-cell/jobs/4953129101",
  officialUrl: "https://www.think-cell.com/en/company/about",
  customersUrl: "https://www.think-cell.com/en/product/success-stories",
  externalUrl: "https://www.meti.go.jp/policy/it_policy/dx/dx.html",
  financeUrl: "https://www.think-cell.com/en/career",
  salesSnapshot: "PowerPointのchart、layout、data更新、brand templateに使うmanual作業を減らし、分析・議論へ時間を戻す会社。日本のMarketing Managerはcampaign、event、partner・influencer施策を認知、engagement、growthへつなぐ。",
  growthSummary: "2002年創業の非公開企業。公式は35,000社、130万人超のusers、Fortune 100の88%、global 220人超、Tokyo officeを表示。日本売上とteam人数は非公開。",
  ipoSummary: "非公開企業。外部調達、売上、ARR、企業価値、IPO時期、日本単体業績は公表されていない。",
  milestones: [
    { year: "2002", label: "創業", detail: "Markus HannebauerとArno SchödlがBerlinで設立。", source: "company" },
    { year: "2022", label: "100万users", detail: "global user baseが100万人を超過。", source: "company" },
    { year: "2025", label: "think-cell Suite", detail: "chart中心から複数productへ拡張。", source: "company" },
    { year: "2026", label: "130万人・35,000社", detail: "会社公式Careersの表示。", source: "company" },
    { year: "2026.08", label: "日本Marketing採用", detail: "東京のMarketing Manager - Japanを公式Greenhouseで確認。", source: "job" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "JTとNTT DATAの公式事例は、chart・schedule・template調整の時間を減らし、分析、research、議論、意思決定へ時間を移す目的を示す。" },
    { title: "製品の成り立ちから見る課題", body: "創業者がconsultingのslide制作を観察し、PowerPoint内の反復layoutとchart更新をautomationした。核は別toolへの移行ではなく既存workflow内で手作業を減らすこと。" },
    { title: "外部環境の要求から見る課題", body: "dataと意思決定の速度が上がる一方、企業ではPowerPointが経営会議・提案・報告の共通formatとして残る。AI生成が増えても、accuracy、brand、更新、storyの品質責任は残る。" },
  ],
  narrative: [
    { label: "背景", body: "analyst、consultant、finance、salesがdata-heavyな資料を短い締切で繰り返し作る。" },
    { label: "課題", body: "chart再作成、位置調整、Excel link、brand修正に時間を使い、分析・議論・story設計が圧迫される。" },
    { label: "解決策", body: "一teamの定例reportでchart、layout、data link、templateを標準化し、作成・更新時間とadoptionを測る。" },
    { label: "選定の理由", body: "native PowerPoint、Office add-in、Canva、agency、custom macroとの比較で、既存workflowへの定着、速度、quality、管理に優位がある場合に選ぶ。" },
  ],
  openingHook: "経営会議や顧客提案の一つのdeckで、chart作成と体裁修正へ何時間使っていますか。",
  valueHypothesis: "deck作成・更新時間、chart修正、template再利用、active user、training後adoption、renewal・expansionを比較する。",
  objection: "PowerPoint標準機能とCopilot、社内templateで十分で、add-inを全社導入するほどではない。",
  reframe: "一機能の便利さではなく、frequent userの時間、brand consistency、data更新、training、adoption、license utilizationで比較する。",
  facts: [
    { label: "創業", value: "2002年", detail: "Berlin発。", source: "company" },
    { label: "顧客", value: "35,000社", detail: "会社公式表示。", source: "company" },
    { label: "users", value: "130万人超", detail: "会社公式表示。", source: "company" },
    { label: "Fortune 100", value: "88%", detail: "会社公式reference page。", source: "customers" },
    { label: "global team", value: "220人超", detail: "2026年8月の公式求人記載。", source: "company" },
    { label: "日本求人", value: "Marketing 1件", detail: "東京のMarketing Manager - Japanを確認。", source: "job" },
  ],
  customers: [
    { company: "Japan Tobacco", products: "think-cell", outcome: "chart作成・Excel linkの手作業を減らし、社内意思決定用report作成を効率化した公式事例。", implication: "国内Enterpriseで日常利用へ定着するproof。" },
    { company: "NTT DATA Institute of Management Consulting", products: "think-cell Suite", outcome: "schedule作成時間を10分の1にし、brand consistencyと資料再利用を改善した公式事例。", implication: "consulting workflowでの定量proof。" },
    { company: "Bank of Georgia", products: "think-cell", outcome: "report作成時間を50%削減した公式事例。", implication: "analytics teamの意思決定速度へ接続。" },
  ],
  externalSignals: [
    { label: "knowledge work", value: "作成から判断へ時間移行", detail: "DXが進んでも経営・営業・consultingの意思決定はdocumentとpresentationを介して行われる。", caveat: "生産性効果は利用頻度とadoptionで異なる。" },
    { label: "生成AI", value: "draft速度と品質統制", detail: "AIでslide draftが速くなるほど、source accuracy、brand、data link、human reviewのworkflowが重要になる。", caveat: "AI機能だけでstoryの品質を保証しない。" },
  ],
  role: "東京のMarketing Managerが日本市場のmulti-channel campaign、event、partner・influencer施策、sales enablementを企画・実行し、performanceを分析する。",
  organization: "Tokyo officeを含むglobal 220人超の組織。日本語・英語が必須。現行求人本文では出社頻度、日本team人数、担当budgetを確認できない。",
  careerValue: "Japan field marketing、event、partner・influencer、brand、sales enablementをproductivity SaaSで横断する経験。",
  globalHeadcount: "220人超",
  japanPresence: "東京office・Japan customer team",
  japanSince: "日本拠点開始年は一次情報で未確認",
  solutions: [
    { name: "think-cell Charts", valueProp: "PowerPoint内でbusiness chartとdata linkを自動化する。", url: "https://www.think-cell.com/en/product/charts", competitors: "PowerPoint native、Excel chart、custom macro。", differentiation: "consulting-grade chartをPowerPoint内で高速作成。" },
    { name: "think-cell Library", valueProp: "slide、image、templateを検索・再利用する。", url: "https://www.think-cell.com/en/product/library", competitors: "SharePoint、brand portal、manual folder。", differentiation: "PowerPoint workflow内のasset access。" },
    { name: "think-cell Suite", valueProp: "chart、layout、data storytelling、AI支援を統合する。", url: "https://www.think-cell.com/en/product", competitors: "Office add-in群、Canva、Copilot、agency。", differentiation: "既存PowerPoint利用を変えずにautomationを追加。" },
  ],
  fitTags: ["B2B Marketing", "Events", "Partnerships", "PowerPoint", "Productivity", "Japan"],
  comparisons: [
    { arena: "PowerPoint productivity", companies: ["think-cell", "PowerPoint native", "Office add-ins"], why: "作成時間、quality、data link" },
    { arena: "Presentation workflow", companies: ["think-cell", "Canva", "agency・specialist team"], why: "既存workflow、brand、collaboration" },
    { arena: "AI slide", companies: ["think-cell", "Microsoft Copilot", "AI deck tools"], why: "accuracy、editing、data connection、governance" },
  ],
}, {
  slug: "think-cell", leaderName: "Alexander von Fritsch", leaderLabel: "CEO", leaderUrl: "https://www.think-cell.com/en/company/about", localName: "松塚展国", localLabel: "think-cell Japan社長", localUrl: "https://www.think-cell.com/ja/resources/content-hub/summary-pivot-matsutsuka",
  companyId: "think-cell-company", jobId: "think-cell-job", customersId: "think-cell-customers", externalId: "think-cell-external", financeId: "think-cell-finance",
  targets: ["経営企画・Finance・IR部門", "consulting・professional services部門", "Sales・Market Intelligence部門"],
  heroSummary: "PowerPointのchart、layout、data更新、brand調整へ時間を使い、分析・議論・意思決定が圧迫される課題を解決する。既存のPowerPoint workflow内で反復作業を自動化し、knowledge workerの時間を判断とstoryへ戻す。",
  competitors: "PowerPoint native、Copilot、Canva、Office add-in、custom macro、agencyとの比較では、時間、quality、data link、adoption、総costを見る。",
  feature: "Charts、Library、layout、data link、template、AI支援をPowerPoint内へ統合する。",
  advantage: "利用者に別のauthoring toolを学ばせず、日常のPowerPoint workflow内でconsulting-gradeのautomationを提供する。",
  benefit: "chart・deck作成と更新の時間を減らし、analysis、discussion、customer・management communicationへ時間を移す。",
  evidence: "JTとNTT DATA Institute of Management Consultingの国内公式事例で、作成効率、brand consistency、意思決定への効果を確認。",
  marketVerdict: "広いglobal利用と国内named proofがある。日本ではconsulting・financeを中心とする既存認知を、event、partner、influencer、sales enablementで継続的な需要へ変える再現性が成長条件。",
  marketParagraphs: ["data量と意思決定頻度が増えるほど、presentation作業のautomationは経営・営業・consultingの隠れた生産性投資になる。", "AI slide機能が増えるほど、PowerPoint内のeditability、source data、brand、adoptionを一続きに管理できることが差になる。"],
  cultureHeadline: "campaign実行だけでなく、event、partner、influencer、sales enablementとperformance分析まで持つJapan Marketing role。",
  classification: "未確認", displayLabel: "Tokyo勤務（出社頻度は未確認）", officeDays: "現行求人本文に固定日数の記載なし", remoteOnly: "remote専任ではない", flexibility: "日本市場のregional marketingを担当",
  goodFor: ["日本市場のcampaignをend-to-endで持ちたい人", "event・partner施策をgrowthへつなげたい人"], cautionFor: ["単一channelの運用だけを望む人", "分析・sales enablementを避けたい人"],
  unresolved: [
    ["budget", "日本向けcampaignをend-to-endで担う。", "年間budget、channel配分、裁量範囲、approvalは。"],
    ["KPI", "growth、brand awareness、engagementを担う。", "pipeline、revenue、event ROI、influencer施策のKPIとattributionは。"],
    ["channel", "event、partner、influencerを横断する。", "現在の主力channelと、直近12カ月の成功・失敗例は。"],
    ["team", "Sales、Product、Design、Contentと連携する。", "JapanのSales・Marketing人数とglobal teamとの責任分界は。"],
    ["career", "日本市場のB2B marketing経験を求める。", "次role、昇進基準、直近24カ月の異動・退職は。"],
  ],
});

export const additions20260822JapanFiveIntelligenceBySlug: Record<string, CompanyPublicIntelligence> = {
  workiva: workivaIntelligence,
  outsystems: outsystemsIntelligence,
  sailpoint: sailpointIntelligence,
  pingcap: pingcapIntelligence,
  "think-cell": thinkCellIntelligence,
};
