import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildPreEntryIntelligence } from "@/lib/company-public-intelligence-pre-entry-wave-two";
import { buildIntelligence } from "@/lib/company-public-intelligence-wave-two";

const sierraIntelligence: CompanyPublicIntelligence = buildIntelligence({
  checkedAt: "2026-08-13", slug: "sierra", name: "Sierra", jobUrl: "https://jobs.ashbyhq.com/Sierra/8ee59347-bea3-4358-93bf-ef6d93d818fb", officialUrl: "https://sierra.ai/jp", customersUrl: "https://sierra.ai/jp/customers", externalUrl: "https://www.meti.go.jp/shingikai/mono_info_service/ai_shakai_jisso/index.html", financeUrl: "https://sierra.ai/jp/blog/corporate",
  salesSnapshot: "Sierraは、CX・Customer Service・Operations責任者が抱える「問い合わせが増え採用だけでは24時間・多言語対応を広げられない」「従来botは回答止まりで本人確認やsystem更新を人へ戻す」「AIの誤案内・権限・human handoffを管理しながら成果を測れない」という3つの課題を、actionを完了するAI agentで解く会社。東京拠点、SoftBankとの提携、OPERA TECH買収を経て、日本のpartner-led GTMを作る営業としての面白さがある。",
  growthSummary: "2026年2月にARR 1.5億ドル超、5月に150億ドル超の評価額で9.5億ドル調達を会社発表。Fortune 50の40%超で利用され、東京拠点と日本語サイトを開設。", ipoSummary: "非公開企業。IPO時期、日本売上、国内顧客数は未公表。",
  milestones: [{ year: "2023", label: "創業", detail: "Bret TaylorとClay Bavorがcustomer experience向けAI agent companyとして創業。", source: "company" }, { year: "2025.12", label: "日本進出", detail: "東京office開設とSoftBank Vision Fund 2からの出資を発表。", source: "company" }, { year: "2026.02", label: "ARR", detail: "ARR 1.5億ドル超を会社発表。", source: "finance" }, { year: "2026.03", label: "国内買収", detail: "東京のEnterprise AI企業OPERA TECHを買収。", source: "company" }, { year: "2026.05", label: "大型調達", detail: "9.5億ドルを150億ドル超の評価額で調達。", source: "finance" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "Casperは24時間・多言語対応、Singtelは10週間でlaunchし70%超の解決率、Cignaは本人確認時間を80%削減したと公式事例で紹介。顧客はFAQ置換ではなく、service operationの完了率と顧客体験を変えるために導入する。" }, { title: "製品の成り立ちから見る課題", body: "汎用LLMのchat UIではなく、企業systemへ接続してpolicy、identity、workflow、human handoffを運用するAgent OSとして設計。成果単位の料金によりtoken消費ではなく完了した顧客成果へcommercial modelを合わせる。" }, { title: "外部環境の要求から見る課題", body: "人手不足と24時間対応の要求が強まる一方、生成AIには正確性、個人情報、安全性、説明可能性、人への引継ぎが求められる。Buyerはautomation率だけでなく誤案内、権限逸脱、監査、顧客満足を同時に管理する必要がある。" }],
  narrative: [{ label: "背景", body: "問い合わせ量とchannelが増え、採用だけで応答速度・品質・多言語・営業時間を同時に伸ばしにくい。" }, { label: "課題", body: "従来botは回答止まりで、本人確認や基幹system操作を人へ戻すため、解決率と顧客体験が分断する。" }, { label: "解決策", body: "一つの高頻度journeyをagentへ接続し、解決率、handoff、処理時間、CSAT、retention、costをbaselineと比較する。" }, { label: "選定の理由", body: "Salesforce、Zendesk、Intercom、Genesys、内製agentとの比較で、複雑な顧客actionを安全に完了し、成果課金と継続改善まで一体化できる場合に選ばれる。" }],
  openingHook: "問い合わせの何割が『答えを返す』だけでなく、本人確認からsystem更新まで人手なしで安全に完了していますか。", valueHypothesis: "返品・注文変更等の一journeyでresolution、AHT、handoff、error、CSAT、retention、cost per resolutionを測る。", objection: "既存CRM・contact centerのAI機能か内製で十分。", reframe: "chatbot機能ではなく、productionまでの期間、完了率、policy制御、human handoff、継続改善、成果単価を同じjourneyで比較する。",
  facts: [{ label: "ARR", value: "$150M超", detail: "2026年2月の会社発表。", source: "finance" }, { label: "評価額", value: "$15B超", detail: "2026年5月調達時。", source: "finance" }, { label: "Fortune 50", value: "40%超", detail: "会社公式発表の導入比率。", source: "company" }, { label: "東京拠点", value: "2025年12月", detail: "日本展開開始を公式発表。", source: "company" }, { label: "国内買収", value: "OPERA TECH", detail: "2026年3月。", source: "company" }, { label: "日本求人", value: "Partnerships Sales", detail: "Tokyoの公式求人を確認。", source: "job" }],
  customers: [{ company: "Singtel", products: "Sierra Agent", outcome: "10週間でlaunchし、70%超のresolution rateを公式紹介。", implication: "large enterpriseでも短期productionと業務完了を売れる。" }, { company: "Cigna", products: "Sierra Agent", outcome: "8週間でproductionへ進み、本人確認時間を80%削減。", implication: "regulated journeyは速度とcontrolの両方が価値。" }, { company: "Casper", products: "Sierra Agent", outcome: "24時間・多言語のserviceへ拡張。", implication: "staff増員だけでは難しいcoverageを成果化できる。" }],
  externalSignals: [{ label: "AI事業者ガイドライン", value: "安全・透明性・人間中心", detail: "経産省・総務省の議論はrisk管理、data、透明性、人の関与を重視。", caveat: "Sierraの個別適合性や法的結論を示さない。" }, { label: "CXの人手不足", value: "品質と生産性の両立", detail: "問い合わせ増と労働力制約によりautomation投資の説明責任が強まる。", caveat: "AI導入だけで業務標準化や顧客満足が自動的に改善するわけではない。" }],
  role: "TokyoでSI、consulting、technology partnerを開拓し、共同GTM、pipeline、enablement、executive relationshipを作るPartnerships Sales。", organization: "Customer Obsession、Craftsmanship、Intensityを掲げ、officeで密に協働しながらresearchをbusiness outcomeへ実装する組織。", careerValue: "Enterprise AI、CX transformation、partner ecosystem、日本市場立ち上げ、outcome-based commercial modelを横断できる。", globalHeadcount: "501〜1,000人規模（LinkedIn公開レンジ）", japanPresence: "Tokyo office / 日本語公式サイト / OPERA TECH買収", japanSince: "2025年12月",
  solutions: [{ name: "Sierra Agent", valueProp: "顧客の問い合わせからsystem actionまでを自然言語で完了。", url: "https://sierra.ai/jp", competitors: "Salesforce Agentforce、Zendesk AI、Intercom Fin、Genesys。", differentiation: "brand-specific agent、enterprise action、outcome-based pricing。" }, { name: "Agent Studio / Ghostwriter", valueProp: "business teamとtechnical teamがagentを構築・改善。", url: "https://sierra.ai/jp/blog/agents-as-a-service", competitors: "内製framework、cloud agent builder。", differentiation: "production CX運用と継続最適化を一つのplatformで扱う。" }, { name: "Agent Data Platform", valueProp: "conversationとcustomer contextをagent改善へ接続。", url: "https://sierra.ai/jp/blog/siriusxm-and-sierra-announce-a-deeper-collaboration", competitors: "CDP、contact center analytics、data platform。", differentiation: "agent actionとcustomer dataを同じexperienceへ結ぶ。" }],
  fitTags: ["日本進出直後", "Enterprise AI", "Customer Experience", "Partner", "Founding Team", "Outcome Pricing", "Tokyo"], comparisons: [{ arena: "AI Customer Service", companies: ["Sierra", "Salesforce", "Zendesk"], why: "workflow完了、既存suite、運用model" }, { arena: "AI Agent", companies: ["Sierra", "Intercom", "内製"], why: "production速度、control、成果単価" }],
});

const lucanetIntelligence: CompanyPublicIntelligence = buildIntelligence({
  checkedAt: "2026-08-13", jobConfirmed: false, slug: "lucanet", name: "Lucanet", jobUrl: "https://www.lucanet.com/en/press-releases/lucanet-expands-to-japan-16-06-2026/", officialUrl: "https://www.lucanet.com/ja/", customersUrl: "https://www.lucanet.com/ja/", externalUrl: "https://www.meti.go.jp/policy/it_policy/investment/keiei_meigara/dx-report.html", financeUrl: "https://www.lucanet.com/en/careers/",
  salesSnapshot: "Lucanetは、CFO・経理・経営企画が抱える「法人ごとにERP・会計dataが分断する」「連結・予算・開示をExcelで補完しcloseが遅れる」「制度対応と速いscenario planningを同時に回せない」という3つの課題を、finance専門のCFO Solution Platformで解く会社。2026年6月に東京のlocal teamと完全localizationを伴って正式進出し、CFO transformationの日本playbookを作る営業としての面白さがある。",
  growthSummary: "2026年6月にARR 2億ユーロ超と日本正式進出を同時発表。6,000社超（careersでは6,500社超）、900人超、25年のfinance domain expertiseを持つ。", ipoSummary: "非公開企業。日本ARR、国内顧客数、採用人数、IPO計画は未公表。",
  milestones: [{ year: "1999", label: "創業", detail: "finance professional向けconsolidation softwareとしてBerlinで創業。", source: "company" }, { year: "2022", label: "成長投資", detail: "Hgとの提携でglobal CFO platform化を加速。", source: "finance" }, { year: "2024", label: "platform拡張", detail: "planning、reporting、tax、ESG等をCFO Solution Platformへ統合。", source: "company" }, { year: "2026.06", label: "日本進出", detail: "東京local teamと完全localized platformを公式発表。", source: "job" }, { year: "2026.06", label: "ARR", detail: "2億ユーロ超を公式発表。", source: "finance" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "multi-entity企業は連結、予算、reportingをspreadsheetとERP exportで回し、closeの遅延、version混在、audit evidence不足を抱える。導入目的はtool置換ではなく、finance dataを一つにして意思決定へ使う時間を取り戻すこと。" }, { title: "製品の成り立ちから見る課題", body: "会計・連結の専門家向けout-of-the-box softwareから始まり、planning、disclosure、tax、ESG、cashへ拡張。汎用BIではなくfinance ruleとworkflowを標準搭載し、CFO office全体のsource of truthを作る設計。" }, { title: "外部環境の要求から見る課題", body: "group経営の複雑化、M&A、為替・tariff変動、開示・税務制度、AI活用で、Financeは速い予測と厳密なcontrolを同時に求められる。spreadsheet依存ではspeed、traceability、scenario analysisを両立しにくい。" }],
  narrative: [{ label: "背景", body: "企業groupはERP・会計systemが法人ごとに分かれ、close、planning、reportingをExcelで補完する。" }, { label: "課題", body: "data収集、mapping、adjustment、承認が属人化し、数字確定が遅くscenarioへ時間を使えない。" }, { label: "解決策", body: "一つのgroupまたはprocessを選び、close日数、manual adjustment、error、report作成時間、forecast cycleをbaseline化してplatformへ移す。" }, { label: "選定の理由", body: "SAP、Oracle、Workday Adaptive、Anaplan、Board、国内連結会計製品との比較で、finance専門性、導入速度、consolidationとplanningの統合、local complianceを同時に満たす場合に選ばれる。" }],
  openingHook: "月次・四半期closeで、Financeがdata回収とExcel整形に使う日数は、経営分析に使う日数より多くありませんか。", valueHypothesis: "一つのgroup closeで日数、manual file、adjustment、差戻し、audit inquiry、forecast更新時間を測る。", objection: "ERPとExcel、国内連結会計製品で十分。", reframe: "license比較ではなく、group全体のclose速度、traceability、planning再利用、制度更新、運用人件費を同じTCOで比較する。",
  facts: [{ label: "ARR", value: "€200M超", detail: "2026年6月の会社発表。", source: "finance" }, { label: "顧客", value: "6,000社超", detail: "日本進出発表時。careersは6,500社超と記載。", source: "company" }, { label: "社員", value: "900人超", detail: "会社公式careers。", source: "finance" }, { label: "歴史", value: "25年", detail: "CFO領域での会社公式表記。", source: "company" }, { label: "日本責任者", value: "Makoto Yabushita", detail: "Country Manager Japan。", source: "company" }, { label: "営業求人", value: "未確認", detail: "日本進出とlocal teamは確認、公開営業求人は未確認。", source: "job" }],
  customers: [{ company: "Ritter Sport", products: "Consolidation / Planning", outcome: "group financeの標準化事例として公式公開。", implication: "multi-entity mid-marketへcloseとplanningを同じroadmapで提案できる。" }, { company: "AUTO1 Group", products: "Lucanet", outcome: "急成長企業のfinancial reportingを支援する事例。", implication: "M&A・international expansionで増えるentity complexityへ強い。" }, { company: "Mister Spex", products: "Lucanet", outcome: "finance processのautomation事例を公式紹介。", implication: "small finance teamのmanual work削減を定量化できる。" }],
  externalSignals: [{ label: "DX経営", value: "dataと業務変革", detail: "経産省のDX関連資料はlegacy・部門分断を経営課題として扱う。", caveat: "Lucanetの効果や適合性を直接示さない。" }, { label: "Financeの外部要求", value: "speedとcontrol", detail: "制度開示、税務、監査と不確実な経営環境がforecast更新とtraceabilityを求める。", caveat: "具体的な適用要件は企業規模・上場区分・会計基準で異なる。" }],
  role: "Country Managerを中心にsales、customer success、partner relationsを担う東京のlocal teamを構築し、既存日本顧客と国際企業へ展開", organization: "finance domain expertise、out-of-the-box、trust、継続改善を重視する900人超のglobal SaaS組織。", careerValue: "CFO transformation、consolidation、FP&A、country launch、partner-led enterprise salesを横断できる。", globalHeadcount: "900人超", japanPresence: "Tokyo local team / 完全localized platform", japanSince: "2026年6月",
  solutions: [{ name: "Consolidation & Financial Planning", valueProp: "group close、連結、planningを一つのfinance dataへ統合。", url: "https://www.lucanet.com/ja/solutions/consolidation-and-financial-planning/", competitors: "SAP、Oracle、国内連結会計製品。", differentiation: "finance専門のout-of-the-box設計と導入速度。" }, { name: "xP&A", valueProp: "財務と事業planをscenarioで接続。", url: "https://www.lucanet.com/ja/solutions/extended-planning-analysis/", competitors: "Anaplan、Workday Adaptive、Board。", differentiation: "actualとconsolidation dataを同じplatformで利用。" }, { name: "Disclosure / Tax / ESG", valueProp: "法定・経営reportingとcompliance workflowを自動化。", url: "https://www.lucanet.com/ja/platform/", competitors: "Workiva、Wolters Kluwer、point solutions。", differentiation: "CFO platformの共通dataとworkflowへ統合。" }],
  fitTags: ["日本進出直後", "CFO", "FP&A", "Consolidation", "Finance Transformation", "Partner", "Mid-Market", "Tokyo"], comparisons: [{ arena: "Consolidation", companies: ["Lucanet", "SAP", "国内連結会計"], why: "finance depth、導入速度、local compliance" }, { arena: "Planning", companies: ["Lucanet", "Anaplan", "Workday Adaptive"], why: "planning breadthとactual統合" }],
});

const addeparIntelligence: CompanyPublicIntelligence = buildPreEntryIntelligence({
  checkedAt: "2026-08-13", slug: "addepar", name: "Addepar", homepage: "https://addepar.com/", growthUrl: "https://addepar.com/newsroom/", careersUrl: "https://addepar.com/careers/", customersUrl: "https://addepar.com/clients/", trustUrl: "https://addepar.com/why-addepar", apacUrl: "https://addepar.com/connect-with-us/", externalUrl: "https://www.fsa.go.jp/policy/pjlamc/20250627.html", linkedinUrl: "https://www.linkedin.com/company/addepar/",
  salesSnapshot: "Addeparは、family office、wealth manager、private bankが抱える「複数custodian・通貨・asset classへportfolio dataが分散する」「alternative assetと複雑なownershipをExcelで管理する」「reportingの手作業がadvisorのclient時間を奪う」という3つの課題を、investment Data & AI Platformで解く会社。SingaporeをAPAC hubにした直後で、日本のwealth management市場へ広がる成立条件を追える営業としての面白さがある。",
  growthSummary: "9兆ドル超のasset、1,500社超、60カ国超を公式発表。2025年に2.3億ドルを32.5億ドル評価で調達し、2026年4月にSingaporeをAPAC hubとして開設。", verdict: "日本進出の可能性は中。APAC hubとproduct scaleは揃うが、国内金融data・custodian接続とlocal deliveryが条件", entryNarrative: "Addeparは9兆ドル超、1,500社超、60カ国超という十分なplatform scaleを持ち、SingaporeをAPAC hubとしてregional clientとdata operationを拡張している。日本の富裕層、family office、private bank、alternative investmentの複雑性とは親和性が高い。一方、Japan・Tokyo拠点、日本求人、日本語site、国内custodian・信託・証券とのintegration、国内顧客事例は確認できない。金融機関のsecurity・data residency・outsourcing審査に加え、accounting・tax・reportingのlocal conventionへ対応する必要がある。Singaporeから日本のlighthouse clientを獲得し、国内data connectivityとimplementation partnerをproductionで証明できれば、Japan podが現実的になる。",
  headcount: "1,001〜5,000人規模", headcountDetail: "LinkedIn企業ページの会社規模レンジ。公式の厳密値ではない。", apacPresence: "2026年4月にSingapore officeをAsia-Pacific hubとして開設。公式拠点一覧にもSingaporeを掲載。", productLanguage: "60カ国超で利用されるmulti-currency platformだが、日本語site、Japan office、国内custodian integration、国内referenceは未確認。",
  milestones: [{ year: "2009", label: "創業", detail: "投資家が保有assetを理解できる透明な金融systemを目指して創業。", source: "company" }, { year: "2023", label: "$5T", detail: "platform asset 5兆ドル超を発表。", source: "growth" }, { year: "2025", label: "Series G", detail: "2.3億ドルを32.5億ドル評価で調達。", source: "growth" }, { year: "2026", label: "$9T超", detail: "1,500社超・60カ国超へ拡大。", source: "growth" }, { year: "2026.04", label: "Singapore hub", detail: "APAC regional hubを開設。", source: "apac" }],
  issueLenses: [{ title: "既存顧客の導入目的から見る課題", body: "WE Family Officesはmanual transactionを27%削減し、取引量2倍でもoperations headcount増加0%、report作成時間94%削減を公式事例で公開。顧客はdashboardではなく、complex portfolioを正確にscaleするoperating leverageを買う。" }, { title: "製品の成り立ちから見る課題", body: "創業時から複雑なownership、alternative asset、複数custodianを共通data modelへ正規化し、portfolio analysis、reporting、client portal、tradingへ拡張。一般的なaccounting systemでは失われる投資関係をdata layerで保持する設計。" }, { title: "外部環境の要求から見る課題", body: "private marketとcross-border assetが増え、wealth managerは透明性、適合性、security、迅速なreportingを求められる。日本でも資産運用立国政策とwealth management競争が進む一方、個人情報・金融規制・委託先管理を満たすlocal operating modelが必要。" }],
  narrative: [{ label: "背景", body: "富裕層・family officeの資産はbank、fund、private company、real assetへ分散し、statementとvaluationが揃わない。" }, { label: "課題", body: "analystがportalとspreadsheetからdataを集め、ownershipとcurrencyを補正するため、reportが遅くscaleしない。" }, { label: "解決策", body: "一つのclient bookでcustodian・alternative dataを統合し、reconciliation、report作成時間、error、analysis speed、advisor capacityを測る。" }, { label: "選定の理由", body: "Black Diamond、SS&C Advent、Envestnet、private bank内製、Excelとの比較で、complex ownershipとalternativesを大規模に正規化し、analysis・reporting・workflowへ再利用できる場合に選ばれる。" }],
  openingHook: "一つのfamily portfolioを正確に説明するため、何人が何日かけてbank portal、PDF、Excel、private asset valuationを突合していますか。", valueHypothesis: "優先client segmentでdata収集時間、manual transaction、reconciliation error、report lead time、advisor capacity、client responseを測る。", objection: "custodian portalとExcel、既存wealth platformで十分。", reframe: "画面機能ではなく、複雑なownershipとalternativesを含むdata accuracy、manual work、client report速度、operations headcount、integration維持費で比較する。",
  facts: [{ label: "platform assets", value: "$9T超", detail: "会社公式about。", source: "growth" }, { label: "顧客", value: "1,500社超", detail: "60カ国超。", source: "growth" }, { label: "Series G", value: "$230M", detail: "2025年、$3.25B評価。", source: "growth" }, { label: "APAC hub", value: "Singapore", detail: "2026年4月開設。", source: "apac" }, { label: "日本拠点", value: "未確認", detail: "公式拠点一覧にJapan・Tokyoなし。", source: "careers" }, { label: "日本求人", value: "未確認", detail: "Japan・Tokyo勤務地を確認できず。", source: "careers" }],
  customers: [{ company: "WE Family Offices", products: "Addepar Platform", outcome: "report作成時間94%削減、transaction 2倍でoperations headcount増加0%。", implication: "high-touch serviceを維持しながらoperationsをscaleする価値。" }, { company: "Papo Group", products: "Addepar Platform", outcome: "manual taskへ使っていた時間の75%を取り戻したと公式事例で紹介。", implication: "small family officeでもsingle source of truthが効く。" }, { company: "CD&R", products: "Addepar Platform", outcome: "複雑なprivate asset dataを多様なstakeholderへ深く速く提供。", implication: "private equityとinstitutional workflowへ提案できる。" }],
  externalSignals: [{ label: "資産運用立国", value: "運用高度化", detail: "金融庁は資産運用業の高度化、競争、service改善を政策課題として整理。", caveat: "Addeparの日本需要や参入承認を直接示さない。" }, { label: "金融data", value: "securityと委託先管理", detail: "金融・wealth dataは個人情報、access、audit、vendor riskへの高い説明責任がある。", caveat: "適用法・監督要件は顧客とservice scopeで異なる。" }],
  entryAssessment: { verdict: "進出可能性は中。Singapore hubから日本の有償proofとdata connectivityを作れるかが分岐点", factSignals: [{ title: "十分なglobal scale", body: "9兆ドル超、1,500社超、60カ国超はspecialized wealth platformとして大規模。", sourceIds: ["growth", "company"] }, { title: "APACへ固定投資", body: "Singaporeをregional hubとして開設し、Asiaのwealth manager・family officeへ現地接点を作った。", sourceIds: ["apac", "careers"] }, { title: "日本課題との親和", body: "multi-custodian、alternative asset、family office reportingの複雑性は日本のwealth managementにも存在。", sourceIds: ["customers", "external"] }, { title: "product investment", body: "Data ExchangeとAI workflowを拡張し、data activationまでplatformを広げている。", sourceIds: ["growth", "company"] }], hurdles: [{ title: "国内data connectivity", body: "銀行、証券、信託、fund administrator、private assetのdataを正確・継続的に取り込む接続が必要。", sourceIds: ["company", "external"] }, { title: "financial-grade local control", body: "data residency、個人情報、vendor risk、audit、BCP、supportを日本の金融機関審査へ合わせる必要。", sourceIds: ["trust", "external"] }, { title: "local convention", body: "税務、会計、reporting、family office serviceの慣行をglobal modelへ翻訳するimplementation能力が必要。", sourceIds: ["customers", "external"] }, { title: "specialized TAM", body: "高単価platformを必要とする国内family office・wealth firm数とsales cycleをSingaporeから検証する必要。", sourceIds: ["apac", "careers"] }], readinessConditions: [{ title: "Japan lighthouse", body: "private bank、wealth manager、family officeでproduction利用とrenewalを証明。" }, { title: "data partner", body: "国内custodian・administratorとの継続的なdata feedを構築。" }, { title: "local implementation", body: "日本語でonboarding、data reconciliation、report design、supportを提供。" }, { title: "regulatory readiness", body: "security・privacy・outsourcing資料を国内審査へ対応。" }, { title: "dedicated pod", body: "Country lead、Sales、Solutions、Data Operations、Client Serviceを専任化。" }], watchSignals: ["Japan・Tokyo求人", "日本語site", "国内金融機関の顧客事例", "custodian・trust bank partnership", "Singapore求人のJapan territory表記", "国内officeまたは法人"],
  },
  sourceIds: ["growth", "company", "careers", "customers", "trust", "apac", "external", "linkedin"], salesMotion: "family office・wealth manager・private bankのCOO、CIO、CTO、Operationsへdata accuracyとoperating leverageから入り、implementationとclient workflowをmulti-yearで広げるconsultative enterprise sale。", careerValue: "WealthTech、investment data、alternative assets、financial services、APAC country buildを横断する可能性。", leader: { name: "Eric Poirier", role: "CEO", read: "透明なfinancial systemという創業missionを、complex investment dataとAI workflowのglobal platformへ拡張。" },
  solutions: [{ name: "Addepar Platform", valueProp: "portfolio data、ownership、analysis、reportingを統合。", url: "https://addepar.com/platform/", competitors: "SS&C Advent、Black Diamond、Envestnet、内製。", differentiation: "complex ownership・alternatives・multi-custodianのdata model。" }, { name: "Addepar Data Exchange", valueProp: "investment dataをwarehouse・AI・downstream workflowへactivation。", url: "https://addepar.com/blog/a-new-data-foundation-for-modern-investment-firms", competitors: "data warehouse、ETL、custodian feeds。", differentiation: "validated investment dataとentitlementを一体化。" }, { name: "Addison / AI", valueProp: "自然言語でportfolioを分析しactionable insightを作る。", url: "https://addepar.com/newsroom/", competitors: "BI copilot、private bank内製AI。", differentiation: "9兆ドル超のoperational platform contextへnative接続。" }],
  fitTags: ["日本未進出", "WealthTech", "FinTech", "Investment Data", "Family Office", "APAC", "Enterprise", "AI"], comparisons: [{ arena: "Wealth Platform", companies: ["Addepar", "SS&C Advent", "Black Diamond"], why: "data model、alternatives、reporting" }, { arena: "Investment Data", companies: ["Addepar", "internal data lake", "custodian portals"], why: "accuracy、connectivity、workflow" }],
});

export const daily20260813IntelligenceBySlug: Record<string, CompanyPublicIntelligence> = {
  sierra: sierraIntelligence,
  lucanet: lucanetIntelligence,
  addepar: addeparIntelligence,
};
