import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-10-06";

export const companies20261006Daily: Company[] = [
  {
    slug: "ecovadis",
    name: "EcoVadis",
    category: "サプライチェーン・サステナビリティ評価",
    broadCategory: "AI・データ基盤",
    hq: "パリ（フランス）",
    japanPresence: "2019年に東京オフィスを開設。公式求人は日本オフィス約55人と記載し、東京の3求人を確認",
    hiringStatus: "積極採用",
    salesRoles: 1,
    description: "企業の環境・労働・倫理・調達の管理体制を評価し、取引先リスクと改善を可視化。東京で営業開拓、評価分析、人事運営を募集。",
    lastChecked: checkedAt,
    careersUrl: "https://careers.ecovadis.com/",
    tags: ["Sustainability", "Supply Chain", "Procurement", "Ratings", "Tokyo"],
  },
  {
    slug: "cic",
    name: "CIC",
    category: "イノベーション拠点・スタートアップ支援",
    broadCategory: "業務自動化・コラボレーション",
    hq: "ケンブリッジ（米国）",
    japanPresence: "CIC Japan合同会社。東京・福岡・大阪の3拠点を運営し、日本の公式求人5件を確認",
    hiringStatus: "積極採用",
    salesRoles: 2,
    description: "起業家、企業、研究機関、行政をつなぐイノベーション拠点と支援プログラムを運営。日本・アジア拡張に向け5職種を募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jp.cic.com/career/",
    tags: ["Innovation Campus", "Startup Ecosystem", "Deep Tech", "Japan", "APAC"],
  },
  {
    slug: "ionq",
    name: "IonQ",
    category: "量子コンピューティング・ネットワーク",
    broadCategory: "AI・データ基盤",
    hq: "カレッジパーク（米国）",
    japanPresence: "豊田通商との販売提携、産総研とのMOU、大阪のCountry Manager求人を確認。日本法人・常設拠点は未確認",
    hiringStatus: "継続観測",
    salesRoles: 1,
    description: "イオントラップ方式の量子計算、ネットワーク、センシング、セキュリティを提供。日本市場責任者の採用を進出シグナルとして観測。",
    lastChecked: checkedAt,
    careersUrl: "https://www.ionq.com/careers",
    tags: ["日本進出兆候", "Quantum Computing", "Enterprise", "Toyota Tsusho", "Osaka"],
    entryStatus: "pre-entry-signal",
  },
];

type JobDraft = Pick<Job, "id" | "companySlug" | "title" | "segment" | "location" | "workStyle" | "language" | "source" | "descriptionSummary" | "genbaTake" | "desiredProfile" | "compensationReality">;

function makeJob(draft: JobDraft): Job {
  return {
    ...draft,
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    careerInsights: {
      fit: `${draft.segment}で、専門知識を顧客・組織の具体的な成果へ変えたい人に向く。`,
      thingsToKnow: "目標、達成率、担当範囲、国内支援体制、評価・昇進、報酬構成は公開情報だけでは十分に分からない。",
      marketValue: `${draft.segment}の成果を商談、導入、運用、顧客KPIで定量化できれば、隣接する海外テクノロジー企業へ再現性を説明しやすい。`,
      tenureAndPromotion: "在籍年数だけでなく、担当拡張、顧客・組織成果、再利用できる実行の型が次の役割の土台になる。",
      priorCompanies: "企業向け営業、分析、技術運用、複数の意思決定者を動かす業務の経験が隣接する。",
      nextCompanies: "担当市場と成果を数字で残せれば、企業営業、地域リード、専門分析、事業運営、技術責任者へ広げやすい。",
    },
  };
}

export const jobs20261006Daily: Job[] = [
  makeJob({
    id: "ecovadis-sales-development-associate-japanese-744000141295519",
    companySlug: "ecovadis",
    title: "Sales Development Associate - Japanese Speaker",
    segment: "Japan Sales Development / Sustainable Procurement",
    location: "Tokyo",
    workStyle: "Hybrid。出社日数は公式求人で未確認",
    language: "日本語・英語とも流暢な読み書きと会話",
    source: { label: "EcoVadis Careers (SmartRecruiters)", url: "https://jobs.smartrecruiters.com/ecovadis/744000141295519" },
    descriptionSummary: "日本企業のサステナビリティ・調達責任者へ接点を作り、課題発見、案件化、商談設定、活動・案件指標の達成を担う。",
    genbaTake: "評価サービスの案内ではなく、環境・人権・倫理を取引先管理と経営リスクの会話へ変える市場開拓職。",
    desiredProfile: "日本語・英語、見込み顧客開拓、経営層との対話、調達・サステナビリティへの関心が重要。",
    compensationReality: "日本の給与、賞与、目標、達成率、株式は公開求人で確認できない。",
  }),
  makeJob({
    id: "ecovadis-sustainability-analyst-japanese-744000148224301",
    companySlug: "ecovadis",
    title: "Sustainability Analyst - Japanese Speaker",
    segment: "Sustainability Ratings / Japan Analysis",
    location: "Tokyo",
    workStyle: "Hybrid。入社後3カ月は週3日、その後は週2日出社",
    language: "日本語・英語とも高度な読み書きと会話",
    source: { label: "EcoVadis Careers (SmartRecruiters)", url: "https://jobs.smartrecruiters.com/ecovadis/744000148224301-sustainability-analyst-japanese-speaker" },
    descriptionSummary: "企業の方針・手順・報告書・外部ニュースを読み、環境、労働・人権、倫理、持続可能な調達の管理体制を共通方法論で評価する。",
    genbaTake: "文書を要約する仕事ではなく、証拠の十分性と管理体制の実効性を基準へ照らし、企業間取引の判断材料へ変える分析職。",
    desiredProfile: "日英の読解、サステナビリティ文書の分析、細部への注意、AI提案を人が検証する批判的思考が重要。",
    compensationReality: "日本の給与、賞与、評価件数、品質KPI、昇進条件は公開求人で確認できない。",
  }),
  makeJob({
    id: "ecovadis-people-operations-senior-associate-744000152649339",
    companySlug: "ecovadis",
    title: "People Operations Senior Associate",
    segment: "Japan People Operations / Office Administration",
    location: "Tokyo",
    workStyle: "Hybrid。公式求人で出社日数の詳細は未確認",
    language: "日本語・英語とも業務上高度な水準",
    source: { label: "EcoVadis Careers (SmartRecruiters)", url: "https://jobs.smartrecruiters.com/ecovadis/744000152649339" },
    descriptionSummary: "約55人の日本オフィスで、入退社、給与・福利厚生、労務、衛生委員会、就業規則、職場運営と生成AI活用を担う。",
    genbaTake: "人事手続きだけでなく、日本の労務・安全衛生とグローバル方針をつなぎ、成長する国内組織の運営基盤を作る役割。",
    desiredProfile: "日本の労務法制を含む人事運営8年以上、日英での調整、外部専門家との実務が重要。",
    compensationReality: "日本の給与、賞与、職位レンジ、担当人数の将来計画は公開求人で確認できない。",
  }),
  makeJob({
    id: "cic-founders-associate-tokyo-2d313196",
    companySlug: "cic",
    title: "Founder's Associate - Tokyo, JP",
    segment: "Founder Operations / Global Innovation Network",
    location: "Tokyo",
    workStyle: "Hybrid。CIC Tokyoを主な勤務拠点とする",
    language: "英語の高度な読み書き・会話。日本語水準は公式求人で明記なし",
    source: { label: "CIC Careers (Lever)", url: "https://jobs.lever.co/cic/2d313196-b9b2-4248-90fa-0c9c03b17579" },
    descriptionSummary: "創業者の予定・受信箱・意思決定・国際移動・関係者・発信を一つの運営系にまとめ、AIで定型業務と組織記憶を改善する。",
    genbaTake: "秘書業務の範囲を越え、創業者の時間と文脈を守り、世界のイノベーション関係者との約束を実行へ変える経営運営職。",
    desiredProfile: "細部、判断、先回り、英語、機密管理、AIを使った業務再設計が重要。日本の就労資格が必要。",
    compensationReality: "競争力のある給与との記載のみ。6カ月の契約後に無期契約へ移行する条件を明記。金額は非公開。",
  }),
  makeJob({
    id: "cic-hr-director-japan-korea-82f1fa79",
    companySlug: "cic",
    title: "HR Director Japan & Korea - Tokyo, JP",
    segment: "Japan & Korea People Leadership",
    location: "Tokyo",
    workStyle: "On-site",
    language: "日本語は流暢、英語は高度な業務水準",
    source: { label: "CIC Careers (Lever)", url: "https://jobs.lever.co/cic/82f1fa79-163d-498a-a9e3-42671c693d0d" },
    descriptionSummary: "日本の3拠点と将来の韓国拠点に向け、組織設計、採用、管理職支援、評価、報酬、労務、人数計画を率いる。",
    genbaTake: "人事制度の運用だけでなく、日本で拡張した複数拠点をアジアの次の組織づくりへ接続する地域人事責任者。",
    desiredProfile: "人事7年以上、日本の労働法、労使対応、管理職支援、日本語と英語が重要。",
    compensationReality: "競争力のある給与との記載のみ。給与、賞与、部下人数、評価KPIは非公開。",
  }),
  makeJob({
    id: "cic-marketing-director-tokyo-672575fe",
    companySlug: "cic",
    title: "Marketing Director - Tokyo, JP",
    segment: "Japan & APAC Marketing Leadership",
    location: "Tokyo",
    workStyle: "On-site",
    language: "日本語は流暢、英語は非常に高い業務水準",
    source: { label: "CIC Careers (Lever)", url: "https://jobs.lever.co/cic/672575fe-8764-44ac-8b1d-b32f42a332e3" },
    descriptionSummary: "日本の拠点・支援事業のブランド、市場分析、広報、集客、案件育成、予算とKPIを率い、将来のアジア拠点展開も支える。",
    genbaTake: "施設の集客ではなく、入居、企業・行政プログラム、都市のイノベーション事業を一つの市場戦略へ束ねる責任者。",
    desiredProfile: "日本でのマーケティング10年以上、無形B2Bサービス、管理職5年以上、日英の経営調整が重要。",
    compensationReality: "競争力のある給与との記載のみ。給与、賞与、予算、KPI、チーム人数は非公開。",
  }),
  makeJob({
    id: "cic-systems-network-engineer-japan-488d0ff2",
    companySlug: "cic",
    title: "Systems & Network Engineer, Japan",
    segment: "Japan Campus Infrastructure",
    location: "Tokyo（公式日本語ページは東京・大阪・福岡と記載）",
    workStyle: "On-site。ネットワーク緊急時のオンコールあり",
    language: "日本語は上級または母語、英語はビジネス以上",
    source: { label: "CIC Careers (Lever)", url: "https://jobs.lever.co/cic/488d0ff2-0585-477c-bc4e-efd00dbb1bc5" },
    descriptionSummary: "多数の無線アクセスポイント、入退室管理、クラウド、仮想基盤を運用し、日本拠点の信頼性、安全性、容量を支える。",
    genbaTake: "社内IT支援だけでなく、入居企業が利用する物理空間とデジタル基盤を止めないサービス運用職。",
    desiredProfile: "ネットワーク運用7年以上、無線、認証、クラウド、監視、障害対応、日英での連携が重要。",
    compensationReality: "競争力のある給与との記載のみ。給与、オンコール頻度・手当、担当拠点数は非公開。",
  }),
  makeJob({
    id: "cic-accounting-manager-tokyo-47c2a02b",
    companySlug: "cic",
    title: "Accounting Manager - Tokyo, JP",
    segment: "Japan Finance Operations",
    location: "Tokyo",
    workStyle: "On-site",
    language: "日本語・英語の具体的な水準は公式求人で要確認",
    source: { label: "CIC Careers (Lever)", url: "https://jobs.lever.co/cic/47c2a02b-e453-4178-aceb-5140f62f5d9b" },
    descriptionSummary: "複数の日本法人の会計、月次・年次決算、統制、報告、小規模チームを担い、アジア拡張に耐える財務運営を作る。",
    genbaTake: "記帳・決算だけでなく、3拠点と複数法人の成長を支える標準化・統制を作る会計責任者。",
    desiredProfile: "一連の会計業務、決算、内部統制、チーム運営、国内外関係者との調整が重要。",
    compensationReality: "競争力のある給与との記載のみ。給与、賞与、部下人数、締め日程は非公開。",
  }),
  makeJob({
    id: "ionq-country-manager-enterprise-japan-6001723004",
    companySlug: "ionq",
    title: "Country Manager - Enterprise",
    segment: "Japan Enterprise Quantum GTM",
    location: "豊中市・大阪府",
    workStyle: "公式求人で出社・リモート条件の詳細は未確認",
    language: "日本市場の顧客・パートナー対応に必要な日英水準は選考で要確認",
    source: { label: "IonQ Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/ionq/jobs/6001723004" },
    descriptionSummary: "日本の企業市場で量子計算・ネットワーク等の需要を作り、顧客・パートナー・社内技術部門を束ねて事業を立ち上げる。",
    genbaTake: "完成した市場で製品を売るのではなく、量子技術の実用課題、販売経路、投資判断を日本で同時に作るカントリーマネージャー。",
    desiredProfile: "先端技術の企業営業、市場開拓、経営層提案、技術部門と商用条件をつなぐ経験が重要。",
    compensationReality: "日本の給与、変動給、株式、目標、雇用主体、国内支援人数は公開求人で確認できない。",
  }),
];
