import type { CompanyPublicIntelligence } from "@/lib/company-public-intelligence";
import { buildIntelligence, type Profile } from "@/lib/company-public-intelligence-wave-two";
import { buildPreEntryIntelligence } from "@/lib/company-public-intelligence-pre-entry-wave-two";

const checkedAt = "2026-08-14";

const enteredProfiles: Profile[] = [
  {
    checkedAt,
    slug: "shopify",
    name: "Shopify",
    jobUrl: "https://www.shopify.com/careers/product-partnerships-lead_d9993b7d-d973-409c-9da3-0c8d48cff776",
    officialUrl: "https://www.shopify.com/jp/enterprise",
    customersUrl: "https://www.shopify.com/jp/case-studies",
    externalUrl: "https://www.meti.go.jp/policy/it_policy/statistics/outlook/ie_outlook.html",
    financeUrl: "https://www.shopify.com/investors",
    publicInfo: { ticker: "SHOP", exchange: "NASDAQ", listedSince: "2015年5月" },
    salesSnapshot: "Shopifyは、EC責任者・Digital・Retail・ITが抱えるchannel、customer data、checkout、運用の分断をUnified Commerce Platformで解く会社。日本でProduct Partnerships Leadを採用し、marketplace、payments、logistics、marketing、vertical SaaSとの統合を広げる。単体製品を売るより、merchantの成長をpartner ecosystemとproduct roadmapの両方で作る営業・事業開発が面白い。",
    growthSummary: "2025年は売上成長30%、free cash flow margin 17%を会社が開示。現在はmillionsのmerchantを175カ国超で支え、累計GMV 1.6兆ドル、米国EC market share 14%超を公式IRで示す。",
    milestones: [
      { year: "2006", label: "Shopifyを開始", detail: "merchantが自らcommerceを始め、運営し、成長できるplatformを公開。", source: "company" },
      { year: "2015.05", label: "上場", detail: "SHOPとして公開市場へ上場。", source: "finance" },
      { year: "2020年代", label: "Unified Commerceへ拡張", detail: "online storeからPOS、B2B、Markets、Payments、AI、enterpriseへ製品面を拡張。", source: "company" },
      { year: "2025", label: "成長とcash generation", detail: "通期売上成長30%、free cash flow margin 17%を開示。", source: "finance" },
      { year: "2026.08", label: "Japan ecosystem採用", detail: "Product Partnerships Leadの現行求人を確認。", source: "job" },
    ],
    issueLenses: [
      { title: "既存顧客の導入目的から見る課題", body: "Anker Japanの自社EC売上200%超、三陽商会のGMV115%・session120%、ちいかわマーケットのGMV5倍超という事例は、storefront構築ではなく、運用速度、brand体験、OMO、peak耐性、customer relationshipを成長基盤へ変える目的を示す。" },
      { title: "製品の成り立ちから見る課題", body: "自社snowboard storeを運営するためのsoftwareから始まり、merchantがcustomer・brand・channelを自ら所有できるcommerce operating systemへ拡張。App、API、partner ecosystemにより、標準化とmerchant固有の差別化を両立する。" },
      { title: "外部環境の要求から見る課題", body: "国内ECの拡大、実店舗とのOMO、越境販売、AI agent経由の購買が同時進行し、企業にはchannel追加ではなく、在庫・顧客・決済・注文を一貫させながら変化へ速く対応する要求がある。" },
    ],
    narrative: [
      { label: "背景", body: "brandは自社EC、marketplace、実店舗、海外、B2B、AI channelへ販売接点を広げている。" },
      { label: "課題", body: "channelごとにcommerce engine、customer data、inventory、promotion、developmentが分かれ、施策速度と顧客体験が落ち、保守費が増える。" },
      { label: "解決策", body: "優先channelとcustomer journeyを一つ決め、Shopify Plus、Checkout、POS、Markets、App/APIを組み、release lead time、conversion、GMV、運用費、repeat率をbaseline比較する。" },
      { label: "選定の理由", body: "Adobe Commerce、Salesforce Commerce Cloud、国内EC package、composable内製との比較で、標準checkoutの強さ、merchant control、ecosystem、開発速度、global/local要件の総合TCOが合う場合に選ばれる。" },
    ],
    openingHook: "新しい販売施策を企画してから全channelで公開し、在庫・顧客・注文まで一貫して測れるまで、現在何週間と何vendorが必要ですか。",
    valueHypothesis: "release lead time、conversion、GMV、full-price sales、運用費、incident、repeat率をchannel別に導入前後で測る。",
    objection: "国内EC packageと既存SI、marketplace、POSで十分。",
    reframe: "初期構築の機能数ではなく、3年分の変更速度、peak耐性、channel追加、customer data ownership、partner依存、total costで比較する。",
    facts: [
      { label: "merchant", value: "millions / 175+カ国", detail: "Shopify公式IRの現行Key Facts。", source: "finance" },
      { label: "累計GMV", value: "1.6兆ドル", detail: "創業以来の累計GMVを公式IRで開示。", source: "finance" },
      { label: "2025成長", value: "売上+30%", detail: "2025通期、free cash flow marginは17%。", source: "finance" },
      { label: "国内事例", value: "574件掲載", detail: "Shopify日本のcase study一覧で確認。", source: "customers" },
      { label: "Anker Japan", value: "自社EC売上+200%超", detail: "Shopify Plus導入後の公式事例。", source: "customers" },
      { label: "現在の求人", value: "Product Partnerships Lead", detail: "Japanのstrategic technology partnerを担当。", source: "job" },
    ],
    customers: [
      { company: "Anker Japan", products: "Shopify Plus / Payments / Checkout", outcome: "旧platform比で自社EC売上が200%超増加。", implication: "少人数での施策速度とbrand-owned commerceをbusiness outcomeへ変えられる。" },
      { company: "三陽商会", products: "Shopify Plus / OMO", outcome: "8つのEC siteを統合し、GMV115%、session120%、full-price sales120%。", implication: "replatformingをOMOと収益性の改善へ接続できる。" },
      { company: "ちいかわマーケット", products: "Shopify Plus / Shop Pay", outcome: "server down zero、3年でGMV5倍超、Shop Pay比率約40%。", implication: "peak trafficとcheckout frictionを人気IPの成長へつなげるproof。" },
    ],
    externalSignals: [
      { label: "国内EC市場", value: "channel横断の成長", detail: "経産省の電子商取引調査は国内外のEC市場を継続把握し、企業の販売・取引digitalizationが構造変化であることを示す。", caveat: "市場成長がShopifyの採用や個社成果を直接保証するものではない。" },
      { label: "AI commerce", value: "discoveryからpurchaseへ", detail: "AI agentが商品発見と購入導線へ入るほど、正確なcatalog、price、inventory、attribution、brand controlが必要になる。", caveat: "agentic commerceの普及速度とchannel別成果は未確定。" },
    ],
    role: "Product Partnerships Leadとして日本のmarketplace、payments、logistics、marketing、vertical SaaS partnerを開拓し、契約・integration・共同roadmapを作る。",
    organization: "Partnershipsを軸にProduct、Marketing、Sales、Legal、Financeと連携するglobal remote organization。日本のpartner要件をinternational product roadmapへ戻す。",
    careerValue: "Unified Commerce、platform partnerships、API ecosystem、executive negotiation、日本固有要件のproduct localizationを横断する経験。",
    globalHeadcount: "約8,000人",
    japanPresence: "日本語公式サイト、日本向けRemote GTM、国内merchant事例とpartner directoryを展開。日本単体の売上・営業人数は非公開。",
    japanSince: "日本市場で継続展開",
    solutions: [
      { name: "Shopify Plus", valueProp: "Enterprise commerceをonline、B2B、global channelへ拡張。", url: "https://www.shopify.com/jp/plus", competitors: "Adobe Commerce、Salesforce Commerce Cloud、国内EC package。", differentiation: "標準platform、checkout、ecosystem、merchant controlの組み合わせ。" },
      { name: "Shopify POS / Unified Commerce", valueProp: "storeとonlineのcustomer、inventory、orderを接続。", url: "https://www.shopify.com/jp/pos", competitors: "Square、Lightspeed、国内POS・OMS。", differentiation: "online commerceと同じplatformで店頭を運用。" },
      { name: "Shopify Markets / B2B", valueProp: "越境販売と法人取引を一つのcommerce stackで管理。", url: "https://www.shopify.com/jp/markets", competitors: "cross-border tool、B2B EC package、内製。", differentiation: "checkout、catalog、localization、operationを既存storeへ統合。" },
    ],
    fitTags: ["認知企業", "Commerce", "Enterprise", "Partner", "Platform", "Ecosystem", "Japan", "Public"],
    comparisons: [
      { arena: "Enterprise Commerce", companies: ["Shopify", "Adobe Commerce", "Salesforce Commerce Cloud"], why: "time-to-market、customization、ecosystem、TCO" },
      { arena: "Unified Commerce", companies: ["Shopify", "国内EC/POS", "composable内製"], why: "online/store data、operation、merchant control" },
      { arena: "Partner ecosystem", companies: ["Shopify", "marketplace", "SI-led platform"], why: "API、merchant reach、joint roadmap、delivery" },
    ],
  },
  {
    checkedAt,
    slug: "zilliz",
    name: "Zilliz",
    jobUrl: "https://jobs.lever.co/zilliz/8144e236-2836-4980-92cf-b6501ce0f81c",
    officialUrl: "https://zilliz.com/jp/",
    customersUrl: "https://zilliz.com/customers/filevine",
    externalUrl: "https://www.meti.go.jp/policy/it_policy/ai-governance/index.html",
    financeUrl: "https://zilliz.com/blog/how-zilliz-saw-the-future-of-vector-databases-and-built-for-production",
    salesSnapshot: "Zillizは、AI・Data・Platform Engineeringが抱えるunstructured dataの検索、production latency、scale、運用の課題をMilvusとZilliz Cloudで解く会社。東京でEnterprise AEとFounding Field Engineerを同時採用し、日本のfounding teamを作る段階。open-source adoptionをproduction契約へ変え、PoCから稼働後まで顧客と作る営業・field engineeringが面白い。",
    growthSummary: "Milvusは45,000超のGitHub stars、10,000超の企業・AI startupでのproduction deploymentを公式求人で説明。Zilliz Cloud顧客の約80%がMilvus userから始まったと会社が公開し、open-source-to-cloudの成長loopを持つ。",
    ipoSummary: "非公開企業。IPO時期、ARR、評価額、日本売上は公式に確認できない。",
    milestones: [
      { year: "2017", label: "創業", detail: "AI application向けdata managementを簡素化する会社として創業。", source: "company" },
      { year: "2019", label: "Milvusをopen source化", detail: "vector searchをpurpose-built databaseとしてcommunityへ公開。", source: "company" },
      { year: "2022〜", label: "Zilliz Cloudを拡張", detail: "managed Milvusからserverless、multi-cloud、Vector Lakebaseへ展開。", source: "company" },
      { year: "現在", label: "production adoption", detail: "10,000超の企業・AI startup、45,000超のGitHub starsを公式求人で説明。", source: "finance" },
      { year: "2026.08", label: "Japan founding team", detail: "東京でEnterprise AEとFounding Field Engineerを同時募集。", source: "job" },
    ],
    issueLenses: [
      { title: "既存顧客の導入目的から見る課題", body: "Filevineはlegal dataを30 billion超のvectorで扱い、attorneyの情報探索時間を大幅に減らすproduction AIへ利用。採用理由はdemo精度だけでなく、大規模performance、stability、security、implementationの現実性だった。" },
      { title: "製品の成り立ちから見る課題", body: "Milvusをopen sourceで開発し、developerがvector searchを自ら検証できる入口を作った後、upgrade、failure、performance、costを継続運用する難しさをZilliz Cloudで引き受ける。OSS利用の約80%をcommercial cloudへつなぐ設計が特徴。" },
      { title: "外部環境の要求から見る課題", body: "生成AIがexperimentからcustomer-facing productionへ移るほど、企業はanswer qualityだけでなくdata lineage、access、latency、availability、cost、human oversightを継続管理し、AI governanceを運用へ落とす必要がある。" },
    ],
    narrative: [
      { label: "背景", body: "RAG、semantic search、recommendation、AI agentがtext、image、audio、videoを業務で使い始めている。" },
      { label: "課題", body: "PoCでは動いても、vector数、tenant、filter、update、peak loadが増えるとlatency、cost、reliability、operationが崩れ、production移行が止まる。" },
      { label: "解決策", body: "一つのproduction候補use caseでsuccess criteriaを決め、Milvus/Zilliz Cloud上でrecall、P99 latency、QPS、availability、operator time、unit costをbaseline比較する。" },
      { label: "選定の理由", body: "Pinecone、Weaviate、Qdrant、Elasticsearch/OpenSearch、PostgreSQL pgvector、self-managed Milvusとの比較で、scale、performance、open source portability、managed operation、multi-cloudが要件に合う場合に選ばれる。" },
    ],
    openingHook: "現在のRAG・AI検索は、PoCの精度だけでなくproductionのP99 latency、failure recovery、1,000 query当たりcostまで測れていますか。",
    valueHypothesis: "PoC-to-production日数、P99 latency、recall、QPS、incident、operator hour、infrastructure cost、AI feature adoptionを測る。",
    objection: "PostgreSQL/Elasticsearchのvector機能か、self-managed Milvusで十分。",
    reframe: "最初の1 million vectorではなく、100倍のdata、tenant、update、filter、SLAになった時のengineering costと移行riskまで含めて比較する。",
    facts: [
      { label: "Milvus community", value: "45,000+ GitHub stars", detail: "現行Founding Field Engineer求人の会社説明。", source: "job" },
      { label: "production利用", value: "10,000+企業・startup", detail: "Milvus/Zillizの公式求人で説明。", source: "job" },
      { label: "OSS起点", value: "Cloud顧客の約80%", detail: "Zilliz CTOの公式記事。", source: "finance" },
      { label: "AWS region", value: "Tokyo対応", detail: "Zilliz CloudのAWS Tokyo region提供を公式記事で確認。", source: "company" },
      { label: "Japan体制", value: "founding team", detail: "東京hybridの2求人を確認。", source: "job" },
      { label: "公開求人", value: "AE + Field Engineer", detail: "commercialとproduction adoptionを同時に採用。", source: "job" },
    ],
    customers: [
      { company: "Filevine", products: "Zilliz Cloud", outcome: "30 billion超のvectorを扱うlegal AIで、情報探索をhoursからsecondsへ短縮。", implication: "sensitiveなunstructured dataをproduction scaleで扱うreference。" },
      { company: "PayPal", products: "Milvus / Zilliz ecosystem", outcome: "mission-criticalな大規模採用企業として公式customer story内で紹介。", implication: "FinTech規模のperformance・reliability buyerへscale proofを示せる。" },
      { company: "Salesforce", products: "Milvus / Zilliz ecosystem", outcome: "major enterprise adoptionの例として公式customer story内で紹介。", implication: "AI-native startup専用ではなくEnterprise data teamへ広げられる。" },
    ],
    externalSignals: [
      { label: "AI governance", value: "開発から運用へ", detail: "経産省のAI governance関連資料は、AIを継続的なrisk managementとstakeholder説明の対象として扱う。", caveat: "特定のvector database採用や個別構成を義務づけるものではない。" },
      { label: "production AI", value: "品質・cost・resilience", detail: "AI applicationが顧客・従業員workflowへ入るほど、retrieval layerの障害とdata accessが事業riskになる。", caveat: "必要SLAとarchitectureはuse case・data sensitivityで異なる。" },
    ],
    role: "Enterprise AEがpipelineからclose・expansionを担い、Founding Field EngineerがPoC、go-live、production adoption、technical escalationをEngineering側から支える。",
    organization: "Japan founding GTM teamとしてAE、Solutions Architect、Field Engineerがglobal Product・Engineering・Marketing・Partnerと連携する初期market-build組織。",
    careerValue: "Vector Database、RAG、open source、production AI、founding Japan GTM、technical value sellingを横断する経験。",
    globalHeadcount: "51〜200人規模（LinkedIn公開レンジ）",
    japanPresence: "日本語公式site、AWS Tokyo region、東京hybridのEnterprise AE・Founding Field Engineer求人。日本法人名と国内顧客事例は未確認。",
    japanSince: "Japan founding teamを構築中",
    solutions: [
      { name: "Zilliz Cloud", valueProp: "Milvusをfully managedでproduction運用し、scale・reliability・costを最適化。", url: "https://zilliz.com/cloud", competitors: "Pinecone、Weaviate Cloud、Qdrant Cloud。", differentiation: "Milvusのopen-source foundationとmanaged performance・multi-cloud。" },
      { name: "Milvus", valueProp: "大規模vector・hybrid searchをopen sourceで実装。", url: "https://milvus.io/", competitors: "pgvector、Elasticsearch/OpenSearch、Vespa。", differentiation: "purpose-built distributed vector databaseと広いcommunity。" },
      { name: "Vector Lakebase", valueProp: "real-time servingとlarge-scale/on-demand searchをlake-native architectureで統合。", url: "https://zilliz.com/blog/vector-lakebase-ai-data-silo", competitors: "vector DB + data lake内製、search platform。", differentiation: "hot servingとcold data discoveryを同じvector data foundationで扱う。" },
    ],
    fitTags: ["AI Infrastructure", "Vector Database", "Open Source", "Founding Team", "Enterprise", "Field Engineering", "Japan", "Scale-up"],
    comparisons: [
      { arena: "Managed Vector DB", companies: ["Zilliz", "Pinecone", "Weaviate", "Qdrant"], why: "scale、latency、operation、portability、cost" },
      { arena: "既存data platform", companies: ["Zilliz", "Elasticsearch/OpenSearch", "PostgreSQL pgvector"], why: "specialized performanceとstack simplicity" },
      { arena: "Deployment model", companies: ["Zilliz Cloud", "self-managed Milvus", "内製"], why: "control、SLA、upgrade、engineering ownership" },
    ],
  },
];

const airtableIntelligence = buildPreEntryIntelligence({
  checkedAt,
  slug: "airtable",
  name: "Airtable",
  homepage: "https://www.airtable.com/",
  growthUrl: "https://www.airtable.com/about",
  careersUrl: "https://job-boards.greenhouse.io/airtable",
  customersUrl: "https://www.airtable.com/customer-stories",
  trustUrl: "https://www.airtable.com/company/trust-and-security",
  apacUrl: "https://www.airtable.com/about",
  externalUrl: "https://www.meti.go.jp/policy/it_policy/investment/dx-chushokigyou.html",
  linkedinUrl: "https://www.linkedin.com/company/airtable/",
  salesSnapshot: "Airtableは、Operations・Marketing・Product・ITが抱えるspreadsheet、point tool、manual handoff、developer backlogの分断をNo-code App PlatformとAI Workflowsで解く会社。50万組織、700人超、Sydney拠点を持つ一方、公式Greenhouseの現行19求人にJapan・Tokyoはなく、日本法人・専任team・日本語UIも確認できない。global productの越境利用と、local commercial operationを分けて進出条件を観測する。",
  growthSummary: "公式Aboutで50万組織、累計調達13.6億ドル、700人超、世界6拠点を開示。Enterprise customer proofとAI app/workflowへの製品拡張は強いが、売上・ARR・日本単体利用は非公開。",
  verdict: "進出可能性は中。認知度・顧客基盤・Sydney拠点はあるが、日本語製品とlocal GTMの投資判断が未確認",
  entryNarrative: "Airtableは50万組織、700人超、世界6拠点を持ち、SydneyからAPACをcoverできる。business userがcritical workflowを自らapp化する価値は、日本の人手不足・spreadsheet運用・IT backlogにも親和性がある。一方、公式Greenhouseの現行19求人は米国中心でJapan・Tokyoがなく、公式Aboutの拠点一覧にもTokyoはない。UIの公式対応言語は英・仏・独・西で、日本語、国内data residency、日本のcustomer story、partner deliveryも確認できない。日本での既存paid cohortとrenewal、日本語・security・support、partner economicsが見えれば、Sydneyから専任podへ進む余地がある。",
  headcount: "700人超",
  headcountDetail: "Airtable公式Aboutの現行記載。部門・地域別人数は非公開。",
  apacPresence: "Sydney officeを公式Aboutで確認。現行Careers APIでは19求人すべて米国勤務地で、Sydneyを含むAPAC採用とJapan担当求人は確認できない。",
  productLanguage: "公式supportではGUI対応を英語・フランス語・ドイツ語・スペイン語と説明。日本語UI、国内support、Japan data residency、契約・security資料の同等性は未確認。",
  milestones: [
    { year: "2012", label: "創業", detail: "non-technical teamがshared data上に業務appを作るmissionで開始。", source: "company" },
    { year: "成長期", label: "50万組織へ拡大", detail: "Enterpriseを含む幅広い組織のcritical workflowへ採用。", source: "growth" },
    { year: "現在", label: "AI app platformへ拡張", detail: "自然言語でapp、field、automation、analysisを作るAI capabilityを追加。", source: "company" },
    { year: "現在", label: "Sydney拠点", detail: "APACの物理拠点としてSydneyを公式Aboutに掲載。", source: "apac" },
    { year: "2026.08", label: "Japan観測", detail: "現行19求人にJapan・Tokyoなし。Tokyo拠点も未確認。", source: "apac" },
  ],
  issueLenses: [
    { title: "既存顧客の導入目的から見る課題", body: "West Elmは週85時間を削減し、Virgin Voyagesはweekly reporting時間を90%削減、dormakabaは5 systemを一つへ統合。導入目的はdatabase作成ではなく、department間のhandoff、manual entry、status reportingを継続的に変えること。" },
    { title: "製品の成り立ちから見る課題", body: "spreadsheetの操作性とrelational databaseの構造を組み合わせ、business userがdeveloper backlogを待たずに固有workflowをapp化する設計。現在はAIをapp building、data analysis、web research、automationへ埋め込む。" },
    { title: "外部環境の要求から見る課題", body: "日本企業は人手不足のなかで現場主導の業務改善を急ぐ一方、野良spreadsheetや野良SaaSを増やさず、access、audit、data、AI利用をITが統制する必要がある。民主化とgovernanceを同時に満たすことがbuyerの投資理由になる。" },
  ],
  narrative: [
    { label: "背景", body: "各部門がspreadsheet、form、chat、project toolを組み合わせ、固有workflowを個別運用している。" },
    { label: "課題", body: "dataの重複、manual handoff、status確認、IT backlogが増え、現場の変更速度と全社governanceが両立しない。" },
    { label: "解決策", body: "一つの高頻度workflowをconnected appへ移し、manual entry、handoff、cycle time、error、reporting time、active adoptionをbaseline比較する。" },
    { label: "選定の理由", body: "Microsoft Power Platform、ServiceNow、Smartsheet、monday.com、Notion、内製appとの比較で、business userのbuild速度、relational data、automation、AI、Enterprise governanceのbalanceが合う場合に選ばれる。" },
  ],
  openingHook: "現場が一つのworkflowを変更するたびに、何個のspreadsheetとtool、何時間のcopy、何週間のIT待ちが発生していますか。",
  valueHypothesis: "manual entry、handoff、cycle time、error、report作成時間、tool数、builder数、active adoptionを導入前後で測る。",
  objection: "Microsoft 365、Google Workspace、Notion、既存low-codeで十分。",
  reframe: "表の見た目ではなく、shared dataからapp、automation、AI、permission、auditまでをbusiness userが安全に変更できるtotal operating costで比較する。",
  facts: [
    { label: "利用組織", value: "500,000", detail: "Airtable公式AboutのKey Facts。", source: "growth" },
    { label: "累計調達", value: "$1.36B", detail: "Airtable公式AboutのKey Facts。", source: "growth" },
    { label: "team", value: "700+", detail: "Airtable公式About。", source: "growth" },
    { label: "APAC拠点", value: "Sydney", detail: "公式Aboutのoffice一覧。", source: "apac" },
    { label: "日本語GUI", value: "未対応", detail: "公式supportの対応言語は英・仏・独・西。", source: "company" },
    { label: "日本求人", value: "未確認", detail: "2026-08-14取得の公式Greenhouse 19求人にJapan・Tokyoなし。", source: "careers" },
  ],
  customers: [
    { company: "West Elm", products: "Airtable App Platform", outcome: "5部門をつなぎ、週85時間を削減。", implication: "creative operationのmanual dataとasset handoffを定量改善できる。" },
    { company: "Virgin Voyages", products: "Airtable AI / Automations", outcome: "80人超のmarketingを統合し、weekly reporting時間を90%削減。", implication: "growth後のcomplex workflowをAIとautomationで再設計できる。" },
    { company: "dormakaba", products: "Connected Apps", outcome: "5つのsystem・databaseを一つのcentral sourceへ統合。", implication: "field operationとSAP等の既存systemをbusiness-led appで接続できる。" },
  ],
  externalSignals: [
    { label: "現場DX", value: "人手不足と変更速度", detail: "経産省は中小企業を含むDXで、digital technologyによるbusiness process変革と生産性向上を支援している。", caveat: "Airtable採用や日本進出を直接示す資料ではない。" },
    { label: "citizen development", value: "民主化と統制", detail: "現場がappとAI workflowを作るほど、権限、audit、data classification、owner、lifecycle managementが必要になる。", caveat: "必要controlは業界・data・workflowで異なる。" },
  ],
  entryAssessment: {
    verdict: "進出可能性は中。Sydney hubと強いglobal customer proofはあるが、日本語・顧客・partner・専任採用が不足",
    factSignals: [
      { title: "十分なglobal規模", body: "50万組織、700人超、13.6億ドル調達はlocal marketを検討できる事業基盤。", sourceIds: ["growth"] },
      { title: "SydneyのAPAC拠点", body: "日本と近いtime zoneにofficeを持ち、regional supportとmarket testの足場になり得る。", sourceIds: ["apac"] },
      { title: "日本課題との親和", body: "spreadsheet運用、manual handoff、IT backlog、人手不足はconnected appとautomationの価値に合う。", sourceIds: ["company", "external"] },
      { title: "Enterprise customer proof", body: "West Elm、Virgin Voyages、dormakaba等で時間削減とsystem統合を定量公開。", sourceIds: ["customers"] },
    ],
    hurdles: [
      { title: "Japan commercial proofがない", body: "日本顧客事例、Japan ARR、renewal、pipeline、country ownerを公式情報で確認できない。", sourceIds: ["customers", "growth", "careers"] },
      { title: "日本語product gap", body: "公式GUI対応言語に日本語がなく、support、contract、security、AI prompt qualityの同等性も未確認。", sourceIds: ["company", "trust"] },
      { title: "local deliveryが未確認", body: "Tokyo office、Japan AE・SE・CS、国内accredited partner、Japan time supportを確認できない。", sourceIds: ["careers", "apac"] },
      { title: "suite・low-code競争", body: "Microsoft、Google、ServiceNow、Smartsheet、monday.com、Notion、国内SaaSがbundleと既存relationshipを持つ。", sourceIds: ["company"] },
    ],
    readinessConditions: [
      { title: "Japan paid cohort", body: "複数の日本Enterpriseでproduction利用、renewal、seat/workflow expansionを確認する。" },
      { title: "日本語readiness", body: "GUI、AI、support、契約、security資料を主要buyerが運用できる水準へ揃える。" },
      { title: "local partner", body: "SI・consulting・業務改善partnerがarchitecture、build、governance、trainingを提供する。" },
      { title: "専任Japan pod", body: "AE、Solution、CS、Partner、Legal/Securityを日本時間でcoverする。" },
      { title: "repeatable economics", body: "pipeline、ACV、sales cycle、retention、services負荷がlocal固定費を支える。" },
    ],
    watchSignals: ["Japan・Tokyo求人", "日本語GUI・AI・support", "国内顧客事例", "Tokyo office・country leader", "国内accredited partner", "Sydney teamのJapan territory表記"],
  },
  sourceIds: ["growth", "company", "careers", "customers", "trust", "apac", "external", "linkedin"],
  salesMotion: "team内のspreadsheet replacementから入り、cross-functional app、automation、AI、Enterprise governanceへusageとworkflowをexpandするPLG-to-enterprise sale。",
  careerValue: "No-code app platform、citizen development、AI workflow、Enterprise governance、partner-led Japan entryを横断する可能性。",
  leader: { name: "Howie Liu", role: "Co-founder / CEO", read: "software creationをdeveloperだけでなくbusiness userへ開き、shared data上のcritical workflow platformへ広げる。" },
  solutions: [
    { name: "Airtable App Platform", valueProp: "shared relational dataからbusiness app、interface、automationを構築。", url: "https://www.airtable.com/platform", competitors: "Microsoft Power Apps、Smartsheet、monday.com。", differentiation: "spreadsheet-like UXとrelational data・app buildingの組み合わせ。" },
    { name: "Airtable AI", valueProp: "app building、analysis、research、workflow actionへAIを埋め込む。", url: "https://www.airtable.com/platform/ai", competitors: "Microsoft Copilot、Notion AI、内製agent。", differentiation: "業務dataとautomationのcontext内でAIを実行。" },
    { name: "Enterprise Hub / Governance", valueProp: "user、data、app、permission、auditをorganization全体で管理。", url: "https://www.airtable.com/platform/governance", competitors: "ServiceNow、Power Platform CoE、custom governance。", differentiation: "business-led buildとcentral governanceを同じplatformで扱う。" },
  ],
  fitTags: ["日本未進出", "No-code", "AI Workflows", "Enterprise", "PLG", "Governance", "Sydney", "APAC"],
  comparisons: [
    { arena: "No-code App Platform", companies: ["Airtable", "Microsoft Power Apps", "ServiceNow"], why: "builder UX、data model、governance、ecosystem" },
    { arena: "Work Management", companies: ["Airtable", "Smartsheet", "monday.com", "Notion"], why: "project toolとcustom appの境界" },
    { arena: "Japan entry", companies: ["Airtable", "Sydney regional coverage", "local partner"], why: "language、customer proof、delivery economics" },
  ],
});

export const daily20260814WaveTwoIntelligenceBySlug: Record<string, CompanyPublicIntelligence> = {
  ...Object.fromEntries(enteredProfiles.map((profile) => [profile.slug, buildIntelligence(profile)])),
  airtable: airtableIntelligence,
};
