import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchEleven: Job[] = [
  job({
    id: "ideals-account-executive-japan-current",
    companySlug: "ideals",
    title: "Account Executive - Japan",
    segment: "Enterprise / M&A & Finance",
    location: "東京",
    workStyle: "ハイブリッド / remote-first、顧客訪問時は丸の内二重橋ビル",
    language: "日本語（native）／英語（business）",
    source: { label: "iDeals Careers (Ashby)", url: "https://jobs.ashbyhq.com/ideals/6fabd9ca-f8b5-4124-b06b-e5fe5e3d43e4" },
    descriptionSummary: "finance・banking・C-suiteへoutboundし、M&A等のVDRを3〜6カ月のcycleでannual contractへcloseする。英日票は同一機能のtranslationとして1職種に統合。",
    genbaTake: "storage単価でなく、dealの権限、Q&A、redaction、audit、buyer experienceをdeal velocityと情報controlの両立へ翻訳する。",
    compensationReality: "日本の給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人は360度sales、outbound closing、finance・banking C-suite、native Japanese、business Englishを重視。",
    domain: "Virtual Data Room・Enterprise Sales",
  }),
  job({
    id: "ideals-premium-solutions-manager-japan-current",
    companySlug: "ideals",
    title: "Premium Solutions Manager - Japan",
    segment: "Premium Solutions / Delivery",
    location: "東京",
    workStyle: "ハイブリッド / Japan remote team",
    language: "日本語（native）／英語（businessが理想）",
    source: { label: "iDeals Careers (Ashby)", url: "https://jobs.ashbyhq.com/ideals/b42a416a-4abf-4469-bfcd-78f124b95ca0" },
    descriptionSummary: "premium customerのonboarding、permission、redaction、migration、Q&A、運用設計を担うcustomer-facing delivery role。",
    genbaTake: "room開設で終わらず、deal参加者が権限を誤らず、Q&Aと証跡を止めずに運用できる状態をtime-to-valueにする。",
    compensationReality: "日本の給与、bonus、variable、delivery KPI、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はcustomer onboarding、権限・data migration、複数stakeholder、native Japaneseを重視。Business Englishは理想要件。",
    domain: "Virtual Data Room・Customer Delivery",
  }),
  job({
    id: "ideals-business-development-associate-japan-current",
    companySlug: "ideals",
    title: "Business Development Associate Japan",
    segment: "Business Development / Full-cycle",
    location: "東京",
    workStyle: "ハイブリッド / remote-first、顧客訪問時は丸の内二重橋ビル",
    language: "日本語（native）／英語（business）",
    source: { label: "iDeals Careers (Ashby)", url: "https://jobs.ashbyhq.com/ideals/4d988c1c-2260-4517-8e2d-4e2d18d799fd" },
    descriptionSummary: "Account Executive（BDA）と360度のprospecting、discovery、demo、negotiation、close、quotaを担う。",
    genbaTake: "meeting供給役ではなく、finance・M&Aの機密dealを開拓からannual contractまで持つ。",
    compensationReality: "日本の給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人は360度sales、outbound、closing、native Japanese、business Englishを重視。",
    domain: "Virtual Data Room・Business Development",
  }),
  job({
    id: "knowbe4-ciso-advisor-japan-current",
    companySlug: "knowbe4",
    title: "CISO Advisor (Fluent in Japanese)",
    segment: "Security Advisory / GTM",
    location: "東京",
    workStyle: "ハイブリッド環境（出社日数は非公開）",
    language: "日本語（fluent）／英語は水準の明記なし",
    source: { label: "KnowBe4 Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/knowbe4/jobs/8523441002" },
    descriptionSummary: "CISO視点のthought leadership、media・PR・event、顧客対話、sales支援を通じて日本のhuman risk management需要を作る。",
    genbaTake: "製品demo専任ではなく、経営riskと従業員行動、SOC運用をつなぐcategory educationの役割。",
    compensationReality: "日本の給与、bonus、equity、成果指標は公式求人で確認できない。",
    desiredProfile: "公式求人はCISO・security leadershipの経験、発信、顧客・event対応、fluent Japaneseを重視。",
    domain: "Human Risk Management・Security Advisory",
  }),
  job({
    id: "knowbe4-customer-success-architect-japan-current",
    companySlug: "knowbe4",
    title: "Customer Success Architect (Fluent in Japanese)",
    segment: "Customer Success / Architecture",
    location: "東京",
    workStyle: "ハイブリッド環境（出社日数は非公開）",
    language: "日本語（fluent）／英語reading・writingは望ましい",
    source: { label: "KnowBe4 Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/knowbe4/jobs/8092088002" },
    descriptionSummary: "enterprise customerのimplementation、solution architecture、adoption、business review、risk reductionを支援する。",
    genbaTake: "training実施で終わらず、click/report rate、高risk user、triage工数を改善する運用設計が価値になる。",
    compensationReality: "日本の給与、bonus、equity、portfolio数、更新KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はcustomer success、implementation、solution architecture、fluent Japaneseを重視。",
    domain: "Human Risk Management・Customer Success",
  }),
  job({
    id: "knowbe4-director-sales-enterprise-japan-current",
    companySlug: "knowbe4",
    title: "Director of Sales (ENT) (Fluent in Japanese)",
    segment: "Enterprise Sales Leadership",
    location: "東京",
    workStyle: "ハイブリッド環境（出社日数は非公開）",
    language: "日本語（fluent）／英文resume必須、英語水準は明記なし",
    source: { label: "KnowBe4 Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/knowbe4/jobs/8622659002" },
    descriptionSummary: "Japan enterpriseのAE・AM組織を率い、ARR、pipeline、forecast、coaching、cross-functional executionを持つ。",
    genbaTake: "seat数の拡大より、訓練からemail defense・triage・behavior changeまでのportfolio化と予測可能な営業運用を作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、team quota、達成率は公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise sales leadership、ARR責任、coaching、fluent Japaneseを重視。",
    domain: "Human Risk Management・Sales Leadership",
  }),
  job({
    id: "knowbe4-partner-account-manager-japan-current",
    companySlug: "knowbe4",
    title: "Partner Account Manager",
    segment: "Channel Sales",
    location: "東京",
    workStyle: "ハイブリッド環境（出社日数は非公開）",
    language: "英文resume必須／日英のproficiency水準は明記なし",
    source: { label: "KnowBe4 Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/knowbe4/jobs/5500554002" },
    descriptionSummary: "Japan channel partnerの開拓、enablement、joint plan、pipeline、revenueを担う。",
    genbaTake: "partner数ではなく、訓練・email security・SOC運用を統合提案できる販売・delivery能力を作る。",
    compensationReality: "日本の給与、OTE、pay mix、equity、partner quota、credit ruleは公式求人で確認できない。",
    desiredProfile: "公式求人はchannel・partner sales、pipeline、enablement、cross-functional executionを重視。",
    domain: "Human Risk Management・Channel Sales",
  }),
  job({
    id: "knowbe4-regional-ae-enterprise-japan-current",
    companySlug: "knowbe4",
    title: "Regional Account Executive (Enterprise) (Fluent in Japanese)",
    segment: "Enterprise / New & Expansion",
    location: "東京",
    workStyle: "ハイブリッド環境（出社日数は非公開）",
    language: "日本語（fluent）／英文resume必須、英語水準は明記なし",
    source: { label: "KnowBe4 Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/knowbe4/jobs/7089100002" },
    descriptionSummary: "enterpriseのnew logo、cross-sell、monthly quota、pipeline、forecastを担う。",
    genbaTake: "annual trainingの販売ではなく、行動dataとemail運用を用いてhuman riskを継続的に下げる経営案件へ変える。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota、達成率は公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise new logo・cross-sell、monthly quota、fluent Japaneseを重視。",
    domain: "Human Risk Management・Enterprise Sales",
  }),
  job({
    id: "knowbe4-sales-engineer-japan-current",
    companySlug: "knowbe4",
    title: "Sales Engineer (Fluent in Japanese)",
    segment: "Pre-sales / Security",
    location: "東京",
    workStyle: "ハイブリッド環境（出社日数は非公開）",
    language: "日本語（fluent）／英文resume必須、英語水準は明記なし",
    source: { label: "KnowBe4 Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/knowbe4/jobs/6221857002" },
    descriptionSummary: "customer discovery、demo、POV、security architecture、technical objection、sales enablementを担う。",
    genbaTake: "phishing simulationの機能表ではなく、identity・email・SOCの既存stackにhuman risk workflowをどう組み込むかを検証する。",
    compensationReality: "日本の給与、bonus、equity、variable、POV KPIは公式求人で確認できない。",
    desiredProfile: "公式求人はtechnical presales、demo・POV、securityとcustomer communication、fluent Japaneseを重視。",
    domain: "Human Risk Management・Sales Engineering",
  }),
  job({
    id: "lighthouse-business-development-manager-ae-japan-current",
    companySlug: "lighthouse",
    title: "Business Development Manager (Account Executive) - Japan",
    segment: "Hospitality / Full-cycle",
    location: "日本・Greater Tokyo Area",
    workStyle: "Full-Time Remote",
    language: "日本語・英語（fluent）",
    source: { label: "Lighthouse Careers (Greenhouse EU)", url: "https://job-boards.eu.greenhouse.io/lighthouse/jobs/4500582101" },
    descriptionSummary: "Japan hotel marketのfull-cycle hunterとして自力pipeline、3x coverage、MEDDPICC、discovery、demo、negotiation、closeを担う。",
    genbaTake: "rate-shopping toolではなく、demand、pricing、portfolio performance、direct・distributionをADR・RevPAR・運用工数の共通caseにする。",
    compensationReality: "日本の給与、OTE、pay mix、equity、quota額、accelerator、rampは公式求人で確認できない。",
    desiredProfile: "公式求人はSaaS closing 2〜5年、self-sourced pipeline、MEDDPICC、3x coverage、fluent Japanese・Englishを重視。",
    domain: "Hospitality Commercial Intelligence・Enterprise Sales",
  }),
  job({
    id: "mambu-senior-account-executive-channel-japan-current",
    companySlug: "mambu",
    title: "Senior Account Executive (Channel)",
    segment: "Japan Channel / Cloud Banking",
    location: "日本・リモート（JP-Remote）",
    workStyle: "remote（location dependent）、60日のworking abroad制度",
    language: "日本語・英語とも公式求人で明記なし",
    source: { label: "Mambu Careers (iCIMS)", url: "https://careers-mambu.icims.com/jobs/3352/senior-account-executive-%28channel%29/job" },
    descriptionSummary: "reseller portfolio経由のannual New ACV、partner採用・onboarding・enablement・certification、共同GTM、complex salesを担う。",
    genbaTake: "core replacementの機能表ではなく、greenfield・dual-core・段階移行とresilience、exitをpartnerと立証する。",
    compensationReality: "competitive base salaryとcompany equityは公式記載。金額、通貨、OTE、pay mix、quota、acceleratorは非公開。",
    desiredProfile: "公式求人はchannel・partner・indirect sales、pipeline・quota、FinTech/B2B SaaS、cloud delivery理解を重視。",
    domain: "Composable Core Banking・Channel Sales",
  }),
];
