import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-20";

export const companies20260820Daily: Company[] = [
  {
    slug: "twilio",
    name: "Twilio",
    category: "Customer Engagement / CPaaS / Communications APIs",
    broadCategory: "CRM・顧客体験",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Twilio Japan合同会社・東京都渋谷区（2018年設立）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "Voice、Messaging、Email、Verify、Flex、SegmentをAPIと顧客dataでつなぐ顧客engagement基盤。日本でStrategic Account Executiveを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://job-boards.greenhouse.io/twilio",
    tags: ["アンカー企業", "Customer Engagement", "CPaaS", "Communications API", "AI", "Strategic Sales", "Remote", "Japan"],
  },
  {
    slug: "perforce",
    name: "Perforce Software",
    category: "DevOps / Test Data Management / Developer Tools",
    broadCategory: "セキュリティ・IT運用",
    hq: "ミネソタ州ミネアポリス（米国）",
    japanPresence: "Delphix Software合同会社・東京都港区／国内販売partnerを確認",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "code、quality、test data、infrastructure automationをportfolioで提供。日本在住RemoteのEnterprise Account Executive - Delphixを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.lever.co/perforce?department=Sales",
    tags: ["DevOps", "Test Data Management", "Data Compliance", "Developer Tools", "Enterprise Sales", "Remote", "Japan"],
  },
  {
    slug: "fusion-worldwide",
    name: "Fusion Worldwide",
    category: "Electronic Components / Supply Chain Intelligence / Independent Distribution",
    broadCategory: "コマース・業界特化",
    hq: "ニューハンプシャー州ポーツマス（米国）",
    japanPresence: "Fusion Trade Japan合同会社・東京／丸の内（2021年設立）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "半導体・電子部品の不足、EOL、余剰在庫、品質riskをglobal sourcing、inspection、market intelligenceで解く独立系distributor。東京でSales Account Executiveを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://job-boards.greenhouse.io/fusionworldwide",
    tags: ["Electronic Components", "Semiconductors", "Supply Chain", "Quality", "Enterprise Sales", "Tokyo", "Japan"],
  },
  {
    slug: "deepgram",
    name: "Deepgram",
    category: "Voice AI / Speech-to-Text / Voice Agents",
    broadCategory: "AI・データ基盤",
    hq: "カリフォルニア州サンフランシスコ（米国）",
    japanPresence: "Japan Country Leader求人を確認（日本法人・常設拠点は未確認）",
    hiringStatus: "採用中",
    salesRoles: 1,
    description: "real-timeのSTT、TTS、Voice Agent APIをcloud・self-hostedで提供。日本市場を立ち上げるSales Country Leaderを公式募集しているが、日本法人・常設拠点は未確認。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/Deepgram",
    tags: ["日本進出の兆し", "Voice AI", "Speech-to-Text", "Text-to-Speech", "Voice Agents", "Country Leader", "Japan"],
    entryStatus: "pre-entry-signal",
  },
];

const careerInsights = (title: string, domain: string): Job["careerInsights"] => ({
  fit: `${domain}で顧客・partner・社内専門職を動かし、事業成果を定量化したい人に向く。`,
  thingsToKnow: "日本の個別報酬、quota、達成率、担当範囲、平均ACV、ramp、昇進・離職分布は公式求人で確認できない。",
  marketValue: `${title}の成果をpipeline、受注、利用量、gross margin、顧客KPI、team productivityで示せれば、隣接するEnterprise softwareの上位scopeへ説明しやすい。`,
  tenureAndPromotion: `【Genba仮説】${title}では在籍年数より、個人・team成果、再利用できるplaybook、複数stakeholderを動かした証拠が昇進材料になる。支持材料: 公式求人は事業目標、部門横断の実行、継続的な改善を責任として置く。反証・留保: 日本teamの平均在籍年数、昇進率、manager別離職、社内公募実績は公開されていない。面接で確認: 直近24カ月の昇進・異動・退職件数、次levelへ進んだ人の共通KPI、managerのpromotion実績を聞く。`,
  priorCompanies: `【Genba仮説】${domain}、Enterprise software、cloud、consulting、channelでdiscoveryから受注・定着まで進めた人が隣接する。支持材料: ${title}は製品知識だけでなく、複数stakeholder、事業計画、実行責任を求める。反証・留保: 日本teamの入社元企業分布を十分な母数で確認できず、特定企業からの採用傾向は断定できない。面接で確認: 現teamで活躍する人の前職類型、採用時に評価した定量成果、ramp支援を聞く。`,
  nextCompanies: `【Genba仮説】${title}でpipeline、受注、利用量、gross margin、顧客KPI、team成果を定量化できれば、Strategic Sales、Country Leadership、APAC Leadershipが隣接する。支持材料: ${domain}は顧客規模、地域、portfolio、team責任を広げる形で上位scopeへ接続する。反証・留保: 実際の退職後転職先や昇給幅を示す日本の公開分布ではない。面接で確認: alumniの代表的な進路、社内の次role、必要なKPIとpeople leadership実績を聞く。`,
});

export const jobs20260820Daily: Job[] = [
  {
    id: "twilio-strategic-account-executive-japan-1099553600898",
    companySlug: "twilio",
    title: "Strategic Account Executive",
    segment: "Strategic Accounts / Existing Customer Expansion",
    location: "日本",
    workStyle: "Remote（日本国内）／約50%の出張を想定",
    language: "日本語／英語はbusiness reading・writing、verbal fluencyを歓迎",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Twilio Careers", url: "https://jobs.twilio.com/careers?pid=1099553600898&sort_by=timestamp&start=0" },
    descriptionSummary: "既存のStrategic customerでterritory planを作り、Voice、Messaging、Email、Flex、Segment等のup-sell・cross-sellを社内専門職と進める。",
    genbaTake: "API利用量を増やすだけでなく、顧客の対話workflow、AI agent、delivery、gross margin、complianceを複数productの成長計画へ変えるaccount sale。",
    compensationReality: "日本向けのbase、variable、equity、quota、gross margin・usage・multi-productのcreditは公式求人で確認できない。",
    desiredProfile: "通信・CPaaS・CCaaS・SaaS・cloudのStrategic Sales、既存顧客拡張、technical・business stakeholder、日本語と英語でのglobal collaborationを担える人。",
    careerInsights: careerInsights("Strategic Account Executive", "Customer Engagement・CPaaS・Strategic Sales"),
  },
  {
    id: "perforce-enterprise-account-executive-delphix-japan-9eeec4e8",
    companySlug: "perforce",
    title: "Enterprise Account Executive - Delphix",
    segment: "Enterprise Sales / Test Data Management",
    location: "日本",
    workStyle: "Remote（日本在住）",
    language: "日本語・英語の具体水準は公式求人で確認できない",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Perforce Careers (Lever)", url: "https://jobs.lever.co/perforce/9eeec4e8-9bc0-4a07-9ac1-3cbd99236b7d" },
    descriptionSummary: "日本のEnterprise顧客へDelphixのtest data management・data complianceを提案する新規・既存account営業。",
    genbaTake: "data copyの高速化だけでなく、非本番環境の機密dataをmasking・provisioning・governanceし、release速度とprivacyを同じbusiness caseで売る。",
    compensationReality: "日本向けのbase、variable、equity、quota、territory、partner・renewal creditは公式求人で確認できない。",
    desiredProfile: "Enterprise software、DevOps、database・data platform、security・complianceの複雑商談を日本企業で進められる人。",
    careerInsights: careerInsights("Enterprise Account Executive", "Test Data Management・DevOps・Data Compliance"),
  },
  {
    id: "deepgram-sales-country-leader-japan-3ecb28e4",
    companySlug: "deepgram",
    title: "Sales Country Leader (Japan)",
    segment: "Country Leadership / Enterprise & Partner Sales",
    location: "日本",
    workStyle: "公式求人でRemote・Hybrid・出社条件の明記なし",
    language: "business-level日本語／native-levelの日本商習慣理解",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Deepgram Careers (Ashby)", url: "https://jobs.ashbyhq.com/Deepgram/3ecb28e4-4ce3-468c-8bf2-e2b3c4a722bf" },
    descriptionSummary: "日本のpipelineとARRを持ち、direct enterpriseとpartner・co-sellを構築し、strategic dealを自ら進めながらAE teamを採用・育成する。",
    genbaTake: "完成済みのcountry operationではなく、Voice AI categoryの教育、lighthouse customer、partner motion、forecast、採用を同時に作るplayer-coach role。",
    compensationReality: "日本向けのbase、variable、equity、country quota、採用budget、雇用主体は公式求人で確認できない。",
    desiredProfile: "日本Enterprise市場の開拓、category creation、長期複雑商談、team build、SI・ISV・hyperscalerとのco-sellを担えるsales leader。",
    careerInsights: careerInsights("Sales Country Leader", "Voice AI・Developer Infrastructure・Country Build"),
  },
  {
    id: "fusion-worldwide-sales-account-executive-tokyo-5079961003",
    companySlug: "fusion-worldwide",
    title: "Sales Account Executive (Tokyo)",
    segment: "Enterprise Sales / Electronic Components & Supply Chain",
    location: "東京（日本）",
    workStyle: "東京office勤務／flexible hours、国内出張は勤務時間の20%以下を想定",
    language: "日本語nativeまたはfluent／英語reading・writing・speaking",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Fusion Worldwide Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/fusionworldwide/jobs/5079961003" },
    descriptionSummary: "日本の製造・IT・自動車等の顧客を新規開拓し、半導体・電子部品の調達、価格・納期、品質、余剰在庫をglobal purchasing teamと解くfull-cycle営業。",
    genbaTake: "部品を転売するだけでなく、供給不足、EOL、counterfeit、excess inventoryを顧客の生産停止risk、cash、納期、qualityへ翻訳するrelationship型のsupply-chain sale。",
    compensationReality: "求人はperformance連動のuncapped commissionを明記するが、日本のbase、OTE、pay mix、quota、accelerator、保証額は確認できない。",
    desiredProfile: "3年以上のB2B営業、cold callと新規開拓、価格交渉、長期関係構築、日本語・英語、国内出張を担える人。電子部品業界経験は必須と明記されていない。",
    careerInsights: careerInsights("Sales Account Executive", "半導体・電子部品調達・Supply Chain Sales"),
  },
];
