import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchTen: Job[] = [
  job({
    id: "figma-account-executive-enterprise-tokyo-current",
    companySlug: "figma",
    title: "Account Executive, Enterprise (Tokyo, Japan)",
    segment: "Enterprise / Product Development",
    location: "東京",
    workStyle: "勤務形態は明記なし（対面onboarding必須）",
    language: "公式求人で明記なし",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/5806875004" },
    descriptionSummary: "従業員5,000人超のEnterpriseでnew logoと既存拡張のpipeline、executive sponsorship、account plan、suite deploymentを担う。",
    genbaTake: "design seatでなく、Product・Engineering・Marketingのworkflow、design system、AI buildをenterprise-wide deploymentの成果へ変える。",
    compensationReality: "日本の給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はEnterprise SaaS、complex account、executive value selling、new・expansion、forecast disciplineを重視。言語要件は明記なし。",
    domain: "Product Development・Enterprise Sales",
  }),
  job({
    id: "figma-account-executive-smb-tokyo-current",
    companySlug: "figma",
    title: "Account Executive, SMB (Tokyo, Japan)",
    segment: "SMB / New + Existing Business",
    location: "東京",
    workStyle: "Tokyo Hub / フルタイム",
    language: "日本語（native level）／英語は明記なし",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/5729844004" },
    descriptionSummary: "従業員500人以下のinbound・outbound、discovery、evaluation、close、existing expansionを1〜3カ月のhigh-volume cycleで担う。",
    genbaTake: "PLG利用を起点に、handoff、component reuse、review、releaseの待ち時間をteam contractの価値へ変える。",
    compensationReality: "日本の給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はSMB SaaS sales、high-volume、1〜3カ月cycle、native-level Japaneseを重視。英語要件は明記なし。",
    domain: "Product Development・SMB Sales",
  }),
  job({
    id: "figma-account-executive-strategic-tokyo-current",
    companySlug: "figma",
    title: "Account Executive, Strategic (Tokyo, Japan)",
    segment: "Strategic Accounts / Product Development",
    location: "東京",
    workStyle: "勤務形態は明記なし（対面onboarding必須）",
    language: "日本語（native level）／英語（business level）",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/5756182004" },
    descriptionSummary: "named strategic accountsのexecutive relationship、account plan、new・expansion pipeline、multi-product deploymentを担う。",
    genbaTake: "design toolの標準化で終わらず、複数事業・職種のproduct-development operating modelへ拡張する。",
    compensationReality: "日本の給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はstrategic enterprise sales、executive multi-threading、technical audience、native Japanese、business Englishを重視。",
    domain: "Product Development・Strategic Sales",
  }),
  job({
    id: "figma-manager-solutions-consulting-tokyo-current",
    companySlug: "figma",
    title: "Manager, Solutions Consulting (Tokyo, Japan)",
    segment: "Solutions Consulting Leadership",
    location: "東京",
    workStyle: "勤務形態は明記なし（対面onboarding必須）",
    language: "公式求人で明記なし",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/6134908004" },
    descriptionSummary: "Solutions Consultant teamの採用・coaching・成果を持ち、technical pre・post-sales strategyとscale programを作る。",
    genbaTake: "demo品質だけでなく、evaluation、security、workflow design、adoptionを再現可能なtechnical winにする。",
    compensationReality: "給与、bonus、OTE、team target、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はSolutions Consulting・Sales Engineeringのfrontline management 3年以上、customer-facing 8年以上を重視。言語要件は明記なし。",
    domain: "Product Development・Solutions Consulting Leadership",
  }),
  job({
    id: "figma-onboarding-manager-customer-experience-tokyo-current",
    companySlug: "figma",
    title: "Onboarding Manager, Customer Experience (Tokyo, Japan)",
    segment: "Customer Experience / Onboarding",
    location: "東京",
    workStyle: "ハイブリッド / フルタイム",
    language: "日本語・英語（fluent）",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/6051050004" },
    descriptionSummary: "large customerをpre-sales handoffからonboarding closeoutまで担い、success plan、stakeholder、risk、adoptionを管理する。",
    genbaTake: "kickoff完了でなく、time-to-first-value、対象team、workflow、governanceを定義しrenewal前の価値の土台を作る。",
    compensationReality: "給与、bonus、onboarding KPI、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はenterprise onboarding、program management、complex stakeholder、日本語・英語fluencyを重視。",
    domain: "Product Development・Customer Onboarding",
  }),
  job({
    id: "figma-senior-manager-enterprise-sales-tokyo-current",
    companySlug: "figma",
    title: "Senior Manager, Enterprise Sales (Tokyo, Japan)",
    segment: "Enterprise Sales Leadership",
    location: "東京",
    workStyle: "Tokyo Hub / フルタイム",
    language: "日本語・英語（fluent）",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/5753194004" },
    descriptionSummary: "Enterprise sales teamのcoaching、pipeline、forecast、deal strategy、採用・育成を担い、customer meetingにも入る。",
    genbaTake: "top seller依存でなく、PLG signal、multi-product discovery、executive value、technical validationをteam processにする。",
    compensationReality: "給与、OTE、pay mix、team quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はEnterprise sales leadership、coaching、hiring、forecast、日本語・英語fluencyを重視。",
    domain: "Product Development・Enterprise Sales Leadership",
  }),
  job({
    id: "figma-senior-sales-enablement-manager-tokyo-current",
    companySlug: "figma",
    title: "Senior Sales Enablement Manager (Tokyo, Japan)",
    segment: "Sales Enablement / Japan",
    location: "東京",
    workStyle: "ハイブリッド / フルタイム",
    language: "公式求人で明記なし",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/6003308004" },
    descriptionSummary: "Japanのpipeline generation、deal progression、executionを改善するenablement program、playbook、manager toolをglobalと作る。",
    genbaTake: "training回数でなく、pipeline conversion、stage velocity、methodology adoption、manager coachingを営業成果へ変える。",
    compensationReality: "給与、bonus、enablement KPI、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はSales Enablement、Japan buyer・sales cycle、global programのlocalization、pipeline・deal executionを重視。言語名は明記なし。",
    domain: "Product Development・Sales Enablement",
  }),
  job({
    id: "figma-technical-account-manager-tokyo-current",
    companySlug: "figma",
    title: "Technical Account Manager (Tokyo, Japan)",
    segment: "Technical Account Management",
    location: "東京",
    workStyle: "Tokyo Hub / フルタイム",
    language: "日本語・英語（professional fluency）",
    source: { label: "Figma Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/figma/jobs/6006175004" },
    descriptionSummary: "enterprise customerのtechnical advisorとしてarchitecture、governance、integration、AI・MCP guideline、adoption、escalationを担う。",
    genbaTake: "support ticket処理でなく、安全なworkflow、platform integration、AI agent context、横展開をcustomer healthとexpansionの根拠にする。",
    compensationReality: "給与、bonus、renewal・expansion target、equityは公式求人で確認できない。",
    desiredProfile: "公式求人はtechnical account management、enterprise architecture・integration、AI・MCP、日本語・英語professional fluencyを重視。",
    domain: "Product Development・Technical Account Management",
  }),
  job({
    id: "fivetran-bdr-commercial-japan-current",
    companySlug: "fivetran",
    title: "Business Development Representative, Commercial",
    segment: "Commercial / Business Development",
    location: "日本・APAC",
    workStyle: "リモート / フルタイム／入社2週目に対面Bootcamp",
    language: "公式求人で明記なし",
    source: { label: "Fivetran Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7724750003" },
    descriptionSummary: "Japan commercial accountへoutboundし、data movement・analytics engineering・trusted AI dataのqualified pipelineを作る。",
    genbaTake: "connector一覧でなく、schema change、pipeline運用、data freshness、AI reliabilityをaccount固有の投資理由へ変える。",
    compensationReality: "base salary＋uncapped commissionの定性記載のみ。数値給与・OTE・quotaは非公開。",
    desiredProfile: "公式求人はprospecting、qualification、CRM、Revenue Bootcamp出張を重視。言語要件は明記なし。",
    domain: "Data Movement・Business Development",
  }),
  job({
    id: "fivetran-customer-solutions-architect-japan-current",
    companySlug: "fivetran",
    title: "Customer Solutions Architect",
    segment: "Customer Solutions / Post-sales",
    location: "日本・APAC",
    workStyle: "リモート / フルタイム",
    language: "公式求人で明記なし",
    source: { label: "Fivetran Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7747140003" },
    descriptionSummary: "導入後のtechnical ownerとしてarchitecture、adoption、value、expansion、incremental ARR・NRRを担う。",
    genbaTake: "connector稼働で終わらず、time-to-data、incident、model reliability、利用部門をrenewal・expansionの根拠にする。",
    compensationReality: "給与、bonus、renewal・expansion targetは公式求人で確認できない。",
    desiredProfile: "公式求人はdata architecture、SQL・Python・bash、customer success、adoption・value realizationを重視。言語要件は明記なし。",
    domain: "Data Movement・Customer Solutions",
  }),
  job({
    id: "fivetran-partner-sales-manager-japan-current",
    companySlug: "fivetran",
    title: "Partner Sales Manager",
    segment: "Partner Sales / Data Infrastructure",
    location: "日本・APAC",
    workStyle: "リモート / フルタイム",
    language: "公式求人で明記なし",
    source: { label: "Fivetran Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7818344003" },
    descriptionSummary: "ISV、SI、GSIとjoint plan、enablement、co-sellを作り、partner-sourced・influenced pipelineとrevenueを担う。",
    genbaTake: "紹介数でなく、ingestion・transformation・governanceをpartner solutionへ組み込み、deliveryとrevenueを再現可能にする。",
    compensationReality: "給与、OTE、pay mix、partner targetは公式求人で確認できない。",
    desiredProfile: "公式求人はtechnology partner sales、joint GTM、pipeline・revenue ownershipを重視。言語要件は明記なし。",
    domain: "Data Infrastructure・Partner Sales",
  }),
  job({
    id: "fivetran-sales-director-japan-current",
    companySlug: "fivetran",
    title: "Sales Director",
    segment: "Enterprise Sales",
    location: "日本・APAC",
    workStyle: "リモート / フルタイム",
    language: "公式求人で明記なし",
    source: { label: "Fivetran Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7818382003" },
    descriptionSummary: "Japan enterpriseのcomplex full-cycle、POC、account planning、new・expansion revenueを担う。",
    genbaTake: "ELT toolの販売でなく、source-to-warehouseの運用負荷、data trust、AI readinessを経営・platform・analyticsへ束ねる。",
    compensationReality: "salary、equity、performance payの定性記載のみ。数値給与・OTEは非公開。",
    desiredProfile: "公式求人はenterprise software sales、complex account、POC・account planningを重視。言語要件は明記なし。",
    domain: "Data Movement・Enterprise Sales",
  }),
  job({
    id: "grafana-labs-senior-enterprise-ae-acquisition-japan-current",
    companySlug: "grafana-labs",
    title: "Senior Enterprise Account Executive, Acquisition | Tokyo, Japan",
    segment: "Enterprise / New Logo",
    location: "日本",
    workStyle: "リモート / フルタイム",
    language: "公式求人で言語名の明記なし",
    source: { label: "Grafana Labs Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/grafanalabs/jobs/6092347004" },
    descriptionSummary: "enterprise new logoを自ら開拓し、technical discovery、demo・PoC、proposal、negotiation、closeをSEと進める。",
    genbaTake: "OSSの利用を契約へ変えるのではなく、self-managedのoperator hours、telemetry economics、MTTR、governanceをbusiness caseへ束ねる。",
    compensationReality: "日本の給与、OTE、pay mix、quota、equityは公式求人で確認できない。",
    desiredProfile: "公式求人は5年以上のinfrastructure technology sales、new business、full-cycle、demo・PoC、forecast disciplineを重視。",
    domain: "Observability・Enterprise Acquisition",
  }),
  job({
    id: "grafana-labs-senior-solutions-engineer-japan-current",
    companySlug: "grafana-labs",
    title: "Senior Solutions Engineer | Tokyo, Japan | Remote",
    segment: "Solutions Engineering / Observability",
    location: "日本",
    workStyle: "リモート / フルタイム",
    language: "公式求人で言語名の明記なし",
    source: { label: "Grafana Labs Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/grafanalabs/jobs/6104605004" },
    descriptionSummary: "technical discovery、architecture、demo、PoC、security reviewを通じ、Grafana Cloudのtechnical winとcustomer trustを作る。",
    genbaTake: "dashboard demoでなく、metrics・logs・traces・profilesのdata path、cardinality、retention、SLO、TCOを実負荷で検証する。",
    compensationReality: "公式OTEは年1,400万〜1,850万円。base・variable内訳、quota、RSU額、ramp、達成率は非公開。",
    desiredProfile: "公式求人はobservability、cloud・Kubernetes、customer-facing technical sale、demo・PoCを重視。",
    domain: "Observability・Solutions Engineering",
  }),
  job({
    id: "hightouch-enterprise-account-executive-apac-japan-current",
    companySlug: "hightouch",
    title: "Enterprise Account Executive, APAC (Japan)",
    segment: "Enterprise / Japan Market",
    location: "Australia / Singapore（Japan担当）",
    workStyle: "公式求人で明記なし",
    language: "公式求人で明記なし",
    source: { label: "Hightouch Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/hightouch/jobs/5836057004" },
    descriptionSummary: "Japan marketのenterprise pipeline、reseller、Data・Marketing executiveへのvalue selling、technical evaluation、closeを担う。",
    genbaTake: "CDP機能比較でなく、warehouse投資、audience作成時間、channel activation、AI decisioningを一つのdata operating modelへ上げる。",
    compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。US rangeは日本担当roleへ転用しない。",
    desiredProfile: "公式求人はenterprise software full-cycle、Japan marketのnew business、executive relationship、partner・resellerを重視。言語・勤務形態は明記なし。",
    domain: "Composable CDP・Enterprise Sales",
  }),
];
