import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchSeven: Job[] = [
  job({ id: "censys-senior-solutions-engineer-japan", companySlug: "censys", title: "Senior Solutions Engineer, Japan", segment: "Solutions Engineering / Presales", location: "日本", workStyle: "リモート / フルタイム", language: "日本語・英語（fluent）", source: { label: "Censys Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/censys/jobs/8558562002" }, descriptionSummary: "discovery、demo、technical briefing、PoC、deployment・testing、technical win、競合分析を担う。", genbaTake: "scan規模の説明でなく、未知asset、threat investigation、SOC統合を顧客環境で再現しtechnical winを作る。", compensationReality: "給与・bonus金額は非公開。", desiredProfile: "security presales・engineering、PoC・deployment、日本語・英語fluencyを求める。", domain: "Internet Intelligence・Solutions Engineering" }),
  job({ id: "cloudflare-director-enterprise-sales-japan", companySlug: "cloudflare", title: "Director, Enterprise Sales, Japan", segment: "Enterprise Sales Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Cloudflare Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/cloudflare/jobs/7374496" }, descriptionSummary: "日本Major EnterpriseのAE組織を採用・育成し、team pipeline、forecast、revenue target、executive coverageを担う。", genbaTake: "個人の大型受注でなく、Application・SASE・Network・Developerの複数入口をteamの再現性へ変える。", compensationReality: "給与・OTE・team quotaは非公開。", desiredProfile: "Enterprise sales leadership、team hiring・coaching、forecast・revenue ownershipを求める。言語要件は明記なし。", domain: "Connectivity Cloud・Enterprise Sales Leadership" }),
  job({ id: "cloudflare-senior-director-partner-sales-japan", companySlug: "cloudflare", title: "Senior Director, Partner Sales - Japan", segment: "Partner Sales Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "日本語・英語（fluent）", source: { label: "Cloudflare Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/cloudflare/jobs/7844485" }, descriptionSummary: "Partner Account Manager組織を率い、GSI、service provider、MSSP等のpartner-led・co-sell revenueを担う。", genbaTake: "partner数でなく、solution・delivery・pipeline・closeを持つJapan ecosystemを組織として作る。", compensationReality: "給与・OTE・team quotaは非公開。", desiredProfile: "partner sales leadership、GSI・service provider・MSSP、日本語・英語fluencyを求める。", domain: "Connectivity Cloud・Partner Leadership" }),
  job({ id: "cloudflare-senior-partner-account-manager-japan", companySlug: "cloudflare", title: "Senior Partner Account Manager, Japan", segment: "Partner Sales / Ecosystem", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Cloudflare Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/cloudflare/jobs/7981489" }, descriptionSummary: "joint business plan、partner pipeline、co-sell、deal registrationからclose、MDF・SPIFFを担う。", genbaTake: "enablementで終わらず、partner-sourced opportunity、delivery readiness、commercial closeを一つのplanで運営する。", compensationReality: "給与・OTE・partner targetは非公開。", desiredProfile: "technology partner sales、joint planning・pipeline・co-sell・deal registrationを求める。言語要件は明記なし。", domain: "Connectivity Cloud・Partner Sales" }),
  job({ id: "cloudflare-premium-technical-support-engineer-vietnamese-tokyo", companySlug: "cloudflare", title: "Premium Technical Support Engineer - Vietnamese Speaking", segment: "Premium Support / Customer Delivery", location: "シドニー・シンガポール・東京・クアラルンプール", workStyle: "ハイブリッド / フルタイム／rotational shifts", language: "ベトナム語（native）／英語（fluent）", source: { label: "Cloudflare Careers (Greenhouse)", url: "https://job-boards.greenhouse.io/cloudflare/jobs/7388133" }, descriptionSummary: "Premium customerのtechnical issueを調査・解決し、夜間・週末・祝日を含むrotational shiftsでproduction supportを担う。", genbaTake: "日本専任ではないが東京勤務を選べるcustomer delivery role。internet serviceのavailabilityとtechnical escalationを直接支える。", compensationReality: "給与・shift手当は非公開。", desiredProfile: "Vietnamese native、English fluent、technical troubleshooting、rotational shiftsへの対応を求める。", domain: "Connectivity Cloud・Premium Support" }),
  job({ id: "cognition-gtm-operations-japan", companySlug: "cognition", title: "GTM Operations - Japan", segment: "GTM Operations", location: "東京", workStyle: "オンサイト / フルタイム", language: "公式求人で明記なし", source: { label: "Cognition Careers (Ashby)", url: "https://jobs.ashbyhq.com/cognition/0116dd2e-5a6d-45c7-89e4-0ed5e467d8d6" }, descriptionSummary: "pipeline hygiene、forecast、renewal、sales compensation、quota・attainment、GTM・Finance planning、CRM・data qualityを担う。", genbaTake: "急成長するJapan GTMを感覚で運営せず、pipeline・forecast・compensation・renewalを一つのoperating modelへ整える。", compensationReality: "給与・bonus・equity金額は非公開。", desiredProfile: "GTM／Revenue Operations、forecast・compensation、CRM・SQL、Financeとのplanning経験を求める。", domain: "Frontier AI・GTM Operations" }),
  job({ id: "cognition-ai-support-engineer-japan", companySlug: "cognition", title: "AI Support Engineer", segment: "Technical Support / AI Engineering", location: "東京・ニューヨーク", workStyle: "オンサイト / フルタイム", language: "公式求人で明記なし", source: { label: "Cognition Careers (Ashby)", url: "https://jobs.ashbyhq.com/cognition/7e89aab6-3d43-436b-8c7c-2d7cb6515636" }, descriptionSummary: "Devin・Devin Desktop利用企業のcodebase、CI/CD、API、container、cloud・IDE問題を再現し、root cause、escalation、playbook・automationを担う。", genbaTake: "ticket処理でなく、AI coding agentが本番の開発環境で失敗する原因を解き、再発防止をProductへ戻すtechnical customer role。", compensationReality: "給与・bonus・equity金額は非公開。", desiredProfile: "4年以上のtechnical role、software・infra・CI/CD・cloud、顧客対応とroot-cause analysisを求める。", domain: "AI Software Engineering・Technical Support" }),
  job({ id: "cognition-deployed-engineer-apac-japan", companySlug: "cognition", title: "Deployed Engineer - APAC", segment: "Customer Engineering / Delivery", location: "東京", workStyle: "オンサイト / フルタイム", language: "公式求人で明記なし", source: { label: "Cognition Careers (Ashby)", url: "https://jobs.ashbyhq.com/cognition/9ebb0dff-2cbf-42ba-bb4a-0256812a06e0" }, descriptionSummary: "technical discovery、demo・pilot、deployment、activation、use-case選定、enterprise rollout・training、product feedbackを担う。", genbaTake: "demo成功で終わらず、accepted task、adoption、governance、production rolloutまで顧客の開発成果を作る。", compensationReality: "給与・bonus・equity金額は非公開。", desiredProfile: "STEM背景、enterprise deployment、customer-facing engineering、曖昧さの中での実装を求める。", domain: "AI Software Engineering・Deployed Engineering" }),
  job({ id: "cognition-partner-deployed-engineer-apac-japan", companySlug: "cognition", title: "Partner Deployed Engineer - APAC", segment: "Partner Engineering / Delivery", location: "東京", workStyle: "オンサイト / フルタイム／出張25〜50%", language: "公式求人で明記なし", source: { label: "Cognition Careers (Ashby)", url: "https://jobs.ashbyhq.com/cognition/b1c2ccf9-b606-4c9e-a5ea-c741ab78741b" }, descriptionSummary: "GSIのtechnical onboarding・enablement、reference architecture、partner-led pilot・production、integration・security・CI/CD escalationを担う。", genbaTake: "partner trainingで終わらず、SIが再現可能にDevinを設計・導入できるdelivery capacityを作る。", compensationReality: "給与・bonus・equity金額は非公開。", desiredProfile: "partner/customer engineering、enterprise deployment、integration・security・CI/CD、APAC出張25〜50%に対応できる経験を求める。", domain: "AI Software Engineering・Partner Delivery" }),
  job({ id: "cognition-head-of-partnerships-japan", companySlug: "cognition", title: "Head of Partnerships - Japan", segment: "Partnerships Leadership", location: "東京", workStyle: "オンサイト / フルタイム", language: "日本語・英語（fluent）", source: { label: "Cognition Careers (Ashby)", url: "https://jobs.ashbyhq.com/cognition/ce05fcaa-4f22-495f-bfd6-d858a1c37bcf" }, descriptionSummary: "Japan President配下でEnterprise・SI・cloud・公共ecosystem、agreement、co-sell・co-build、partner-sourced pipeline・revenueを率いる。", genbaTake: "紹介networkでなく、日本のSI・cloud deliveryをDevinのproduction adoptionとrepeatable revenueへ変えるecosystem leadership。", compensationReality: "給与・OTE・bonus・equity金額は非公開。", desiredProfile: "Japan partner ecosystem、enterprise・SI・cloud・public sector、commercial agreement、日本語・英語fluentを求める。", domain: "Frontier AI・Partnerships Leadership" }),
  job({ id: "cognition-partner-director-japan", companySlug: "cognition", title: "Partner Director - Japan", segment: "Partnerships / Ecosystem", location: "東京", workStyle: "オンサイト / フルタイム", language: "日本語・英語（fluent）", source: { label: "Cognition Careers (Ashby)", url: "https://jobs.ashbyhq.com/cognition/2877fee4-4657-4986-aa07-15514b66ff41" }, descriptionSummary: "SI・cloud・政府aligned partnerとのjoint GTM、multi-party agreement、enablement、pipeline・revenueを担う。", genbaTake: "partner数を増やすより、共同solution、案件ownership、production delivery、revenue creditを再現可能にする。", compensationReality: "給与・OTE・bonus・equity金額は非公開。", desiredProfile: "Japan ecosystem、joint GTM、commercial agreement、日本語・英語fluencyを求める。", domain: "Frontier AI・Partner Sales" }),
  job({ id: "cambly-sales-director-apac", companySlug: "cambly", title: "Sales Director, APAC", segment: "APAC Sales & Marketing Leadership", location: "上海・東京", workStyle: "ハイブリッド / フルタイム", language: "日本語または中国語（fluent）／英語（proficient）", source: { label: "Cambly Careers (Ashby)", url: "https://jobs.ashbyhq.com/Cambly/96f0b293-0cdc-4d96-9b36-507c787f2b34" }, descriptionSummary: "日本・中国・韓国の売上計画、直販、AE・AM・B2B Marketing組織の構築を担うAPAC leadership role。", genbaTake: "英会話研修のseat販売ではなく、利用、CEFR、実務行動、renewalをAPAC共通のrevenue modelへ変える。", compensationReality: "給与・OTE・commission・equity金額は非公開。", desiredProfile: "training・EdTech 15年以上、Sales・B2B Marketing leadership 10年以上、日本語または中国語fluency、英語proficiencyを求める。", domain: "Corporate Learning・APAC Sales Leadership" }),
  job({ id: "cato-networks-customer-success-manager-japan", companySlug: "cato-networks", title: "Customer Success Manager", segment: "Customer Success / SASE", location: "東京", workStyle: "公式求人で明記なし", language: "英語（solid）／日本語は明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4936215101" }, descriptionSummary: "adoption、health、QBR、renewal、upsellを担う。", genbaTake: "導入完了で終わらず、network・security統合の利用、運用削減、renewal・expansionを成果へ結ぶ。", compensationReality: "給与・bonus・renewal targetは非公開。", desiredProfile: "SaaS・network・securityのCustomer Success、QBR、renewal・upsell、英語力を求める。", domain: "SASE・Customer Success" }),
  job({ id: "cato-networks-customer-success-manager-ai-security-japan", companySlug: "cato-networks", title: "Customer Success Manager, AI Security", segment: "Customer Success / AI Security", location: "東京", workStyle: "公式求人で明記なし", language: "日本語（solid）／英語は明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4936207101" }, descriptionSummary: "AI Securityのarchitecture・integration、adoption、value realization、renewal・upsellを担う。", genbaTake: "AI機能の導入数でなく、利用policy、risk visibility、incident対応、business valueを継続利用へ変える。", compensationReality: "給与・bonus・renewal targetは非公開。", desiredProfile: "security customer success、architecture・integration、value realization、日本語力を求める。", domain: "AI Security・Customer Success" }),
  job({ id: "cato-networks-major-sales-engineer-japan", companySlug: "cato-networks", title: "Major Sales Engineer, Japan", segment: "Presales / Major Enterprise", location: "日本", workStyle: "公式求人で明記なし", language: "公式求人で明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4677389101/major-sales-engineer-japan/" }, descriptionSummary: "AI Security・SASEのtechnical validation、demo、RFI・RFP、POVを大手顧客で担う。", genbaTake: "機能demoでなく、既存network・securityとのcoexistence、data path、policy、SLA、migrationを顧客環境で反証する。", compensationReality: "給与・bonus・quotaは非公開。", desiredProfile: "enterprise network・security presales、demo・RFI/RFP・POVを求める。言語要件は明記なし。", domain: "SASE・Major Enterprise Presales" }),
  job({ id: "cato-networks-product-support-engineer-t2-japan", companySlug: "cato-networks", title: "Product Support Engineer T2, Japan", segment: "Technical Support / Tier 2", location: "東京", workStyle: "公式求人で明記なし", language: "日本語・英語（solid）", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4861400101" }, descriptionSummary: "顧客のnetwork・security technical issueを調査し、Tier 2 supportとescalationを担う。", genbaTake: "ticketを閉じるだけでなく、global SASEの障害切分け、顧客影響、再発防止を日本語と英語でつなぐ。", compensationReality: "給与・shift・on-call手当は非公開。", desiredProfile: "network・security troubleshooting、customer support、日本語・英語力を求める。", domain: "SASE・Technical Support" }),
  job({ id: "cato-networks-product-support-engineer-team-lead-t2-japan", companySlug: "cato-networks", title: "Product Support Engineer Team Lead Tier 2", segment: "Technical Support Leadership", location: "東京", workStyle: "公式求人で明記なし／月〜金", language: "公式求人で明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4920264101" }, descriptionSummary: "Tier 2 support teamを率い、重大incident・escalation、品質、育成を担う。", genbaTake: "個別解決ではなく、SLA、escalation、knowledge、再発防止を日本support teamのoperating modelへする。", compensationReality: "給与・bonus・team KPIは非公開。", desiredProfile: "technical support leadership、network・security、escalation・coachingを求める。言語要件は明記なし。", domain: "SASE・Support Leadership" }),
  job({ id: "cato-networks-product-support-engineer-t3-japan", companySlug: "cato-networks", title: "Product Support Engineer, Tier 3", segment: "Technical Support / Tier 3", location: "東京", workStyle: "公式求人で明記なし", language: "日本語・英語（solid）", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4820239101/product-support-engineer-tier-3/" }, descriptionSummary: "評価・onboarding・post-salesから継続supportまで、難度の高いtechnical issueとengineering escalationを担う。", genbaTake: "productionの複雑な障害を解き、導入前の前提からProduct・Engineeringの恒久対策までつなぐ。", compensationReality: "給与・shift・on-call手当は非公開。", desiredProfile: "advanced network・security troubleshooting、post-sales、customer communication、日本語・英語力を求める。", domain: "SASE・Advanced Technical Support" }),
  job({ id: "cato-networks-regional-sales-manager-japan", companySlug: "cato-networks", title: "Regional Sales Manager - Japan", segment: "Enterprise Sales / SASE", location: "東京", workStyle: "公式求人で明記なし", language: "英語力／日本語は明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4746820101" }, descriptionSummary: "日本のenterprise pipeline、forecast、full sales cycle、partner relationshipを担う。", genbaTake: "point productの更新ではなく、network・securityの運用、policy、SLA、TCOをsingle architectureのbusiness caseへ変える。", compensationReality: "給与・OTE・quotaは非公開。", desiredProfile: "field sales 3〜5年以上、networking・security、C-level・technical buyer、英語力を求める。", domain: "SASE・Enterprise Sales" }),
  job({ id: "cato-networks-sales-development-representative-japan", companySlug: "cato-networks", title: "Sales Development Representative", segment: "Sales Development / SASE", location: "東京", workStyle: "公式求人で明記なし", language: "英語（required）／日本語は明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4926068101" }, descriptionSummary: "電話・emailでprospecting・qualificationを行い、sales meetingとpipelineを作る。", genbaTake: "SASEという広いcategoryを、拠点・remote・cloud・security運用の具体的painへ分解してqualified opportunityへ変える。", compensationReality: "給与・OTE・quotaは非公開。", desiredProfile: "outbound prospecting、qualification、presentation設定、quota責任、英語力を求める。", domain: "SASE・Sales Development" }),
  job({ id: "cato-networks-sales-engineer-japan", companySlug: "cato-networks", title: "Sales Engineer", segment: "Presales / SASE", location: "日本", workStyle: "公式求人で明記なし", language: "公式求人で明記なし", source: { label: "Cato Networks Careers", url: "https://www.catonetworks.com/careers/careers-post/4821119101/sales-engineer" }, descriptionSummary: "SASEのtechnical evaluation、demo、RFI・RFP、POVを担う。", genbaTake: "single-vendorの主張でなく、traffic、policy、security coverage、SLA、migration rollbackを実環境で比較する。", compensationReality: "給与・bonus・quotaは非公開。", desiredProfile: "network・security presales、technical evaluation、demo・RFI/RFP・POVを求める。言語要件は明記なし。", domain: "SASE・Solutions Engineering" }),
];
