import type { Company, Job } from "@/lib/market-data";

const checkedAt = "2026-08-28";

export const companies20260828Daily: Company[] = [
  {
    slug: "rokt",
    name: "Rokt",
    category: "AIコマース・購入時レレバンス最適化",
    broadCategory: "コマース・業界特化",
    hq: "ニューヨーク（米国）／シドニー発",
    japanPresence: "Rokt合同会社、東京オフィス、日本語公式サイトとTokyo求人を確認",
    hiringStatus: "採用中",
    salesRoles: 0,
    description: "購入完了画面など取引の瞬間に、顧客ごとに関連性の高い広告・オファー・商品を選び、EC事業者の収益と広告主の獲得効率を改善する。東京でRokt AdsのCustomer Success Managerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.rokt.com/jp/company/careers",
    tags: ["AI Commerce", "Retail Media", "Advertising", "Customer Success", "Tokyo", "Japanese"],
  },
  {
    slug: "menlo-security",
    name: "Menlo Security",
    category: "ブラウザセキュリティ・脅威分離",
    broadCategory: "セキュリティ・IT運用",
    hq: "マウンテンビュー（米国）",
    japanPresence: "メンロ・セキュリティ・ジャパン株式会社、東京拠点、日本語公式サイトとJapan求人を確認",
    hiringStatus: "採用中",
    salesRoles: 0,
    description: "Web・メール・SaaSへのアクセスをクラウド上で分離・制御し、利用者の操作性を保ちながら未知の脅威とデータ流出を防ぐ。日本でChannel Sales Engineerを公式募集。",
    lastChecked: checkedAt,
    careersUrl: "https://www.menlosecurity.com/ja-jp/about/life-at-menlo",
    tags: ["Browser Security", "Zero Trust", "Threat Prevention", "Channel", "Sales Engineering", "Japan"],
  },
  {
    slug: "witnessai",
    name: "WitnessAI",
    category: "AIセキュリティ・利用統制",
    broadCategory: "セキュリティ・IT運用",
    hq: "マウンテンビュー（米国）",
    japanPresence: "日本法人・国内拠点を確認できず。Japan RemoteのSenior Sales Engineerを公式募集",
    hiringStatus: "採用中",
    salesRoles: 0,
    description: "従業員とAIエージェントのプロンプト・応答・意図を可視化し、シャドーAI、情報流出、脱獄、危険な操作をリアルタイムに制御する。Japan求人を進出シグナルとして掲載。",
    lastChecked: checkedAt,
    careersUrl: "https://jobs.ashbyhq.com/witnessai",
    tags: ["法人未確認・日本向け採用", "AI Security", "AI Governance", "Sales Engineering", "Remote Japan", "Enterprise"],
    entryStatus: "pre-entry-signal",
  },
];

export const jobs20260828Daily: Job[] = [
  {
    id: "rokt-customer-success-manager-rokt-ads-tokyo-361b100e01",
    companySlug: "rokt",
    title: "Customer Success Manager, Rokt Ads",
    segment: "Customer Success / Advertising",
    location: "東京",
    workStyle: "週4日オフィス勤務",
    language: "日本語ネイティブ、英語ビジネスレベル",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Rokt Careers (Workable)", url: "https://apply.workable.com/rokt/j/361B100E01/apply/" },
    descriptionSummary: "日本の広告主を導入し、Rokt Adsの施策設計、開始、運用改善、成果分析、関係拡大を担う。営業、実装、分析、製品の各担当と連携し、広告主の獲得効率と取引後の関連性を高める。",
    genbaTake: "広告枠の進行管理ではなく、購入直後という限られた接点で誰に何を見せるかを検証し、広告主の成果とEC事業者の収益を両立させる顧客成長の役割。",
    compensationReality: "公式求人で日本の給与額、賞与、株式、担当社数、更新・拡大目標は確認できない。週4日オフィス勤務は明記される。",
    desiredProfile: "公式求人はCustomer Success、Account Managementまたはデジタル広告領域で3年以上の経験、日本語ネイティブ、ビジネス英語、データから施策を改善する力を求める。",
    careerInsights: {
      fit: "広告主の目的を施策、計測、改善へ落とし込み、社内の実装・分析担当を束ねて継続成果を作りたい人に向く。",
      thingsToKnow: "担当社数、売上・継続・広告成果の評価配分、既存顧客と新規導入の比率、給与・賞与・株式、日本組織人数は未公開。面接で確認したい。",
      marketValue: "小売メディア、広告運用、購入データ、顧客成功、部門横断の施策改善を一つの成果として説明できる経験。",
      tenureAndPromotion: "【Genba仮説】次の範囲は在籍年数より、広告主の成果を継続・拡大と再現可能な運用へ変えた実績で決まる。支持材料: 公式求人は導入、最適化、分析、関係拡大を同じ役割へ置き、顧客と社内各部門をまたぐ成果を求める。反証・留保: 日本組織の昇進・離職分布、職位別の期待値は未公開で、成果と昇進の関係は確認できない。面接で確認: 直近24カ月の昇進・異動・退職、次の職位の定量基準と昇格例は。",
      priorCompanies: "【Genba仮説】デジタル広告、広告技術、EC、小売メディアで顧客施策と成果分析を持った人が隣接する。支持材料: 公式求人はCustomer Success、Account Managementまたはデジタル広告で3年以上を求める。反証・留保: 日本の直近採用者の前職分布と、異業種からの採用実績は未確認。面接で確認: 現在の担当者の前職領域と、入社後に補う必要が大きい知識は。",
      nextCompanies: "【Genba仮説】広告主の獲得効率、継続、拡大を数字で残せれば、小売メディア、広告技術、EC基盤のCustomer Success・Account Management上位職へ接続しやすい。支持材料: 求人は施策導入から成果分析・関係拡大までを一貫して持つ。反証・留保: 公開された退職者の転職先分布ではなく、職務の隣接性からの推定。面接で確認: 退職者の主な転職先、社内で広げられる担当範囲、再現性を示す評価指標は。",
    },
  },
  {
    id: "menlo-security-channel-sales-engineer-japan-6d39fd97",
    companySlug: "menlo-security",
    title: "Sales Engineer - Channel",
    segment: "Channel Sales Engineering / Browser Security",
    location: "日本",
    workStyle: "勤務区分は公式求人で明記なし",
    language: "日本語・英語の要件は公式求人本文で明記確認できず",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "Menlo Security Careers (Ashby)", url: "https://jobs.ashbyhq.com/menlosecurity/6d39fd97-f731-453c-99ef-8331eca78749" },
    descriptionSummary: "日本の販売パートナーへ技術支援、提案設計、製品説明、デモ、評価、構成助言を行い、Channel Account Managerと共同でブラウザセキュリティ案件を作る。",
    genbaTake: "製品デモだけでなく、パートナーが顧客の業務・既存防御・予算へMenloを組み込める提案能力を作る役割。直販案件の支援と販売網の再現性を同時に持つ。",
    compensationReality: "日本の給与、賞与、株式、担当パートナー数、案件支援目標、出社頻度は公式求人で確認できない。",
    desiredProfile: "公式求人はChannel Sales Engineerとして、顧客の事業要件をセキュリティ構成へ対応づけ、販売パートナーと共同で提案を作れる技術営業経験を求める。",
    careerInsights: {
      fit: "セキュリティ技術を顧客成果へ翻訳し、販売パートナーが自走できる提案・検証の型まで作りたい人に向く。",
      thingsToKnow: "担当パートナー数、直販との案件所有、評価環境、技術支援件数、給与・賞与・株式、日本組織人数は未公開。面接で確認したい。",
      marketValue: "ブラウザセキュリティ、ゼロトラスト、SSE、チャネル設計、技術評価を横断する経験。",
      tenureAndPromotion: "【Genba仮説】次の範囲は在籍年数より、パートナー経由の案件創出と技術評価の勝率を再現可能にした成果で決まる。支持材料: 公式求人はChannel Account Managerとの共同提案、デモ、評価、技術助言を一つの役割へ置く。反証・留保: 日本の昇進・離職分布、職位別の評価基準は未公開。面接で確認: 直近24カ月の昇進・異動・退職、次の職位の定量基準は。",
      priorCompanies: "【Genba仮説】ネットワーク、クラウド、端末防御、SSEのSales Engineer、Solution Architect、販売代理店技術担当が隣接する。支持材料: 公式求人は顧客要件を構成へ対応づけ、パートナーと共同提案を作る経験を求める。反証・留保: 日本の採用者プロフィールを十分な件数で集計しておらず、特定業界からの採用傾向は未確認。面接で確認: 現在の技術営業の前職領域と、入社後の製品・販売網研修は。",
      nextCompanies: "【Genba仮説】販売網の技術力を案件化まで高めた実績は、セキュリティ企業のChannel SE Lead、Solutions Engineering、Partner Engineeringへ接続しやすい。支持材料: 役割は技術評価とパートナーの提案力向上を同時に持つ。反証・留保: 公開された退職者の転職先分布ではなく、職務の隣接性からの推定。面接で確認: 退職者の主な転職先、社内の管理職・専門職経路、次の職位で求める案件成果は。",
    },
  },
  {
    id: "witnessai-senior-sales-engineer-japan-2674ec49",
    companySlug: "witnessai",
    title: "Sr. Sales Engineer - Japan",
    segment: "Sales Engineering / AI Security",
    location: "日本（Remote）",
    workStyle: "Remote表記。福利厚生欄にはHybridの記載もあり、実際の日本勤務条件は要確認",
    language: "日本語・英語の要件は公式求人本文で明記確認できず",
    firstSeen: checkedAt,
    lastChecked: checkedAt,
    source: { label: "WitnessAI Careers (Ashby)", url: "https://jobs.ashbyhq.com/witnessai/2674ec49-4e29-463f-b6a4-07277aac23e6" },
    descriptionSummary: "企業のAI利用に対する技術提案、製品説明、概念実証、構成設計を担い、SASE、ファイアウォール、Windows／Mac、API、SIEMとの統合を設計する。顧客要望を製品・開発へ返す。",
    genbaTake: "AI統制の説明役ではなく、既存の通信・端末・監視基盤のどこでAI利用を観測・制御するかを概念実証で証明する、日本市場立ち上げ型の技術営業。",
    compensationReality: "公式求人は13.8万〜17.7万米ドルのOTEを掲載するが、勤務地・経験等で決定すると注記する。日本の雇用主体、通貨、福利厚生適用、pay mix、株式、税務は未確認のため日本条件として断定しない。",
    desiredProfile: "公式求人は技術営業、Solution Architect等で5〜7年、Enterprise software・cybersecurity・AI governance、SASE、firewall、Windows／Mac、API、SIEMの知識を求める。",
    careerInsights: {
      fit: "AI利用のリスクを既存セキュリティ構成へ落とし込み、概念実証から導入条件まで顧客と作りたい人に向く。",
      thingsToKnow: "日本の雇用主体、営業担当の有無、日本語要件、既存顧客・案件、OTEの適用通貨と内訳、RemoteとHybrid表記の整合は未確認。面接で確認したい。",
      marketValue: "AIセキュリティ、SASE、SIEM、API統合、概念実証、初期市場の製品フィードバックを横断する経験。",
      tenureAndPromotion: "【Genba仮説】次の範囲は在籍年数より、日本の概念実証を本番導入へ変え、再利用できる構成と反論処理を作った成果で決まる。支持材料: 公式求人は提案、概念実証、構成設計、顧客要望の製品還元を同じ役割へ置く。反証・留保: 日本の雇用主体、組織、昇進・離職分布は未確認で、昇進経路そのものが未確定。面接で確認: 日本での評価者、直近の昇進例、次の職位の定量基準は。",
      priorCompanies: "【Genba仮説】SASE、ファイアウォール、SIEM、クラウドセキュリティの技術営業・構成設計経験者が隣接する。支持材料: 公式求人は5〜7年の技術営業経験と、SASE、端末、API、SIEMの知識を求める。反証・留保: 日本の直近採用者の前職集計と、AI統制専業からの採用実績は未確認。面接で確認: 現在の技術営業の前職領域、AI固有知識と既存セキュリティ知識の評価配分は。",
      nextCompanies: "【Genba仮説】AI利用統制と既存防御の統合を成果化できれば、AI Security、Cloud Security、Security Architectureの上位技術営業へ接続しやすい。支持材料: 求人は複数の既存防御との統合と概念実証を担当する。反証・留保: 公開された退職者の転職先分布ではなく、職務の隣接性からの推定。面接で確認: 社内の技術責任者経路、退職者の主な転職先、本番導入として評価される成果は。",
    },
  },
];
