import type { Job } from "@/lib/market-data";

const checkedAt = "2026-08-17";

function careerInsights(domain: string): Job["careerInsights"] {
  return {
    fit: `${domain}の顧客課題を調べ、複数部門と社内専門家を束ねて成果を作りたい人に向く。`,
    thingsToKnow: "給与、quota、担当社数、達成率、昇進、離職は公開情報で確認できない。配属先の数字と具体例を面接で確認したい。",
    marketValue: `${domain}の役割成果をpipeline、受注、導入、利用、顧客KPIで定量化できれば、隣接するEnterprise SaaSの同職種・上位職へ再現性を説明しやすい。`,
    tenureAndPromotion: `【Genba仮説】${domain}では、在籍年数だけでなく担当scope、個人・team成果、再現可能なprocess作りが次のlevelを決める。支持材料: 公式求人は顧客成果、部門横断の実行、継続的な学習を求める。反証・留保: 日本の対象職種だけを十分な件数で集計した在籍年数・昇進率は確認できない。面接で確認: 直近24カ月の昇進・異動・退職件数と、次levelに必要な定量成果は。`,
    priorCompanies: `【Genba仮説】入社元は社名より、${domain}に近い顧客課題、複数stakeholder、目標責任、部門横断の実行が共通項になる。支持材料: 公式求人がrole固有の経験と成果を明記する。反証・留保: 日本の公開profileを4件以上の同一条件で集計できず、特定企業からの採用傾向は断定できない。面接で確認: 直近採用者の前職category上位3つ、共通skill、ramp期間は。`,
    nextCompanies: `【Genba仮説】pipeline、受注、導入、利用、顧客KPIを定量化できれば、${domain}の専門職、上位segment、Lead、managementへ接続しやすい。支持材料: 公式求人が成果責任とcross-functional ownershipを求める。反証・留保: 公開された日本の転職先分布ではなく、隣接する職務構造からの仮説である。面接で確認: 退職者の次role categoryと、社内でscopeを広げた実例は。`,
  };
}

function job(input: Omit<Job, "firstSeen" | "lastChecked" | "careerInsights"> & { domain: string }): Job {
  const { domain, ...record } = input;
  return { ...record, firstSeen: checkedAt, lastChecked: checkedAt, careerInsights: careerInsights(domain) };
}

export const jobs20260817BatchEight: Job[] = [
  job({ id: "cohere-partner-development-manager-japan", companySlug: "cohere", title: "Partner Development Manager - Japan", segment: "Partner Development / Alliances", location: "東京", workStyle: "リモート / フルタイム", language: "日本語（native level）／英語（business level）", source: { label: "Cohere Careers (Ashby)", url: "https://jobs.ashbyhq.com/cohere/1a31d80f-0d8b-475a-a60a-b13393ba8687" }, descriptionSummary: "SI、distributor、reseller、ISV、cloud providerの開拓・enablement・co-sellとsourced・influenced ARRを担う。", genbaTake: "partner数を増やすより、private AIのtechnical delivery、joint pipeline、revenue creditを再現可能なJapan ecosystemへ変える。", compensationReality: "給与、OTE、partner target、equityは公式求人で確認できない。", desiredProfile: "公式求人はJapan partner ecosystem、co-sell・enablement、native-level Japanese、business-level Englishを重視。", domain: "Enterprise AI・Partner Development" }),
  job({ id: "cohere-forward-deployed-engineer-infrastructure-japan", companySlug: "cohere", title: "Forward Deployed Engineer, Infrastructure Specialist", segment: "Customer Engineering / Infrastructure", location: "東京", workStyle: "リモート / フルタイム／出張20〜40%", language: "日本語（fluent）／英語（business level）", source: { label: "Cohere Careers (Ashby)", url: "https://jobs.ashbyhq.com/cohere/38f75a48-199c-4325-a7f8-2af6ed6a1b3b" }, descriptionSummary: "Northのprivate cloud・on-prem導入、Kubernetes・Helm・cloud infrastructure、production rolloutを担う。", genbaTake: "model demoで終わらず、data boundary、GPU・Kubernetes、security、latency、運用を顧客環境でproductionへ移す。", compensationReality: "給与、bonus、equity、on-call条件は公式求人で確認できない。", desiredProfile: "公式求人はprivate cloud・on-prem、Kubernetes・Helm、customer delivery、日本語・英語、出張20〜40%を重視。", domain: "Enterprise AI・Forward Deployed Engineering" }),
  job({ id: "deel-sales-development-representative-japan-current", companySlug: "deel", title: "Sales Development Representative | Japan", segment: "Sales Development / Global HR", location: "日本", workStyle: "フルタイム／remote workの柔軟性・optional WeWork", language: "英語fluencyを応募時に確認／日本語要件は本文に明記なし", source: { label: "Deel Careers", url: "https://jobs.deel.com/deel/job-details/521f9cbb-b198-4e1f-b280-ada22c289cb9/overview" }, descriptionSummary: "inbound・outbound、email・phone・social・eventでprospectをqualifyし、AE handoff、meeting・SQO・pipeline目標を担う。", genbaTake: "meeting数でなく、採用国・worker type・法人・payroll providerを診断し、HR・Finance・Legalの優先課題をqualified opportunityへ変える。", compensationReality: "給与、OTE、pay mix、quota、equityは公式求人で確認できない。", desiredProfile: "現行求人はprospecting、qualification、CRM、quotaを重視。旧求人のTokyo優先・native Japanese・1年以上を現行条件へ転用しない。", domain: "Global HR・Sales Development" }),
  job({ id: "deel-customer-onboarding-manager-japanese", companySlug: "deel", title: "Customer Onboarding Manager | Mandarin or Japanese speaker", segment: "Customer Onboarding / Delivery", location: "日本・オーストラリア・シンガポール・中国・ニュージーランド", workStyle: "フルタイム／remote workの柔軟性・optional WeWork", language: "英語（fluent）＋日本語または中国語（fluent）", source: { label: "Deel Careers", url: "https://jobs.deel.com/deel/job-details/66056631-a83e-4c5c-90e6-0b86cdebbc8f/overview" }, descriptionSummary: "global employee management platformの導入project、product expertise、global payroll onboardingを担う。", genbaTake: "契約後の設定完了で終わらず、country・worker type・payroll cutoff・integration・first payを再現可能に立ち上げる。", compensationReality: "給与、bonus、担当社数、onboarding KPIは公式求人で確認できない。", desiredProfile: "公式求人はB2B SaaS onboarding 3年以上、HR・Payroll・Finance、fluent EnglishとJapaneseまたはMandarinを重視。", domain: "Global HR・Customer Onboarding" }),
  job({ id: "deel-senior-manager-payroll-operations-japan", companySlug: "deel", title: "Senior Manager, Payroll Operations | Japan", segment: "Payroll Operations Leadership", location: "日本", workStyle: "フルタイム／remote workの柔軟性・optional WeWork", language: "公式求人で明記なし", source: { label: "Deel Careers", url: "https://jobs.deel.com/deel/job-details/6d9b2ca8-0024-4342-8940-3fe95aebf9fc/overview" }, descriptionSummary: "日本payroll operationsのdelivery、品質、team、process改善とglobal連携を担う。", genbaTake: "payroll件数を処理するだけでなく、accuracy、cutoff、off-cycle、escalation、auditをJapan deliveryのoperating modelへする。", compensationReality: "給与、bonus、team KPIは公式求人で確認できない。", desiredProfile: "公式求人の現行本文に個別言語要件・給与は明記されていない。Payroll operations leadershipの詳細は面接で確認が必要。", domain: "Global Payroll・Operations Leadership" }),
  job({ id: "deel-senior-payroll-associate-japan", companySlug: "deel", title: "Senior Payroll Associate | Japan", segment: "Payroll Operations / Delivery", location: "日本", workStyle: "フルタイム／remote workの柔軟性・optional WeWork", language: "公式求人で明記なし", source: { label: "Deel Careers", url: "https://jobs.deel.com/deel/job-details/147de544-2cc7-4bc5-abb0-a3301c3c7d94/overview" }, descriptionSummary: "日本payrollの正確な処理、client・internal coordination、issue resolution、compliance運用を担う。", genbaTake: "給与計算の作業量でなく、first-time accuracy、deadline、off-cycle、問い合わせ、監査証跡を顧客体験へ変える。", compensationReality: "給与、bonus、処理件数、shift条件は公式求人で確認できない。", desiredProfile: "現行求人に個別言語要件・給与は明記されていない。日本payrollの実務範囲と責任境界を確認したい。", domain: "Global Payroll・Delivery" }),
  job({ id: "dbt-partner-sales-manager-japan", companySlug: "dbt-labs", title: "Partner Sales Manager", segment: "Partner Sales / Data Infrastructure", location: "日本・APAC（東京周辺）", workStyle: "リモート / フルタイム", language: "公式求人で明記なし", source: { label: "Fivetran + dbt Labs Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7818344003" }, descriptionSummary: "ISV、SI、GSIとのjoint plan、enablement、partner-sourced・influenced pipelineを担う。", genbaTake: "紹介件数でなく、ingestion・transformation・governanceをpartner solutionへ組み込み、deliveryとrevenueを再現可能にする。", compensationReality: "給与、OTE、pay mix、partner targetは公式求人で確認できない。", desiredProfile: "公式求人はtechnology partner sales、joint GTM、pipeline・revenue ownershipを重視。人間言語要件は明記なし。", domain: "Data Infrastructure・Partner Sales" }),
  job({ id: "dbt-bdr-commercial-japan-current", companySlug: "dbt-labs", title: "Business Development Representative, Commercial", segment: "Commercial / Business Development", location: "日本・APAC", workStyle: "リモート / フルタイム／入社2週目に対面Bootcamp", language: "公式求人で明記なし", source: { label: "Fivetran + dbt Labs Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7724750003" }, descriptionSummary: "Japan commercial accountへoutboundし、analytics engineering・trusted dataのqualified pipelineを作る。", genbaTake: "meeting数でなく、SQL・metric・lineage・AI contextの分断をaccount固有のdata reliability課題へ変える。", compensationReality: "base salary＋uncapped commissionの定性記載のみ。数値給与・OTEは非公開。", desiredProfile: "公式求人はprospecting、qualification、CRM、Revenue Bootcamp出張を重視。人間言語要件は明記なし。", domain: "Analytics Engineering・Business Development" }),
  job({ id: "dbt-customer-solutions-architect-japan", companySlug: "dbt-labs", title: "Customer Solutions Architect", segment: "Customer Solutions / Post-sales", location: "日本・APAC", workStyle: "リモート / フルタイム", language: "公式求人で明記なし", source: { label: "Fivetran + dbt Labs Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7747140003" }, descriptionSummary: "導入後のtechnical ownerとしてadoption、value、expansion、incremental ARR・NRRを担う。", genbaTake: "利用率でなく、開発cycle、test・lineage、data incident、metric trustを成果へ変えrenewal・expansionの根拠を作る。", compensationReality: "給与、bonus、renewal・expansion targetは公式求人で確認できない。", desiredProfile: "公式求人はdata architecture、SQL・Python・bash、customer success、adoption・value realizationを重視。人間言語要件は明記なし。", domain: "Analytics Engineering・Customer Solutions" }),
  job({ id: "dbt-sales-director-japan", companySlug: "dbt-labs", title: "Sales Director", segment: "Enterprise Sales", location: "日本・APAC", workStyle: "リモート / フルタイム", language: "公式求人で明記なし", source: { label: "Fivetran + dbt Labs Careers", url: "https://www.fivetran.com/careers/job?gh_jid=7818382003" }, descriptionSummary: "dbt Cloudのenterprise full-cycle、POC、account planning、new・expansion revenueを担う。", genbaTake: "SQL toolの販売でなく、data teamのdeveloper workflowとAI用trusted contextを経営・platform・analyticsへ束ねる。", compensationReality: "salary、equity、performance payの定性記載のみ。数値給与・OTEは非公開。", desiredProfile: "公式求人はenterprise software sales、complex account、POC・account planningを重視。人間言語要件は明記なし。", domain: "Analytics Engineering・Enterprise Sales" }),
  job({ id: "datadog-senior-manager-enterprise-customer-success-japan", companySlug: "datadog", title: "Senior Manager, Enterprise Customer Success", segment: "Customer Success Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "日本語（fluent）／英語（business level）", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8108349/?gh_jid=8108349" }, descriptionSummary: "Enterprise CS組織のadoption、value、renewal、expansion、hiring・coachingを率いる。", genbaTake: "seat・usageでなく、resilience・developer・security・cost成果をrenewalとplatform expansionへ再現する。", compensationReality: "給与、bonus、renewal targetは非公開。", desiredProfile: "Enterprise Customer Success leadership、日本語fluent、英語business levelを重視。", domain: "Observability・Customer Success Leadership" }),
  job({ id: "datadog-regional-manager-sales-engineering-public-sector-japan", companySlug: "datadog", title: "Regional Manager, Sales Engineering - Public Sector", segment: "Public Sector / Presales Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8003531/?gh_jid=8003531" }, descriptionSummary: "Public Sector向けSales Engineering team、technical strategy、PoC・deal supportを率いる。", genbaTake: "demo管理でなく、公共workloadのresilience、security、data residency、procurement条件をtechnical winへ変える。", compensationReality: "給与、bonus、team quotaは非公開。", desiredProfile: "Presales leadershipとpublic sector technical sellingを重視。言語要件は明記なし。", domain: "Observability・Public Sector Presales" }),
  job({ id: "datadog-technical-escalations-engineer-revenue-cost-apj", companySlug: "datadog", title: "Technical Escalations Engineer 2, Revenue and Cost Management - APJ", segment: "Technical Escalations / FinOps", location: "東京・ソウル・シドニー", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8095826/?gh_jid=8095826" }, descriptionSummary: "Revenue・Cost Management領域のtechnical escalation、root cause、customer・engineering連携を担う。", genbaTake: "billing・cost issueをticketで閉じず、usage economics、data volume、product behaviorの再発防止へつなぐ。", compensationReality: "給与、bonus、shift条件は非公開。", desiredProfile: "technical escalation、cloud cost・billing、customer communicationを重視。言語要件は明記なし。", domain: "Observability・Technical Escalations" }),
  job({ id: "datadog-director-commercial-sales-japan", companySlug: "datadog", title: "Director, Commercial Sales", segment: "Commercial Sales Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8059382/?gh_jid=8059382" }, descriptionSummary: "Commercial sales組織のrevenue、pipeline、forecast、hiring・coachingを率いる。", genbaTake: "個人受注でなく、segment別land-and-expand、forecast、seller ramp・達成者比率を改善する。", compensationReality: "給与、OTE、team quotaは非公開。", desiredProfile: "Commercial SaaS sales leadership、hiring・coaching、forecastを重視。言語要件は明記なし。", domain: "Observability・Commercial Sales Leadership" }),
  job({ id: "datadog-senior-enterprise-customer-success-manager-japan", companySlug: "datadog", title: "Senior Enterprise Customer Success Manager", segment: "Enterprise Customer Success", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "日本語（fluent）／英語（writing fluent・spoken high-conversational）", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8054774/?gh_jid=8054774" }, descriptionSummary: "Enterprise顧客のadoption、technical・business outcome、renewal・expansionを担う。", genbaTake: "usageをresilience、release、security、FinOpsの顧客KPIへ翻訳しplatform expansionを作る。", compensationReality: "給与、bonus、renewal・expansion targetは非公開。", desiredProfile: "Enterprise CS、日本語fluent、英語writing fluent・spoken high-conversationalを重視。", domain: "Observability・Enterprise Customer Success" }),
  job({ id: "datadog-technical-account-manager-japan", companySlug: "datadog", title: "Technical Account Manager", segment: "Technical Account Management", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8018694/?gh_jid=8018694" }, descriptionSummary: "顧客のarchitecture、adoption、technical issue、best practice、value realizationを支援する。", genbaTake: "support対応でなく、telemetry設計、運用品質、利用拡張を顧客のproduction outcomeへ変える。", compensationReality: "給与、bonus、担当社数は非公開。", desiredProfile: "technical account management、cloud・observability、customer communicationを重視。言語要件は明記なし。", domain: "Observability・Technical Account Management" }),
  job({ id: "datadog-customer-success-associate-japan", companySlug: "datadog", title: "Customer Success Associate", segment: "Customer Success", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/5486716/?gh_jid=5486716" }, descriptionSummary: "顧客onboarding、adoption、health、renewal supportを担う。", genbaTake: "touch数でなく、time-to-first-value、active use case、risk、renewal readinessを可視化する。", compensationReality: "給与、bonus、renewal targetは非公開。", desiredProfile: "SaaS customer success、organization、customer communicationを重視。言語要件は明記なし。", domain: "Observability・Customer Success" }),
  job({ id: "datadog-sales-development-representative-japan", companySlug: "datadog", title: "Sales Development Representative", segment: "Sales Development", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7806043/?gh_jid=7806043" }, descriptionSummary: "prospecting、qualification、meeting・pipeline creationを担う。", genbaTake: "monitoring関心でなく、cloud incident、developer time、security、tool costをaccount固有の仮説へ変える。", compensationReality: "給与、OTE、quotaは非公開。", desiredProfile: "outbound、qualification、CRM、quota orientationを重視。言語要件は明記なし。", domain: "Observability・Sales Development" }),
  job({ id: "datadog-country-manager-japan", companySlug: "datadog", title: "Country Manager", segment: "Japan GTM Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "日本語（fluent）／英語（professional）", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7975747/?gh_jid=7975747" }, descriptionSummary: "日本GTM、revenue、team、partner、market strategyを統括する。", genbaTake: "大型案件だけでなく、segment・product・partner・customer successをJapan operating modelへ統合する。", compensationReality: "給与、OTE、equity、Japan targetは非公開。", desiredProfile: "Japan enterprise GTM leadership、日本語fluent、英語professionalを重視。", domain: "Observability・Country Leadership" }),
  job({ id: "datadog-senior-partner-enablement-manager-japan", companySlug: "datadog", title: "Senior Partner Enablement Manager", segment: "Partner Enablement", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/8003723/?gh_jid=8003723" }, descriptionSummary: "partnerのsales・technical enablement、readiness、program、adoptionを担う。", genbaTake: "training回数でなく、certification、qualified pipeline、technical win、delivery qualityをpartner capacityへ変える。", compensationReality: "給与、bonus、partner KPIは非公開。", desiredProfile: "technology partner enablement、program design、sales・technical readinessを重視。言語要件は明記なし。", domain: "Observability・Partner Enablement" }),
  job({ id: "datadog-senior-partner-manager-channels-japan", companySlug: "datadog", title: "Senior Partner Manager - Channels", segment: "Channel Sales", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7982373/?gh_jid=7982373" }, descriptionSummary: "channel partnerのjoint plan、pipeline、co-sell、revenueを担う。", genbaTake: "partner数でなく、sourced・influenced revenue、technical delivery、account ownershipを再現可能にする。", compensationReality: "給与、OTE、partner targetは非公開。", desiredProfile: "channel sales、joint planning、pipeline・revenue ownershipを重視。言語要件は明記なし。", domain: "Observability・Channel Sales" }),
  job({ id: "datadog-manager-premier-support-engineering-japan", companySlug: "datadog", title: "Manager 2, Premier Support Engineering", segment: "Premier Support Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7894188/?gh_jid=7894188" }, descriptionSummary: "Premier Support Engineering team、escalation、service quality、hiring・coachingを率いる。", genbaTake: "ticket量でなく、severity response、resolution、knowledge、customer riskをsupport operating modelへする。", compensationReality: "給与、bonus、support KPIは非公開。", desiredProfile: "technical support engineering leadership、escalation、team developmentを重視。言語要件は明記なし。", domain: "Observability・Premier Support Leadership" }),
  job({ id: "datadog-enterprise-sales-engineer-japan", companySlug: "datadog", title: "Enterprise Sales Engineer", segment: "Enterprise Presales", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7811662/?gh_jid=7811662" }, descriptionSummary: "Enterprise discovery、demo、technical validation、PoC、architecture・security reviewを担う。", genbaTake: "機能demoでなく、telemetry coverage、query、cost、security、migrationを顧客環境でtechnical winへ変える。", compensationReality: "給与、bonus、quotaは非公開。", desiredProfile: "Enterprise presales、cloud・observability、PoC・architectureを重視。言語要件は明記なし。", domain: "Observability・Enterprise Presales" }),
  job({ id: "datadog-manager-technical-support-engineering-japan", companySlug: "datadog", title: "Manager I, Technical Support Engineering", segment: "Technical Support Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム／週末rotation", language: "日本語・英語（written・spoken fluent）", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7343626/?gh_jid=7343626" }, descriptionSummary: "Technical Support team、escalation、quality、週末rotation、hiring・coachingを担う。", genbaTake: "個別解決でなく、severity、SLA、knowledge、engineering feedbackをJapan supportの再現性へする。", compensationReality: "給与、bonus、weekend手当は非公開。", desiredProfile: "support engineering leadership、日本語・英語fluent、週末rotationへの対応を重視。", domain: "Observability・Technical Support Leadership" }),
  job({ id: "datadog-field-cto-japan", companySlug: "datadog", title: "Field CTO, Japan", segment: "Executive Presales / Technology Strategy", location: "東京", workStyle: "ハイブリッド / フルタイム／出張最大50%", language: "日本語（native）／英語（strong written・spoken）", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7526356/?gh_jid=7526356" }, descriptionSummary: "CIO・CTO・CISOへのtechnology strategy、executive advisory、market・product feedbackを担う。", genbaTake: "製品roadmap説明でなく、resilience・security・developer・FinOpsを経営portfolioの優先順位へ翻訳する。", compensationReality: "給与、bonus、equityは非公開。", desiredProfile: "executive technology advisory、日本語native、英語strong、出張最大50%を重視。", domain: "Observability・Field CTO" }),
  job({ id: "datadog-enterprise-customer-success-manager-japan", companySlug: "datadog", title: "Enterprise Customer Success Manager", segment: "Enterprise Customer Success", location: "東京", workStyle: "ハイブリッド / フルタイム／必要時顧客訪問", language: "日本語・英語（written・spoken fluent）", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7435209/?gh_jid=7435209" }, descriptionSummary: "Enterprise onboarding、adoption、outcome、risk、renewal・expansionを担う。", genbaTake: "product usageをMTTR、release、security、cost等の顧客成果へ結び、renewal・platform expansionへつなぐ。", compensationReality: "給与、bonus、renewal targetは非公開。", desiredProfile: "Enterprise CS、日本語・英語fluent、必要時の顧客訪問を重視。", domain: "Observability・Enterprise Customer Success" }),
  job({ id: "datadog-head-enterprise-sales-japan", companySlug: "datadog", title: "Head of Enterprise Sales, Japan", segment: "Enterprise Sales Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で水準の明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7729887/?gh_jid=7729887" }, descriptionSummary: "日本Enterprise sales組織のrevenue、pipeline、forecast、hiring・coachingを率いる。", genbaTake: "大型案件の英雄営業でなく、segment、account planning、seller ramp、platform expansionをteamの再現性へする。", compensationReality: "給与、OTE、team quotaは非公開。", desiredProfile: "Enterprise SaaS sales leadership、hiring・coaching、forecastを重視。言語水準は明記なし。", domain: "Observability・Enterprise Sales Leadership" }),
  job({ id: "datadog-strategic-ae-public-sector-fed-japan", companySlug: "datadog", title: "Strategic Account Executive, Public Sector Japan, FED", segment: "Public Sector / Strategic Sales", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7439149/?gh_jid=7439149" }, descriptionSummary: "Public Sector Japanのstrategic account、pipeline、technical・procurement processを担う。", genbaTake: "求人本文に米国向け表現が残るため、実担当機関・territoryを確認しつつ公共workloadのresilienceとsecurityを売る。", compensationReality: "給与、OTE、quotaは非公開。", desiredProfile: "Public Sector・strategic enterprise salesを重視。米国向けboilerplateと日本の実scopeは確認が必要。", domain: "Observability・Public Sector Sales" }),
  job({ id: "datadog-manager-commercial-sales-japan", companySlug: "datadog", title: "Manager, Commercial Sales", segment: "Commercial Sales Leadership", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7463769/?gh_jid=7463769" }, descriptionSummary: "Commercial sellerのpipeline、forecast、quota、hiring・coachingを担う。", genbaTake: "activityでなく、conversion、cycle、ramp、attainment、land-and-expandをsegment operating modelへする。", compensationReality: "給与、OTE、team quotaは非公開。", desiredProfile: "Commercial sales management、coaching、forecast、quota teamを重視。言語要件は明記なし。", domain: "Observability・Commercial Sales Leadership" }),
  job({ id: "datadog-strategic-ae-public-sector-sled-japan", companySlug: "datadog", title: "Strategic Account Executive, Public Sector Japan, SLED", segment: "Public Sector / Strategic Sales", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/7439152/?gh_jid=7439152" }, descriptionSummary: "Public Sector Japanのstrategic account、pipeline、technical・procurement processを担う。", genbaTake: "State・Local・Education表現を日本へそのまま補完せず、実担当範囲を確認してresilience・securityのbusiness caseを作る。", compensationReality: "給与、OTE、quotaは非公開。", desiredProfile: "Public Sector・strategic salesを重視。SLED分類と日本での実scopeは確認が必要。", domain: "Observability・Public Sector Sales" }),
  job({ id: "datadog-mid-market-account-executive-japan", companySlug: "datadog", title: "Mid Market Account Executive", segment: "Mid-Market", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/6522009/?gh_jid=6522009" }, descriptionSummary: "従業員1,000〜5,000人企業のnew logo、pipeline、technical discovery、negotiation、closeを担う。", genbaTake: "monitoring toolの置換でなく、incident・developer・security・costをplatformのbusiness caseへ束ねる。", compensationReality: "給与、OTE、quotaは非公開。", desiredProfile: "B2B technology sales、new logo、technical・executive stakeholderを重視。言語要件は明記なし。", domain: "Observability・Mid-Market Sales" }),
  job({ id: "datadog-commercial-account-executive-japan-current", companySlug: "datadog", title: "Commercial Account Executive", segment: "Commercial", location: "東京", workStyle: "ハイブリッド / フルタイム", language: "公式求人で明記なし", source: { label: "Datadog Careers", url: "https://careers.datadoghq.com/detail/5798241/?gh_jid=5798241" }, descriptionSummary: "中小・中堅企業のnew logo、pipeline、discovery、negotiation、closeを担う。", genbaTake: "機能数でなく、重要serviceのMTTR・developer工数・tool costを短いsales cycleで定量化する。", compensationReality: "給与、OTE、quotaは非公開。", desiredProfile: "Commercial B2B technology sales、prospecting、consultative sellingを重視。言語要件は明記なし。", domain: "Observability・Commercial Sales" }),
];
